### ISSUE TITLE
?options=text [it was ?text=true] for all GET operations

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1001]
Some operations (https://github.com/telefonicaid/fiware-orion/issues/997) use `?text=true` as a way of providing a `text/plain` description.

This issue is about extending `?text=true` to all GET operations in order to hava a way of "pretty print" the element in text.

**Comment by fgalan** [comment]
It has been discussed to implement this the `text` option (within the `options` parameter).

From an implementation point of view, probably is a matter of using the `present()` methods to render this textual information (maybe `present()` could be renamed to `toText()`).

**Comment by kzangeli** [comment]
The *present* method was initially to present the data onscreen (using the PRINTF macro). Now it is changed to present to the log file, using the LM_F log macro.

We recently invented the *toJson* method so *toText* seems like a very reasonable name for this new method. The *present* method does a different thing and cannot be used for this purpose.

**Comment by fgalan** [comment]
My reasoning about using present() for this is that what is good for onscreen/logfile is algo good to be rendered as textual representation of an entity, attribute, etc. However, I could be wrong (I don't remember right now what present() is exactly printing).

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
