### ISSUE TITLE
Get information of a given type

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1028]
Implement the following operation in in v2:

```
GET /v2/type/<entityType>
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Implemented in PR #1167

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending to resolve the issue #1833

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
