### ISSUE TITLE
geo:point attribute type support [+ geo:line, geo:box and geo:polygon]

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1038]
(Originally included as comment on https://github.com/telefonicaid/fiware-orion/issues/947)

Support the special processing of geo:point, i.e. string format checking and using it to match geo-queries.

**Comment by fgalan** [comment]
Partially implemented for geo:point in PR https://github.com/telefonicaid/fiware-orion/pull/1771. The other "geo:things" are pending.

**Comment by fgalan** [comment]
Completed in PR https://github.com/telefonicaid/fiware-orion/pull/1982

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1982. Moved to QATestPending while the acceptance test to cover this functionality gets implemented.

**Comment by iariasleon** [comment]
LGTM
issue associated: #2426
