### ISSUE TITLE
date attribute type support

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1039]
Formatting checking and storing it as ISODate() at MongoDB (in order to be used in attribute filters).

**Comment by fgalan** [comment]
The answer to following question in SOF has to be edited before closing this issue: http://stackoverflow.com/questions/32630801/query-orion-context-broker-by-dates

**Comment by fgalan** [comment]
Basic implementation in PR https://github.com/telefonicaid/fiware-orion/pull/1796. What is pending yet is support in `q=` filter, e.g.:

```
GET /v2/entitites?q<2016-04-05T14:00:00.00Z
```

**Comment by fgalan** [comment]
Finished in PR https://github.com/telefonicaid/fiware-orion/pull/1834

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests are created in its feature associated
bug associated: #1885

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/022_pep2cbv2_datetimeprocessing.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
