### ISSUE TITLE
Solve the ambiguity with structured attribute values

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1040]
(Originally included as comment in https://github.com/telefonicaid/fiware-orion/issues/947)

Finally, it is not part of PR #958 solving the ambiguenty problems for compound attributes e.g.:

What I mean is that for example the following rendering for attribute A1:

```
"A1": {
  "value": "M1", 
  "type": "a4", 
  "m2": {
    "type": "tm2", 
    "value": "M2"
   }, 
   "m3": 3,
}
```
Could be interpreted in two different ways:

* As an attribute without metadata and type and which value is the following JSON object:

```
{
  "value": "M1", 
  "type": "a4", 
  "m2": {
    "type": "tm2", 
    "value": "M2"
   }, 
   "m3": 3,
}
```

* As an attribute of type "a4" and value "M1" with 2 metadata (one named "m2" with type "tm2" and value "M2" and the other named "m3" of type "number" and value 3.

**Comment by kzangeli** [comment]
Perhaps we should treat the two cases the exact same way?
I.e. if a user creates an attribute with a compound value and it coincides with 'standard stuff', why not 'assume' it is just 'standard stuff' ?

**Comment by fgalan** [comment]
With the new JSON format being worked at https://github.com/telefonicaid/fiware-orion/issues/1259, this ambiguity is no longer possible.
