### ISSUE TITLE
options=count

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1041]
(Originally included as comment on https://github.com/telefonicaid/fiware-orion/issues/947)

After latest discussion, the `count` option (within the `options` parameter) will be used instead of `count=true`. The code needs to be fixed (PR #958 was based on `count=true`).

**Comment by kzangeli** [comment]
Also, detect all cases of

    ciP->uriParam["options"] == "something"

And modify, using ciP->uriParamOptions.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1251
