### ISSUE TITLE
Subscription cache

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1048]
In order to improve csubs queries, we need a subscription cache for subscriptions.

We need to implement a SubscriptionCache class (or similar name). It is important to implement it as a class (although only one instance of that class would exist at the same time at execution, i.e. a singleton pattern) in order to make it easy to mock in unit test (similar to the case of the Notifier class).

The class should implement "table", being each subscription in the cache a "row", with the following information (columns):

* ID (string): based in the subscription ID at MongoDB, which is unique.
* List of entity information (given that NGSI10 allows subscription list), each element being:
 * Entity pattern (regex_t): based on the pattern entities in the subscription. , this field should be a list. Regular expressions are compiled at creation/updateing time (thus, we use the regex_t type), so they are stored compiled in the cache for increased performance.
  * An example of use of regext_t is in matchEntity() function
 * Entity type (string).
* Attrs (vector of strings)
* Expiration time (long long? time_t? I don't remember right now...)

In addition, the class should provide the following method (just a draft, maybe some new one is needed, someone doesn't make sense at the end, etc.).

* insert(subscripttionRow sub): look for a subscription in the cache with the same ID of sub. If found, the row is updated. If not found, a new row is added. To be called mainly from subscribeContext and updateContextSubscription logic.
* delete(string id): removes the subscription identified by ID. To be called mainly from the unsubscribeContext logic.
* refresh(): sync cache with DB content, i.e. creating/updating new rows with insert() and delete rows that are not longer in DB with delete(). The implementation of this method may rely on (new) functions at mongoBackend. The class constructor must invoke this method at construction time. To be called mainly by the main thread from time to time.
* search(entity, attribute): search if the context element identified by entity and attribute match with some of the rows in the cache. In that case, the sub ID is returned. To be called mainly from the addTriggeredSubscription() in order to avoide the "$where" part of the query DB to datbase.

Probably, a read/write locks should be implemented, as the cache is supposed to be used concurrently from several threads.

**Comment by kzangeli** [comment]
A "subscription row", should have its Throttling as well?

What about the Reference, Restriction and NotifyConditionVector?

**Comment by fgalan** [comment]
Thottling, Reference, Restriction and NotifyConditionVector could make sense. Probably the best strategy is to assume that all them are necesary, then check at the end if we were used removing them in negative case.

**Comment by kzangeli** [comment]
Also, no 'isPattern'?
How do we know that "Entity pattern (regex_t)" is actually a pattern?

Without this information we can no longer have entities with EntityId::id ".*", or any other string that is also a valid regex.

**Comment by fgalan** [comment]
By definition the cache only contains subscriptions which use pattern entities, so isPattern is not needed. The not-pattern entities are searched in DB as usual as search for them is not "expensive" in terms of DB.

In the case of a subscription mixing pattern and not pattern in its EntityIdVector (it is weird, but theoretically possible) the not pattern entities could be filter out, e.g.

EntityIdVector = [ E1-nopattern, E2-pattern, E3-nopattern, E4-pattern ]

will be stored in the cache as:

EntityIdVector = [ E2-pattern, E4-pattern ]

**Comment by fgalan** [comment]
Implemented in PR #1105
