### ISSUE TITLE
options=values (Compact Response to a Query)

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1049]
This functionality will allow Simple API to offer terse responses providing only entity attribute values in response to a query. Basic example 

I want to know all the card brands registered in the system: 

http://broker.example.org/v2/entities?type=CarBrand&attrs=name&options=values

Response:

[‘Ford’, ‘Mercedes Benz’, ‘Hyundai’] 

Compact response is always an array of attribute values. If an entity does not contains such an attribute, the corresponding value in the array will be null. 

With more than one attribute, we will respond with an Array of Arrays
http://broker.example.org/v2/entities?type=CarBrand&attrs=name,country&options=values

[ [‘Ford’, ‘USA’], [‘Mercedes Benz’, ‘Deutchsland’], [‘Hyundai’, ‘Republic of Korea’]]

If an attribute is not present, null will rendered in the corresponding position of the Array

**Comment by fgalan** [comment]
At the end, this is going to be implemented as described in [the NGSIv2 specification](http://telefonicaid.github.io/fiware-orion/api/v2/):

> values mode. This mode represents the entity only by a collection of attribute values conveyed by an Array. Id and type information are left out. See example below.
>
> [ 'Ford', 'black', 78.3 ]

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1809

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests are created in its feature associated

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
