### ISSUE TITLE
options=distinct (Provide only those values which are distinct)

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1050]
The idea is to have an API functionality intended to provide only the distinct values provided by a query. That would be similar to the 'distinct' modifier present in MongoDB or SQL queries. 

Examples:

Please tell me all the countries on which cars are made. As the same country might manufacture different car brands, We would need the 'distinct' modifier, otherwise an Array with duplicated elements would appear. 

http://broker.example.org/v2/entities?type=CarBrand&attrs=country&options=values, distinct

[“Deutchsland”, “USA”, “Republic of Korea”] 

I want what are the different vehicle brand and model which are currently in a certain area :

http://broker.example.org/v2/entities?type=Vehicle&attrs=brand, model&options=values, distinct&coords=lat,long&geometry=circle;radius=4000

[ [“Ford”, “Mustang”], [“Mercedes Benz”, “C 200”], … ]

In this case all the distinct pairs will be considered and only will be provided those which are distinct.

**Comment by fgalan** [comment]
Implemented at PR https://github.com/telefonicaid/fiware-orion/issues/1050 (although using `options=unique` at the end).

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests in its feature associated

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
