### ISSUE TITLE
Use Case: Group and count

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1052]
Should we support the following Use Case in the Context Broker?:

I want to know, per Card brand and model how many vehicles are in a certain area:

This is the response I would like to have (roughly speaking):

``` js
[
  {
    count: 45,
   value: ["Mercedes-Benz", "C200"]
  },
  {
    count: 1000,
    value: ["Opel", "Corsa"]
  }
]
```

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
