### ISSUE TITLE
Cleanup lib/common/sem.cpp

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1056]
The curl-related functions in lib/common/sem.cpp to be moved to a separate file, probably in the **rest** library.

**Effort: 1 man day**

**Comment by Anjali-NEC** [comment]
Hi @kzangeli @fgalan Sir,

I would like to work on this issue. Please assign this issue to me.
Thanks

**Comment by fgalan** [comment]
Thanks! Assigned :)

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

As per issue requirement I have created two files inside `src/lib/rest `named `curl.cpp` and `curl.h` and moved all the curl related functions from `src/lib/common/sem.cpp` and `src/lib/common/sem.h` to `src/lib/rest/curl.cpp` and `src/lib/rest/curl.h`

I have raised PR for the same. Please have a look, if it is ok then please merge into master.
