### ISSUE TITLE
contextType  query of a service  gets types from all services, when contextBroker is configured without -multiservice

### ISSUE THREAD

**Issue by rbl219** [telefonicaid/fiware-orion#1066]
If contextBroker is launched without –multiservice option, contextTypes from all services are received ,  when contexTypes from a service is made.

 For example, asking :

curl 'http://0.0.0.0:1026/v1/contextTypes' -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: santander' --header 'Fiware-ServicePath: /' --header 'Accept: application/json'

You receive 

{
  "types" : [
    {
      "name" : "Factory42",
      "attributes" : [
        "temperature",
        "battery",
         ……

But only exists entities of type "Factory42" in a service different of santander

**Comment by rbl219** [comment]
Another test with CB 0.22.0


With -multiservice
----------------------

Lanching CB with -multiservice, contextTypes request of a service, returns only his contextTypes 

/usr/bin/contextBroker -multiservice  -writeConcern 1 -reqMutexPolicy all -dbPoolSize 1

[cloud-user@iota-install ~]$ curl 'http://0.0.0.0:1026/v1/contextTypes' -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: performance' --header 'Fiware-ServicePath: /' --header 'Accept: application/json'
{
  "types" : [
    {
      "name" : "thing",
      "attributes" : [
        "attr_1"
      ]
    }
  ],
  "statusCode" : {
    "code" : "200",
    "reasonPhrase" : "OK"
  }
}


[cloud-user@iota-install ~]$ curl 'http://0.0.0.0:1026/v1/contextTypes' -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: santander' --header 'Fiware-ServicePath: /' --header 'Accept: application/json'
{
  "types" : [
    {
      "name" : "string",
      "attributes" : [
        "position"
      ]
    }
  ],
  "statusCode" : {
    "code" : "200",
    "reasonPhrase" : "OK"
  }
}




Without -multiservice
----------------------------

Lanching CB without -multiservice, contextTypes request of a service, returns all services contextTypes 

 /usr/bin/contextBroker -writeConcern 1 -reqMutexPolicy all -dbPoolSize 1


[cloud-user@iota-install ~]$ curl 'http://0.0.0.0:1026/v1/contextTypes' -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: performance' --header 'Fiware-ServicePath: /' --header 'Accept: application/json'
{
  "types" : [
    {
      "name" : "string",
      "attributes" : [
        "position"
      ]
    },
    {
      "name" : "thing",
      "attributes" : [
        "attr_1"
      ]
    }
  ],
  "statusCode" : {
    "code" : "200",
    "reasonPhrase" : "OK"
  }
}

**Comment by fgalan** [comment]
Please, do the following test:

1. Clear all DBs at Mongo (to ensure we start from a clean point)
2. Start CB **with** -multiservice
3. Create the following entities:
   * ID: E1, type: T1 without Fiware-Service header
   * ID: E2, type: T2 with Fiware-Service: ServA
   * ID: E3, type: T3 with Fiware-Service: ServB
4. Get context types without Fiware-Service hader
5. Get context types with Fiware-Service: ServA
6. Get context types with Fiware-Service: ServB
7. Stop CB
8. Start CB again **without** -multiservice
9. Get context types without Fiware-Service hader
10. Get context types with Fiware-Service: ServA
11. Get context types with Fiware-Service: ServB

What is the result of 4, 5, 6, 9, 10, 11? (Only the returned types, for the sake of briefness, as the entire payload is not needed).

**Comment by rbl219** [comment]
Result starting CB with -multiservice
============================

4.Get context types without Fiware-Service hader

  "types" : [
    {
      "name" : "T1"
    }
  ],


5.Get context types with Fiware-Service: ServA

  "types" : [
    {
      "name" : "T2"
    }
  ],


6.Get context types with Fiware-Service: ServB

  "types" : [
    {
      "name" : "T3"
    }
  ],



Result starting CB without -multiservice
==============================

9.Get context types without Fiware-Service hader

  "types" : [
    {
      "name" : "T1"
    },
    {
      "name" : "T2"
    },
    {
      "name" : "T3"
    }
  ],
 


10.Get context types with Fiware-Service: ServA

  "types" : [
    {
      "name" : "T1"
    },
    {
      "name" : "T2"
    },
    {
      "name" : "T3"
    }
  ],



11.Get context types with Fiware-Service: ServB

  "types" : [
    {
      "name" : "T1"
    },
    {
      "name" : "T2"
    },
    {
      "name" : "T3"
    }
  ],

**Comment by fgalan** [comment]
After researching on this, it has been forund that the behaviour is correct, to this is not actually a bug. Closing.
