### ISSUE TITLE
Support array and object in metadata value

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1068]
(In some way, this issue is a spin-off of #970 )

**Comment by fgalan** [comment]
After the limitations discovered in NGSIv1 metadata rendering for metadata created with NGSIv2 in PR https://github.com/telefonicaid/fiware-orion/pull/2340, this issue should take into account the following:

* Modify 2339_json_native_types_in_v1/json_native_types_in_v1.test to include metadata cases for JSON array and object.
* Fix the problem, so md created with NGSIv2 gets correctly rendered in NGSIv1 as attributes do.
* Modify documentation in "Native JSON types" section in v1_v2_coexistence.md to remove the sentence about the limitation in metadata.

**Comment by fgalan** [comment]
The part regarding limitations in rendering non-string medatada has been fixed in PR #2348

**Comment by fgalan** [comment]
After completing this issue documentation at https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/user/ngsiv2_implementation_notes.md has to be modified to remove:

> NGSIv2 specification allows metadata value to be JSON Array or Object. However, such datatypes are yet to be implemented for metadata values in Orion.

**Comment by fgalan** [comment]
The two compund cases used in cases/0000_ngsi10_compound_values/compound_convop_json.test for attrs could be used for metadata test.

**Comment by fgalan** [comment]
Impllemented in #2377.

This should be now checked by QA in order to close definitively. Not sure what to do... leave it in 1.3.0 milestone (if verificaiton is going to happen soon) or move to QATestPending in order to accumulate with others for the future. @iariasleon what do you think?

**Comment by iariasleon** [comment]
LGTM
