### ISSUE TITLE
Functests with mixed v1 and v2 calls

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1072]
A few new functests use a mix of /v1 and /v2.
They were made before "POST /v2/entities" was implemented and use /v1 to create entities.

We will keep those tests as is, but they should be "copied and converted to 100% /v2":

* 0947_v2_list_all_entities/GET_v2_entities.test
* 0950_GET_v2_entity/GET_v2_entity.test
* 0950_GET_v2_entity/GET_v2_entity_not_found.test
* 0989_GET_v2_entity_attribute/GET_v2_entity_attribute.test
* 1005_GET_v2_entities_string/1005_GET_v2_entities_string.test
* 1005_GET_v2_entities_string/1005_GET_v2_entities_string.test

[ there might be more cases of version mix ... ]

**Effort: 2 man day**

**Comment by fgalan** [comment]
> We will keep those tests as is, but they should be "copied and converted to 100% /v2":

I think is better just to replace /v1 by /v2 at entity creation steps. I think there is little gain in having the "v1 and v2 mixed version" and may add confusion and make maintenance difficult in the long term.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1125
