### ISSUE TITLE
"APPEND as UPDATE" doesn't generate notifications

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1076]
From Pedro Gonçalves email report (thanks! :)

> - I Create a Virtual Machine with Orion Context Broker (orion-psb-image-R4.2) - which has a version 0.19.0 Broker.
> - I Subscribed to changes in all entities inside the Broker.
> - I Developed my app which was sending entity information to the Broker as APPEND.
> - The Broker was sending notifications to my REST server.
>
> - A few days ago, I retested that part of our architecture:
> - I subscribed to changes in all entities inside the Broker (exact same request than before but different REST endpoint).
> - But when my app sent update information to the Broker (as APPEND action), I was not getting any notifications.
> - I removed the Broker (yum remove)
> - I Installed the Broker (yum install) - Now 0.23.0
> - I Subscribed to changes in all entities inside the Broker.
> - I received a notification on my REST server (because a subscription is seen as an update).
> - I sent an APPEND entity to the Broker (data was behind update - checked with a Query context)
> - But no notification on the REST Server.
> - I sent the exact same message but with UPDATE action and I got the notifications.

So it seems that in some point between 0.19.0 and 0.23.0 generate notificaitons based on "APPEND as UPDATE" has broken. We need to have a deeper look on this to confirm the problem and fix it.

**Comment by kzangeli** [comment]
We should also decide whether we want to forward this UPDATE to context providers.
As the APPEND has been converted to an UPDATE, I really think it should be forwarded ...

**Comment by fgalan** [comment]
Not able to reproduce, pending from author response.

**Comment by fgalan** [comment]
I have tried to reproduce the problem using the following script and I have failed, using Orion 0.24.0.

* Clean up MongoDB database
* Start CB in the following way in a shell terminal: `contextBroker -fg`
* Create subscription (using your suggested pattern + condsValue)

```
(curl localhost:1026/v1/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "Room",
            "isPattern": "true",
            "id": ".*"
        }                 
    ],                        
    "reference": "http://localhost:1028/accumulate",
    "duration": "P1M",
    "notifyConditions": [         
        {                        
            "type": "ONCHANGE",
            "condValues": [
                "temperature"
            ]
        }
    ]
}
EOF
```

* Run a listening process on port 1028 in a shell terminal: `nc -l -p 1028`
* Create the entity

```
(curl localhost:1026/v1/updateContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "contextElements": [
        {
            "type": "Room",
            "isPattern": "false",
            "id": "Room1",
            "attributes": [
            {
                "name": "temperature",
                "type": "float",
                "value": "23" 
            },                                     
            {
                "name": "pressure",
                "type": "integer",
                "value": "720"
            }             
            ]            
        }   
    ],
    "updateAction": "APPEND"
}
EOF
```

* Check that I have received the notification in the nc terminal

```
POST /accumulate HTTP/1.1
User-Agent: orion/0.23.0-next libcurl/7.26.0
Host: localhost:1028
Accept: application/xml, application/json
Content-length: 595
Content-type: application/json

{
  "subscriptionId" : "55f7d265af86d12b4b826206",
  "originator" : "localhost",
  "contextResponses" : [
    {
      "contextElement" : {
        "type" : "Room",
        "isPattern" : "false",
        "id" : "Room1",
        "attributes" : [
          {
            "name" : "pressure",
            "type" : "integer",
            "value" : "720"
          },
          {
            "name" : "temperature",
            "type" : "float",
            "value" : "23"
          }
        ]
      },
      "statusCode" : {
        "code" : "200",
        "reasonPhrase" : "OK"
      }
    }
  ]
}
```

* Restart `nc -l -p 1028` (as it was closed upon notification reception)
* Update the entity with a different value for temperature, using APPEND message

```
(curl localhost:1026/v1/updateContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "contextElements": [
        {
            "type": "Room",
            "isPattern": "false",
            "id": "Room1",
            "attributes": [
            {
                "name": "temperature",
                "type": "float",
                "value": "26"
            }                                      
            ]
        }                         
    ],                           
    "updateAction": "APPEND"
}                         
EOF
```

* Check that I have received the notification in the nc terminal

```
POST /accumulate HTTP/1.1
User-Agent: orion/0.23.0-next libcurl/7.26.0
Host: localhost:1028
Accept: application/xml, application/json
Content-length: 595
Content-type: application/json

{
  "subscriptionId" : "55f7d265af86d12b4b826206",
  "originator" : "localhost",
  "contextResponses" : [
    {
      "contextElement" : {
        "type" : "Room",
        "isPattern" : "false",
        "id" : "Room1",
        "attributes" : [
          {
            "name" : "pressure",
            "type" : "integer",
            "value" : "720"
          },
          {
            "name" : "temperature",
            "type" : "float",
            "value" : "26"
          }
        ]
      },
      "statusCode" : {
        "code" : "200",
        "reasonPhrase" : "OK"
      }
    }
  ]
}
```

**Comment by fgalan** [comment]
According to users input, the issue happened to him whem upgraded to 0.23.0. In a new test with 0.23.0 he confirms that it's working with both APPEND and UPDATE and it's still 0.23.0.

Thus, it may have been due to some unknown (and hard to reproduce) gltich in the 0.23.0 upgrading step. The issue will be closed (if new problems arise related with this, we will open a new issue).
