### ISSUE TITLE
support for attributes with empty values

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1077]
Right now orion doesn't support empty values for ContextAttribute (v1 works that way).
In v2 we want to be able to update e.g. the metadata of an attribute without touching its value.
That is right now not possible - changes in mongoBackend are necessary.

**Comment by fgalan** [comment]
Support for attribute with empty values means to support the (string) "" as a valid value for an attribute.

**Comment by fgalan** [comment]
This issue is somehow covered by https://github.com/telefonicaid/fiware-orion/issues/1259 (absent attrinutes in the new NGSIv2 JSON format) and https://github.com/telefonicaid/fiware-orion/issues/1188 (empty attribute),
