### ISSUE TITLE
API v2: "batch" queryContext

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1080]
Implement the following operation in in v2:

```
POST /v2/op/query
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.
### A doubt about error handling:

The payload has three optional fields, "entities", "attributes", and "scopes".
What if the payload is non-empty but contains **none** of the three (but some other, irrelevant field, like a misspelling: "entties")?
Do we return an error or do we return an empty vector (nothing found) ?

**Comment by fgalan** [comment]
Some comments to take into account, raised in PR #1060 but not yet resolved:

* Making entities optional slightly breaks NGSI OMA spec, as Section 5.4.1.1 specifies that the lower bound for the EntityIdList is 1.
* Note that we are not using Restriction anymore (see Section 5.4.1.1), using directly an array of Scopes. This is a nother slight breach in the NGSI OMA standard, but in this case I think it makes sense, as any AttributeExpression could me mapped to the corresponding Scope.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1781

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/016_pep2cbv2_batchoperations.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
