### ISSUE TITLE
Sorting capabilities in list entity operation [pending: orderBy=$near]

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1103]
Eg:

`http://broker.example.org/entities?type=Room&q=temperature<=22&sort=seatNumber`

The parameter could be also used with a sequence of attributes, e.g `sort=seatNumber,temperature`. ASC and DESC order are specified with a `+` (default) and `-` prefix.

`sort=+seatNumber,-temperature`

Feasibility assessment with Mongo shell: https://gist.github.com/fgalan/efd63ef261fa33d91784

**Comment by fgalan** [comment]
Sorting by `creDate` and `modDate` (definitive names pending) should be also possible.

**Comment by fgalan** [comment]
SOF answers that need to be edited when this issue gets completed: http://stackoverflow.com/questions/32703011/change-order-of-orion-response/32712248#32712248

**Comment by fgalan** [comment]
Take into account talso sort by "nearest point". This PR may be useful: https://github.com/telefonicaid/fiware-orion/pull/1651.

**Comment by fgalan** [comment]
SOF answer that need to be edited when this issue gets completed: http://stackoverflow.com/questions/35172155/orion-context-broker-nearest-to-point-query

**Comment by fgalan** [comment]
Code implementation completed in PR https://github.com/telefonicaid/fiware-orion/pull/1815. However, let's keep this issue opened while doc for NGSIv2 get reviewed (and eventually updated) and the questions in SOF edited.

**Comment by fgalan** [comment]
At the end, the name of the URI parameter (to use in the documentation) is `orderBy`

**Comment by fgalan** [comment]
Doc modifications describing `orderBy` implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1818. However, let's keep this issue opened until `orderBy=$near` gets implemented (issue name will be adjusted).

**Comment by fgalan** [comment]
* orderBy=geo:proximity implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1824
* orderBy=dateCreation and orderBy=dateModification implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1829

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests are created in its feature associated

**Comment by fgalan** [comment]
Issues in milestone QATestPendingNotE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
