### ISSUE TITLE
Using special type "date", should be converted to ISODate() in mongo?

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1107]
date: identifies dates, in ISO8601 format. These attributes can be used with the greater than, lesser than, greater or equal, lesser or equal and range query operators.

#### Request:
```
http://<host>:<port>/v2/entities
Fiware-Service: dfgdf
Fiware-ServicePath:/ewe
{
   "type": "room", 
   "id": "room16", 
   "timestamp": {
              "value": "2017-06-17T07:21:24.238Z",
              "type": "date"}
}
```

#### Mongo:
```
{ "_id" : { "id" : "room16", "type" : "room", "servicePath" : "/ewe" }, "attrNames" : [ "timestamp" ], "attrs" : { "timestamp" : { "value" : "2017-06-17T07:21:24.238Z", "type" : "date", "creDate" : 1438079050, "modDate" : 1438081627 } }, "creDate" : 1438079050, "modDate" : 1438081627 }

```

**Comment by fgalan** [comment]
This issue is related (potentially duplicated) with https://github.com/telefonicaid/fiware-orion/issues/1039. Note that date support is not part of the basic functionality in NGSIv2 planned for 0.24.0, thus the milestone has been changed.

**Comment by fgalan** [comment]
At the end, we are using timestamps (i.e. numbers) to store dates at MongoDB. The implementation itself has answered this question :)
