### ISSUE TITLE
Metadata identification based on just 'name' instead of 'name'+'type'

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1112]
*Edit*: this issue was formelly of bug type, but after discussing we have realized it has to do with the fact that metadata are identified by name-type instead of just name (as attributes are). Thus, it is not actually a bug (as it is coherent with the current way of representing name-type) although we acknowledgue that it would be more coherent that metadata behave as the attribute (i.e. identified only by name). The issue has been changed to "backlog" type, as implementing it involves functional changes (and changes in the database model, to use a metadata keymap instead of an array).

Original issue description below (NGSIv2 operations were used):

If we create a new entity with a metadata without type:
```
{"type":"room", "id": "room_2", "temp": {"value": "34", "very_hot": "true"}}
```
And after update the same entity, but, the same metadata append metadata type:
```
{"type":"room", "id": "room_2", "temp": {"value": "34", "very_hot": {"type":"alarm", "value": "true"}}}
```
the metadatas are duplicated in mongo
```
{ "_id" : { "id" : "room_2", "type" : "room", "servicePath" : "/test" }, "attrNames" : [ "temp" ], "attrs" : { "temp" : { "value" : "34", "type" : "", "md" : [ { "name" : "very_hot", "type" : "alarm", "value" : "true" }, { "name" : "very_hot", "value" : "true" } ], "creDate" : 1438340060, "modDate" : 1438340098 } }, "creDate" : 1438340060, "modDate" : 1438340098 }

```

**Comment by fgalan** [comment]
Good catch! This is legacy from the times in which attributes where identified by the name-type combination (attributes behaviour was changed, but not the same for metadata). However, this bug is not related with the functionality covered by 0.24.0, thus I'm changing milestone.

**Comment by iariasleon** [comment]
This issue only appy with POST v2/entities request. first I create a new entity with a metadata without type:
```
 POST http://<host>:<port>/v2/entities/
  Content-Type: application/json
  Fiware-Service: test_happy_path
  Fiware-ServicePath: /test
  {"type":"room", "id": "room_2", "temp": {"value": "34", "very_hot": "true"}}
``` 
and after retry the same request, but, the same metadata append metadata type.
```
 POST http://<host>:<port>/v2/entities/
  Content-Type: application/json
  Fiware-Service: test_happy_path
  Fiware-ServicePath: /test
  {"type":"room", "id": "room_2", "temp": {"value": "34", "very_hot": {"type":"alarm", "value": "true"}}}
```
In the future this second request will return a error "entity does exists", and this case never will occur

**Comment by fgalan** [comment]
Implementation in PR https://github.com/telefonicaid/fiware-orion/pull/2350. However, this issue cannot be considered completed until de migration script is developed.

**Comment by fgalan** [comment]
Migration script and associated doc at PR #2355

**Comment by fgalan** [comment]
This issue is now ready to be tested by QA. @iariasleon if you find it ok, close it, pls.

**Comment by iariasleon** [comment]
LGTM 
```
http code: 422 - Unprocessable Entity
headers:
   date: Thu, 21 Jul 2016 09:13:05 GMT
   fiware-correlator: 551e9d4e-4f23-11e6-b24a-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 56
payload: {"error":"Unprocessable","description":"Already Exists"}
```
