### ISSUE TITLE
If attribute value is the same, metadatas are not updated

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1113]
Part of a functional test to detect this bug:

    echo "01. POST /v2/entities with metadata 'm1' = 1"
    echo "============================================"
    payload='{
      "type":"T1",
      "id": "E1",
      "temp": {
        "value": "1",
        "m1": 1
      }
    }'
    orionCurl --url /v2/entities --payload "$payload" --json
    echo
    echo
    
    
    echo "02. POST /v2/entities with metadata 'm1' = 2"
    echo "============================================"
    payload='{
      "type":"T1",
      "id": "E1",
      "temp": {
        "value": "1",
        "m1": 2
      }
    }'
    orionCurl --url /v2/entities --payload "$payload" --json
    echo
    echo

Mongo dump after running this:

    {
      "_id" : {
        "id" : "E1",
        "type" : "T1",
        "servicePath" : "/" 
      },
      "attrNames" : [ "temp" ],
      "attrs" : {
        "temp" : { 
          "type" : "",
          "creDate" : 1438602795,
          "modDate" : 1438602795,
          "value" : "1",
          "md" : [
           {
              "name" : "m1",
              "value" : 1
            }
          ]
        }
      },
      "creDate" : 1438602795, "modDate" : 1438602795
    }

The value of metadata "m1" should be '2', not '1'.
If I change the value of the attribute "temp" in the second call, then the metadata is updated. Same value for the attribute, no update for the metadata ...

Seems like a bug to me ...

**Comment by fgalan** [comment]
Yes, seems to be a bug.

**Comment by fgalan** [comment]
The problem doesn't happen with string, e.g. using `"m1": "1"` and `"m2": "2"` works fine. Probably it is related with boolean/numbers in v2 for metadata.

**Comment by kzangeli** [comment]
Good, then the bug isn't as 'important' as we thought :-)

**Comment by fgalan** [comment]
Fixed in #1152
