### ISSUE TITLE
Optimize subscriptionsTreat() function

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1114]
subscriptionsTreat() function uses a sub-optimal query for all the subscriptions, i.e. `{}`.

This issue is about using a narrower query, in particular taking into account:

1. Only subscriptions with ONCHANGE
2. Only subscriptions which have at least one element using isPattern=true in the vector.
3. Not expired

**Effort: 2 man day**

**Comment by fgalan** [comment]
Given that now the cache covers now also itPattern=false cusbs, 2 doesn't make sense. I think that 1 was implemented time ago.

The only point to remains is the one about expiration. Should be easy to implement.

**Comment by kzangeli** [comment]
Yes, point 1 was implemented time ago and point two doesn't exist anymore.

Now, about expired subscriptions:
I am not so sure that we *don't* want expired subscriptions in the cache.
If all lookups are done in the cache, and a sub-update-request enters, on an expired subscription (to change its expiration date would be the typical reason to update an expired subscription), then if this subscription is not in the cache, it will not be found. An error will be returned.

So, as long as we allow to update subscriptions, I see no alternative but to keep expired subscriptions in the cache. Unless we decide to do a lookup in mongo also if a sub is not found in the cache (which seems like an insane alternative to me ...).

**Comment by fgalan** [comment]
Thus, I understand by your comment that doing what I suggest regaring item 3 will make complex cache logic (a reason powefull enough to not implementing this issue).

The motivation was to avoid a large cache containing old csubs that are not used anymore, but that "weight" in the cache (for lookups, memory footprint, etc.) but other stretegies can ce used to control that (e.g. garbage-collector.py script).

**Comment by kzangeli** [comment]
I think that what we should do (for v2) is not to allow subs to be modified.
They can always be removed and created anew.
Also, expired subs should be thrown away as soon as they expire.
However, this is not fully backwards-compatible and can probably not be implemented for V1. But for V2, why not?

**Comment by fgalan** [comment]
I think that the ability of modifying a subscripcion is an esential part of NGSIv2. However, doing as you suggest would simplify *a lot* CB logic :)

@jmcanterafonseca what do you think about the possibility of *not* allowding modifying subs in NGSIv2 API?

**Comment by fgalan** [comment]
(I'm closing the issue as I understand that no action will be taken to it. Depending on the follow up conversation about forbidding subscription updating, we could create new issues, of a different kind, probably "backlog" and "APIv2).
