### ISSUE TITLE
GET list of subscriptions

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1116]
It would be pretty nice to be able to ask the broker of its current subscriptions:

GET /v2/subscriptions

Or, based on entity-id or entity-type:

[ For example - I've always been a sucker for URI-params ... :-) ]
GET /v2/subscriptions?entity::id=xxx
GET /v2/subscriptions?entity::type=xyyy

Having these operations/requests would help our users debug their own code for the broker and the op/reqs would even be really helpful for the functional test suite of the broker.

**Comment by fgalan** [comment]
Actually, the one suggested by @jmcanterafonseca is:

```
GET /v2/entities/{entityId}/subscriptions 
```

I'd suggest to change the name of the present issue to:

"GET /v2/entities/{entityId}/subscriptions operation"

(Note that `GET /v2/subscriptions` is a NGSIv2 operation defined in https://docs.google.com/spreadsheets/d/1f4m624nmO3jRjNalGE11lFLQixnfCENMV6dc54wUCCg/edit#gid=0 and and specific issue will be created for that)

**Comment by kzangeli** [comment]
Yeah, I know - sorry about that, I just find that it would be A LOT easier for our users to add the selectors in URI params ...
[ Just my personal opinion. ]

Do we *really* want that many URIs, servicing purposes so similar ... ?

**Comment by fgalan** [comment]
I think the main operation is `GET /v2/subscriptions`. The other operation `GET /v2/entities/{entityId}/subscriptions` is just a helper to get all the subscription associated to a given entity.

However, let be his inventor (@jmcantera) to argue about the need of `GET /v2/entities/{entityId}/subscriptions` :)

**Comment by fgalan** [comment]
Btw, maybe this issue needs a "twin" about the same pattern but for registrations, i.e.: `GET /v2/entities/{entityId}/registrations`.

**Comment by kzangeli** [comment]
Or /v2/registrations?entity::id=XXX ;-)

**Comment by fgalan** [comment]
> Or /v2/registrations?entity::id=XXX ;-)

Let's dissuss the URL in the new issue for that ;)

**Comment by kzangeli** [comment]
ok :-D

**Comment by fgalan** [comment]
This issue is actually taken into accoun in the following issues: 

* #1118: GET /v2/entities/{entityId}/subscriptions
* #1120: GET /v2/types/{typeId}/subscriptions 
* #1126: GET /v2/subscriptions
