### ISSUE TITLE
Functest and v1 for op=append for POST  /v2/entities/<entityId>  [+  replace]

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1127]
More functests for "POST /v2/entities/<entityId>, to add to the PR  #1124

    POST /v2/entities/E1 atribute 'attr2' (and check it is there)
    POST /v2/entities/E1?op=append atribute 'attr3' (and check it is there)
    POST /v2/entities/E1?op=append atribute 'attr3+attr4' (attr3 already exists - make sure attr4 is created and that the operation returns an error about attr3 

Also, if we want to support "appendonly" in v1, tests for that (and possibly modifications in the source code) will be necessary. And, of course, the documentation must be updated to reflect the modifications. Also, changes_next_release will need a line about this (perhaps we should create an issue for only the v1-part-about-append-only).

**Effort: 3 man day**

**Comment by fgalan** [comment]
We have introduced also a "replace" actionType. It would be interesting also as part of this issue to include it in the documetnation, CNR and test harness suite.

**Comment by fgalan** [comment]
Fixed in #1168
