### ISSUE TITLE
check example's source code line length

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1135]
That will make them more readable in readthedocs.org

**Comment by fgalan** [comment]
Do you mean the curl fragments?

**Comment by jmcanterafonseca** [comment]
yes

2015-08-10 10:24 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
We need to define the max length we want to have. Which one should be the right one?

**Comment by jmcanterafonseca** [comment]
No more than 90-100 chars

**Comment by fgalan** [comment]
It has been fixed in https://github.com/telefonicaid/fiware-orion/pull/1166. @jmcanterafonseca , please have a look and close the issue if you find it ok.

**Comment by jmcanterafonseca** [comment]
looks good now by using '\' for line continuation

thanks
