### ISSUE TITLE
Add Table of Contents

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1136]
At least for the README.md file or in those files where a long content might deserve it

**Comment by fgalan** [comment]
What about the README.md in docker/ ?

**Comment by fgalan** [comment]
Discussed at skype: README.md in docker/ will not include ToC.

@jmcanterafonseca could you close this issue if you find ToCs are ok, pls?

**Comment by jmcanterafonseca** [comment]
Some TOCs are a bit strange, for instance the README on which all the items are children of the Introduction one ...

**Comment by fgalan** [comment]
Fixes needed in README.md:

* Convert "Introduction" in a second level section, i.e. use "##" instead of "#"
* "Introduction" should appear at the same level than the other points, not as the parent of all them. The fix would be just to indent "* Introduction" at the same level of the next point.

**Comment by fgalan** [comment]
Problem on: 

* https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/database_admin.md
* https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/database_model.md
* https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/diagnosis.md
* https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/logs.md
* https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/user/filtering.md

"Introduction" should appear at the same level than the other points, not as the parent of all them. The fix would be just to indent "* Introduction" at the same level of the next point.

In addition, first-level section (the one with `#`) should be reserved only for the document title at the very top of the document. Introduction should use `##`.

**Comment by fgalan** [comment]
In https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/user/walkthrough_apiv1.md we have the same problem described above:

> In addition, first-level section (the one with `#`) should be reserved only for the document title at the very top of the document. Introduction should use `##`.

**Comment by fgalan** [comment]
Fixed in PR #1213
