### ISSUE TITLE
Simple Query : Support conditions over attribute structured content

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1156]
Example 

``` js
{ 
   "temperature": {
      "value": 23,
      "accuracy": 0.1
   }
}
```

```
q=temperature.accuracy < 0.1
```

Please note that this should work in the case of metadata or in the case of values which are actually Javascript objects. 

``` js
{
   "category": ["luxury", "spanish"]
}
```

```
q=category|=spanish
```

category field contains spanish

or

```
q=category|=[spanish, luxury]
```

category either spanish or luxury 

```
q=category&=[spanish, luxury]
```

category contains at least both spanish and luxury 

```
q=category==[spanish, luxury] 
```

category is exactly an array with two elements spanish and luxury.

**Comment by fgalan** [comment]
What about referring to a particular element of a list? Do we want to support that kind of use case?

**Comment by jmcanterafonseca** [comment]
I cannot see the use case because depending on an specific position in the array can be problematic

**Comment by fgalan** [comment]
The answer to the following question at SOF have to be edited before closing this issue: http://stackoverflow.com/questions/32735329/search-by-attribute-value-orion-ngsiv2/32742522#32742522

**Comment by fgalan** [comment]
JsonPath (http://goessner.net/articles/JsonPath) could be useful as source of inspiration (thanks to 
marcc-orange for the feedback!)

**Comment by jmcanterafonseca** [comment]
My wishlist here is to allow querying without specifying the whole path
i.e. if I have

{
   address {
        "addressCountry": "ES",
        "postalCode": "39001",
        "addressLocality": "Santander"
    }
}

I could specify my query as

/v2/entities?q=addressCountry:ES

without having to say explicitly address.addressCountry

Of course whenever there is ambiguity, an error should be raised.

2016-02-02 20:16 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
> My wishlist here is to allow querying without specifying the whole path

Achieve that could be hard, taking into account the DB model for the entities. I'd suggest to go step by step. First, to implement filtering for structure values (and metadata) knowing the path to the element used to filter. In a second phase, we can analyze how to achieve "free path" filtering.

**Comment by jmcanterafonseca** [comment]
oh, yes probably you are going to need to extend the DB Model ... as this
is a new functionality ... not present in previous versions ...

2016-02-03 15:24 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by kzangeli** [comment]
A feature of this kind will require a lot of processing power of the broker and for gaining a feature that isn't *that* interesting.

To find 'addressCountry', we first need to lookup all attributes, if not found (or even if found?), lookup all metadata of all attributes ...

Not sure we really want this.

If the feature is only for metadatas, and **only to avoid having to add the attribute name in the query**, in my opinion it is not worth it. If on the other hand it is meant for compound values, and to find some attribute in deeper levels in a compound ... then perhaps I would see its value ...

**Comment by fgalan** [comment]
Changes in NGSIv2 WIP .apib partially addressed in https://github.com/telefonicaid/fiware-orion/pull/2337.

In particular, the part regarding "free search without knowing the path" hasn't been included in that PR.

**Comment by kzangeli** [comment]
About filtering over an attribute/metadata with wrong type:

It is costly, both implementation-wise and especially in run-time to assure that the used type in a filter coincides with the type the attribute/metadata (or item in a JSON value), e.g.:

    ?q=A>10

The attribute A is assumed to be a Number, and the issuer of a request like this will know that A is actually a Number. Now, if A is some other type (the issues made a mistake), the outcome is undefined. It depends on how the database treats this 'invalid' filter.

We don't see this as a problem. It should never occur.

[ And, if the future proves us wrong, we know what to do to fix the problem. ]

**Comment by fgalan** [comment]
Completed at NGSIv2 spec (*). Changing milestone to 1.3.0 (version in which this is going to be implemented at Orion).

(*) For the parts not covered in the current NGSIv2 spec (e.g. free search without knowing the path) a new issue should be created.

**Comment by fgalan** [comment]
Metadata filtering implemented in PR #2367

**Comment by fgalan** [comment]
Compound attributes filtering implemented in PR #2385

**Comment by fgalan** [comment]
Compound attribute filtering in notifications (expression.q) implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2403:

What is pending after that PR:

* Compound metadata filtering implemented for mq=
* Compound metadata filtering in notifications (expression.mq)

**Comment by fgalan** [comment]
Compound metadata filtering implemented for mq= in PR https://github.com/telefonicaid/fiware-orion/pull/2423

What is pending after that PR:

* Compound metadata filtering in notifications (expression.mq)

**Comment by fgalan** [comment]
Final PR with compound metadata filtering in notifications (expression.mq): https://github.com/telefonicaid/fiware-orion/pull/2430

**Comment by fgalan** [comment]
Some final .test implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2436

**Comment by fgalan** [comment]
Ready for QA testing.

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/019_pep2cbv2_filteronstructuredcontent.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
