### ISSUE TITLE
POST /v2/entities must return error if the entity to create already exists

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1158]
It would return the following error:

HTTP status code: 422 Unprocessable Entity
Payload:

```
{
   "error": "AlreadyExists",
   "description": "Entity already exists"
}
```

**Comment by fortizc** [comment]
I send a pull request but it haven an error because my code broke the "update or append entity atribute". The main problem is know when is a update or an append. Any ideas?

**Comment by fortizc** [comment]
I found a way to check when a operation is an "entity creation" or an "update or append entity atribute" if we check the uriParams map, when is a "update or append entity atribute" it have a "op" key, because in this operation some options can be added.

**Comment by fortizc** [comment]
what if we move buildGeneralErrorResponse() method from MongoCommonUpdate.cpp to mongoUpdateContext.cpp and we catch all exceptions in mongoUpdateContext() ??

**Comment by fgalan** [comment]
> what if we move buildGeneralErrorResponse() method from MongoCommonUpdate.cpp to mongoUpdateContext.cpp and we catch all exceptions in mongoUpdateContext() ?? 

Let's consider that, but please create a new issue to discuss about it (note that the present issue is about AlreadyExists error and it is better to keep independent topics in independent issues).

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1295. @iariasleon please have a look and close if if you find it ok.

**Comment by iariasleon** [comment]
LGTM
tested with:
 - only id, 
 - id and type,
 - id, type and service_path
```
http code: 422
{
    "error":"InvalidModification",
    "description":"Entity already exists"
}
```
