### ISSUE TITLE
Convenience operations that perform registry should use service function postRegisterContext

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#116]
### Description
All convenience operations that does any type of registration must also forward to configuration manager.
This is taken care of by the service routine postRegisterContext, so instead of inventing a new service routine, the already existing postRegisterContext should be used.
The RegisterProviderRequest must be transformed to a RegisterContextRequest and postRegisterContext be called.

**Effort: 5 man day**

**Comment by kzangeli** [comment]
This was implemented in the set PRs that made ALL convops use stdops not so long ago (2 months?).

**Comment by fgalan** [comment]
Yes, it is already implemented (although not remember in which Orion version :)
