### ISSUE TITLE
XML parsing is ignoring CDATA

### ISSUE THREAD

**Issue by pjt33** [telefonicaid/fiware-orion#1163]
If I submit a context element

	<?xml version="1.0" encoding="UTF-8"?>
	<updateContextRequest>
	  <contextElementList>
		<contextElement>
		  <entityId type="Bug" isPattern="false">
			<id>Bug1</id>
		  </entityId>
		  <contextAttributeList>
			<contextAttribute>
			  <name>foo</name>
			  <type>string</type>
			  <contextValue><![CDATA[myValue]]></contextValue>
			</contextAttribute>
		  </contextAttributeList>
		</contextElement>
	  </contextElementList>
	  <updateAction>APPEND</updateAction>
	</updateContextRequest>

then I get the response

	<updateContextResponse>
	  <contextResponseList>
		<contextElementResponse>
		  <contextElement>
			<entityId type="Bug" isPattern="false">
			  <id>Bug1</id>
			</entityId>
			<contextAttributeList>
			  <contextAttribute>
				<name>foo</name>
				<type>string</type>
				<contextValue></contextValue>
			  </contextAttribute>
			</contextAttributeList>
		  </contextElement>
		  <statusCode>
			<code>472</code>
			<reasonPhrase>request parameter is invalid/not allowed</reasonPhrase>
			<details>action: APPEND - entity: [Bug1, Bug, false] - offending attribute: foo - empty attribute not allowed in APPEND or UPDATE</details>
		  </statusCode>
		</contextElementResponse>
	  </contextResponseList>
	</updateContextResponse>

But the attribute is clearly not empty when submitted, so the parser must be ignoring the `CDATA` element.

**Comment by fgalan** [comment]
XML support was deprecated in Orion 0.23.0 (see https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/deprecated.md). Would it be possible to use JSON in your case?

**Comment by pjt33** [comment]
What precisely is deprecated, and what precisely do I need to change? The `notifyContextRequest` message which is sent to my subscribed context is definitely still XML, so is it that all messages *to* Orion should be changed to use JSON, but all recipients of messages *from* Orion should continue to expect XML?

**Comment by kzangeli** [comment]
Deprecated is perhaps not the correct word. XML is still supported for backwards compatibility but **all** new implementation is done solely in JSON. Some day, XML will be completely removed from the broker. The date of this change is not fixed.

**Comment by fgalan** [comment]
Not sure if applies to your case, but you can subscribe using XML and receive notifications in JSON (or vicversa), see https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Cross-format_notifications.

However, my recomendation is to adapt your clients and  notification receivers to JSON. As @kzangeli explains, XML is no longer our focus (based on developers community feedback, most of people are using JSON nowdays).
