### ISSUE TITLE
Clearer error on "PUT /v2/entities/<entityId>/attrs/<atrtrName>" without 'value' in payload

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1164]
A `PUT /v2/entities/<entityId>/attrs/<atrtrName>` without { "value": "xxx" } in the payload gives an error. The error message is not clear at all and should be improved.

The error is due to the broker demands an attribute to have a value. Doing a PUT, the entire state of the attribute is replaced by the new state and if no "value" is present ... then it is an error.

For now it seems the broker will keep working this way and we just need to return a clearer response. However, another approach would be to loosen the restriction on 'value' mandatory for attributes and let the request through.

**Effort: 1 man day**

**Comment by fgalan** [comment]
The error will use "422 unprocessable entity" as HTTP status code and "InvalidModification" in the `error` text. The `description` feld would include an explanation about value is missing.

The .apib for v2 has to be edit as part of this issue to include the new error in the documentation.

**Comment by rbl219** [comment]
With code modifications currently implemented to resolve this issue,  generated error response will be:

'''
HTTP/1.1 422 Unprocessable Entity
Content-Length: 96
Content-Type: application/json
Date: Wed, 16 Sep 2015 18:13:34 GMT

{"error":"Invalid Modification","description":"Empty attribute not allowed in APPEND or UPDATE"}
'''

You consider this response is correct, or some improvements should be made?

**Comment by fgalan** [comment]
Just to know... before modifications, which error message was being generated?

**Comment by fgalan** [comment]
Some recomendations on the new error message:

* Use `InvalidModifications` (without whitespace)
* I

**Comment by rbl219** [comment]
Before modifications error was:



HTTP/1.1 472 Unknown
Content-Length: 0
Date: Wed, 16 Sep 2015 15:10:11 GMT

**Comment by kzangeli** [comment]
Just one comment on this ...
We are now to allow requests with attributes without 'value'.
Perhaps it should be allowed here too ?

**Comment by fgalan** [comment]
We are allowing request without 'value' in operations where it make sense (e.g. PATCH), but in this case the `PUT /v2/entities/<entityId>/attrs/<atrtrName>` semantics are "throw away value/type/metadata of the attribute and replace it by the value/type/metadata in the payload of the request". Given that 'value' is mandatory in NGSI, this particular operation has to have a 'value' field.

Anyway, given that this issue is about adjusting the error message (as far as I understand) and that this error message could be re-used in some other places, I have suggested a neutral wording (see my comment above).

**Comment by fgalan** [comment]
>  this particular operation has to have a 'value' field.

Of course, that value could be the empty string "" (taking into account the current ongoing work in #1188)

**Comment by kzangeli** [comment]
That's what I were referring to, I expressed myself badly ...

**Comment by rbl219** [comment]
I have changed error description and included new error in V2 apiary

**Comment by rbl219** [comment]
This issue has been resolved in PR #1245. @iariasleon, please have a look to it and close it if you find is solved.

**Comment by fgalan** [comment]
Actually, this issues was not raised by QA so it can be closed without @iariasleon verification.
