### ISSUE TITLE
Implement vector for URI param 'options'

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1169]
The URI param **options** can take as value a comma-separated list of *options*.
We need to parse this list and store it as a vector.
Furthermore, we need a lookup-function, like:

    bool uriOptions(const std::string& name)

Also, if any unsupported option enters, the broker should immediately respond with a 400 Bad Request.

Now, the request **GET /v2/type** needs to use this function (PR #1171)

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1178
