### ISSUE TITLE
Remove entire convenienceMap layer

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#117]
### Description
The convenienceMap layer has proven not necessary and should be removed completely.
What is done in the convenience map functions should be done in the corresponding service function (that currently invokes the convenience map function).

These convenience service functions should transform the incoming structures into their corresponding standard structures (e.g. RegisterProviderRequest into RegisterContextRequest) and call the service function for the standard operation.

**Effort: 30 man day**

**Comment by kzangeli** [comment]
Actually, the later shouldn't be removed, but modified.
There are cases with more than one convop translated to one and the same standard op.
So, the translation of the input data to 'standard op input data' should be implemented in the library convenienceMap.  Also the translation of 'standard output data' to 'convop output data'.

**Comment by fgalan** [comment]
In addition, we have been talking about a change name:

> Refactorize convenienceMap library. The new name will be convenienceTranslation and will be used from serviceRoutines. The serviceRoutines functions will keep the “flow control” instead of the current approach in which some operations are passed to convenienceMap (i.e. convenienceMap is able to invoke mongBackend). In the new approach, only serviceRoutines library can invoke mongoBackend (in some cases, one convop-oriented serviceRoutine function will invoke a “sibling” standard-operation oriented serviceRoutine)

**Comment by kzangeli** [comment]
Finally, I believe no library will be necessary (which means the convenienceMap library will disappear).
The new functionality is added to fill methods for the standard request types. More elegant IMHO.

**Comment by fgalan** [comment]
Sound good. I'm eager for seening the first PR about this :)

**Comment by kzangeli** [comment]
Fixed by a number of PRs on branches called **hardening/117_XXX**
