### ISSUE TITLE
Implement options=values for the request  "GET /v2/types"

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1170]
The URI parameter **options=values** must be implemented for the request

```
GET /v2/type
```

**Comment by fgalan** [comment]
An operation in mongoBackend will be implemented for this (using the current ony will be inefficient, i.e. time is wasted getting entiies counts and attribute types that are removed at the end at rendering time).

In addition, moved from "techdebt" to "backlog".

**Comment by fgalan** [comment]
Implement this issue *after* implementing https://github.com/telefonicaid/fiware-orion/issues/1833

**Comment by fgalan** [comment]
Call to getAttributeTypes() should be avoided (to avoid the same problem that described at https://github.com/telefonicaid/fiware-orion/issues/2073)

**Comment by fgalan** [comment]
Implemented in PR #2132

**Comment by fgalan** [comment]
Moved to the QATestPending until corresponding acceptance tests get implemented.

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/014_pep2cbv2_typesoperation.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
