### ISSUE TITLE
Fix the mess in names of types/files regarding /v2/type

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1173]
He have four different types to serve the requests /v2/type and /v2/type/<typeName>:

* TypeEntity
* TypeEntityVector
* EntityTypeAttributesResponse
* EntityTypesResponse

EntityTypeAttributesResponse is:

    TypeEntity
    StatusCode

EntityTypesResponse is:

    TypeEntityVector
    StatusCode

The names are **very** confusing.

I would change these type names to:

* TypeEntity => EntityType
* TypeEntityVector  => EntityTypeVector
* EntityTypeAttributesResponse => EntityTypeResponse
* EntityTypesResponse => EntityTypeVectorResponse

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR #1243
