### ISSUE TITLE
Redirect standard output and errors of the Orion service

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-orion#1175]
The command to start Orion in the RPM service currently looks like this:
```
su $BROKER_USER -c "${EXECUTABLE} ${BROKER_OPTS} &> /dev/null
```
It redirects the standard output and error to null. This should be changed, in order to redirect all this information to a secondary log in the `/var/log/contextBroker` folder.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Currently contextBroker.log contains the same that contextBroker bimnary prints in stdout (using a different line format), so we only need stderrr. We could use contextBroker.stderr as name.

This contextBroker.stderr is not a regular log file and it is expected to be small, so I don't think we need associated logrotate configuration.

My only doubt right now is if we should append or clean the file eacth time the contextBroker service is restarted...

**Comment by kzangeli** [comment]
It should be enough with saving one old copy of the file, like this:

    mv contextBroker.stderr contextBroker.stderr.old
    contextBroker 2> contextBroker.stderr

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/1270
