### ISSUE TITLE
[BUG] creation of DBs recursively in contextBroker-0.23.0_20150824123458-1.x86_64.rpm version

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1186]
I see that in contextBroker-0.23.0_20150824123458-1.x86_64.rpm version multiples DBs are created recursively (concatenating orion in name)
Ex:
```
> show dbs
admin                                                         (empty)
local                                                         0.031GB
orion                                                         0.031GB
orion-orion                                                   (empty)
orion-orion-orion                                             (empty)
orion-orion-orion-orion                                       (empty)
orion-orion-orion-orion-orion                                 (empty)
orion-orion-orion-orion-orion-orion                           (empty)
orion-orion-orion-orion-orion-orion-orion                     (empty)
orion-orion-orion-orion-orion-orion-orion-orion               (empty)
orion-orion-orion-orion-orion-orion-orion-orion-orion         (empty)
orion-orion-orion-orion-orion-orion-orion-orion-orion-orion   (empty)
orion-orion-orion-orion-orion-orion-orion-orion-orion-pepe_1  (empty)
orion-orion-orion-orion-orion-orion-orion-orion-orion-pepe_2  (empty)
orion-orion-orion-orion-orion-orion-orion-orion-pepe_1        (empty)
orion-orion-orion-orion-orion-orion-orion-orion-pepe_2        (empty)
orion-orion-orion-orion-orion-orion-orion-pepe_1              (empty)
orion-orion-orion-orion-orion-orion-orion-pepe_2              (empty)
orion-orion-orion-orion-orion-orion-pepe_1                    (empty)
orion-orion-orion-orion-orion-orion-pepe_2                    (empty)
orion-orion-orion-orion-orion-pepe_1                          (empty)
orion-orion-orion-orion-orion-pepe_2                          (empty)
orion-orion-orion-orion-pepe_1                                (empty)
orion-orion-orion-orion-pepe_2                                (empty)
orion-orion-orion-pepe_1                                      (empty)
orion-orion-orion-pepe_2                                      (empty)
orion-orion-pepe_1                                            (empty)
orion-orion-pepe_2                                            (empty)
orion-pepe_1                                                  0.031GB
orion-pepe_2                                                  0.031GB
```

Menssage in mongo log:
```
2015-08-25T12:27:21.907+0200 [conn6] assertion 16256 Invalid ns [orion-orion-orion-orion-orion-orion-orion-orion-orion-orion-pepe_1.csubs]
```

Menssage in CB log:
```
2015-08-25T12:27:21.908+0200 [conn6] assertion 16256 Invalid ns [orion-orion-orion-orion-orion-orion-orion-orion-orion-orion-pepe_2.csubs] ns:orion-orion-orion-orion-orion-orion-orion-orion-orion-orion-pepe_2.csubs query:{}
```

### Steps:
1- install last rpm 
2- request:
```
        http://<host>:1026/v2/entities
        Fiware-Service: happy_path
        Fiware-ServicePath: /test
         {"id": "room_0", "type": "room", "timestamp_0": {"type": "date", "value": "017-06-17T07:21:24.238Z", "very_hot_1": {"type": "alarm", "value": "Afe1BuMTcf"}, "very_hot_0": {"type": "alarm", "value": "Afe1BuMTcf"}}}
```
3- Review dbs in mongo `show dbs` and CB log

**Comment by LeandroGuillen** [comment]
I found another way to present the bug.

I have two CBs (0.23 of July 27th and 0.23 of August 24th) connected to a MongoDB 2.6 instance. Only by starting them I get the following state:

	> show dbs
	admin   (empty)
	local   0.078125GB
	orion   0.078125GB
	orion-orion     0.078125GB
	orion-orion-orion       0.078125GB
	orion-orion-orion-orion (empty)
	orion-orion-orion-orion-orion   (empty)
	orion-orion-orion-orion-orion-orion     (empty)
	orion-orion-orion-orion-orion-orion-orion       (empty)
	orion-orion-orion-orion-orion-orion-orion-orion (empty)
	orion-orion-orion-orion-orion-orion-orion-orion-orion   (empty)
	orion-orion-orion-orion-orion-orion-orion-orion-orion-orion     (empty)

The one causing the problem is the newer version from August (I called it _orionnew\_1_):

	orionnew_1 | ERROR@09:51:20  SubscriptionCache.cpp[297]: Database Error (error retrieving _id field in doc: '{ $err: "Invalid ns [orion-orion-orion-orion-orion-orion-orion-orion-orion-orion-orion.csubs]", code: 16256 }')

And then this string of requests that repeat every 10 seconds exactly:

	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})
	orionnew_1 | INFO@09:51:40  MongoGlobal.cpp[2856]: Database Operation Successful ({})

This has to do with the new subscription cache, obviously. I'll take a closer look at the code, although this would be probably fastest done by @kzangeli  :)

**Comment by LeandroGuillen** [comment]
By the way, if you need to reproduce this bug I have set up an environment with a docker-compose and a script (available upon request).

    orionold:
      image: centos:6
      ports: 
        - "1026:1026"
      volumes:
        - .:/data
      links: 
        - mongo
      command: /bin/bash data/install_orion1.sh

    orionnew:
      image: centos:6
      ports:
        - "1027:1026"
      volumes: 
        - .:/data
      links: 
        - mongo
      command: /bin/bash data/install_orion2.sh

    mongo:
      image: mongo:2.6

**Comment by fgalan** [comment]
>This has to do with the new subscription cache, obviously

This error was observed in the CI platform (where we have `ftest-ftest-ftest-fest` etc). That would mean is is not acused by the new implementation on subscription cache (although it may happen that due to some unknown reason, the existence of the subscription cache increases the probability the problem happens).

**Comment by fgalan** [comment]
The problem seems to be caused by the wrong usage of database name in the getSubscribeContextCollectionName() function invocation in the subscriptions cache. The PR #1208 should fix it.

**Comment by iariasleon** [comment]
LGTM
