### ISSUE TITLE
Creating an entity with attribute value empty string

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/fiware-orion#1187]
POSTing an entity whit attr "" returns 200 OK, but the entity is not created (or not GETable)

Try https://github.com/telefonicaid/fiware-orion/blob/dbb0bfbad282132317fa28aba864f5e3905f397c/test/functionalTest/cases/1185_udpate_change_value_type/create_empty_string.test

**Comment by fgalan** [comment]
This is maybe related with #1188. Probably it should be addressed after #1188 get solved.

**Comment by fgalan** [comment]
Fixed along with #1188
