### ISSUE TITLE
Update an attribute to empty string

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/fiware-orion#1188]
Changing an attribute to empty string ("") gives a 472 Unknown

Try https://github.com/telefonicaid/fiware-orion/blob/dbb0bfbad282132317fa28aba864f5e3905f397c/test/functionalTest/cases/1185_udpate_change_value_type/update_empty_string.test

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1247
