### ISSUE TITLE
[BUG]  Entity is created without attribute value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1195]
If try to create a entity without attribute value, 

-  with attribute type:
```
 {"type": "room", "temperature": {"type": "alarm"}, "id": "room2_1"}
```

The entity is created (201)  and response:
```
{"id":"room2_1","type":"room","temperature":{"type":"alarm"}}
```

- with metadata:
```
 {"type": "room", "temperature": {"very_hot_1": {"type": "alarm", "value": "hot"}, "very_hot_0": {"type": "alarm", "value": "hot"}}, "id": "room2_0"}
```

The entity is created (201)  and response:
```
{"id":"room2_0","type":"room","temperature":{"very_hot_1":{"type":"alarm","value":"hot"},"very_hot_0":{"type":"alarm","value":"hot"}}}
```

**Comment by kzangeli** [comment]
See #1196

**Comment by fgalan** [comment]
This issue is related with the JSON format for representing entities/attributes/metadata, which is currently under discussion. Thus, it has been deferred to milestone 0.26.0.

**Comment by iariasleon** [comment]
LGTM

Tested with:
 1- attribute without any field (value, type and metadata)
 2- attribute without value but with type
 3- attribute without value but with metadata 
```
http code: 400
{
       "error":"BadRequest",
       "description":"no 'value' for ContextAttribute without keyValues"
}
```
