### ISSUE TITLE
[BUG] Entity is updated or appended by entity_id without attribute value

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1196]
If try to update or append an entity by id `POST /v2/entities/<entity_id>`

  with attribute type:
```
 pepe_2":{"type":"dfrty"}
```

The entity is updated  or appended if it does not exist (201)  :
```
{"id":"room_9","type":"room","pepe":"ququ","pepe_2":{"type":"dfrty"}}
```

- with metadata:
```
{"pepe_2": {"alarm":{"type":"dfrty", "value": "34"}}}
```

The entity is updated  or appended if it does not exist (201)  :
```
{"id":"room_9","type":"room","pepe":"ququ","pepe_2":{"alarm":{"type":"dfrty","value":"34"}}

**Comment by kzangeli** [comment]
In all these examples there is a value for the attributes.
Actually, it is not even possible to update/create an attribute without value.
We have three cases:

SIMPLE:            "a": <string|int|bool|vector>
OBJECT:           "a": { "value": xxx, ... }
COMPOUND:   "a": { "no_value_in_obj": "therefore a compound", ... }

So, should this issue be closed as 'not an issue' ?

**Comment by fgalan** [comment]
This issue is related with the JSON format for representing entities/attributes/metadata, which is currently under discussion. Thus, it has been deferred to milestone 0.26.0.

**Comment by raconte** [comment]
####  Create an entity 
```
(curl localhost:1026/v2/entities -s -S --header Content-Type:application/json --header 'Accept: application/json' -d @- | python -mjson.tool)<< EOF
{
  "type": "Apartment",
  "id": "Floor20",
  "temperature": {
    "value": "24.4"
  }
}  
EOF
```


#### Append an entity without an attribute value only the type
```
(curl localhost:1026/v2/entities/Floor20 -s -S --header Content-Type:application/json --header 'Accept: application/json' -d @- | python -mjson.tool)<< EOF
{
	"temperature_2": {
		"type": "celsius"
	}
}
EOF
```

The response is:
```
{
    "description": "no 'value' for ContextAttribute without keyValues",
    "error": "BadRequest"
}

```
#### Append the metadata (as the example shown)
```
(curl localhost:1026/v2/entities/Floor20 -s -S --header Content-Type:application/json --header 'Accept: application/json' -d @- | python -mjson.tool)<< EOF
{
	"temperature_2": {
		"alarm": {
			"type": "noise",
			"value": "34"
		}
		
	}
}
EOF
```
The response 
{
    "description": "no 'value' for ContextAttribute without keyValues",
    "error": "BadRequest"
}

**Comment by iariasleon** [comment]
LGTM
```
{
    "description": "no 'value' for ContextAttribute without keyValues",
    "error": "BadRequest"
}
```
