### ISSUE TITLE
[BUG] error in documentation "Update or append entity attributes"

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1197]
http://telefonicaid.github.io/fiware-orion/api/v2/ in  "Update or append entity attributes" `Optional parameters` do not match.

In Info:
```
Optional Parameters
op 	Operation options. Allowed values: append.
```
In console:
```
Parameters
    options    Strict append.    Example: append.     String
```

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1204. @iariasleon , pls have a new look to the web reference to check that now it correct, then close issue.

**Comment by iariasleon** [comment]
LGTM
