### ISSUE TITLE
[BUG] in update/append by ID, if entity_id does not exists, the entity is created 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1206]
### Request: 
```
http://<host>:<port>/v2/entities/ghfhfg
Fiware-Service: happy_path
Fiware-ServicePath: /test
{"alarm": false}
```

### Mongo:
```
{ "_id" : { "id" : "ghfhfg", "servicePath" : "/test" }, "attrNames" : [ "alarm" ], "attrs" : { "alarm" : { "type" : "", "creDate" : 1441366314, "modDate" : 1441366314, "value" : false } }, "creDate" : 1441366314, "modDate" : 1441366314 }
```
The entity should not be created and the expected response,  would be:
```
Status 404 Not Found
{
      error: "NotFound"
      description: "The requested entity has not been found. Check type and id"
}
```

**Comment by fgalan** [comment]
At the end, this is the normal behaviour. However, .apib NGSIv2 documentation should be improved (section: "Update or append entity attributes" in "Entity by ID") including the following sentence just before "Response":

"If the entity doesn't previously exist, it is created."

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/1166/files#diff-d5ec9d3a1874c68d6328577a86cd5dc0

@iariasleon please check that NGSIv2 spec document is ok after merging this PR and close the issue in that case.

**Comment by iariasleon** [comment]
LGTM 
```
If the entity doesn't previously exist, it is created.
```
