### ISSUE TITLE
[BUG] if mongo is restarted, Context Broker is stopped

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1210]
### Options used

 `BROKER_EXTRA_OPS="-multiservice -t 0-255"` - with these options CB is stopped

 `BROKER_EXTRA_OPS="-multiservice -t 0-255 -subCacheIval 0"` - with these options CB is not stopped

**Comment by fgalan** [comment]
Fixed in PR #1211. This issue will be closed by @iariasleon , once the PR gets merged and he can test that new version of the code is ok.

**Comment by iariasleon** [comment]
LGTM
