### ISSUE TITLE
Subscriptions & request forwarding

### ISSUE THREAD

**Issue by dgebaei** [telefonicaid/fiware-orion#1225]
I've got two questions regarding Orion subscriptions.

1. If we register entity with provider application url in Orion and create a subscription for it (e.g. sending updates every 15 minutes), what will happen if there is no data in Orion's local DB? Will it query data provider to fetch data from specified url and then return this a subscription update, or will it return nothing?

2. This is somewhat related to the first one. Is there an option to specify "max duration" of an attribute value in Orion's local DB (e.g. if an attribute is not updated in 1 hour, delete it's value)?
We have the following example in mind: A subscription is set up for an entity to send update every 15 minutes to our server. Updates from sensors to Orion should be done every 5 minutes. Now, if something is not working with the sensor and it stops sending updates, we will get the last value stored in Orion DB forever, unless there's the "max-duration" option for that attribute that deletes the value if it's not changed in specified time period.
When subscription update is triggered, in case that there's no value for that attribute in Orion's local DB, it should query the provider application for data (Q1).

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the product become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, it is better to ask your question using that platform, using the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

It would be great if you could "move" your questions to SOF. Don't worry, if you cannot, we will do it (and include the links to the questions as comments in this issue).

**Comment by dgebaei** [comment]
Thanks, it's here http://stackoverflow.com/questions/32519080/subscriptions-request-forwarding, you can delete this then, and try to give me a response there :)
