### ISSUE TITLE
Change order of orion response

### ISSUE THREAD

**Issue by danigonza** [telefonicaid/fiware-orion#1246]
Hi!

I'm calling orion with a Geo-location filter, like this one:
```
(curl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
  "entities": [
  {
    "type": "City",
    "isPattern": "true",
    "id": ".*"
  }
  ],
  "restriction": {
    "scopes": [
    {
      "type" : "FIWARE::Location",
      "value" : {
        "circle": {
          "centerLatitude": "40.418889",
          "centerLongitude": "-3.691944",
          "radius": "13500"
        }
      }
    }
    ]
  }
}
EOF
````
I read on the fiware orion documentation that the returned entities are returned by increasing entity/registration creation time. Like is explained [here](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Pagination)

There is the possibility to change this behaviour?

Thanks in advance!!

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the product become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, it is better to ask your question using that platform, using the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

It would be great if you could "move" your questions to SOF. Don't worry, if you cannot, we will do it (and include the links to the questions as comments in this issue).

**Comment by fgalan** [comment]
Posted in SOF: http://stackoverflow.com/questions/32703011/change-order-of-orion-response. This issue will be closed and the discussion will continue there.
