### ISSUE TITLE
Query Orion Context Broker by Dates

### ISSUE THREAD

**Issue by nespapu** [telefonicaid/fiware-orion#1249]
I tried to query by dates interval in Orion 0.24 with no success.

A call to:

    URL: http://<some-ip>:<some-port>/v2/entities?type=some-entity

Gives:

    [
      {
        "id": "some-id",
        "type": "some-entity",
        "coordenadas": {
          "type": "geo:point",
          "value": "43.7723705, -7.6784461"
         },
         "fecha": {
           "type": "date",
           "value": "2015-08-21T22:00:00.000Z"
         },
     },
     {
        "id": "some-id",
        "type": "some-entity",
        "coordenadas": {
           "type": "geo:point",
           "value": "43.6850207, 7.5716216"
        },
        "fecha": {
            "type": "date",
            "value": "2015-09-09T22:00:00.000Z"
        }
      }
    ]

Then I query by dates interval in the following ways:

Call 1:

    http://<some-ip>:<some-port>/v2/entities?type=some-entity&q=fecha==2015-08-01..2015-08-30

Call 2:

    http://<some-ip>:<some-port>/v2/entities?type=some-entity&q=fecha==1441065601..1443657601
    
Both calls respond with a 200 code and payload []. I also tried other operators '>', '<' with the same result.

In the [documentation](http://telefonicaid.github.io/fiware-orion/api/v2/) says we can store dates, so I am doing so. Should I store them as numbers?

thanks

**Comment by fgalan** [comment]
Answered at StackOverflow: http://stackoverflow.com/questions/32630801/query-orion-context-broker-by-dates/32654581#32654581
