### ISSUE TITLE
Return parse error if not needed fields are found

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1256]
For example, in the case of

```
PUT /v2/entities/e1/attrs/a

{
  "value": "foo",
  "type": "bar",
  "should_not_be_here": "xxx"
}
```

The existence of `should_not_be_here` should raise a parse error.

**Comment by fgalan** [comment]
This issue is not especifically related with NGISv2, so APIv2 label is removed. The issue keeps opened.

CC: @jmcanterafonseca

**Comment by Anjali-NEC** [comment]
Fixed issue in PR#4049

**Comment by kzangeli** [comment]
Wait ...
Parse Error?
No, an unexpected item in a correctly parsed JSON payioad should **not ever** give a parse error!
Parse Errors should give parse errors, nothing else.

Quite straightforward, don't you think? ;-) 

A "strange" item in a payload should complain about **unexpected item** or something similar

**Comment by Anjali-NEC** [comment]
> Wait ... Parse Error? No, an unexpected item in a correctly parsed JSON payioad should **not ever** give a parse error! Parse Errors should give parse errors, nothing else.
> 
> Quite straightforward, don't you think? ;-)
> 
> A "strange" item in a payload should complain about **unexpected item** or something similar

I think you are correct.  I have fixed this issue according to the comment in https://github.com/telefonicaid/fiware-orion/issues/1256#issue-107490829 But it shouldn't raise parse error so I reverted my changes.

Thanks

**Comment by kzangeli** [comment]
Ok! Good!
Not your fault.
Fermin's initial comment about "The existence of should_not_be_here should raise a parse error" is misleading.

**Comment by kzangeli** [comment]
Old, old issue! (2015) ... :)
At that time, we still didn't know very well what we were doing, Fermin and I  :)

**Comment by fgalan** [comment]
I have had a look to #1256. It seems you are covering only a very specific case (in the attribute parsing logic) but this issue is more general. Is about detecting unknown fields in **every possible** JSON object in **every possible** JSON request.

If a general solution is not possible, you should add a similar code in too many places. And .test cases to covering all them. It seems to be be a lot of effort taking into account the usefulness of this issue (not too high). Maybe it's better to put effort on another issues.

**Comment by kzangeli** [comment]
Last thought on 
```
"should_not_be_here": "xxx"
```

That would work just fine is key-values is turned on.
And if not, the value of "should_not_be_here" would need to be a JSON object, which it isn't.

Hopefully, Orion has this "Object check" already covered and giving an error of "Not a JSON Object".

I'm starting to doubt this entire issue ...

In short:
* If key-values, all OK
* If no key-values: invalid JSON type of the value of "should_not_be_here"

It's not that it "shouldn't be there". It's OK to be there, but the JSON type of the value must be a JSON object if key-values is not used.

...   Right?

**Comment by fgalan** [comment]
> Last thought on
> 
> ```
> "should_not_be_here": "xxx"
> ```
> 
> That would work just fine is key-values is turned on. And if not, the value of "should_not_be_here" would need to be a JSON object, which it isn't.
> 
> Hopefully, Orion has this "Object check" already covered and giving an error of "Not a JSON Object".
> 
> I'm starting to doubt this entire issue ...
> 
> In short:
> 
>     * If key-values, all OK
> 
>     * If no key-values: invalid JSON type of the value of "should_not_be_here"
> 
> 
> It's not that it "shouldn't be there". It's OK to be there, but the JSON type of the value must be a JSON object if key-values is not used.
> 
> ... Right?

Note the request:

```
PUT /v2/entities/e1/attrs/a
```

Thus, it is an attribute update (not an entity update) so keyValues mode doesn't make sense there.

However, it's just an example. The whole point is to avoid elements in the JSON payloads that are not part of the API. Each request type would have different cases. But I'm unsure of the usefulness of this issue if covering each case would involve a lot of effort.

**Comment by kzangeli** [comment]
Sure, key-values or not, the error is not that "it doesn't belong", the error is that it's not a JSON object (for PUT /v2/entities/e1/attrs/a).

Checking for "should not be there" makes a lot of sense for creating/updating registrations and subscriptions.
Not so much for entity operations, as there, the error is another one, and it should really be covered already.

I'm also surprised to hear that registration/subscription requests don't give errors already for unexpected fields ...

**Comment by fgalan** [comment]
> Sure, key-values or not, the error is not that "it doesn't belong", the error is that it's not a JSON object (for PUT /v2/entities/e1/attrs/a).

I think I don't get your point... Under my understading both when it's not a JSON object

```
PUT /v2/entities/e1/attrs/a

{
  "value": "foo",
  "type": "bar",
  "should_not_be_here": "this is a string"
}
```

and when it is a JSON object

```
PUT /v2/entities/e1/attrs/a

{
  "value": "foo",
  "type": "bar",
  "should_not_be_here": {
    "x": 1,
    "y": 2
  }
}
```

are wrong are none of them complies with the NGSIv2 API.

**Comment by kzangeli** [comment]
Ehh ... yes, if you insist on having an erroneous value :)
BUT, the error is NOT that is "doesn't belong".
The error is that "there's no type for the attribute" and, "there's no value for the attribute.
It's perfectly OK to be there, but the JSON content has some constaraints. If not fulfilled, them THAT is the error to report.

To make it clearer, imagine the following payload body:
```
PUT /v2/entities/e1/attrs/a

{
  "value": "foo",
  "type": "bar",
  "should_not_be_here": {
    "type": "String",
    "value": 2
  }
}
```

Should it still "not be there" ?

**Comment by fgalan** [comment]
> To make it clearer, imagine the following payload body:
> 
> ```
> PUT /v2/entities/e1/attrs/a
> 
> {
>   "value": "foo",
>   "type": "bar",
>   "should_not_be_here": {
>     "type": "String",
>     "value": 2
>   }
> }
> ```
> 
> Should it still "not be there" ?

This should response with 400 Bad Request error, as the only allowed first-level keys in this kind of payload are `value`, `type` and `metadata` and the string `should_not_be_here` don't belong to these three allowed cases.

**Comment by kzangeli** [comment]
Ah, so that's the confusion then. I was sure there was something ... :)

You group the metadata inside a "metadata" object in V2 ... ?
NGSI-LD doesn't work that way.

Sorry, my bad. Short memory.

**Comment by fgalan** [comment]
Thinking on this 6 years after :)...

Implementing this issue could take a significative effort and even it could not be a good idea... Some existing integrations using waterfall patterns may be adding extra fields (a typical situation in which the JSON object used in the API is used also in other places by the client system) and could break if we are too strict.
