### ISSUE TITLE
[BUG] in update PATCH some errors not return error and description in response

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1260]
- In case of the unknown entity is returned a 404, but without error and description in de body response.

###### Expected:
```
{
    "error": "NotFound",        (mandatory)
    "description": "..............."   (optional)
}
```
- In case of more than one entity with the same id is returned a 409, but without error and description in de body response.

###### Expected:
```
{
    "error": "TooManyResults",        (mandatory)
    "description": "There is more than one entity that match the update. Please refine your query."(optional)
}

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1281. @iariasleon please check that it is ok and close the issue in that case.

**Comment by iariasleon** [comment]
Some tests still are not  been verified because depend of another issues: 
- https://github.com/telefonicaid/fiware-orion/issues/1106
- https://github.com/telefonicaid/fiware-orion/issues/1278
- https://github.com/telefonicaid/fiware-orion/issues/1212

**Comment by raconte** [comment]
As it has been mentioned in this bug in case of the unknown entity is returned a message : error:"Not found" and the corresponding description.

For the second case, when there are more than one entity with the same id , also returns the corresponding  message  "error":"TooManyResults" and the description. 

So this bug no longer exists

**Comment by raconte** [comment]
#### Create an entity
```
(curl localhost:1026/v2/entities --header Content-Type:application/json -d @- | python -mjson.tool)<< EOF
{
	"type": "flat",
	"id": "apartment_1",	
	"temperature_2": {
		"value": 40
	}
}
EOF
```
#### GET unknown entity 
```
(curl localhost:1026/v2/entities/room1234 -s -S --header Content-Type:application/json --header 'Accept: application/json'| python -mjson.tool)
```
Response :
```
{
    "description": "The requested entity has not been found. Check type and id",
    "error": "NotFound"
}
```
#### Create entity (POST)
```
(curl localhost:1026/v2/entities --header Content-Type:application/json -d @- | python -mjson.tool)<< EOF
{
	"type": "house",
	"id": "apartment_1",	
	"temperature_2": {
		"value": 40
	}
}
EOF
```
#### GET the entitie with the ID--> apartment_1
```
(curl localhost:1026/v2/entities/apartment_1 -s -S --header Content-Type:application/json --header 'Accept: application/json'| python -mjson.tool)
```
#### Response 
```
{
    "description": "There is more than one entity with that id. Refine your query.",
    "error": "TooManyResults"
}
```
Solved

**Comment by raconte** [comment]
#### Intent to patch a non-existing entity
```
curl localhost:1026/v2/entities/Floor3 -s --header Content-Type:application/json --header 'Accept: application/json' -X PATCH | python -mjson.tool
```
The response is: 
```
{
    "description": "The requested entity has not been found. Check type and id",
    "error": "NotFound"
}

```

#### Create two entities (same id)

(curl localhost:1026/v2/entities -s -S --header Content-Type:application/json --header 'Accept: application/json' -d @- | python -mjson.tool)<< EOF
{
  "type": "House",
  "id": "Floor3",
  "temperature": {
    "value": 24.4
  }
}  
EOF
```
```
(curl localhost:1026/v2/entities -s -S --header Content-Type:application/json --header 'Accept: application/json' -d @- | python -mjson.tool)<< EOF
{
  "type": "Apartment",
  "id": "Floor3",
  "temperature": {
    "value": 27.4
  }
}  
EOF
```
#### Update entity (PATCH) 
```
(curl localhost:1026/v2/entities/Floor3 -s --header Content-Type:application/json --header 'Accept: application/json'-X PATCH | python -mjson.tool)<< EOF
{
  "temperature": {
    "value": 27.4
  }
}
EOF
```
The response is:
```
{
    "description": "There is more than one entity with that id. Refine your query.",
    "error": "TooManyResults"
}
```

Solved

**Comment by iariasleon** [comment]
LGTM
