### ISSUE TITLE
Report CLI invalid parameters that a "super-string" of a valid one of flag type

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1282]
Note the different behaviour when the user miss the CLI argument, either `-foo` or `-multiservicex`:

```
[fermin@centollo contextBroker]$ contextBroker -multiservicex
Usage: contextBroker  [option '-U' (extended usage)]
                      [option '-u' (usage)]
                      [option '--version' (show version)]
                      ...

[fermin@centollo contextBroker]$ contextBroker -foo
option '-foo' not recognized

Usage: contextBroker  [option '-U' (extended usage)]
                      [option '-u' (usage)]
                      [option '--version' (show version)]
                      ...
```

A `option '-multiservicex' not recognized` message should be printed also in the first case, but it isn't.

It could be due to the parsing argument library is prepared to process no-flag arguments in a no-whitespace mode, i.e. `-port1026` as an alias for `-port 1026`.

**Effort: 2 man day**

**Comment by kzangeli** [comment]
This is a bug.
A value is given to a bool option (-multiservice).
The error is detected, but no warning message is printed on stdout.

The text "-multiservice: bool option" or something similar should be printed.

**Comment by fgalan** [comment]
For me the ideal error message is 

'-multiservicex' not recoginezed

as in the Orion CLI (https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/cli.md) -multisercice is defined as flag value, without parameters (i.e. it is not defined as `-multiservice true`. Of course, internally we use a bool for managing that, but the user shouldn't be bother with that detail.

**Comment by kzangeli** [comment]
I would prefer to just 'tell the truth'.
A text like this:
  option '-multiservice' is a boolean option - cannot have a value (XXX)

parseArgs is a 'stand-alone' library and will be used for more projects in the future.
However, we could let the user modify the treating of this error (paConfig) and have both ways.
The default behaviour should be to 'tell the truth' though.

**Comment by fgalan** [comment]
Alternative:

'-multiservice' is a flag option - cannot have any value (XXX)

In my opinion, a "boolean option" is an option that accept "true" or "false", and that is not what is described at https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/cli.md for multiservice.

**Comment by fgalan** [comment]
(My last comment applies to cases like `-multiservice foo`, not to the `-multiservicex` case, which is ok with "'-multiservicex' not recognized").

**Comment by kzangeli** [comment]
"-multiservice foo" is perfectly correct.
-multiservice is a boolean option and foo is another option or parameter.
Just like "ls -l foo"

**Comment by fgalan** [comment]
That's correct in a general purpose library, but not in the CLI implemented by CB. In CB all the parameters use `-parameter` (except some old ones with use `--parameter`).

(However, this seems to be off-topic, as it this issue is about parameters with unknown name assuming "whitespace separation" syntax, which as far we have discussed at skyp and in some minutes I'll review in the PR, is ok).

**Comment by kzangeli** [comment]
Yes, this is true.
I see the parseArgs library more as a standalone library while you see it as a 'broker specific library'.
I will do everything possible to 'tailor' the parseArgs library to the needs of the broker, but, I can't destroy its genericness in the process - it is still a standalone generic library, and will be used in more projects after the context broker.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1574
