### ISSUE TITLE
[QUESTION] Index Key Limit in mongo

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1283]
see http://docs.mongodb.org/v2.6/reference/limits/#indexes

in CB the primaries keys are compound by id, type and service-path.

About the reference, the limit is 1024 bytes (no chars), the service-path only could be 510 chars (in case of use special chars a few more), therefore, id and type together must be less than 500 bytes aprox.

What would be the maximum values for id and type with this limitation?

**Comment by fgalan** [comment]
By the time being, I think that documentation provides that information. Thus, maybe this issue can be closed.
