### ISSUE TITLE
Strip broker code from iotAgent stuff

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1302]
We may have some old code for the iotAgent left in the broker.
This should be investigated and if found, this old, now unused, code should be removed from the broker.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Changed to nice-to-have (in my opinion, it is not so critical to be "should").

**Comment by fgalan** [comment]
No traces of "iota" or "iotagent" in the code at the present moment, so I understand this issue can be closed (probably most of the pending iotagent code was removed along with XML stuff when working on #1862).
