### ISSUE TITLE
BUG: PUT Individual Attribute with 'empty' JSON object as payload is accepted

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1303]
PUT /v2/entities/E1/attrs/A1 with an empty payload should give an error.

**Comment by fgalan** [comment]
By empty payload I understand you mean "{ }". I understand that true empty payload (i.e. content lengh equal to 0 in request) in a PUT/POST/PATCH message is already captured as error by the HTTP communications layer (please, tell me if I'm wrong).

I would extend this bug to other operations that should return error in the same situation. I guess that every operation using PUT, POST or PATCH, as they are used to create/update things and it doesn't makes sense to create/update something without providing the input to do that creation/update.

**Comment by kzangeli** [comment]
Yes, this issue is meant for an 'empty' JSON object - i.e. the payload isn't really empty ... even though the JSON object doesn't really contain anything.

The title has been changed to reflect this.

Requests without payloads, i.e. content length == 0, is another story.
I can only assume we have functests covering this, and that it works just fine.
Should be investigated, of course.

About including ALL requests in this issue ... This issue is about a detected bug, it's something specific that we know fails.
I would prefer to create a separate issue about 'everything else', and another one to assure that "truly empty" payloads are treated correctly.

**Comment by fgalan** [comment]
> I would prefer to create a separate issue about 'everything else', and another one to assure that "truly empty" payloads are treated correctly.

Having an issue covering all and issues that are particular case of that "all" is a little bit of issue-aucracy (as in "bureaucracy" :), but if you prefer so, fine with me.

**Comment by kzangeli** [comment]
Issues already created ...

**Comment by rbl219** [comment]
After studying the issue, we are found that it does not is a bug
