### ISSUE TITLE
Make sure the broker responds correctly to requests without payloads

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1304]
Not sure how to provoke this, using curl.

Perhaps it is as easy as sending a curl without payload (defaults to a GET), changing the verb with the -X switch ...
OR: -D "" might work also (perhaps ...)

To make sure the broker handles this correctly, we need a functest sending a POST, PUT or PATCH without payload.
Not sure that we need a functest for every type of request/verb. It would be good, of course, it just seems like A LOT of work and perhaps it's a little bit of an overkill ... 

**Effort: 1 man day**

**Comment by fgalan** [comment]
Not sure, but I think that -X could make the trick.

**Comment by fgalan** [comment]
Regarding:

> Not sure that we need a functest for every type of request/verb

Let's use a reasonable sampling.

**Comment by fgalan** [comment]
After looking in deep, it seems that this is currently rightly covered by tests. Thus, this issue is closed without action.
