### ISSUE TITLE
Test PUT/POST/PATCH with 'empty' JSON object as payload

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1305]
Using the empty JSON object {} as payload, all 'payload-expecting' requests should be tested, to make sure they all behave as expected.

What is expected?
Well, I guess they should all return an error.

**Effort: 2 man days**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1341
