### ISSUE TITLE
IsDouble + string2double

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1306]
Now that we have a possible solution to the problem about assuring a string is a 'double', let's add a few functions to the 'common' lib:

    bool isDouble(char*);
    bool string2double(char* s, double* dP);  // return FALSE if 's' does NOT contain a double

Also, all uses of atof, strtod and similar functions must be looked up and made use these new functions instead of whatever they are using right now.

Already known cases:
Case 1: PUT .../attribute/value   with Content-Type text   (See PR #1299)
Case 2: Fermin had a similar problem not long ago - there we probably can use these new functions as well
Case X: any other uses of atof, strtod etc ...

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR #1762
