### ISSUE TITLE
API v2: Create subscription

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1316]
Implement the following operation in in v2:

```
POST /v2/subscriptions
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Once NGSIv2 subscription get fully implemented ("fully" meaning the posibility of implement filters using the `condition` field) the answer to question http://stackoverflow.com/questions/33669300/fiware-orion-context-broker-restrictions-on-subscriptions/33752490#33752490 should be properly edited.

**Comment by fgalan** [comment]
The answer to the following question at SOF has to be edited upon this issue completion: http://stackoverflow.com/questions/34136801/orion-context-broker-v2-subscription-issue/34187804#34187804

**Comment by fgalan** [comment]
Basic creation implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1650. However, this issue should be kept opened until actual expression evaluation (at least for `q`) gets implemented.

**Comment by fgalan** [comment]
Subscription q expression evalution upon update entity implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1687

**Comment by fgalan** [comment]
Initial notification taking into account filters implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1691

**Comment by fgalan** [comment]
At the present moment, the tasks that remain to close this issue are related with cache. In particular, to take into account q, georel, geometry and coords in the cache entries (adjust addTriggeredSubscription_withCache needed, look for `FIXME P10 #1316` in the code).

Moreover, it could be a good idea not storing `q` as string but as a class, in order to parse once time (i.e. the moment in which the cache entry is populated) intead of each time a new update context arrives and the expression is evaluated from the cache entry. The same idea could be extended to the other three: georel, geometry and coord (not currently used but they will be in the near future).

**No need of new test harness**. Just look for `# FIXME P10: replace with just 'brokerStart CB' once cache part gets implemented` inside cases/1316_XX .test and adjust `brokerStart` line consecuently.

**Comment by fgalan** [comment]
Finished in PR #1704. The task about using objects instead of string for expression has been defered to a tech debt issue: https://github.com/telefonicaid/fiware-orion/issues/1705

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by iariasleon** [comment]
LGTM
