### ISSUE TITLE
[BUG] if attr name has "." is replace by "=" in "attrNames" field after replace attribute by ID request

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1323]
If attribute name has a "."  in replace attributes by ID request `PUT /v2/entities/<entity_id>`, this char is replaced by "=" in a `"attrNames"` field in mongo.

#### Create request:
```
POST http://<host>:<port>/v2/entities
Content-Type: application/json 
Fiware-Service: happy_path
Fiware-ServicePath: /test
{"id": "room_0", "timestamp.0": "pepe"}
```

#### Doc in mongo after of create the entity:
```
{ "_id" : { "id" : "room_0", "servicePath" : "/test" }, "attrNames" : [ "timestamp.0" ], "attrs" : { "timestamp=0" : { "type" : "", "creDate" : 1444055885, "modDate" : 1444055885, "value" : "pepe" } }, "creDate" : 1444055885, "modDate" : 1444055885 }
```

#### Replace request:
```
PUT http://<host>:<port>/v2/entities/room_0 
Content-Type: application/json 
Fiware-Service: happy_path
Fiware-ServicePath: /test
{"alarm.pepe": true}
```

#### Doc in mongo after of replace the entity:
```
{ "_id" : { "id" : "room_0", "servicePath" : "/test" }, "attrNames" : [ "alarm=pepe" ], "attrs" : { "alarm=pepe" : { "type" : "", "creDate" : 1444056031, "modDate" : 1444056031, "value" : true, "md" : [ ] } }, "creDate" : 1444055885, "modDate" : 1444056031 }
```

**Comment by crbrox** [comment]
Do you have a test case showing the impact in functionality? (Maybe a GET of an attribute not working, I guess)

**Comment by iariasleon** [comment]
feature: `replace_attributes_by_id.feature` in `test/acceptance/behave/components/ngsiv2/entities`
name: `replace attributes by entity ID using NGSI v2 with several attribute names` 
tag:  `attribute_name_replace`
cases: 2 and 7
if try a GET of an entities `/v2/entities/room` the response succesfully.
ex:
```
{
    "id":"room_0",
    "alarm.pepe":true
}
```

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/1331

**Comment by iariasleon** [comment]
LGTM
