### ISSUE TITLE
Pause subscriptions

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1328]
Use the `status` field in a subscription in order to "pause" (so status changes to "paused") or "resume" (so status changes to "active" or "expired").

**Comment by jmcanterafonseca** [comment]
We need to take into account that the initial status of a subscription could not be active, but suspended or paused.

**Comment by fgalan** [comment]
.apib changes in PR #1926

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1998. Moving to QATestPending milestone so @iariasleon can test and finally close it.

**Comment by iariasleon** [comment]
LGTM
implemented in https://github.com/telefonicaid/fiware-orion/blob/develop/test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_status.feature
