### ISSUE TITLE
[INTEGRATION] Error retrieving entities created without "ispattern"

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1338]
If several entities are created without attribute "ispattern" and the entitity names are very similar (e.g MOBA_test and MOBA_test2) the entitiy cannot be retrieved. CB answer with the incorrect entitity.

This fact occurs when the name of one entity is contained in another entity.

see Internal reference: DM-663

**Comment by fgalan** [comment]
It seems to be a duplicated of the (currently closed): https://github.com/telefonicaid/fiware-orion/issues/1322

**Comment by iariasleon** [comment]
LGTM
tested in v1
