### ISSUE TITLE
APIv1 empty values support.

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1358]
Currently, trying to create/update an empty value (i.e. value set to "") or not include attribute at all leads to this error: `"action: APPEND - entity: [Room2, Room, false] - offending attribute: temperature - empty attribute not allowed in APPEND or UPDATE"`

Thus, in some way, we are breaking backward compatibility as something that results in an error in a previous version, now it is not  an error anymore. However, it shouldn't be a problem (it would be a problem in the opossite case).

This issue is somehow related with https://github.com/telefonicaid/fiware-orion/issues/1077 (already closed) for APIv2.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1373

**Comment by iariasleon** [comment]
LGTM
```
  <version>0.25.0-next</version>
  <git_hash>4b8e7621ec3e742a89bb7dcee0a06a0609163173</git_hash>
```
