### ISSUE TITLE
GCC stack protector

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1359]
When adding the options 

    -fstack-check -fstack-protector

to the compiler, the broker doesn't compile.
These extra warnings might be very useful for the broker, we should use this (only as debugging tools)

**Effort: 3 man day**

**Comment by fgalan** [comment]
Current CMakeLists.txt is ready for this. It is only a matter of uncomenting the line:

```
add_definitions(-fstack-check -fstack-protector)
```

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1418
