### ISSUE TITLE
Time measures in the broker itself

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1367]
The way we measure the time spent waiting for semaphores, we could "easily" implement for **blocks** of the code in the broker.
Typical blocks would be 
- jsonParse
- xmlParse
- jsonParseV2
- xmlRender
- jsonRender
- mongoBackend
- mongoSubCache (which is really a part of mongoBackend ...)

And probably many more.

As time measuring is time consuming, we would only perform these measurements if a CLI is set, just like we do with the semaphore waiting time (-mutexTimeStat).
To see the statistics, we'd just use the GET /statistics, just like with mutex-times.
No real reason to invent a new REST request for this (I wouldn't mind though: GET /profiling).

**Comment by fgalan** [comment]
Not sure if I name this issue "profiling", which is a more wider topic. I will focus in the time measure, so probably "time measure in the context broker" maybe.

**Comment by kzangeli** [comment]
Sure, just rename the issue :-)

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1502
