### ISSUE TITLE
Possible problem in functests due to database-name/tenant 

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1375]
dbInit and dbDrop accept a database-name as input, when they should instead have a tenant-name as input, prepending the 'basename' of the DB.
The basename should be set in testEnv.sh and used by dbInit/dbDrop

[ CB_DATABASE_NAME **is** the basename, but a different variable should be used ]

The potential problem is that scripts/testEnv.sh might be modified, changing the base-name (currently 'ftest'), here:

    export CB_DATABASE_NAME=${CB_DATABASE_NAME:-ftest}
    export CM_DATABASE_NAME=${CM_DATABASE_NAME:-ftest_cm}
    export CP1_DATABASE_NAME=${CP1_DATABASE_NAME:-ftest_cp1}
    export CP2_DATABASE_NAME=${CP2_DATABASE_NAME:-ftest_cp2}
    export CP3_DATABASE_NAME=${CP3_DATABASE_NAME:-ftest_cp3}
    export CP4_DATABASE_NAME=${CP4_DATABASE_NAME:-ftest_cp4}
    export CP5_DATABASE_NAME=${CP5_DATABASE_NAME:-ftest_cp5}

This should be something like:

    export DATABASE_NAME_BASE=ftest
    export CB_DATABASE_NAME=${CB_DATABASE_NAME:-$DATABASE_NAME_BASE}
    etc. (not even sure that last line even is correct ...)

[ This problem all originates in the fact that the broker will not recognize **any** database. The databases **must** start with the prefix 'DATABASE_NAME_BASE', which is 'orion' for a normal run of the broker and 'ftest' when the broker is running in a functional test ]

The functests (one line per dangerous db) with this possible problem are:

    0713_propagate_tenant/propagate_tenant_for_update_and_query_standard_ops.test:dbInit ftest-t1
    0713_propagate_tenant/propagate_tenant_for_update_and_query_standard_ops.test:dbInit ftest-t2
    0713_propagate_tenant/propagate_tenant_for_update_and_query_standard_ops.test:dbInit ftest_cp1-t1
    0713_propagate_tenant/propagate_tenant_for_update_and_query_standard_ops.test:dbInit ftest_cp1-t2
    1308_subscription_cache/subCacheThrottlingAndExpirationAfterRefresh.test:dbInit ftest-t1
    1308_subscription_cache/cache_reset_from_db.test:dbInit ftest-t1
    1308_subscription_cache/cache_reset_from_db.test:dbInit ftest-t2
    1308_subscription_cache/subCacheThrottlingAndExpiration.test:dbInit ftest-t1

**Effort: 1 man day**

**Comment by fgalan** [comment]
Old text in duplicated #1374:

(Raised in https://github.com/telefonicaid/fiware-orion/pull/1372#discussion_r42214899)

We shouldn't use dbInit to initialize tenant DBs in this way:

```
dbInit ftest-t1
```

As the "ftest" part depends on a env variable (CB_DATABASE_NAME).

It would be better to use something like this:

```
dbInitTenant CB t1
```

Same situation probably with dbDrop (not checked yet).

All the .test should be reviewed. This may happen in mutiple places.

**Comment by fgalan** [comment]
Changed to nice-to-have (in my opinion, it is not so critical to be "should").

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1436
