### ISSUE TITLE
CLI '-reqMutexPolicy' silently accepts any value

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1377]
Usage says:

    [option '-reqMutexPolicy' <mutex policy (none/read/write/all)>]

Now, if -reqMutexPolicy is fed "nada", then "all" (which also is the default value) is silently picked.

Perhaps the broker should die with an error message instead?

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1435
