### ISSUE TITLE
[BUG] in update request /v2/entities/<ID>/attrs/<ATTR_NAME> with two entities with the same id

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1387]
in update request `/v2/entities/<ID>/attrs/<ATTR_NAME>` with two entities with the same id
Ex:
#### create request Nº1
```
POST http://localhost:1026/v2/entities
Content-Type: application/json
Fiware-Service: test_update_more_entities
Fiware-ServicePath: /test
{"temperature_2": "34", "type": "house", "id": "room"}
```

#### create request Nº2
```
POST http://localhost:1026/v2/entities
Content-Type: application/json
Fiware-Service: test_update_more_entities
Fiware-ServicePath: /test
{"temperature": "67", "type": "home", "id": "room"}
```

####  Update by id and attr name 
```
PUT http://localhost:1026/v2/entities/room/attrs/temperature
Content-Type: application/json
Fiware-Service: test_update_more_entities
Fiware-ServicePath: /test
{"value": "80"}
```
####  Response
```
 http code: 204
 content-length: 0
```
And both entites are updated in mongo 
```
{ "_id" : { "id" : "room", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "80", "type" : "", "creDate" : 1445334741, "modDate" : 1445334741}}, "creDate" : 1445334741, "modDate" : 1445334741 }
{ "_id" : { "id" : "room", "type" : "home", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "80", "type" : "", "creDate" : 1445334741, "modDate" : 1445334741}}, "creDate" : 1445334741, "modDate" : 1445334741 }
```

#### Expected
```
http code: 409 Conflict
{ 
   "error":  "TooManyResults",                                                                 
    "description": "There is more than one entity that match the update. Please refine your query."
}
```

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1757. @iariasleon please have a look to check it has been solved.

**Comment by iariasleon** [comment]
Tested with:
version: 0.27.0-next 
hash: 2228e50076ebe0757a19ade0201223f477e60856

The same behavior, several entities with the same id (types different), try to update an attribute data, and the response is without payload (body):
```
http code: 409
date: Wed, 24 Feb 2016 13:45:25 GMT
connection: Keep-Alive
content-length: 0
```

**Comment by fgalan** [comment]
Ok, Devel will have a second look on this.

**Comment by iariasleon** [comment]
if we try to update an id uknown, returns without payload too.
```
http code: 404
date: Wed, 24 Feb 2016 14:09:52 GMT
connection: Keep-Alive
content-length: 0
```

**Comment by fgalan** [comment]
>  Devel will have a second look on this.

(Not sure if this will be fixed by @crbrox , @kzangeli or me. Thus, let's have this unsasigned by the moment).

**Comment by kzangeli** [comment]
So, after creating a functest for this, the only problem with this issue seems to be the 'missing' payload.
Do we want error payload for 409?
In my opinion, 409 is self-explanatory.
After receiving it, the users should take a look at their request payload.

Perhaps we solve this issue by solving issue #1360? (which would mean this issue can be closed.)

The PR #1757 seems to have it working with /v2/entities/<eid>/attrs/<attr-name>/value, whereas this issue is about  /v2/entities/<eid>/attrs/<attr-name>, but we can see in the functest of PR #1757 that there is payload in the 409 ...

**Comment by iariasleon** [comment]
LGTM
```
http code: 409
date: Tue, 15 Mar 2016 10:45:07 GMT
connection: Keep-Alive
content-type: application/json
content-length: 98
{     
      "error":"TooManyResults",
      "description":"More than one matching entity. Please refine your query"
}
```
