### ISSUE TITLE
[BUG] in a feature name in http://telefonicaid.github.io/fiware-orion/api/v2/

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1393]
Url: http://telefonicaid.github.io/fiware-orion/api/v2/   --> Attribute Value --> By Entity ID --> Get attribute data 
GIT: https://github.com/telefonicaid/fiware-orion/blob/develop/doc/apiary/v2/fiware-ngsiv2-reference.apib#L715

The **Get attribute data** name  should be replaced by the **Get attribute value** name.

**Comment by fgalan** [comment]
LTTM (passing the ball to @kzangeli for final LGTM + merge + delete branch)

**Comment by fgalan** [comment]
It seems that current spec hasn't this problem. Assigned to @iariasleon for checking again.

**Comment by iariasleon** [comment]
LGTM
