### ISSUE TITLE
Statistics: include counter for requests w/o payload

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1400]
A bug was fixed for release 0.25.0 - incoming requests without payload were counted as XML requests. Now, a new counter has been added in statisticsUpdate (lib/common/statistics.cpp) but it is not yet added to the response of "GET /statistics".
Should be added - lots of functests and one unittest will fail upon adding this counter.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/3855/
