### ISSUE TITLE
Semaphore for subCache when mutex policy is none

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1401]
Right now, the subscription cache uses the mongo request semaphore, but this has an *important* limitation - the broker cannot be started with -mutexPolicy != all, unless also -noCache is present.

To fix this, the subscription cache needs a semahpore of its own, in case the mongo request semaphore is not in use.

And, this must be removed from contextBroker.cpp:

    if ((strcmp(reqMutexPolicy, "all") != 0) && (noCache == false))
    {
      LM_E(("Bad Input (reqMutexPolicy != 'all'  AND  subscription-cache CANNOT be used together in 0.24.0 (cache can be disabled using -noCache))"));
      exit(1);
    }

**Effort: 2 man day**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1435
