### ISSUE TITLE
Too long tenant names

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1403]
The max length of a tenant is set to 50 characters.
If a request comes in with a tenant name that is longer than 50, it is just silently shortened to 50.
This is pretty dangerous as this could give complications.
If somebody uses the broker with 2 "different" tenants that are equal until byte 50 and then different in byte 51, this user will believe he's working on two different tenants when really he has only one tenant:

    tenant1 = this_is_the_very_long_name_of_my_tenant_more_than_fifty_chars_01
    tenant2 = this_is_the_very_long_name_of_my_tenant_more_than_fifty_chars_02

Both these tenants will have the name "this_is_the_very_long_name_of_my_tenant_more_than_", and only **one** database will be used.

The broker should detect this and return an error.

**Effort: 1 man day**

**Comment by kzangeli** [comment]
This issue was fixed in PR #1402.
In MongoGlobals.h, MAX_SERVICE_NAME_LEN was changed from 1024 to 50 and
in RestService.cpp (function tenantCheck()), this is done:

#define MAX_TENANT_NAME_LEN            50
  if (strlen(name) > MAX_TENANT_NAME_LEN)
  {
    LM_W(("Bad Input (a tenant name can be max %d characters long. Length: %d)", MAX_TENANT_NAME_LEN, strlen(name)));
    return "bad length - a tenant name can be max " MAX_TENANT_NAME_LEN_STRING " characters long";
  }

Unfortunately we have two different definitions for tenant max length:
  - MAX_SERVICE_NAME_LEN in MongoGlobals.h   and
  - MAX_TENANT_NAME_LEN  in RestService.cpp

Perhaps we should do something about this ...

**Comment by fgalan** [comment]
So now we have two definitions, both set to 50.

I'd suggest to unify and have only one definition (maybe in globals.h, as placeholder for global constants?).

**Comment by kzangeli** [comment]
Yes, I fully agree

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/1572.
