### ISSUE TITLE
mongo sub cache to own library

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1405]
The sub cache currently resides completely in the mongoBackend library.
However, part of the implementation of the cache has nothing to do with mongo and should be moved from mongoBackend. Either to a new library (perhaps 'cache'?) or to some existing one.

Function from sub-cache to stay in mongoBackend:

    Perhaps only one function:
    o mongoSubCacheRefresh(std::string database) (or the part of the function that retrieves subs from mongo)

    Then we have two functions that use BSONObj, but no direct contact with mongo:
    o mongoSubCacheItemInsert(const char* tenant, const BSONObj& sub)?
    o mongoSubCacheItemInsert(const char* tenant, const BSONObj& sub, const char* subscriptionId, const char* servicePath)?

I would extract the part of mongoSubCacheRefresh that actually queries mongo and put that single function in mongoBackend, everything else out to a new 'cache' library.
Not to forget, EntityInfo could/should have its own header and source file.

**Effort: 2 man day**

**Comment by fgalan** [comment]
I'd suggest to move the old code to archive/ in the case we want to preserve at 0.25.0 releasing time.

**Comment by kzangeli** [comment]
sure, why not

**Comment by fgalan** [comment]
Code moved in PR https://github.com/telefonicaid/fiware-orion/pull/1434. Good enough for 0.25.0 (this issue could be moved to the next milestone).

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1557
