### ISSUE TITLE
Unify addTriggeredSubscriptions functions

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1408]
The functions 

* addTriggeredSubscriptions_noCache and 
* addTriggeredSubscriptions_withCache 

share a lot of code and a few helper functions should be extracted to avoid the copies of source code.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Given the evolution of the csubs cache to cover all ONCHANGE subcription (i.e. no matter if pattern or not) in 0.26.0, both functions are now very different, so the original idea of refactoring common code doesn't make sense any longer. Thus closing.
