### ISSUE TITLE
APIv2: what makes entities unique?

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1409]
In the "Terminology" section it is currently written that an entity is uniquely identified by its ID.

On the other hand, in the "Entity by ID" section a potential conflict between several entities having the same ID is mentioned. 

We had this discussion already when defining NGSI 1...

Possible solutions are
 (1) Entities are uniquely identified by their ID
 (2) Entities are uniquely identified by the combination of their ID and their type. The absence of a type is interpreted like a special type, say *null*. This means e.g. that updating an entity without specifying its type will update the entity with the *null* type, but not affect an entity with the same ID but type *my_type*. When querying an entity ID without specifying its type, only the entity with the *null* type is returned.
 (3) Entities are uniquely identified by the combination of their ID and type. Specification of an ID with absence of a type is interpreted as "all entities with that ID". For example, whenever in a query the type is not specified and there are several entities with that ID, all of them (or an error; to be discussed) are returned. When updating an entity without specifying the type, the update is applied to all entities with that ID, or an error is returned (to be discussed).

In my view 1) is the simplest approach and good enough for any practical scenario I can think about.

What is your opinion?

**Comment by fgalan** [comment]
Not clear yet what is the best option, but to provide some feedback:

1) is the simplest approach but we have to take into account the following consideragion in the OMA NGSI spec (section 5.2.1):

> Context Entities are identified using an entity identifier (EntityId). The optional entity type may be needed when the EntityId doesn’t contain type information or when the EntityId is only unique per entity type.

So "the EntityId is only unique per entity type" means that they are considering cases in which EntityId could be reused in different types. In fact, it is not an uncommon case: users may identify their entities by numbers and use type to distinguish between the Car entity with number 1234 and the Road entity with number 1234.

If we adopt approach 1) we are going againts OMA NGSI data model. This is not necesarily a problem, as far as we are aware and understand the uses cases that wouldn't be possible.

Next approach in simplicty is 2). Regarding 3) it is more complex (although the way in which Orion implements NGSIv1 is closer to 3) that any other...).

**Comment by tobiasjacobs** [comment]
if users really make use of the possibility to have the same ID for different entities of different types, it is a good reason not to remove that possibility.

What is also thinkable is a variant of 3) where the absence of type is translated into the assumption that the entity is uniquely identified by the ID. If this assumption is found by the server not to be valid, an error message is returned.

**Comment by fgalan** [comment]
In order to refer to a given entity, we could use:

```
/v2/entities/<id>
```

If ambiguety occurs (i.e several entities with the same id but different types), then the server should return an error. In that case (or if the client knows the ambiguety in advance) a `?type` parameter could be used:

```
/v2/entities/<id>?type=<type>
```

E.g:

```
/v2/entities/Car1?type=Car
```

**Comment by tobiasjacobs** [comment]
sounds ok. Is this a special application of the simple query language, so here the type is treated as a special attribute whose value has to be "Car"?

**Comment by fgalan** [comment]
Not really... in the GET /v2/entities operation, `type` URI param always refer to entity type. Attribute filters are specified using the `q` URI param.

**Comment by fgalan** [comment]
I understand that after releasing NGSIv2 Release Candidate 2016.05 version the current way of univocally identify an entity (based on the combination id+type) is something that is not going to change in the future. Thus, this issue could be closed.

**Comment by tobiasjacobs** [comment]
This particular issue can be closed from my viewpoint, but in general please note that there is no commitment to backwards compatibility to the version that has been released as candidate version without having reached a consensus.
