### ISSUE TITLE
Change in func test harness to help catch the ftest-ftest bug

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1411]
Each functest is responsible for removing all used databases in the TEARDOWN part.
The functest harness should be modified to NOT accept a functest as OK if any
ftest\* database still exists after the TEARDOWN part.

This modification of the functest harness will help us find the ftest-ftest bug.

[ Should be an old issue about ftest-ftest, but I can't find it right now ... ]

**Effort: 1 man day**

**Comment by fgalan** [comment]
Not sure but I'd say that we haven't see again the ftest-ftest problem in months... @iariasleon , @kzangeli what do you think?

**Comment by fgalan** [comment]
After more than one year without activity, this quarentine issue can be closed.
