### ISSUE TITLE
Erratic behavior in one of the Hackaton instances

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-orion#1414]
Seems to be a bug but its not clear at all. The following Curl command is issued to the CB:
```
curl -i -X GET http://<hackathonMahine>:1026/v1/contextEntities/<entityId> -H "Accept: application/json" -H "Fiware-Service: todosincluidos" -H "Fiware-ServicePath: /iot" -H "x-auth-token:  <validToken>" -H "Content-Type: application/json"
```
This request gets passed the PEP Proxy and returns de follwing CB error:
```
{
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "Sorry, no request treating object found for RequestType /IndividualContextEntity/"
  }
}
```
The same request without the Content-type header works like a charm. The same request both with or without headers going directly to the Context Broker port works like a charm. No errors are shown neither in the proxy nor in the broker.

I've used TCPDump to get the headers that arrive to the CB, for each scenario.

Sending the request to the PEP with the header:
```
host: hackathon.ttcloud.net:1026
accept: application/json
fiware-service: todosincluidos
fiware-servicepath: /iot
x-auth-token: 17730f7315454b68999c361e222b7e60
content-type: application/json
x-forwarded-for: 2.137.135.141
connection: close
content-length: 2
```

Sending the request to the PEP without the header:
```
user-agent: curl/7.37.1
host: hackathon.ttcloud.net:1026
accept: application/json
fiware-service: todosincluidos
fiware-servicepath: /iot
x-auth-token: 17730f7315454b68999c361e222b7e60
x-forwarded-for: 2.137.135.141
connection: close
```

Sending directly to the CB with the header:
```
User-Agent: curl/7.37.1
Host: hackathon.ttcloud.net:10026
Accept: application/json
Fiware-Service: todosincluidos
Fiware-ServicePath: /iot
x-auth-token: 17730f7315454b68999c361e222b7e60
Content-Type: application/json
```

Sending directly to the CB without the header:
```
User-Agent: curl/7.37.1
Host: hackathon.ttcloud.net:10026
Accept: application/json
Fiware-Service: todosincluidos
Fiware-ServicePath: /iot
x-auth-token: 17730f7315454b68999c361e222b7e60
```

**Comment by fgalan** [comment]
Not sure if this is related with the problem, but... is the `content-length: 2` correct in the first tcpdump fragment? I understand that the request (a GET) doens't have any payload.

Moreover... if the request doesn't have a payload, is correct to have a "Content-Type" header?

**Comment by kzangeli** [comment]
Oops, if the HTTP header says that the incoming request has a payload ...
It is a GET and it shouldn't have any payload so I guess we could ignore it, however, this seems like a bad usage of the broker.

We could protect the broker against this kind of bad usage, or we could decide not too.
It seems to me the broker is acting more or less correctly.
A request comes in, saying it carries a JSON payload  of two bytes and the broker responds that it doesn't know how to treat this kind of payload.

Please try this test again but without the "Content-Length: 2" and see what happens.

[ Are we sure the "Content-Length: 2" comes to the broker? ]

**Comment by dmoranj** [comment]
Probably related with this old PEP issue:

https://github.com/telefonicaid/fiware-pep-steelskin/issues/222

**Comment by dmoranj** [comment]
First things first: "It is a GET and it shouldn't have any payload". I'm not sure about that. The semantics of GET imply that it should be idempotent, but, at least reading the specification diagonally, it doesn't say anything about the existence of a body.

Anyway, sending an empty body with `content-type: application/json` its, indeed, wrong (as the empty payload is not valid JSON), so a 400 BAD_REQUEST is the expected result in that case (I would even return the 400 as an HTTP code instead of a Context Broker code, but that's a different story).

That being said, my vote is NTC.

**Comment by dmoranj** [comment]
I'm closing the equivalent PEP issue right now, in fact.
