### ISSUE TITLE
New version overrides configuration

### ISSUE THREAD

**Issue by DerJayDee** [telefonicaid/fiware-orion#1457]
After the update to version 0.25.0 (via yum install contextBroker) the configuration file (/etc/sysconfig/contextBroker) was overwritten. From my point of view this is bad behaviour and should at least get addressed in the notification email for the new version.

**Comment by fgalan** [comment]
A copy of the previous file is backed up and the user make aware at updating time:

```
contextBroker requires additional configuration before the service can be
started. Edit '/etc/sysconfig/contextBroker' to provide the needed database
configuration.

Note that if you have a previously existing '/etc/sysconfig/contextBroker' it
has been renamed to /etc/sysconfig/contextBroker.orig-2015-11-02.

After configuring /etc/sysconfig/contextBroker execute 'chkconfig contextBroker on' to
enable contextBroker after a reboot.
```
Could you check if the /etc/sysconfig/contextBroker.orig-2015-11-02 file is in your system after updating, please?

**Comment by DerJayDee** [comment]
Sorry for the delayed response.

The file you described indeed is located on the system. It seems that I missed the quoted part during the update.

Thank you.

**Comment by fgalan** [comment]
Great! Thus I understand the issue can be closed.
