### ISSUE TITLE
APIv2: roles

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1459]
Introducing different roles.

What do you think about introducing "roles" of NGSI enablers. The role of an enabler determines which operations of NGSI it implements. One could distinguish between
- components providing all operations
- components who provide NGSI data operations
- components who provide NGSI availability operations
- components who only act as clients calling the NGSI updateContext operation
- components who act as NGSI data consumers, implementing the notification operation when necessary
- etc.

The roles could be called "context provider", "context catalogue", etc.

Would this make sense? Any specific roles you would want to be defined?

**Comment by jmcanterafonseca** [comment]
The problem is how to define compliance. To my mind there are two levels of compliance: full compliance and query-level compliance. The spec should be developing what means being 'full compliance" and query-level compliance.

**Comment by fgalan** [comment]
I'd suggest to let the API definition evolve, then consider the roles topic once it achieves a higher maturity status. Maybe with just Context Consumer, Context Producer and Context Provider roles it suffices, thus avoiding over-terminology.

**Comment by tobiasjacobs** [comment]
find with me to consider it later, but I think we will need different profiles to make up for the dropped distinction between NGSI 9 and 10.

**Comment by marcc-orange** [comment]
Not all NGSI systems will want to be fully compatible with the NGSIv2 spec as it addresses the complete needs of a broker.
Using a query level compliance to define the compatibility of a system could be a good step, but is not enough.

We should allow `/v2` endpoint to work on a verb + query level, not just at query level.
I propose that `/v2` return for each supported query an additional `verbs` :

```json
{
  "entities": { "url" : "/v2/entities", "verbs": ["GET", "POST", "PUT", "DELETE"] },
  "types": { "url": "/v2/types" }
}
```

A missing `verbs` means all defaults verbs specified in NGSIv2 are supported.
A missing entry (like "subscriptions" or "registrations" in the above example) means that theses queries are unsupported entirely.

This would allow to express server-side "roles" from NGSI v1.

For example, the [IoT Agent node library](https://github.com/telefonicaid/iotagent-node-lib), that supports limited entity query for "lazy" attributes and entity updates for executing commands, could return :

```json
{
  "entities": { "url" : "/v2/entities", "verbs": ["GET", "PUT"] }
}
```

**Comment by jmcanterafonseca** [comment]
The proposed mechanism is pretty simple and might work and It is aligned with HEATEOAS principles.  Yesterday, we were thinking whether it would be a good idea to have finer granularity levels, for instance being able to state whether an implementation support Geoqueries or not. 

What do you think? when you state that you support GET /v2/entities are you saying that all queries are supported?

**Comment by fgalan** [comment]
@jmcanterafonseca , please have a look to `"capabilities"` idea at https://github.com/telefonicaid/fiware-orion/issues/2110#issuecomment-217114454. I think it addresses what you described.

**Comment by fgalan** [comment]
More than 2 years have passed since this issue was updated last time.

At the end it seems we don't need to define the concept of roles. After 2 years of practical experience with the API usage, no user seems to need that concept.
