### ISSUE TITLE
APIv2: multiple values of the same attribute

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1460]
Pasting the previous discussion email thread: (will paste new comments below)

5: ------------- :5

[NEC]: For NEC it is important to preserve the possibility to have multiple instances of attribute values. This might not be so important for most of the cases where NGSI is used these days, where entities represent sensors and attributes represent their readings. However, in we expect that in IoT scenarios entities will represent arbitrary objects like rooms, houses, etc. and then there can indeed be several providers of the same attribute values who should be distinguishable. 
However, we also see that this possibility should not make the life of users difficult who do not care about multiple attribute value instances because in their scenarios this does not play a role. Therefore our proposal is that NGSI systems treat attribute values with no given ID as having a specific “null” ID. 
By this, the value ID possibility can be completely ignored by scenarios where it is not needed, while the NGSI standard still offers the possibility to have multiple values.

[FGM] In order to fully understand you idea about IDs, could you elaborate an example aligned with the current NGSIv2 in order to see how it would looks like, please?

[TJ] Assume you have a context entity representing a street, and the co2-level of the street is measures by two different devices. In the NGSI model, the attribute “co2level” would then have two relevant values, each delivered by a distinct device, and these two values would be distinguished by distinct value IDs.
In FIWARE NGSI 1, applications who wish to retrieve only a specific attribute value could 
-        make a queryContextRequest and add to it an XPATH restriction which would limit the response to the attribute value instance having the desired value ID as metadata
-        or use the convenience function making a GET on {ngsi10path}/contextEntities/myStreet/attributes/co2level/id1
  A query not specifying the ID would, in contrast, return two attribute values.
  In FIWARE NGSI 2 we can discuss whether the possibility to query a specific value needs to be included in the convenience function as a sub-resource of resources representing attributes – maybe this not necessary, and specific value instances can still be queried by using the corresponding restriction [restrictions are another question to discuss].
  However, conceptually the NGSI system should distinguish between several value instances, so if two attribute values with different ID metadata exist, then e.g. an update on one instance should not overwrite the other.

[JMCF] I’m sympathetic to what you are proposing but I was wondering if what you are pursuing might result in API over engineering just to support a use case that can be seamlessly handled by the application itself. For instance, you can have a CO2 level value which can be obtained from the contribution of several measurements coming from different sensors . You might even automatically update the resulting value when a new measurement arrives by using the CEP. For instance.  

```
{
   id: “Friedrichstrasse”,
  type: “Street”, 
  co2Level: 0.1
}
{
   id: “Sensor-789”,
   type: “CO2Sensor”,
   location: “ Friedrichstrasse”,
  measurement: 0.15
}
{
   id: “Sensor-900”,
  type: “CO2Sensor”,
   location: “ Friedrichstrasse”,
  measurement: 0..09
}
```

[TJ]: In your example you refer to entities representing the different sensors, and of course such a representation is always possible. 
In the IoT chapter we typically speak of “higher-level” entities representing more abstract Things like streets, and we expect that the IoT user is not aware of which are the names of the sensors who deliver the information., so the user would query for “street” instead of “Sensor-900”. And it is in such scenarios where the same attribute is potentially delivered by several providers.

[FGM] In an scenario in which you combine low level and high level entities, you can always ask to low level entities for the particular values is you need. Moreover, the advantage of having the high level entity is to hide the details of the low level entities (i.e. abstraction), thus is you consider the posibility to ask for low level entities through the high level entity (using IDs or other means) you are breaking that abstraction.

[TJ] Hmm…my point was that when someone asks for an attribute of a more abstract entity, there could be several providers of that attribute, so there could be several valid instances of that value, and all of them should be returned, not only one of them. And the way to distinguish between the value instances would then be through the ID.

[FGM] The problem of using metadata for that is that with the "flat" JSON rendering you cannot have duplicated key, e.g. the following example is not valid JSON:

```
{
  "id": "Friedrichstrasse",
  "type": "Street",
  ...
  "temp" {
      "value": 22.2,
      "id": "sensor4"
   },
  "temp" {
      "value": 23.3,
      "id": "sensor5"
   }
   ...
}
```

An alternative would be to use compound attribute values for this, in this way (at the same time, note that is more compact than the previous one):

```
{
  "id": "Friedrichstrasse",
  "type": "Street",
  ...
  "temp" {
      "sensor4": 22.2,
      "sensor5": 23,3
   ...
}
```

However, I'm not sure if this behaviours should be standarized in NGSIv2, as it seems to be specific of a given use case / application domain.

[TJ] OK, I see where the problem with „flat“ JSON rendering is. So it might be better to make the “canonical representation” the standard one, and declare the “flat” one as syntactic sugar.

[FGM] The canonical representation doesn't solve the problem, given that

```
{
  "id": "Friedrichstrasse",
  "type": "Street",
  "attrs": {
     "temp": {
        "value": 22.2,
        "type": null,
        "metadata": {
           "id": "sensor4"
         }
     },
     "temp": {
        "value": 23.3,
       "type": null,
       "metadata": {
           "id": "sensor5"
       }
     }
     ...
   }
}
```

also have the problem of duplicated keys (this time in the "attrs" object).

**Comment by tobiasjacobs** [comment]
Would the representation problem be solved in the canonical format description by making the "attrs" value a list? Each list member will be an object with properties "name", "type", "value", "metadata".

This is a little less compact, but as we are anyway talking about a canonical representation....

**Comment by jmcanterafonseca** [comment]
I think there can be alternative ways to enable your use case without changing natural representations. An idea, for instance, is to standardize a metadata for attributes called 'source'. The metadata value for such a standardized metadata could correspond to a list of entity ids that will allow the caller to follow her nose to know more about the different sources of the data and its different values. 

Furthermore, We can even add an ?options=attrsSource to the query parameters that will allow the caller to specify that he want to retrieve all the source values for the attribute and that will be resolved automatically by the implementation ...  

so with this approach we keep the functionality standardized and we make it simple 

```js
{
   "id": "Room4",
   "temperature": [
      value: 22,
      metadata: {
        "source": [<list_of_ids>]
      }
    ]
}
````
@tobiasjacobs would you be happy with that solution and if so, would you be in a position to develop a spec for that?

**Comment by fgalan** [comment]
Is this really a functionality (i.e. metadata `source` and `?options=attrsSource`) that should be standardized? Or maybe it correspond to a "profile usage" of the NGSIv2 that shouldn't be part of the "core" API? Over-specifiying the core would lead to a complex API, difficult to develop fully implementations.

**Comment by tobiasjacobs** [comment]
@jmcanterafonseca In your example there is only a single value of the temperature attribute. How would one express that there is one value "22" from provider "A" and another value "23" from provider "B"?

**Comment by jmcanterafonseca** [comment]
@tobiasjacobs my proposal was

```
{
   "id": "Room4",
   "temperature": [
      value: 22,
      metadata: {
        "source": ["Sensor1", "Sensor2"]
      }
    ]
}

{
   "id": "Sensor1"
   "temperature": 22.5
}

{
   "id": "Sensor2"
   "temperature": 21.5
}

````

i.e. have as many auxiliary entities as the length of the source metadata array indicates. Maybe NEC could implement a profile that allow to perform queries over this predefined structure ...

**Comment by fgalan** [comment]
More than 2 years have passed since this issue was updated last time. 

The API spec (as it is now) provides enough mechanism to support this use case. Or at least no user has complaint in past 2 years about functional lack about this.
