### ISSUE TITLE
APIv2: pagination discussion

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1461]
(Pasting from previous email discussions; the point is still open)

Pagination: In principle NEC supports the concept of pagination. However we are not sure how it can be realized in practice, as query results are dynamic (especially when getting the queried data live from a distributed system like IoT systems do). What the user probably expects is that the query results are “frozen” for him and then delivered page by page. But then something like a query ID is needed to collect the query results.
Alternatively the query result could be represented by a specific http resource (which is similar to a query id). 
In both cases things become slightly more complex…

Do you have a proposal how to deal with that issue?

[FGM] Frozen the query at NGSI server implementation could have an important performance impact (as the frozen results would need to be maintained in memory from an undefined amount of time while the client gets all the result) and would make NGSI sever implementation stateful, which is very bad from the point of view of HA and horizontal scaling. 

Some ordering criteria may alleviate the problem In particular, entity creation date, which ensures that any new entity have to be put at the end. However, even in this case, there could be some problems if an entity already seen page is deleted (as it would introduce a shift in the next pages).

Thus, the solution based on limit/offset is not perfect, but may suffice most of the cases and have a good simplicity tradeoff. So, it is probably "the best of the worse" solution. But this point is still opened. 

[TJ] I understand the scalability aspect. 
On the other hand, NGSI systems who do not have the information ready in a database but need to assemble it from various sources anyway somehow have to cache the query result when it is retrieved page by page, as otherwise they would have to run the same queries on the subsystem again and again.
From this point of view the question is whether clients should have separate control on data generation and on data retrieval, or if this difference should be transparent to applications. To be discussed.

[FGM] I agree that pagination in a distributed context (as the architecture based on CB + CPrs is) is hard. We have been discussing about it at https://github.com/telefonicaid/fiware-orion/issues/847 long time, but without having found a perfect solution.

**Comment by jmcanterafonseca** [comment]
I think that the current API definition enables the NEC approach as well, as the caller must not hardcode the pagination requests but follow the next and prev links. So nothing prevents NEC to add extra parameters to the pagination Link URLs that will allow to reference particular snapshots of data at a certain time ... 

@tobiasjacobs would you be happy with that solution?

**Comment by fgalan** [comment]
> I think that the current API definition enables the NEC approach as well, as the caller must not hardcode the pagination requests but follow the next and prev links

Let me clarify that before going to an approach based on next/prev (btw, not yet mentioned in http://telefonicaid.github.io/fiware-orion/api/v2/, as far as I have checked) there are some issues that need to be solved. In particular, how to calculate the prev link without extra queries to DB to count element. (which may impact performancce). E.g. f you are in limit=100+offset=400 (items from 401 to 500) you cannot say that next is limit=100+offest=500 (items from 501 to 600) without looking to DB count, as the total number of element would be exactly 500, thus 501 to 600 will lead to "overflow".

**Comment by fgalan** [comment]
In a second thought, assuming that it is ok to provide a next pointing to empty results (as in the case above) the "algorithm" to generate prev and next given limit=L and offset=O could be as follow:

Regarding prev:

* If O=0, prev is not incluced in the Link header
* If the query results in empty list, prev is not included in Link header
* In other cases, prev is returned as: limit=L + offset=min(O-L,0)

Regarding next:

* If the query results in empty list, next is not included in Link header
* If the query results in a number of element (strictly) less than L, then next is not included in Link header
* In other cases, next is returned as: limit=L +  offset=O+L
  * Exception: if the sever has knowledgue that the above next could result in empty list then it MAY omitt next in the Link header (implementation specific, as in many implementation having that knowlewgue could have a performance penalty)

Please have a look, to detect possible flaws in the algorithm.

**Comment by fgalan** [comment]
More than 2 years have passed since this issue was updated last time. 

During this period, no user has report problems with the current pagination system described by the API, so I understand that the current one can be consolidated.
