### ISSUE TITLE
APIv2: context entities and elements

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1463]
[Another open point from emails I paste here for further discussion]

Now this is the discussion about whether we need to separate between context elements and context entities. See the discussion at https://github.com/telefonicaid/fiware-orion/pull/1078
The separation would be that the context entity represents a real-world object, and so each context entity is unique. A context element is a container for information about a context entity, and so there can be multiple such context elements for one entity.
For achieving a greater simplicity one could alternatively remove the distinction and call both just context entity.
While this simplifies terminology (one term less), it makes it more difficult to understand that the data object called “context entity” in general only contains partial information about the entity.
[FGM] Maybe we can leave this as it is now in http://telefonicaid.github.io/fiware-orion/api/v2/ (with the disclaimer in "Context Elements" section) and take the decision at the end, once the spec gets mature and we can see if "context element" term is needed or not.  
[FGM](To close)

**Comment by jmcanterafonseca** [comment]
Conceptually the distinction between context elements and context entities makes sense. An example of a context element is a Position element composed by two attributes (Location, speed). At the same time location is another context element composed by three values (latitude, longitude, altitude). A context element has no meaning outside the real world entity it belongs to, although the same context element can be related to more than one context entity. 

As NGSI only talks about Entities and attributes it happens that context elements have to be represented either by complex (i.e object) attribute values or by secondary entities linked from primary entities. In this case we could represent Position by an entity or, alternatively, as it often happens, as a complex attribute value. 

So I'm in favor of making the distinction conceptually clear but at the same time adding some wording to the spec, clarifying how context elements are in reality represented in NGSI, similar to what I have explained above. 

@tobiasjacobs does it make sense to you? Would you be able to make a PR to provide the wording?

**Comment by tobiasjacobs** [comment]
I am not sure if I understand correctly.

Are you talking about the possibility to use different context elements for different representations of the same information about a context entity?

From my point of view a context entity is a real-world object, while a context element is a data container for information about a real-world object. So one can use different context elements 
- for representing different information about the same context entity (this is what I had in mind)
- for representing the same information about a context entity in a different format (this is how I understand you comment)

ok?

**Comment by tobiasjacobs** [comment]
I agree with the reality-check; I also have never used the term "context element" in NGSI tutorials.

**Comment by jmcanterafonseca** [comment]
then, can we keep this issue on hold, for the time being, and move forward to other subjects which are more important to finish the spec.

**Comment by fgalan** [comment]
More than 2 years have passed since this issue was updated last time. 

The distintion between context elements and entities seems not needed at the end. At least no user, after practical usage of the draft spec during more than 2 years, has report the need of such distinton and the current draft seems to be clear enough without extra terminological elements in the spec text.
