### ISSUE TITLE
APIv2: registration metadata

### ISSUE THREAD

**Issue by tobiasjacobs** [telefonicaid/fiware-orion#1464]
For NEC it is important that context registration continue to have registration metadata. We use that metadata for expressing various things like (1) association information (ie. how assemble information on the registered entities from other entities) (2) geographic information about the context provider.

Additionally we propose to make "callback" optional, see below (was in email discussions)

"
[TJ] NEC proposes to make in the “contextRegistration” structure the “providingApplication” URL optional. 
The reason is that in some cases it makes sense to register entities without providing NGSI servers where they can be retrieved:
- for announcing that in principle a system can provide information about that entity, even if at the moment no provider is available.
- for registering associations which describe how to compute entity information from another other entities (sensor2things concept). Up to now we have used a dummy URL in that case as a workaround…
"

**Comment by jmcanterafonseca** [comment]
I'm ok about adding a metadata dictionary to enable additional annotations over a context provider registration.

Wrt to callback as an optional field I'm ok as well

**Comment by jmcanterafonseca** [comment]
closed. https://github.com/telefonicaid/fiware-orion/commit/8b151dbe1806e9ec5081704e6a9618aab05d2b4f

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/1511 (in the case just the commit is not enought and we want to recover the comment conversation)
