### ISSUE TITLE
GET /v2/subscriptions responds with 400 Bad request

### ISSUE THREAD

**Issue by alecava** [telefonicaid/fiware-orion#1470]
After installing orion 0.25 I executed "curl localhost:10026/v2/subscriptions" to get all the subscriptions in Orion but i got this response:

```xml
<orionError>
  <code>400</code>
  <reasonPhrase>Bad Request</reasonPhrase>
  <details>service not found</details>
</orionError>
```
is there something wrong with my request or is a bug in Orion?

**Comment by fgalan** [comment]
What do you get when runnint "curl localhost:10026/version" ?

**Comment by alecava** [comment]
I get 

```xml
<orion>
  <version>0.18.0-next</version>
  <uptime>0 d, 3 h, 12 m, 44 s</uptime>
  <git_hash>1e8518d6ebe1a49695c85d4535ae32bf3279927e</git_hash>
  <compile_time>Fri Oct 30 12:57:54 CET 2015</compile_time>
  <compiled_by>orion</compiled_by>
  <compiled_in>nozomi-cloud</compiled_in>
</orion>
```

but when I run "contextBroker --version" I get:

```
0.25.0-next (git version: e855f89776787652a6ab288e2e7bbc504ee1d545)
Copyright 2013-2015 Telefonica Investigacion y Desarrollo, S.A.U
Orion Context Broker is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Orion Context Broker is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
General Public License for more details.

Telefonica I+D
```

I don't know why two different versions are reported

**Comment by fgalan** [comment]
Probably because CB was running at upgrading time. In that case, the solution is quite simple: just stop the current (0.18.0) CB process and start CB again.

**Comment by alecava** [comment]
I tried to reinstall orion stopping the service first but the result is the same, I can't use the /v2/subscriptions url and the version numbers are mismatching

**Comment by fgalan** [comment]
It could happen that the old CB process has got "deattached" from the service start/stop logic. Thus, I'd recommend to use Linux kill command. In sum the procedure will be as follows:

* Get the PID of the process that is listening to 10026 and reporting the "0.18.0-next" version, e.g. using `sudo netstat -ntlpd | grep 10026`
* Check that that process correspond to an actual contextBroker process, e.g. `ps ax | grep <PID>`
* Kill the process with `kill <PID>`.
* Check that the process has been actually killed with `ps ax | grep <PID>`. In the case plain kill doesn't work, try with `kill -9 <PID>`.
* Start Orion as service now, e.g. `sudo /etc/init.d/contextBroker start`.

**Comment by alecava** [comment]
Thank you for the detailed description but I found the real problem, the last installation script changed the installation directory and my startup script was still loading the old file. Now the /version url give me the right response and the subscriptions url is working well

**Comment by fgalan** [comment]
Happy to know that it was solved successfully! :)
