### ISSUE TITLE
Get backup via API

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1493]
(Feedback from ECFI 2015 at Hamburg)

It has been suggested to implement an administrative operation to create backups of context subsets (or the whole context set). This idea needs to be matured, anyway.

**Comment by jmcanterafonseca** [comment]
GET /v2/entities?options=download ... could fit the fill, allowing to download a big chunk using the standard HTTP download mechanisms ...

**Comment by fgalan** [comment]
I think we are covered, either at MongoDB side or at API side (it would be pretty easy to develop a client program doing paginated GET /v2/entities to recover everything). In addition to the lack of interest in the last 3 years (no comments since November 2015) make me think this issue should be closed.
