### ISSUE TITLE
ContextBroker running in a Raspberry

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#15]
This is as simple (or difficult :) as to compile Context Broker code in a Raspberry Pi device. Given that we currently compile it in Debian in some systems, it shouldn't be too dificult.

**Comment by fgalan** [comment]
According to user's report, the current driver used by Orion (release 0.19.0 and before) cannot be compiled in 32 bits (that I understand is the architecture Raspberry uses).

It seems that mongo-cxx-driver-legacy-1.0.0 can be compiled in Raspberry. At the end, I think we will move to that driver (the main motiviation is to use a "modern" version of the driver).

**Comment by avelardev** [comment]
This mongodb run in Raspberry pi 2: http://facat.github.io/cross-compile-mongodb-for-arm.html

**Comment by fgalan** [comment]
Thanks @avelardev, very valuable information to implement this issue!

**Comment by avelardev** [comment]
I'm working on the migration of Orion Context Broker to Raspberry Pi 2 as a research project of my school so I'll be posting my results.

**Comment by fgalan** [comment]
Just to clarify regarding

> It seems that mongo-cxx-driver-legacy-1.0.0 can be compiled in Raspberry. At the end, I think we will move to that driver (the main motiviation is to use a "modern" version of the driver).

that we moved to mongo-cxx-driver-legacy-1.0.2 in Orion 0.22.0, so this impediment to compile Orion in Raspberry Pi was removed.

**Comment by avelardev** [comment]
@fgalan Which version of mongo-cxx-driver-legacy is runing in Orion 0.24.0, the most resent is 1.0.5

**Comment by fgalan** [comment]
> @fgalan The version of mongo-cxx-driver-legacy of Orion 0.22.0 is the same of Orion 0.24.0

Yes, it is.

**Comment by fgalan** [comment]
Raspberry is at the present moment out of target systems in which Orion have to run. Thus, we are closing this issue.

However, we are always open to contribution from the community so if you have a procedure about it, please don't hesitate to cast the corresponding pull request :)

**Comment by fgalan** [comment]
So, in the end, more than 6 years after we created this issue :), @fisuda has achieved it! See PR https://github.com/telefonicaid/fiware-orion/pull/3630
