### ISSUE TITLE
[BUG] in GET /v2/entities using the idPattern query parameter is allowed forbidden values

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1523]
in GET /v2/entities using the idPattern query parameter is allowed forbidden values
Datasets:
```
      | id_pattern    |
      |---------------|
      | house<flat>   |
      | house=flat    |
      | house'flat'   |
      | house"flat"   |
      | house;flat    |
      | house(flat)   |
```

#### Request:
```
GET http://qa-orion-fe-02:1026/v2/entities?idPattern=house(flat)
Content-Type: application/json
Fiware-Service: test_list_only_id_pattern
Fiware-ServicePath: /test
```

#### Response:
```
http code: 200
[]
```

#### Expected:
```
 http code: 400
 {   
      "error":"BadRequest",
      "description":"invalid character in URI parameter"
 }
```

**Comment by kzangeli** [comment]
All URI params **except** 'q' and 'idPattern' are checked for **forbidden characters**.
'q' and 'idPattern' are special as they need the characters that are normally forbidden for their normal function.  Escape these characters would render the text impossible to read.
After consulting with 'security', we decided to not check forbidden chars for 'q' and 'idPattern'.

This issue can probably be closed.

**Comment by iariasleon** [comment]
LGTM
