### ISSUE TITLE
Dockerfile manual is too complex! -.- Please provide a standalone GE env running OOTB

### ISSUE THREAD

**Issue by IAIS4EP** [telefonicaid/fiware-orion#1533]
For happy customers, Docker gives you a possibility to demonstrate the power of your software solution by running one or two lines to get a demo environment up and running locally within just one minute!

Your current manual looks very sophisticated but it takes too long time to get to a running environment - given the risk that manual could contain errors, the frustration would be even higher.

Is it possible to provide a version where you do not have to deal with manual steps beyond starting the container to have a live Orion instance?

Using Docker Compose is undoubtedly a good architectural solution, but again a customer friendly manual would look also in this case way more shorter - have a look for example on the instructions given along with the Sonarqube Dockerfile. 
https://hub.docker.com/_/sonarqube/

Thank you!

**Comment by fgalan** [comment]
However, on the contrary, too short versions of the manual (as the older ones are) create some missunderstanding in users (I have personally check it at hackathons and similar events).

It is difficult to find the right abstraction level that make everybody happy... ;)

**Comment by IAIS4EP** [comment]
Hi Fermin,

thank you very much for this rapid response! I admit that your argumentation is correct, but I am talking not about a just shorter manual ;-) but about accessibility of the topic and the number of steps.
The idea of the Dockerfile is to replace manuals with formal process description; you can put comments there too. Good to have a long explanation for customers you have got - but to get new customers, provide a 1 minute OOOB standalone Dockerfile. egm is now blocked since one day to step through this manual which makes no sense to them because they just need a running instance.

kind regards
Peter
P.S. do not take my escalation mail personally, as you are not responsible for defining the QA strategy of FICORE, your case is just an example.

**Comment by abbasahmad** [comment]
My Docker file : 

```
FROM fiware/orion

RUN curl http://localhost:1026/version
```
Then i want to build : 
```
docker build ./
Sending build context to Docker daemon 8.704 kB
Sending build context to Docker daemon
Step 0 : FROM fiware/orion
 ---> 1c7803fcf7f8
Step 1 : RUN curl http://localhost:1026/version
 ---> Running in c1cc99402a7f

curl: (7) couldn't connect to host
INFO[0001] The command [/bin/sh -c curl http://localhost:1026/version] returned a non-zero code: 7

```

This is impossible for now

**Comment by LeandroGuillen** [comment]
> but to get new customers, provide a 1 minute OOOB standalone Dockerfile

http://bit.ly/fiware-orion-024-vbox

**Comment by 1605200517** [comment]
Hi Leandro,

Thanks for sharing a virtual box vm image of 1.3 GB size. 
However, this is the approach referenced as "golden image" which was used by enterprises already in 2002 to replicate server and desktop environments from a central master template. 
http://searchservervirtualization.techtarget.com/definition/golden-image

The clear benefit of Docker beyond this approach is in my opinion that a Dockerfile is easy to share and to collaborate on, and it is a transparent AND machine executable formal description of human labour required to setup an environment. There is no "master" Dockerfile, it is always just a reference, easy to read, grasp and work with.

kind regards
Peter

**Comment by fgalan** [comment]
Regarding VBox image, although the "golden image" paradigm is old, it is still valid and very useful ("old" doesn't necessarly mean "bad" ;). Although of course Docker is a wonderful tool to deploy software in a very easy and quick way, it assumes an important requirement: Docker is already installed in the hosting system, which requires a relatively modern kernel in the case of Linux system and a not-so-easy installation in Windows/Mac systems. I have personally meet many users (in hackathons and similar events) comming with Windows/Mac or old Linux distributions in which installed Docker was a problem, so they thanked the existente of the VirtualBox image.

Focusing on the original purpose of this issue about documentation (let use #1534 for the tehcnical issues related with Dockerfile and testing... I think we are making progress with @abbasahmad there) the process should be very clear as:

1. User lands at documentation: https://github.com/telefonicaid/fiware-orion/blob/develop/docker/README.md
2. User reads in the very beginning of the document: "Have everything automatically done for me". See Section 1. The Fastest Way (recommended)" and goes to that section.
3. That section describes how to deploy Orion in 3 steps that can be done in less than 1 minute.

I think that is quite straighforward from an "user experience" point of view. However, if you have suggestion about how to improve this, I'd be more than happy to know them so we can improve documentation. Otherwise, I'd suggest to close this issue.

Thanks for the feedback!

**Comment by marcc-orange** [comment]
@IAIS4EP As a new Orion user, I find the Docker Compose provided by Orion ("the fastest way" section) very simple to use:

Have a file "orion.yml" with content of https://github.com/telefonicaid/fiware-orion/blob/develop/docker/docker-compose.yml

and run: 

`docker-compose -f orion.yml up -d orion`

This can't get more simple, no ?

Docker containers are not meant to contain more than one app, I'm against having a mongo + orion single Docker image. Docker Compose is clearly the easiest and cleanest solution for new comers.

**Comment by IAIS4EP** [comment]
Hi, the fast track path for unpatient patients like myself is really the best, thank you! I also fully agree that using docker compose is much better than to put all in one monolitic image, then we would have again the 'golden image pattern'...

Nevertheless, also the acceptance test following your instructions unfortunately fails and gives the following result - see attached screenshot. Please help us to get it running! Thanks.

![image](https://cloud.githubusercontent.com/assets/13382270/11403592/db3cb4ac-939d-11e5-87b1-2872f7f31345.png)

**Comment by fgalan** [comment]
Could you show the content of the downloaded file (i.e. `cat orion.yml`)? If the file is too long or complex to be included in a github comment, please use https://gist.github.com/ (including the URL in this issue comments).

**Comment by marcc-orange** [comment]
@IAIS4EP Come on, your "acceptance test" does not take in account that Github returns HTML for the URL I provided... if you had followed to link you could have seen a "raw" button to get the content directly : https://raw.githubusercontent.com/telefonicaid/fiware-orion/develop/docker/docker-compose.yml

**Comment by IAIS4EP** [comment]
Hi Marcc, indeed, please take my apologies that I did not know about this gotcha with the HTML, this is a littly bit tricky for me!

Now I followed the new instructions you have kindly provided, and took me this time not even 30 seconds. Howerver, there is again a red ERROR marker with an output I cannot understand. Can you assist me further please? Thank you!

![image](https://cloud.githubusercontent.com/assets/13382270/11404117/9c32a642-93a0-11e5-8cb5-c4700f2df591.png)

**Comment by IAIS4EP** [comment]
Btw. I have just thought maybe this is about the versions of Docker itself and docker-compose, but these are not same numbers as I can see. (new screenshot attached)

![image](https://cloud.githubusercontent.com/assets/13382270/11404164/d7d06c34-93a0-11e5-8100-b8a7894077be.png)

**Comment by marcc-orange** [comment]
This is indeed a known docker issue (https://github.com/docker/docker/issues/14077). Please upgrade your docker server.

**Comment by IAIS4EP** [comment]
Thank you!

**Comment by IAIS4EP** [comment]
Upgraded to docker-engine with docker 1.9.1, now the acceptance test passes! Thank you. :-)

![image](https://cloud.githubusercontent.com/assets/13382270/11418183/eb7124fe-941d-11e5-8ead-fe25f30b3a2b.png)
