### ISSUE TITLE
Docker for testing

### ISSUE THREAD

**Issue by abbasahmad** [telefonicaid/fiware-orion#1534]
What we wanted to say in the issue : https://github.com/telefonicaid/fiware-orion/issues/1533 

My Docker file : 

```
FROM fiware/orion

RUN curl http://localhost:1026/version
```
Then i want to build : 
```
docker build ./
Sending build context to Docker daemon 8.704 kB
Sending build context to Docker daemon
Step 0 : FROM fiware/orion
 ---> 1c7803fcf7f8
Step 1 : RUN curl http://localhost:1026/version
 ---> Running in c1cc99402a7f

curl: (7) couldn't connect to host
INFO[0001] The command [/bin/sh -c curl http://localhost:1026/version] returned a non-zero code: 7

```
This is impossible for now

**Comment by abbasahmad** [comment]
In the end what i am trying to do, is to launch automatc test on the Orion CB docker instance : 
```
FROM fiware/orion

#Instal wget
RUN yum -y install wget

#Install Java 8 
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm"
RUN sudo yum localinstall jdk-8u60-linux-x64.rpm

#Run Automatic Tests writen by EGM
RUN wget https://bitbucket.org/eglobalmark/egm_testexecorioncb/raw/b69758c3aa5f386e8e30d783d92c93a8e6783a49/testExecOrionCB.jar
RUN java -jar testExecOrionCB.jar -p 1026 -ip http://127.0.0.1 -o http://207.249.127.73:7070/report -t 2 -header Fiware-Service#egmtestexectests@Fiware-ServicePath#/egmtestexectests
```
Looking at the last line, is where the Orion ContextBroker should respond on 127.0.0.1 with port 1026.

One of the main issue, is that the Docker "fiware/orion" needs an other docker "mongo" But then i cant "build" my test docker as i would need to have a Docker run with the link. That is something that i dont want as the whole process is to Build with Jenkins and get the results.

**Comment by fgalan** [comment]
Have you tested with docker compose (https://github.com/telefonicaid/fiware-orion/tree/develop/docker#1-the-fastest-way)? Once the .yml file is ready (downloable from here: https://github.com/telefonicaid/fiware-orion/blob/develop/docker/docker-compose.yml) it is a matter of running (in the same directory):

```
docker-compose up
```

After some seconds, Orion is runing at port 1026:

```
curl localhost:1026/version
```

**Comment by LeandroGuillen** [comment]
>FROM fiware/orion
>RUN curl http://localhost:1026/version

I don't think you are using the Orion image correctly here. You are assuming Orion running in the image, but it isn't. To launch it you have to "docker run" it at least, it is not enough to extend the image.

If you want to launch a test suite that will run in a container that is concurrently running Orion (and possibly MongoDB) then the fiware/orion image is not a good fit. You would need a specialized image for that.

**Comment by LeandroGuillen** [comment]
The second Dockerfile looks better. But you are still assuming that Orion is running. You have to at least do a "RUN contextBroker ..." of some kind, don't you?

**Comment by abbasahmad** [comment]
@LeandroGuillen @fgalan You are right. i think i am miss-using the fiware/orion image.
The contextBroker is not runing and needs a mongo DB. i will try to build a running OrionContextBroker from one dockerfile and share it with you if you are interested. 

Thanks for the support.

**Comment by fgalan** [comment]
@abbasahmad do you mean to budle together Orion + MongoDB + test software in the same Dockerfile?

**Comment by abbasahmad** [comment]
@fgalan yes! i want to build a Running Orion ContextBroker make the tests with my testSoftware wich will send a report on a distant server. Then the docker can disapear. All this will be launched via Jenkins for automated testing.

**Comment by fgalan** [comment]
@abbasahmad In that case, my suggestion is to use docker compose as bundle unit instead of a single docker witll all stuff inside. In other workds, to bundle using a docker-compose.yml instead of a Dockerfile. 

Thus, you could have 3 dockers composed at docker-compose.yml:

* The one for Orion (already created)
* The one for MongoDB  (already created)
* The one with your testing framework, liked to the others.

I.e., you are reusing 2/3 of the needed dockers. In fact, you can use the current docker compose file for Orion as a base for that .yml: https://github.com/telefonicaid/fiware-orion/blob/develop/docker/docker-compose.yml

**Comment by abbasahmad** [comment]
@fgalan Thanks for the advice. Will try it out.

**Comment by fgalan** [comment]
Great! Please, use this issue to keep updated about your progress. Thanks!

**Comment by fgalan** [comment]
(I have renamed the issue, to provide a clearer name)

**Comment by abbasahmad** [comment]
OK no problem i am actually building something to have an automated docker version runing. 
Will post it here as soon as it is working. i am on it.

**Comment by abbasahmad** [comment]
# This is what i wanted to do at first : 

I wanted a one step Orion context broker worrking in a Docker file to be launched via "docker build ./" : 
### NOTE : This docker file was just a test :raised_hand: It is not functional
```
FROM centos:6.7

#Install MongoDB 2.6

RUN echo -e "[mongodb-org-2.6]\n\
name=MongoDB 2.6 Repository\n\
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/\n\
gpgcheck=0\n\
enabled=1" > /etc/yum.repos.d/mongodb-org-2.6.repo

RUN mkdir -p /data/db /var/log/mongodb /var/run/mongodb
RUN yum -y install mongodb-org
RUN echo "Cache Buster 1"
RUN echo "smallfiles = true" >> /etc/mongod.conf
EXPOSE 27017
CMD ["service", "mongod", "restart"]

#Install Orion

RUN echo -e "[testbed-fi-ware]\n\
name=Fiware Repository\n\
baseurl=http://repositories.testbed.fi-ware.org/repo/rpm/x86_64/\n\
gpgcheck=0\n\
enabled=1\n" > /etc/yum.repos.d/testbed-fi-ware.repo

RUN yum -y install contextBroker
EXPOSE 1026
CMD ["service", "contextBroker", "restart"]

#Instal wget
RUN yum -y install wget

#Install Java 8
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm"
RUN sudo yum localinstall jdk-8u60-linux-x64.rpm

#Run Automatic Tests writen by EGM
RUN wget https://bitbucket.org/eglobalmark/egm_testexecorioncb/raw/b69758c3aa5f386e8e30d783d92c93a8e6783a49/testExecOrionCB.jar
RUN java -jar testExecOrionCB.jar -p 1026 -ip http://127.0.0.1 -o http://207.249.127.73:7070/report -t 2 -header Fiware-Service#egmtestexectests@Fiware-ServicePath#/egmtestexectests
````
And as @marcc-orange stated in https://github.com/telefonicaid/fiware-orion/issues/1533  : 

> Docker containers are not meant to contain more than one app, I'm against having a mongo + orion single Docker image. Docker Compose is clearly the easiest and cleanest solution for new comers.

I decided to stay on the on step test but this time with docker-compose. So this time i dont have any dockerfile that i will write myself but a shell script that will use fiware/orion docker compose image.

## Script to use docker-compose and run Easy Global Market functional tests + report generation : 
```
#!/bin/bash

WAITFOR=30
echo "WAITFOR time defined = $SLEEPTIME"

echo "Creating test Directory"
mkdir ./OrionCBTesting
cd OrionCBTesting

echo "########## Actualy going to run in $(pwd) ##########"
echo "Getting the docker compose file from https://raw.githubusercontent.com/telefonicaid/fiware-orion/develop/docker-compose.yml"
wget https://raw.githubusercontent.com/telefonicaid/fiware-orion/develop/docker/docker-compose.yml
docker-compose up -d
echo "Going to sleep : Give time for docker instances to spawn"
sleep $WAITFOR

echo "Downloading the EGM functional test"
wget https://bitbucket.org/eglobalmark/egm_testexecorioncb/raw/b69758c3aa5f386e8e30d783d92c93a8e6783a49/testExecOrionCB.jar

echo "Executing the EGM functional test on 127.0.0.1:1026 (Orion instance) and reporting tests result to : http://207.249.127.73:7070/report"
java -jar testExecOrionCB.jar -p 1026 -ip http://127.0.0.1 -o http://207.249.127.73:7070/report -t 2 -header Fiware-Service#egmtestexectests@Fiware-ServicePath#/egmtestexectests

echo "removing Docker instances created..."
docker rm -f OrionCBTesting_mongo_1
docker rm -f OrionCBTesting_orion_1

echo "Deleting created directory"
cd ..
rm -r ./OrionCBTesting

echo "Bye bye"
```

I would like to thank you @fgalan @LeandroGuillen for your support .

Best regards.

**Comment by fgalan** [comment]
Happy to see you achieve it at the end :) Thanks!
