### ISSUE TITLE
GCC optimization level

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1554]
Right now we use -O2 for RELEASE compilation.
We should consider -O3, as it supposedly optimizes much better than -O2.

Years ago you had to be careful with -O3, it was buggy.
This seems to no longer be the case.
For example, see:
http://stackoverflow.com/questions/11546075/is-optimisation-level-o3-dangerous-in-g

We would just need to change -O2 for -O3 in the toplevel CMakeLists.txt and run a few tests.

**Effort: 1 man day**

**Comment by fgalan** [comment]
At the end, nothing to do regarding this. See comments in PR #1630 for details.
