### ISSUE TITLE
csub cache logic must ignore orion-XXXX dbs in the case of not using -multiservice

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1555]
As far as I understand, the refresh csub cache logic reads all database following the `orion[-XXX]?` pattern no matter if `-multiservice` is enabled or not.

The right behaviour should be ingore `orion-XXX` dbs in the case of not using `-multiservice`. Or, in other words, if `-multiservice` is not in use, then only pay attention to the `orion` database.

(Not sure how to label this, but I think it should be "bug").

**Comment by kzangeli** [comment]
Sure, this can be considered a bug.

The 'cache logic' depends on getOrionDatabases() to get the list of databases.
Now, if getOrionDatabases() always returns the entire list, perhaps it needs a new parameter?

     bool getOrionDatabases(std::vector<std::string>& dbs, bool allOrionDatabases) ?

Either that or the cache itself looks at the -multiservice flag and **not** call getOrionDatabases() if multi-service is off.

I don't have a strong opinion on how to solve the problem.

**Comment by fgalan** [comment]
Is `getOrionDatabases()` getting into account `-multiservice`? In that case, maybe this is not an actual bug.

**Comment by kzangeli** [comment]
The "problem" is that getOrionDatabases does not look at multiservice, it just returns all the databases (I just looked it up).

So, there are two solutions, either to make getOrionDatabases a little more intelligent (have it look at 'multiservice'), or the sub-cache logic stops calling getOrionDatabases() if multiservice is off

**Comment by fgalan** [comment]
> So, there are two solutions, either to make getOrionDatabases a little more intelligent (have it look at 'multiservice'), or the sub-cache logic stops calling getOrionDatabases() if multiservice is off

Which solution was finally adopted in PR #1557 (the one that solves this issue as far as I understand)?
