### ISSUE TITLE
More constants to common/limits.h

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1575]
The limits for tenant and service-path are already in common/limits.h, but we have a lot more to put in there. The idea is to have a common file with all these limits.

Just a few examples of definitions that should enter:
- httpRequestSend.h:  MAX_STA_MSG_SIZE (name could improve: STA: STATIC)
- httpRequestSend.h:  MAX_DYN_MSG_SIZE (DYN - DYNAMIC)
- uriParamNames.h:    MAX_PAGINATION_LIMIT
- rest.h:                        MAX_LEN_IP
- XXX                          Max len of database for the cli option '-db' is 10

The function restInit in rest.cpp/h has plenty of default values for its parameters:

    bool                _multitenant       = false,
    unsigned int        _connectionMemory  = 64,
    unsigned int        _maxConnections    = 128,
    unsigned int        _mhdThreadPoolSize = 128,
    const std::string&  _rushHost          = "",
    unsigned short      _rushPort          = 0,
    const char*         _allowedOrigin     = NULL,
    const char*         _httpsKey          = NULL,
    const char*         _httpsCert         = NULL,
    RestServeFunction   _serveFunction     = NULL,
    bool                _acceptTextXml     = false

At least  the numerical values could be made definitions in common/limits.h

I'm sure there are plenty of constants still to 'be discovered' ...

**Effort: 2 man day**

**Comment by fgalan** [comment]
Fixed in PR #1648
