### ISSUE TITLE
Header based service/servicePath filtering for csbus

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1577]
GET /v2/subscritpions operation will support result filtering based on Fiware-Service and Fiware-ServicePath headers.

Fiware-Service will allow to specify the service (i.e. database) in which the subscriptions are being queried (in the case of no header or no `-multiservice` the default DB, usually `orion`, will be used). Probably, this is already supported in the GE /v2/subscription operation.

Fiware-ServicePath will be processed in the the following way:
- If its value is (literarly): `/#` then all the subscriptions in the service will be returned. I.e. no actual filtering based on fiware service path.
- If its value is `X` (being `X` different from `/#`) then only the subscriptions which servicePath matches _exactly_ X will be returned.

A look to the csub data model could help: http://fiware-orion.readthedocs.org/en/develop/admin/database_model/index.html#csubs-collection

The servicePath to which each subscription belong is not included in the reponse (neither headers, neither paylaod).

**Comment by crbrox** [comment]
Closed by #1588

**Comment by fgalan** [comment]
Waiting for @anabelegp feedback before closing it definitively.

**Comment by fgalan** [comment]
@anabelengp report that functionality is ok. Closing.

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by fgalan** [comment]
Issues in milestone QATestPendingNotE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
