### ISSUE TITLE
How to install Orion GE on Ubuntu?

### ISSUE THREAD

**Issue by 1605200517** [telefonicaid/fiware-orion#1579]
Please provide a flavor of this GE also for Ubuntu, not only for CentOS.
Or, please provide an OS-independent and working Chef recipe inside the official Dockerfile.
https://forge.fiware.org/scmrepos/svn/testbed/trunk/cookbooks/GESoftware/orion/

Thank you!

kind regards
Peter / IAIS

**Comment by fgalan** [comment]
As far as I understand, docker-base deployment can be done in any host with Docker instaled (including Ubuntu). As far as de Orion docker exposes the API endpoind, which OS is used internally (CentOS, in this case) shouldn't be a concern from the hosting system.

Probably I'm  not getting the point. Could you elaborate on this request and the rationale behind it, please?

**Comment by 1605200517** [comment]
Hi Fermin, this is the other way round.
- current Dockerfile specifies a CentOS flavor and uses e.g. yum etc
- in Ubuntu you would need another sequence of commandos to install the GE, starting with calling apt etc.

-> Request: please provide a Dockerfile specifiying how you would proceed in Ubuntu.

I could imagine that Docker tagging semantics is a good vehicle to leverage this.

kind regards
Peter

**Comment by 1605200517** [comment]
is this one actually what we need? https://hub.docker.com/r/jmcanterafonseca/fiware-orion-dev/

I just wonder what has happened to the Chef recipes (linked above), as somebody has invested a considerable effort of time exactly to abstract from OS via this tool.

**Comment by fgalan** [comment]
What I'm trying to understand is why the current Docker doesn't suffices your use case... I mean, I understand you have a given NGSI client software (maybe some testing software?) that runs in your Ubuntu box and that you want to run it againts the NGSI API endpoint exposed by the Orion docker (pulled from fiware/orion) running also in that box.

That scenario can be achieved with the current CentOS-based docker. You don't need to use the same distribution in the host system (lest's say, Ubuntu) and the one running by the docker container internally. In fact, from host point of view, you don't "see" even the OS run internally by the docker container: you only see the NGSI API endpoint (which, by the way, is the only think the client needs to work).

Having say that, some people (as @jmcanterafonseca ) has developed Dockerfiles for other Linux distribution different from CentOS 6.x. However, we can mantain only one Dockerfile as "official" one, and that one is the one using CentOS 6.x. In fact, don't know if the docker you cite is up to date (you should ask @jmcanterafonseca about it).

**Comment by 1605200517** [comment]
In this use case, the guys want to deploy the server part; I hope JM's Dockerfile will be a help - we will test it with same smoketest.

Please comment on the Chef recipes, as this seems to have been an initial strategy to support not just one official distro. Was it a bad experience with Chef? Really curious to know.

thanks, Peter

**Comment by fgalan** [comment]
> In this use case, the guys want to deploy the server part;

Just to check if I'm understading correctly, you mean to install Orion on a "plain" Ubuntu server (I mean, without docker framework installed on it)?

Regarding Chef receipts, I'm afraid it is a bit out of the scope and I don't an answer for that, sorry. I would recomment you to contact people in charge of Chef in FIWARE (I think that in the Cloud Chapter).

**Comment by 1605200517** [comment]
thank you. Yes they want to install Orion on a "plain" Ubuntu server: we use Dockerfile just to capture a simulation of this process.

**Comment by fgalan** [comment]
Ok, now it's clear :) Appart from the @jmcanterafonseca Dockerfile (which contains implicitly an installation receipt for Ubuntu systems), you can have a look also to: https://github.com/telefonicaid/fiware-orion/issues/11. Note that in both cases the information could be updated.

If based on these inputs you end with a procedure to install Orion in Ubuntu, we will be more than happy to extend this section of the manual with such information: https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/build_source.md#others. Pull requests are welcome! :)

**Comment by jmcanterafonseca** [comment]
@1605200517 the Ubuntu's Docker might not be updated, if you patch it, please make a PR.

**Comment by fgalan** [comment]
@1605200517, did you finally solved this issue? Could this issue be closed, please? Thanks!

**Comment by 1605200517** [comment]
so far clarified, thx for reminding. closing.
