### ISSUE TITLE
Alarms manager at Context Broker

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1582]
Currently CB works in a stateless way regarding alarms and release conditions, which has some problems for the system consuming the logs and setting alarms. Thus, we would implement a better system based on transient-state in CB.

Alarms to take into account are rows 2, 4 and 5 at https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/logs.md#alarm-conditions. CB will mantain an alarm manager, able to manage different kind of alarms.
- Database alarm. This alarm appear whenever an operation fails on database (i.e. ERROR - Database Error (...)). The alarm is released when a sucessfull operation in DB is done. Only one alarm of this type can be in the manager (actually, it could be implemented as a true/false field, instead of an actual table entry).
- Notification alarm. This alarm appears whenever a notification attemp fails (i.e. WARNING - "Notification failure for (...)"). The parameter of the alarm is _the URL of the notification_. The alarm is released when a sucessful notification is sent to that URL.
- Bad Input. This alarm appears whenever a notification atemp fails (i.e. WARNING - "Bad Input (...)"). The parameter of the alarm is the _IP/port_ of the client. The alarm is released when a request if received from that client without having bad input problems.

What does it mean that an alarm is released, from an operational point of view?
- The alarm is removed from the transient status in the manager.
- A trace is printed in the log about alarm releasing, at the same level than the trace that rises alarm:
  - Releasing Database alarms: ERROR
  - Releasing Notification failure alarms: WARNING
  - Releasing Bad Input alarms: WARNING

_Implementation notes_

This is similar to csubs cache (although this time we should go back to the usual std::vector instead... changing from std::vector to own-implemented linked-list was not an actual solution to cache problems, but an attemp when we don't know that the problem wasn't not in the cache itself, but in the cursors). As with csub cache, I think a semaphore is needed to protect concurrent access to the alarms manager.

A proposal for the functions/methods of the alarms manager module/class could be the following (pseudocode):

Internal data:

```
* bool dbStatus;
* vector<url> notifAlarms; // map<url> would be also a good alternative (easy to search)
* vector<pair<ip,port>> badInputAlarm;  // map<pair<ip,port>> could be also an alternative (easy to search)
```

Methods:
- void reportDbError()
  - In the case DB is "false" , do nothing.
  - In the case DB is "true", then change state to "false".
- bool reportDbSuccess()
  - In the case DB is in "true" status, do nothing. Return "false".
  - In the case DB is in "false" status, then change state to "true". Return "true" (this return value is used to know that an  alarm associated to the sucess has been released, so the calling code has to deal with log the alarm release message).
- void reportNotificationFailure(url)
  - In the case there is already a notifAlarm for that url, do nothing.
  - In the case there isn't already a notifAlarm for that url, create alarm entry.
- bool reportNotificationSucess(url)
  - In the case there isn't already a notifAlarm for that url, do nothing. Return "false".
  - In the case there is already a notifAlarm for that url, remove that entry. Return "true" (this return value is used to know that an  alarm associated to the sucess has been released, so the calling code has to deal with log the alarm release message).
- void reportBadInput(ip, port)
  - In the case there is already a badInputAlarm for that ip+port, do nothing.
  - In the case there isn't already a badInputAlarm for that ip+port, create alarm entry.
- bool reportGoodInput(ip, port)
  - In the case there isn't already a badInputAlarm for that ip+port, do nothing. Return "false".
  - In the case there is already a badInputAlarm for that ip+port, remove that entry. Return "true" (this return value is used to know that an  alarm associated to the sucess has been released, so the calling code has to deal with log the alarm release message).

(Maybe the reportBadThings methods should be also of type bool, returning true in the case of transitions, for homogenity).

Where to call these methods?
- reportDbError()/reportDbSuccess(): from the methods in connectionOperations (a module in mongoBackend library), where all the logic for connection to DB is now concentrated.
- reportNotificationFailure(url)/reportNotificationSucess(url): from the notification logic, once the HTTP send has been done and we know the result.
- reportBadInput(ip, port)/reportgGoodInput(ip, port). I understand that every Bad Input situation causes an early response, thus reportBadInput() will be used when as soon as bad input is detected. reportgGoodInput() will be invoked in some point of the request flow when all the Bad Input condigions have passed (to be sure, it could be just before passing the ball to MHD for sending the response)
  -  In the assumption "every Bad Input situation causes an early response" is not corect, then a thread variable "badInput = false" is initialized and checked at the end (before passing the ball to MHD for sending the response) to now if either reportBadInput() or reportgGoodInput() has to be called.

As nice-to-have a "GET /alarms/statistics" operation implemented in the same way "GET /cache/statistics" would be desirable. It can be useful also for test harness covering this functionality.

(There is room from improvement in methods names, of course :)

**Comment by fgalan** [comment]
Code implementation in PR #1616.

However, adjust in log.md are also required, so this issue will remain opened until we can implement them.

**Comment by kzangeli** [comment]
After some Skype discussions we have found the conclusion that Bad Input should be reset right after parse+check of the payload.

BadInput will be
* raised where found and
* reset right after parse+check of the payload if all is OK.

Right now badInputReset is called after the entire request has finished, and if it finished OK.
This has to be changed. It doesn't work ...

**Comment by fgalan** [comment]
Another piece of this (maybe finishing the code?) in PR https://github.com/telefonicaid/fiware-orion/pull/1676

**Comment by fgalan** [comment]
Documentation fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1718. Closing.

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending to review by QA team

**Comment by fgalan** [comment]
Issues in milestone QATestPendingNotE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
