### ISSUE TITLE
log improvements: Dynamic log level change using CB management API

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1584]
Root issue: #1518 

(See http://fiware-orion.readthedocs.org/en/develop/admin/management_api/index.html about Management API).

`-logLevel` will define the initial log level at start time, but then it could be changed using the management API. We could use the `/log/level` prefix, so:

* PUT /log/level/none: sets NONE level
* PUT /log/level/error: sets ERROR level
* PUT /log/level/warning: sets WARNING level
* PUT /log/level/info: sets INFO level
* PUT /log/level/debug: sets DEBUG level

(Is it correct to use PUT in this way, without payload? I hope so, otherwise we have a problem with this approach... :)

**Comment by kzangeli** [comment]
I looked around a little and it seems OK do to PUT/POST without payload.
http://stackoverflow.com/questions/16092989/can-rest-post-put-have-request-parameter-and-no-request-payload
http://stackoverflow.com/questions/4191593/is-it-considered-bad-practice-to-perform-http-post-without-entity-body

**Comment by jmcanterafonseca** [comment]
wouldn't it be better 

PATCH /log 

{
   "level": "error" 
}

**Comment by fgalan** [comment]
Duplicated of #1913 ?

**Comment by fgalan** [comment]
Duplicated
