### ISSUE TITLE
[BUG] in GET /v2/entities with q=+khkhj (query parameter) returns all entities

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1589]
In GET /v2/entities with q=+khkhj (query parameter) returns all entities although there is no such attribute.

#### Create Request
```
POST http://localhost:1026/v2/entities
Fiware-Service: qp_with_type
Fiware-ServicePath: /test
{"id": "room_2", "my_date": "20150412"}
```

#### Mongo doc:
```
{ "_id" : { "id" : "room_2", "servicePath" : "/test" }, "attrNames" : [ "my_date" ], "attrs" : { "my_date" : { "type" : "", "creDate" : 1449047352, "modDate" : 1449047352, "value" : "20150412" } }, "creDate" : 1449047352, "modDate" : 1449047352 }
```

#### Get Request
```
GEThttp://localhost:1026/v2/entities?q=+khkhj 
Fiware-Service: qp_with_type
Fiware-ServicePath: /test
```

#### Get Response
```
Status: 200 OK
[{"id":"room_2","my_date":"20150412"}]
```

**Comment by fgalan** [comment]
In addition, appart from "positive filter" `q=+khkhj`, also `q=-khkhj` has to be taken into account.

**Comment by fgalan** [comment]
Following answer in SOF has to be edited once this issue gets completed: http://stackoverflow.com/questions/34724227/filtering-orion-queries-by-attributes/34774804#34774804

**Comment by crbrox** [comment]
the '+' char should be URL-encoded
for example, ```curl localhost:1026/v2/entities?q=%2Battr1```works

**Comment by fgalan** [comment]
As with https://github.com/telefonicaid/fiware-orion/issues/1587, this issue may need that https://github.com/telefonicaid/fiware-orion/issues/1675 get solved first, so probably is a good idea to defer to 0.28.0.

**Comment by fgalan** [comment]
Syntax changed and `+` is no longer used. The right ones are:

GET /v2/entities?q=A -> all the entities with the attribute named "A"
GET /v2/entities?q=!A -> all the entities without the attribute named "A"

@iariasleon could you test based in that syntax in order to check if everything works as expected, please?

**Comment by iariasleon** [comment]
LGTM 
tested with:
```
  <version>0.28.0</version>
  <git_hash>d9424a63632492d7aa8df500d8aeac2fa98eb51a</git_hash>
```
See `only_q_attribute` tag in:
 components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_2.feature file
