### ISSUE TITLE
Restrict characters in ids and other fields

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1601]
Appart from the usual forbidden character check, some fields need an extra checking. A preliminary list of these fields is the following:
- entity_id
- entity_type
- attribute_name
- attribute_type
- metadata_name
- matadata_type

The specific set of allowed characters is yet under definition (if this issue is started, it should be implemented in a flexible way, so we can adjust the code to the final set to be defined).

To ensure backward compatibility, this checking is actived only if CB runs with the `-idCheck` flag is enabled (or better name for the flag). If a id-forbidden character is found at DB (it shouldn't happen, but it may happen) it has to be "neutralized" replacing it to an allowed one, e.g. "_".

**Comment by fgalan** [comment]
Detailed wording to implement (on the NGSIv2) spec: https://github.com/telefonicaid/fiware-orion/pull/1698

Some additional comments to take into account:

* NGSIv1 default behaviour would be as it is now in order don't break backward compabilitiy. In order to enable the restriction, a new CLI should be implemented, e.g.: `-ngsiv1CheckIdFields`.
* It could happen that Orion has to render (in the NGSIv2 API or NGSIv1 with `-ngsiv1CheckIdFields`) information in the DB not conforming with the restriction. For example, this can happend when upgrading Orion from an old version without reseting DB. In that case, in order to ensure consistency (it is not perfect, but at least it allows to solve the situation in a predectible way):
 * Replace forbidden characters (i.e. non ASCII + `#` + `/` + `?`) by "_"
 * Shorten fields longer than 256 chars to 256.

**Comment by fgalan** [comment]
Error descriptio to use in the case of max length:

```
entity id length: 1234, max length supported: 256
entity type length: 1234, max length supported: 256
attribute name length: 1234, max length supported: 256
attribute type length: 1234, max length supported: 256
metadata name length: 1234, max length supported: 256
metadata type length: 1234, max length supported: 256
```

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1722. This issue will remain opened until .md documents get modified.

**Comment by iariasleon** [comment]
LGTM in Maximum length of fields
```
 {"error":"BadRequest","description":"entity type length: 257, max length supported: 256"}
 {"error":"BadRequest","description":"entity id length: 257, max length supported: 256"}
 {"error":"BadRequest","description":"attribute name length: 257, max length supported: 256"}
 {"error":"BadRequest","description":"attribute type length: 257, max length supported: 256"}
 {"error":"BadRequest","description":"metadata name length: 257, max length supported: 256"}
 {"error":"BadRequest","description":"metadata type length: 257, max length supported: 256"}
```

**Comment by iariasleon** [comment]
Issue related https://github.com/telefonicaid/fiware-orion/issues/1351 about forbidden chars

**Comment by iariasleon** [comment]
Issue related https://github.com/telefonicaid/fiware-orion/issues/1728 about forbidden chars too

**Comment by fgalan** [comment]
> This issue will remain opened until .md documents get modified.

Reopening.

**Comment by fgalan** [comment]
Doc items in PR https://github.com/telefonicaid/fiware-orion/pull/1731

**Comment by fgalan** [comment]
Closing (although it some sense, this continues in https://github.com/telefonicaid/fiware-orion/issues/1733)

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
