### ISSUE TITLE
[BUG] Set of bugs related to "q" query parameter

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1610]
#### Set of bugs related to the "q" query parameter 

 - https://github.com/telefonicaid/fiware-orion/issues/1587
 - https://github.com/telefonicaid/fiware-orion/issues/1589 
 - https://github.com/telefonicaid/fiware-orion/issues/1592
 - https://github.com/telefonicaid/fiware-orion/issues/1594
 - https://github.com/telefonicaid/fiware-orion/issues/1595
 - https://github.com/telefonicaid/fiware-orion/issues/1607

**Comment by fgalan** [comment]
The following has been solved in 0.27.0:

* #1592 
* #1594 
* #1596 
* #1597 

Pending (for 0.28.0 or beyond):

* #1587 
* #1589

**Comment by iariasleon** [comment]
all issues have been closed
