### ISSUE TITLE
Docker-compose link for the subscription service URL

### ISSUE THREAD

**Issue by Bazm0** [telefonicaid/fiware-orion#1614]
Working with the context broker using Docker, you use RuSH to allow for ssl subscription URLs, I'm not crazy about having to spin up a separate RUSH service to accommodate this.

Could you update the context broker to allow users to choose to link their subscription service (container) and interpret the extrapolated container env vars with a subscription end point stub url (the reference value) that's provided in the subscribeContext broker call - wouldn't need https in this scenario, just using the internal IP call, and would allow for easier docker integration on the same docker host.

**Comment by LeandroGuillen** [comment]
I don't fully understand your question.

Do you want to be able to run rush on a separate container? Do you want to be able to tell Orion to use a default HTTP relaying host (container)? Do you want to be able to configure Orion to send all notifications to a certain host by default regardless of "reference" URL, and even use another container for that?

**Comment by Bazm0** [comment]
Hi,

This is the scenario:

1. Running my application services in docker containers on one docker host.
2. Running the context broker in docker containers on the same docker host
3. I don’t need a https relayer, I would like to connect my subscription_service container to the broker container, see below:


mongo:
  image: mongo:2.6
  command: --smallfiles --nojournal
orion:
  image: fiware/orion
  links:
    - mongo
    - subscription_service
  ports:
    - "1026:1026"
  command: -dbhost mongo

4. And provide the subscription_service endpoint path in the subscribeContext broker call, don’t need to provide a full URL here http://<subscription_service_internal_ip:subscription_service_port>/subscription_callback as the url and port are provided by linking in the docker-compose script above.
    
just the endpoint API method name is required (like any other linked container)

     e.g. /subscription_callback

5. As the containers are all running on the same Docker host there is no requirement for https as the endpoint can be exposed securely/internally in this context.
 

Essentially I would just like to be able to link my subscription service container to the context broker container.

Hope this clears up what I’d like to be able to do. Let me know if you need more info.

**Comment by LeandroGuillen** [comment]
So if I understand you correctly, what you want to do is that when subscribing to a context element you don't want to have to indicate the host and port of the consumer of the notification, because this consumer is well known and protected

Then you want to be able to put a resource on the _reference_ field of the subscription as this is how you route your notifications within the _subscription_service_ consumer.

And you want to be able to do this linking by using the docker infrastructure (automatic host naming in /etc/hosts in containers).

If I get anything wrong please correct me.

So the question is, how do you do a subscription from the outside without having to know the _subscription_service_ host name, or even that is exists? So that you could say "subscribe to this entity, and the resource that needs to be notified is _/subsciption_callback_.

Is this correct?

**Comment by Bazm0** [comment]
Yes, exactly, the [optional] capability of linking the subscription container to the broker container in the fully dockerized scenario I outlined above. 

Currently I am providing the internal ip and port API subscription callback as the reference URL:

http://subscription_service_internal_ip:subscription_service_port/subscription_callback

the subscription_service_internal_ip can change every time the container is started and stopped, therefore being able to link the containers would be nice :)

**Comment by LeandroGuillen** [comment]
You could actually use rush for this. So you could run orion with something like `contextBroker -rush <subscription_service_IP>:<port>`

This way, whenever there is a notification, regardless of origin, reference, etc. it will be sent to your docker host. Notice how this does not require you to run rush at all, this is tricking Orion into thinking it's using it :) And then you are acting as the HTTP relayer, only that you are not relaying anything, but consuming the notification. Orion won't care what you do with the notification at this point.

Also, at runtime you know the host and port of your _subsciption_service_, so you can use it to run Orion no problem in your docker-compose.yml.

**Comment by fgalan** [comment]
I understand that the question was solved. If I'm wrong, please re-open the issue or comment about it. Thanks!
