### ISSUE TITLE
Should we have an option for location attributes rendering?

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1618]
As a Follow-up of https://github.com/telefonicaid/fiware-orion/pull/1524#issuecomment-163883129 : 

In the current spec we intend to support two formats to describe locations:

A/ Simple Location Format
B/ GeoJSON

The issue is that when rendering location attributes which format should be used? 

1/ The original format which was used when submitting the entity
2/ A format requested by the user through options. 

Option 1 is simple
Option 2 allows more flexibility 

Could there be some point in the middle? Option 1 when nothing specified and option 2 when 'options' is in place? 

@fgalan @marcc-orange

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
