### ISSUE TITLE
NGSIv2: View (alias) functionality. Study its inclusion in the API

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1632]
It would be nice to have a functionality in the API which allows to create new entity collections based on existing data. There are various use cases:

Synonyms (aliases) . Example 

type=Room --> type=Habitación 

The type 'Room' and the type 'Habitación' will contain the same entity set. 

type=Room;q=capacity>50  --> type=BigRoom

When someone lists entities by type 'BigRoom' the result will include those rooms which have a capacity greater than 50 seats. 

type=PointOfInterest;q=category:WeatherStation --> type=WeatherStation

We are aliasing a kind of POI to a new type hiding the complexity of the original data model. 

This functionality can be pretty useful, I think. A resource which allows to manage the CRUD of aliases would suffice ...  

/v2/aliases

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
