### ISSUE TITLE
[BUG] in GET "/v2/entities/<id>/attrs/<attr_name>/value" with several Accept header

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1635]
in  Attribute Value --> By Entity ID --> Get attribute value 
   GET `/v2/entities/<id>/attrs/<attr_name>/value` 

 - If `Accept: application/json` and the attribute value is number or string or boolean or null returns a json response as `{"value":56.000000}` or `{"value": "34"}` or `{"value":true}`  instead of an error message, ex:
```
HTTP code: 406 Not Acceptable
{
    "error": "NotAcceptable",
    "description": "no defined yet"
} 
```

- If `Accept: text/plain` always returns a string, also in number, boolean or null values

**Comment by fgalan** [comment]
Actually, this is already taken into account in issue #1259 part 6. However, let's hold this issue if you want, to make more explicit the need of checking this after #1259 completion from a QA perspective.

**Comment by raconte** [comment]
1.-Create an entity (POST)
(curl localhost:1026/v2/entities -s -S --header Content-Type:application/json -d @- | python -mjson.tool)<< EOF
{
  "type": "Room",
  "id": "Room1",
  "temperature": {
    "value": 23.4
  },
  "humidity": {
    "value": 78
  },
  "location": {
    "value": "41.3763726, 2.1864475",
    "type": "geo:point",
    "metadata": {
      "crs": {
        "value": "WGS84"
      }
    }
  }
}
Created succesful 

2.-Get attribute value by entity ID
curl localhost:1026/v2/entities/Room1/attrs/temperature/value  --header 'Accept: text/plain'

Returns the number 23.4000

3.-In case of Accept: application/json
curl localhost:1026/v2/entities/Room1/attrs/temperature/value  --header 'Accept: application/json'
	{
		"error":"NotAcceptable",
		"description":"accepted MIME types: text/plain"
	}
	
Solved

**Comment by iariasleon** [comment]
LGTM
```
Status: 406: Not Acceptable
{
"error": "NotAcceptable"
"description": "accepted MIME types: text/plain"
}
```
