### ISSUE TITLE
APIv2: unify subscriptions for entities and registrations ?

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1655]
Current API (NGSIv1) has two very close interfaces (`notifyContext` and `notityContextAvailability`)  for subscribing/notifying an external components of update to entities or to registrations.

A unique `/v2/subscriptions` interface could allow notifying an external component both for entity creation (from `/v2/registrations` operations) or entity updates (from `/v2/entities` operations).

The `condition` field could take an additional `mode` (bad generic name, find a better one)  to allow only receiving notification related to either entities or registrations updates with a value of `entities`, `registrations` or `all`, defaulting to `entities` when omitted.

Example of `POST /v2/subscriptions` :

``` json
        {
            "subject": {
                "entities": [
                    {
                        "type": "Room"
                    }
                ],
                "condition": {
                  "mode": "all"
                 }
            },
            "notification": {
                "callback": "http://localhost:1234",
                "throttling": 5,
            },            
            "expires": "2016-04-05T14:00:00.00Z"
        }
```

Here is an example of a notification payload (`/v2/notify` is not yet defined in APIv2).
It would contains two sections: one for notifying the `entities` and one for the `registrations`.

``` json
{
  "subscriptionId" : "51c04a21d714fb3b37d7d5a7",
  "originator" : "http://originator:8080",
  "entities" : [
    {
      "id" : "Room1",
      "type": "Room",
      "temperature": 26.5
    }
  ],
  "registrations": [
    {
      "subject": {
        "entities": [
          {
           "type": "Room"
          }
        ],
        "attributes": [
          "humidity"
        ]
    },
    "callback":  "http://localhost:1234",
    "metadata" : {
      "provider": {
        "value": "example.com"
      }
    },
    "duration": "PT1M"
  }
]
}
```

A bad idea ?

**Comment by fgalan** [comment]
Unifying subscriptions and notification in NGSIv2 sounds a good idea to me. We have not analyzed yet the best way of achieving it but of course your idea about `mode` will be taken into account.

Thanks for the feedback!

(Sorry for the delay answering this)

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
