### ISSUE TITLE
APIv2: Patch subscription

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1658]
Implement the following operation in in v2:

```
PATCH /v2/subscription/<subId>
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Implemented in PR #1686

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/020_pep2cbv2_patternsinentitytypes.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
