### ISSUE TITLE
Websockets module: avoid size limitations

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1667]
(Parent issue: #1181)

Current implementation uses a hardwired size limit in message (both input and output?) of 128 bytes (if I’m remembering correctly). We should ensure that messages greater than that are correctly handled.

**Comment by fortizc** [comment]
This is was solved in d72aab58bca2fab5c5670ed1fbd953a8115dfcef

**Comment by fgalan** [comment]
For the sake of traceability... do you know the PR number in which the d72aab5 commit was merged into feature/1181_websockets? Thx!

**Comment by fgalan** [comment]
That commit is part of PR https://github.com/telefonicaid/fiware-orion/pull/1814
