### ISSUE TITLE
Websockets module: include status code and headers in output messages

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1668]
(Parent issue: #1181)

Currently the output that the client gets is composed only for the equivalent to the payload in the REST API. However, response messages could also include other information pieces (specially in NGSIv2), in particular: response code and headers.

Maybe using a JSON envelope approach (as for input messages) could be also useful in this case.

**Comment by fortizc** [comment]
Something like this?

```javascript
{
   "headers": {
      "Fiware-Service": "myServ",
      "Fiware-ServicePath": "/test2",
      "X-Auth-Token": <...>
   },
   "message": {
      "error":"NotFound",
      "description":"The requested entity has not been found. Check type and id"
   }
}
```

**Comment by fgalan** [comment]
I understand that is using the same structure of input messages, I mean, input messages also use "headers" and "message" field. In that case, it looks good! :)

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1878.
