### ISSUE TITLE
Wrong replacement of "+" for whitespace in URL path with some versions of libmicrohttpd

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1675]
It has been found that old versions of libmicrohttpd (and, in particular the reference one in Orion build documentation -0.9.22- as long as the one found in CentOS 6.x systems by the time being -0.9.33) wrongly replace "+" by whitespace in URLs.

Lookign to libmicrohttpd changelog it seems thiw was solved in libmicrohttpd 0.9.34:

```
May  2 20:22:45 CEST 2014
        ...
	Releasing 0.9.35. -CG

Thu Apr 10 09:39:38 CEST 2014
	Removed unescaping for URI path (#3371) as '+' should not
	be converted to space in accordance with
	http://www.w3.org/TR/html401/appendix/notes.html#ampersands-in-uris
	and http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
	Note that we now also no longer convert '#38;' to '&'; if needed,
	the application needs to apply unescaping to the path of the URI
	itself (before, MHD unescaped '#38;' but not '&amp;', so this
	inconsistency was now resolved by simply not unescaping anything
	before the first '&'). -CG

...

Mon Feb 24 23:13:53 CET 2014
	...
	Releasing 0.9.34. -CG
```

Fix version is confirmed by this report at GNU bugzilla: https://gnunet.org/bugs/view.php?id=3371

It seems there isn't any easy workaround with 0.9.33 (see https://lists.gnu.org/archive/html/libmicrohttpd/2016-01/msg00007.html) so it seems that we would need to upgrade the libmicrohttpd version used by Orion. Two alternatives appear:

* Rely on operating system packaging system to depend on an RPM newer enough (changes in .spec to include >0.9.35 and probably the installation documentation in the case it is not possible to find the right RPM in official CentOS/EPEL repos).
* Remove external dependency as RPM file and statically compile the library (changes in .spec and building from sources documentation)

**Comment by fgalan** [comment]
At the end we will go with the statical compilation soluction. Although the RPM could be installed from a non-official repository, that could break existing applications relying in the system library specific version (it is a remote possibility, but a possibility after all).

This decision will be reviewed if we move our official support to a new distro (e.g. CentOS 7.x) which a suitable version for libmicrohttpd as sytem library.

**Comment by fgalan** [comment]
Target version: libmicrohttpd 0.9.48

**Comment by kzangeli** [comment]
Two functests implemented when discovered (rediscovered) that '+' in URI params is converted to SPACE. These two functests are:

* 1587_q_query_has_type/q_query_has_type.test
* 1589_query_entities_with_specific_attributes/query_entities_with_specific_attributes.test.pending1675.DISABLED

As you can see, one of them is left as DISABLED, pointing to this issue.
The other one, **q_query_has_type.test** works except for *one* step in the test, so that step has been commented out. 

These two func tests should be 100% reenabled once this issue is fixed, and as their implementation was interrupted by not working, they should be looked over and most possible completed.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/1745 has partially addressed this issue. What is pending before closing:

* Add a .test to cover a case using +34XXX as entity id and using that in the URl
* Modify Dockerfile to build libmicrohttpd from sources
* Get ok from @jcanonav

**Comment by fgalan** [comment]
> Two functests implemented when discovered (rediscovered) that '+' in URI params is converted to SPACE

Actually, they are related with https://github.com/telefonicaid/fiware-orion/issues/1751. A comment has been added in that issue.

**Comment by fgalan** [comment]
Installation scripts for devel environment (fiware-components) successfully updated and verifiyed by @dmoranj . No more activity associated to this issue, so it will be closed (if the "entities with + in the id" problema arises again then we would reopen or create a new issue).
