### ISSUE TITLE
APIv2: align geo-location queries with last changes in spec

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1677]
PR https://github.com/telefonicaid/fiware-orion/pull/1524 introduced some changes in the way geolocation queries work regarding the first implementation (e.g. new `georel` parameter). This issue is about modifying Orion in order to align with that new approach.

**Comment by fgalan** [comment]
As with former NGSIv2 geo-query parameters, the idea is to translate then to a NGSIv1 FIWARE::Location scope, then process that FIWARE::Location at mongoBackend to render the query. As (positive) side effect, NGSIv1 geoquery functionality will be enhanced.

In fact, let's use "FIWARE::Location::NGSIv2". Trying to "fit" NGSIv2 geoqueries in the original FIWARE::Location containers can be hard.

```
            {
                "type": "FIWARE::Location::NGSIv2",
                "value": {
                    "georel": [ <the parsed georel: near, coveredBy, intersects, equals, disjoint; one element in each vector> ]
                    "geometry": "<point|line|polygon|box>",
                   "coords": [ <array of tuples with coordinates> ]
                }
            }
```

Note that "georel" couldn't be a simple property, due to the near operation has minRadious and maxRadius that we need also to take into account.

Probably a new class to hold this information would be needed as interface between serivceRoutines and mongoBackend.

**Comment by fgalan** [comment]
Scope/areas implemented in PR https://github.com/telefonicaid/fiware-orion/issues/1677. Next, mongoBackend processing the new types is needed.

**Comment by fgalan** [comment]
mongoBackend part (along with some adjust in other layers) in PR https://github.com/telefonicaid/fiware-orion/pull/1801

What is missing yet to close this issue is the processing of FIWARE::Location::NGSIv2 scopes as part of the payload of /v1/queryContext

**Comment by fgalan** [comment]
The branch to complete the work is *feature/1677_ngsi2_geoqueries_as_payload_scope*. It currently includes doc changes and .test (only the SHELL part... the REGEXEPCT part would need to be adjusted to the NGSIv1 format).

**Comment by fgalan** [comment]
Finished (the last part regarding NGSIv1) in PR https://github.com/telefonicaid/fiware-orion/pull/1828

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests are created in its feature associated

**Comment by iariasleon** [comment]
E2E covered in:
     features/pepflows/003_pep2cbv2_geojsonsupport.feature
     features/pepflows/017_pep2cbv2_geonotifications.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
