### ISSUE TITLE
APIv2: geoquery expression in subscriptions

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1678]
Issue #1316 is about basic subscription creation, including `q` filters in the expression field. The present issue is about completing the support of the other elements in expression field: `georel`, `geometry` and `coords`.

This issue should be done after https://github.com/telefonicaid/fiware-orion/issues/1677 (given that probably some "reusing" of that is needed in subscriptions).

**Comment by fgalan** [comment]
The following post at SOF must be edited when this issue gets completed: http://stackoverflow.com/questions/36064565/fiware-orion-subscription-with-georel-expression-in-condition

**Comment by fgalan** [comment]
Implemented in PR #2397

**Comment by fgalan** [comment]
Assigned to @iariasleon for final QA verification before closing it.

(If this cannot be checked withitn the 1.3.0 development cycle, it will be moved to QATestPending milestone)

**Comment by iariasleon** [comment]
This issue has been tested in INT environment, but it should be tested in more detail by the area of component, it is moved to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
