### ISSUE TITLE
201 Created returned for entity-updates with POST /v2/entities/<eid>

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1682]
This should return a **204 No Content**.
Except of course if the entity didn't exist prior to the `POST /v2/entities/<eid>` request.
If the entity is created then **201 Created** should be returned.

This means mongoBackend must return the information that the entity did/didn't exist.

**Effort: 2 man day**

**Comment by fgalan** [comment]
> Except of course if the entity didn't exist prior to the `POST /v2/entities/<eid>` request

That cannot happen. Note that `POST /v2/entities/<eid>` cannot be used for creating entities, the only legal operation to create entities in NGSIv2 is `POST /v2/entities` (without `<eid`>).

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1709
