### ISSUE TITLE
(Only changes in doc remain) More than one Bad Input per erroneous request

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1697]
Implementing the Log Summary it seems that some requests forcing a *Bad Input* have 
**more than one Bad Input**.
It might be worthwhile to hunt these occurrences down and get rid of this mildly annoying and not very important problem (does Operation agree to that it is not important?)

**Effort: 2 man day**

**Comment by fgalan** [comment]
(Preliminarirly added to milestone 0.27.0)

**Comment by fgalan** [comment]
Fixed in #1710. However, this issue is kept opened until `relogAlarms` could be taken into accoun in logs.md documentation.

**Comment by fgalan** [comment]
Documentation fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1718. Closing.
