### ISSUE TITLE
Fix names of constants in RequestType enum

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#171]
### Description

The names of the constants of the enum RequestType in src/lib/ngsi/Request.h are pretty bad.
This should be fixed, using a common prefix 'Rt' or even a C++ namespace.
Also, all possible NGSI 'containers' should be added to this enumeration.

With 'container' is referred all the ngsi/ngsi9/ngsi10 classes.
Not only top level classes (Request/Response of ngsi9 and ngsi10 libraries) but also for example the class ContextElement of the ngsi library. Any class that contain other classes, like ContextElement contains EntityId.

**Effort: 2 man day**

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan/ @kzangeli Sir,
According to my understanding:

1. add ```Rt``` prefix before all constants of enum - ```RequestType``` in 'Request.h' file.
2. add all classes of NGSI-9 and NGSI-10 (as all classes are request and response type in this) in enum,  and in NGSI folder I have to add only those classes which has dependencies on other classes with prefix ```Rt```.

Could you please provide your valuable guidance on the same.

**Comment by fgalan** [comment]
Looking at the current `RequestType` enum, the constant names used by NGSIv2 request seem to be fine. With regard to NGSIv1, it is deprecated so it is not a good idea to invest time in changing their names.

So probably this issue is now obsolete (it is almost 6 years old! :) and maybe should be closed. What do you think?

**Comment by kzangeli** [comment]
Yeah, I think we can close this one. Really old and  all APIv1 code will probably soon be removed completely.
