### ISSUE TITLE
API v2: "batch" update

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1715]
Implement the following operation in in v2:

```
POST /v2/op/update
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
This operation should implement delete patterns of entities, as has been suggested for NSGIv1 in this separate issue: https://github.com/telefonicaid/fiware-orion/issues/1645

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1812

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by iariasleon** [comment]
LGTM 
See  https://github.com/telefonicaid/fiware-orion/tree/master/test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update
