### ISSUE TITLE
QueryContext with ID metadata scope ?

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1750]
Hi,
I'm trying to write a QueryContext that only returns an attribute having a precise ID (in its metadata) like it is possible for "convenient" operation:
 `/v1/contextEntities/type/Sensor/Sensor1/attributes/temp/DEADBEEF`.

Is it possible to use some scope restriction on a QueryContext to filter attributes with a `DEADBEEF` ID ?

```json
{
    "entities": [
    {
        "type": "Sensor",
        "isPattern": "false",
        "id": "Sensor1"
    }
    ],
    "attributes" : [
        "temp"
    ],
   "restrictions": {
     "scopes": [
       { "type": "FIWARE::???", "value":"DEADBEEF"},
       { "type": "FIWARE::Location", "value": "[...]"}
     ]
   }
}
```
Thanks.

**Comment by marcc-orange** [comment]
I found about the ["FIWARE::StringQuery" filter](https://fiware-orion.readthedocs.org/en/develop/user/filtering/index.html#string-filter) in the docs that can use the APIv2 Simple Query Language but it does not seem like it is possible to apply a query to a metadata, only to attributes.

Maybe something like :

```json
       { "type": "FIWARE::StringQuery", "value":"temp.ID==DEADBEEF"}
```
could be nice if Simple Query Language supported a kind of JsonPath style for accessing attribute's metadata...

Any thoughts on that ?

**Comment by fgalan** [comment]
We are thinking in supporting queries on structured content (see https://github.com/telefonicaid/fiware-orion/issues/1156). Metadata is already mentioned in that issue.

Thanks for the JsonPath feedback. I haven't look to it into detail but the syntax defined in #1156 seems to be similar to JsonPath.

**Comment by marcc-orange** [comment]
ok, thanks for the feedback.
