### ISSUE TITLE
Change in syntax for URI param 'q'

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#1751]
Attribute Exists & Not Exists, right now use '+' and '-' in the URI param 'q':

    GET /v2/entities?q=+attr1;-attr2

However, the '+' is decoded to a SPACE by MHD and a decision has been made to change the syntaxis, using 'no prefix' for EXISTS and '!' for NOT EXISTS:

    GET /v2/entities?q=attr1;!attr2

We also use '+/-' for TYPE EXISTS:

    GET /v2/entities?q=+type

That syntaxis must be changed the same way, to:

    GET /v2/entities?q=type       # Get entities that have a type
    GET /v2/entities?q=!type      # Get entities that DO NOT have a type

Actions to be taken:
1. Change the source code (qStringFilters in MongoGlobal.cpp)
2. Modify existing functests that use the old syntaxis
3. (if not fully covered), new functests
4. Modify documentation (.apib ngsiv2), including changing examples in the doc using the old syntax

Related issues:
  #1589 
  #1587

**Comment by fgalan** [comment]
Maybe https://github.com/telefonicaid/fiware-orion/issues/1587 is also related (at least partially)

**Comment by fgalan** [comment]
In addition, after completing this issue the following .test need to be enabled (after modifications):

* 1587_q_query_has_type/q_query_has_type.test 
* 1589_query_entities_with_specific_attributes/query_entities_with_specific_attributes.test.pending1675.DISABLED

**Comment by fgalan** [comment]
Fixed by PR #1756 (mainly) and #1760 (two disabled .test).

**Comment by iariasleon** [comment]
Reopen because is pending to test by QA

**Comment by iariasleon** [comment]
LGTM

**Comment by fgalan** [comment]
Changed milestone to 0.28.0, the one in which this will really fixed (see https://github.com/telefonicaid/fiware-orion/releases/tag/0.28.0 and look for "1751").
