### ISSUE TITLE
Updating entity attributes fails when mongo key becomes too long

### ISSUE THREAD

**Issue by olivierdeckers** [telefonicaid/fiware-orion#1764]
The following call creates an entity in a service path:
```
POST /v2/entities/test
Content-Type: application/json
Fiware-Service: default
Fiware-ServicePath: /tester1testcom/e2dbaecbcccccccccccccccccccccccc

{
    "type": "Patient",
    "key": "value"
}
```

If the call is sent again, this should update the attribute 'key'. However, Sending the call a second time returns HTTP statuscode 472, with a mongodb error of a duplicate key insertion.

Also, when using PUT calls to update attributes in this entity, orion reports the entity cannot be found.
The entity was inserted successfully, because a GET call to v2/entities/test returns the correct data.

This leads me to believe the POST/PUT code uses another query to test for the existance of the entity. I assume it fails to find this entity and proceeds by running an insert query, which fails.

By trial and error, I discovered that this behaviour occurs as soon as the mongo _id property has a certain length. In the example call, if we remove one character from either the service path, the entity id or the entity type, orion behaves as expected.

Our service path respects the restrictions of a maximum of 50 characters per level and a maximum of 10 levels.

Also, the mongo maximum index key length is 1024 bytes, which is well above the length of the _id value. Since the entities are successfully inserted into the mongodb database, I don't think the issue is located somewhere in the orion entity update logic rather than in mongodb

This was tested on orion v0.26.1 and mongo v2.6.11

**Comment by abbasahmad** [comment]
Hello,

Just wanted to confirm and give more details about this error on how to reproduce : 

# First TRY (UPDATE With APPEND)
#### POST :
http://IP:PORT/v1/updateContext

#### HEADERS : 
* Content-type: application/json
* Accept: application/json
* Fiware-Service: default
* Fiware-ServicePath: /tester1testcom/e2dbaecbcccccccccccccccccccccccc

#### PAYLOAD : 
```json
{
    "contextElements": [
        {
            "type": "Sensor",
            "isPattern": "false",
            "id": "Room1",
            "attributes": [
            {
                "name": "temperature",
                "type": "float",
                "value": "23"
            },
            {
                "name": "pressure",
                "type": "integer",
                "value": "720"
            }
            ]
        }
    ],
    "updateAction": "APPEND"
}
```
## Response 
```json
{
  "contextResponses": [
    {
      "contextElement": {
        "type": "Sensor",
        "isPattern": "false",
        "id": "Room1",
        "attributes": [
          {
            "name": "temperature",
            "type": "float",
            "value": ""
          },
          {
            "name": "pressure",
            "type": "integer",
            "value": ""
          }
        ]
      },
      "statusCode": {
        "code": "200",
        "reasonPhrase": "OK"
      }
    }
  ]
}
```

# Second try

**Do the Same POST With the SAME headers and payload here is the response : 

## Response 
```json
{
  "contextResponses" : [
    {
      "contextElement" : {
        "type" : "Sensor",
        "isPattern" : "false",
        "id" : "Room1",
        "attributes" : [
          {
            "name" : "temperature",
            "type" : "float",
            "value" : ""
          },
          {
            "name" : "pressure",
            "type" : "integer",
            "value" : ""
          }
        ]
      },
      "statusCode" : {
        "code" : "472",
        "reasonPhrase" : "request parameter is invalid/not allowed",
        "details" : "Database Error &#40;collection: orion-default.entities - insert&#40;&#41;: { _id: { id: \&quot;Room1\&quot;, type: \&quot;Sensor\&quot;, servicePath: \&quot;/tester1testcom/e2dbaecbcccccccccccccccccccccccc\&quot; }, attrNames: [ \&quot;temperature\&quot;, \&quot;pressure\&quot; ], attrs: { temperature: { type: \&quot;float\&quot;, creDate: 1454686805, modDate: 1454686805, value: \&quot;23\&quot; }, pressure: { type: \&quot;integer\&quot;, creDate: 1454686805, modDate: 1454686805, value: \&quot;720\&quot; } }, creDate: 1454686805, modDate: 1454686805 } 
- exception: OperationException: { index: 0, code: 11000, errmsg: \&quot;\&quot;, op: { _id: { id: \&quot;Room1\&quot;, type: \&quot;Sensor\&quot;, servicePath: \&quot;/tester1testcom/e2dbaecbcccccccccccccccccccccccc\&quot; }, attrNames: [ \&quot;temperature\&quot;, \&quot;pressure\&quot; ], attrs: { temperature: { type: \&quot;float\&quot;, creDate: 1454686805, modDate: 1454686805, value: \&quot;23\&quot; }, pressure: { type: \&quot;integer\&quot;, creDate: 1454686805, modDate: 1454686805, value: \&quot;720\&quot; } }, creDate: 1454686805, modDate: 1454686805 } }&#41;"
      }
    }
  ]
}
```

I tried to reduce the Header : ** Fiware-ServicePath: /tester1testcom/e2dbaecbcccccccccccccccccccccccc** to this value : **Fiware-ServicePath: /tester1testcom/e2dbaecbccccccc** and the Multiple append works with no problem. 

Hope it helps you correcting the problem. 

Abbas AHMAD
Easy Global Market

**Comment by fgalan** [comment]
Thank you for the feedback and the detailed report! Our QA team will have a look to it.

**Comment by iariasleon** [comment]
Hi @olivierdeckers,

I saw the problem in 0,26.1 version, was reported in https://github.com/telefonicaid/fiware-orion/issues/1423 and fix in 0.27.0. But this request has been changed in 0.27.0 version, I recomend to update.

In 0.27.0:
`POST v2/entities/<id>` can not to create a new entity
id` and `type` have a max length allowed (256) and only plain ascii are allowed, so it is impossible to arrives to  the mongo maximum index key length (1024 bytes), See "Field syntax restrictions" in http://telefonicaid.github.io/fiware-orion/api/v2/

And the json format will be:
Ex:
```
POST /v2/entities/test
{
    "key": {
         "type": "Patient",
        "value": "value"
    }
}
```
Or
```
POST /v2/entities/test?options=keyValues
{
    "key":  "value"
}
```

I create an issue to v1 version error, Thanks, @abbasahmad

**Comment by iariasleon** [comment]
I close, if you have  some comments, reopen this issue again

**Comment by fgalan** [comment]
The fix in PR https://github.com/telefonicaid/fiware-orion/pull/1780 could be related with the solution to this issue.
