### ISSUE TITLE
APIv2: order of attributes in values mode

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1766]
[Current APIv2 Specification](https://github.com/telefonicaid/fiware-orion/blob/d0c4e79648d493dc201a1d2968f912334603530d/doc/apiary/v2/fiware-ngsiv2-reference.apib) defines a *values mode* in the Simplified Entity Representation section:

> *values mode*. This mode represents the entity only by a collection of attribute values conveyed by an Array. Id and type information are left out. See example below.

```
[ 'Ford', 'black', 78.3 ]
```

There is no mention about ordering of attributes.

Will attributes keys be sorted by an alphabetical/natural order or by attributes creation (guaranteeing existing ordering by appending newer attributes at the end of the array) ?

**Comment by fgalan** [comment]
The order would be the one in the `attrs` parameter, e.g.:

```
GET /v2/entities/MyCar?options=attrs=brand,colour,engine
```

However, it seems this is not clearly explained in the current "Simplified Entity Representation". Let's keep this issue opened until the NGSIv2 .apib get fixed.

Thanks for the feedback!

**Comment by marcc-orange** [comment]
I was thinking for the case where we do not define the list of attributes to retrieve them all, as `attrs` is optional.
> attrs: seatNumber (optional, string) - Comma-separated list of attribute names which data will be included in the response. If this parameter is not included, all the attributes are retrieved.

**Comment by fgalan** [comment]
In that case, the attributes order is arbitraty (i.e. random).

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1818
