### ISSUE TITLE
[BUG] in PATCH v2/entites/<id> if attr_type is empty returns 204 instead of an error message 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1785]
in `PATCH v2/entites/<id>` if attribute type is "" (empty)  returns 204, attribute type is not updated, but the attribute value is updated, instead of an error message as " Invalid characters in attribute type". See "Field syntax restrictions" in http://telefonicaid.github.io/fiware-orion/api/v2/

#### Create Request
```
POST http://localhost:1026/v2/entities
Content-Type: application/json
Fiware-Service: test_update_attribute_type_error
 Fiware-ServicePath: /test
 {"type": "house", "temperature": {"type": "celcius", "value": "34"}, "id": "room_12"}
```

#### Update Request
```
PATCH http://localhost:1026/v2/entities/room_12
Content-Type: application/json
Fiware-Service: test_update_attribute_type_error
Fiware-ServicePath: /test
{"temperature": {"type": "", "value": "89"}}
```

#### Update response
```
http code: 204
date: Thu, 11 Feb 2016 09:58:55 GMT
connection: Keep-Alive
content-length: 0
```

#### Expected response
```
http code: 400
date: Thu, 11 Feb 2016 10:09:29 GMT
connection: Keep-Alive
content-type: application/json
content-length: 75
{"error":"BadRequest","description":"Invalid characters in attribute type"}
```

#### Mongo doc after update request
```
{ "_id" : { "id" : "room_12", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "89", "type" : "celcius", "creDate" : 1455184735, "modDate" : 1455184735 } }, "creDate" : 1455184735, "modDate" : 1455184735 }
```

**Comment by fgalan** [comment]
With the current specification, note that type "" is valid as: a) it doesn't pass the  256 length (in fact, its length is 0), b) it doesn't containt any of the forbidden chars for IDs.

Note the "with the current specification" above. It is very likely that we add a new limit for the minimum of 1 character in entity id, entity type, etc. so let's hold on this issue opened.

**Comment by fgalan** [comment]
Probably when https://github.com/telefonicaid/fiware-orion/issues/1836 gets implemented this issue get also solved.

**Comment by fgalan** [comment]
It seems (by the .test in PR https://github.com/telefonicaid/fiware-orion/pull/2292) that this issue is already fixed. @iariasleon please have a look and close in positive case.

**Comment by iariasleon** [comment]
LGTM
```
http code: 400 - Bad Request
headers:
   date: Fri, 17 Jun 2016 09:07:16 GMT
   fiware-correlator: e3545c26-346a-11e6-aad4-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 88
payload: {"error":"BadRequest","description":"attribute type length: 0, min length supported: 1"}
```
