### ISSUE TITLE
[BUG] in PATCH v2/entities/<id> with only metadata returns error message

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1789]
in PATCH `v2/entities/<id>` with only metadata in the payload returns error message, the way to update successful, you must to add the `attribute value` in the payload.

#### update request
```
PATCH http://localhost:1026/v2/entities/room
Content-Type: application/json
Fiware-Service: test_attribute_metadata_name_update
Fiware-ServicePath: /test
 {
     "temperature": {
           "metadata": {
                    "my_meta": {
                            "value": "5678" } } } }
```

#### update response
```
http code: 400
date: Thu, 11 Feb 2016 15:08:17 GMT
connection: Keep-Alive
content-type: application/json
content-length: 88
{"error":"BadRequest","description":"no 'value' for ContextAttribute without keyValues"}
```

related issue: https://github.com/telefonicaid/fiware-orion/issues/1788

**Comment by fgalan** [comment]
As far as I undertand by:

> Attribute/metadata value may be omitted in requests, meaning that the attribute/metadata has null value

the error message is not correct and the request should be processed as it was:

```
 {
     "value": null,
     "temperature": {
           "metadata": {
                    "my_meta": {
                            "value": "5678" } } } }
```

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1889. Please @iariasleon have a look and close it if you find it solved.

**Comment by iariasleon** [comment]
LGTM
tested in the following features:
 -  Create entity
 -  Update or append entity attributes
 -  Update existing entity attributes
 -  Replace all entity attributes
