### ISSUE TITLE
Fix "Other Error" warnings

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1794]
We have a couple of warnings with the text "Other Error", which is not within the ones we have documented and controlled: Database Error, Notification failure or Bad Input.

```
LM_W(("Other Error (context provider response to QueryContext is empty)"));
```

```
LM_W(("Other Error (context provider response to UpdateContext is empty)"));
```

This is related with fails in CPr interactiong. Probably a good solution would be to define a new category of "Context Provider Failure" (which its associated alarm type, properly documented in logs.md, etc.). Maybe some errors about HTTP connection fails currently in Notification failure category should be clasified under this "Context Provider Error" category

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I would like to work on this issue, please assign this issue to me.
As per my understanding, we need to add new category for "Other Error" named as "Context Provider Failure" in alarm type in logs.md.
Please confirm the above understanding and approch.

**Comment by fgalan** [comment]
Thank you for your willingness to work on this issue! I have assigned it to you :)

With regards to specific actions to do, I think they are the following ones:

* Change message text in traces from "Other Error" to "Forwarding Error" (I think this is a better name than "Context Provider Failure")
* Define a new kind of alarm in https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/logs.md#alarms pretty similar to current number 5 for notifications, per-URL
* Ensure that the alarm works properly in the program flow. I mean, create a couple of functions similar to `notificationError` and `notificationErrorReset` and use them in the right points. The xxxxError function has to be called in situations in which the forwarding has failed, the xxxxErrorReset function has to be called when a forwarding has gone well.

```
  bool forwardingError(const std::string& url, const std::string& details);
  bool forwardingErrorReset(const std::string& url);
```

* Ensure that notification and forwarding alarms work fine (in the sense no notification alarm is incorrectly using a forwarding alarm or the other way around)

**Comment by fgalan** [comment]
In the case it helps:

```
$ grep "Other Error" -R src/
src/lib/serviceRoutines/postQueryContext.cpp:    LM_W(("Other Error (context provider response to QueryContext is empty)"));
src/lib/serviceRoutines/postUpdateContext.cpp:      LM_W(("Other Error (context provider response to UpdateContext is empty)"));
src/lib/serviceRoutines/postUpdateContext.cpp:    LM_W(("Other Error (unexpected response from context provider: %s)", out.c_str()));
```

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I have added functions for forwardingError and  forwardingErrorReset and also modify logs.md file.

> * Ensure that notification and forwarding alarms work fine (in the sense no notification alarm is incorrectly using a forwarding alarm or the other way around)

Can you please guide me how can I check or reproduce this error (forwardingError and  forwardingErrorReset)

**Comment by fgalan** [comment]
> Can you please guide me how can I check or reproduce this error (forwardingError and forwardingErrorReset)

You can stop your notifications/forwarding receiver so notifications or forwarded requests sent to it would raise an alarm. Next, you can bring the receiver up again so the next notification or forwarded request would release the alarm.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir, 
I am putting this issue on hold as currently I am working on another issue.

**Comment by fgalan** [comment]
I'll try to take your PR https://github.com/telefonicaid/fiware-orion/pull/3749 ("duplicating" it to a new PR so I can add new commits) and try to finish it, so your valuable work so far doesn't get wasted :)

Btw, in which "another issue" are you working? Just to know...

**Comment by Anjali-NEC** [comment]
> Btw, in which "another issue" are you working? Just to know...

Currently I am working on issue #3638

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I resume my work on this issue. I have found something suspicious in `src/lib/ngsiNotify/senderThread.cpp` line 70 in which you have declared `int r;` which is a local variable and by default it takes garbage value, then how could you assign its value in line 89 `if (r == 0)`. Please correct my understanding  if I am missing anything.

**Comment by fgalan** [comment]
Nice to see you are back :) Thus, I'm aborting my plan of "duplicating" your PR and continue with the work.

**Comment by fgalan** [comment]
> I resume my work on this issue. I have found something suspicious in `src/lib/ngsiNotify/senderThread.cpp` line 70 in which you have declared `int r;` which is a local variable and by default it takes garbage value, then how could you assign its value in line 89 `if (r == 0)`. Please correct my understanding if I am missing anything.

I understand you refer to this fragment of code:

```
    if (!simulatedNotification)
    {
      int          r;

      r = httpRequestSend(params->from,
                          params->ip,
                          params->port,
                          params->protocol,
                          params->verb,
                          params->tenant,
                          params->servicePath,
                          params->xauthToken,
                          params->resource,
                          params->content_type,
                          params->content,
                          params->fiwareCorrelator,
                          params->renderFormat,
                          &out,
                          &statusCode,
                          params->extraHeaders);

      if (r == 0)
      ...
```

You are right is better to initialize variables with a given value. However, in this case I think is not problematic, as `r` is assigned with the returned value of httpRequestSend(). If you analyze carefully that function in `src/lib/rest/httpRequestSend.cpp` you will see that always an integer is returned.

Anyway, I think this is not related with the issue itself.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/3749 has been merged. Closing issue.
