### ISSUE TITLE
Make use of new docker compose version 2 files

### ISSUE THREAD

**Issue by web-bert** [telefonicaid/fiware-orion#1811]
Hi,

In case you are not aware: I have just been setting up orion with Docker and there is now a ["depends_on" configuration option](https://docs.docker.com/compose/compose-file/#depends-on) for a service so that docker-compose will ensure the service is up.

I just thought it would be worth mentioning as the hack to ensure mongo is available with the "--nojournal" can be removed with a version 2 compose file.

**Comment by fgalan** [comment]
Thank you very much for the feedback! 

Maybe you could contribute with a pull request with the changes you mention to the docker-compose file and documentation so we can see how it looks like, please? Thanks!

**Comment by LeandroGuillen** [comment]
Looking at the [documentation](https://docs.docker.com/compose/compose-file/#links) of docker-compose I find this under the "links" option:

>Links also express dependency between services in the same way as depends_on, so they determine the order of service startup.

I also read [here](https://github.com/docker/compose/issues/2682) that the "links" key is going to be deprecated for version 2, but they don't even know yet how.

I would suggest to wait and see what the developers of docker-compose decide on doing, and then updating for good our docker-compose file.

**Comment by fgalan** [comment]
Ok, let's have this issue "on hold" (using the "quarentine" milestone)

**Comment by fgalan** [comment]
After more than 2 years withoug activity, this quarentine issue can be closed.
