### ISSUE TITLE
[BUG] in POST v2/enitities/<id> with unknown id, the error code is not the expected

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1817]
in POST v2/enitities/<id> with unknown id, the error code is not the expected.

**InvalidModification (422)** is returned if some piece of information is missing in payload. The expected value is **NotFound (404)** because the ID referred in the request has not been found.

#### Update Request 
```
 POST http://localhost:1026/v2/entities/house
 Content-Type: application/json
 Fiware-Service: test_update_entity_id
 Fiware-ServicePath: /test
 {"humidity": {"value": "80"}}
```

#### Update Response 
```
  http code: 422
 date: Mon, 22 Feb 2016 09:40:12 GMT
 connection: Keep-Alive
 content-type: application/json
 content-length: 69
 {"error":"InvalidModification","description":"Entity does not exist"}
```
#### Expected Response 
```
  http code: 404
 {"error":"NotFound","description":"No context element found"}
```

**Comment by fgalan** [comment]
Looking to #1286 (NGSIv2 error rules)

> The resource identified by the request (e.g. entity, subscription) is not found: 404 - Not Found {"error": "NotFound", ...}

which would confirm the "Expected response" above.

**Comment by crbrox** [comment]
Currently, the description is `Entity does not exist`. Should it be `No context element found` ?

**Comment by fgalan** [comment]
I think is better "Entity does not exist", as it is more precise.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1820. @iariasleon please have a look to check if it is fixed.

**Comment by iariasleon** [comment]
LGTM
```
http code: 404
date: Mon, 22 Feb 2016 14:01:25 GMT
connection: Keep-Alive
content-type: application/json
content-length: 58
{"error":"NotFound","description":"Entity does not exist"}
```
