### ISSUE TITLE
APIv2: use of map for listing types ?

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1833]
The current APIv2 uses a map to return the list of entitiy types using type names as key whereas others endpoints (subscriptions, registrations and entities) use an array of objects.
Why use a map only for types, it could have been used for registrations and subscriptions which also have unique IDs ?
Or why not always use array for consistency across the API ? Implementations of the API in strongly types languages can benefit from such consistency to support pagination (with elements count) in a more generic way.

**Comment by jmcanterafonseca** [comment]
+1

**Comment by PascaleBorscia** [comment]
+1

**Comment by fgalan** [comment]
Good point! Thus, we will change the `GET /v2/types` operation to return an array, as follows:

```
[
  {
    "type": "Car",
    "attrs": {
      "speed": {
        "type": "none"
      },
      "fuel": {
        "type": "diesel"
      },
      "temperature": {
        "type": "urn:phenomenum:temperature"
      }
    },
    "count": 12
  },
  {
    "type": "Room",
    "attrs": {
      "pressure": {
        "type": "none"
      },
      "humidity": {
        "type": "percentage"
      },
      "temperature": {
        "type": "urn:phenomenum:temperature"
      }
    },
    "count": 7
  }
]
```

**Comment by iariasleon** [comment]
the response is in **alphabetical order**. It would be useful to add a comment concerning it in the specification
