### ISSUE TITLE
APIv2: printable ASCII set ?

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1839]
Current APIv2 mentions allowed characters for identifiers as:

>  * Allowed characters are the ones in the plain ASCII set except the following ones: whitespace, `&`, `?`, `/` and `#`. 

But the *plain* ASCII set is quite large (128 characters) with a lot of control characters (all those under 32):
![ASCII table](http://www.asciitable.com/index/asciifull.gif)

Maybe the above sentence could be completed like:

>  * Allowed characters are the ones in the plain ASCII set except the following ones: control characters, whitespace, `&`, `?`, `/` and `#`.

or only mention printable characters :

>  * Allowed characters are the ones in the printable ASCII set except the following ones: whitespace, `&`, `?`, `/` and `#`.

**Comment by fgalan** [comment]
Make sense and would lead to a more precise specification. Thanks for the feedback! To be modified soon an upcoming PR.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1840
