### ISSUE TITLE
APIv2: attribute values and multiple accept types

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1849]
The current APIv2 specification states that attribute value requests support client-server HTTP negotiation :
> The payload MIME type in responses is based on client-server HTTP negotiation, based on client `Accept` header.

But the given algorithm does not seem to handle `accept` header with multiple values :

> * If response payload MIME type is `application/json`: [...]
>    * If attribute value is a string, number, null or boolean, a HTTP error "406 Not Acceptable: accepted MIME types:
    text/plain" is returned.
> * If response payload MIME type is `text/plain`, [...]

Example: If `Accept: application/json, text/plain`, the implementation should not return a `HTTP error "406 Not Acceptable: accepted MIME types: text/plain"`. It should be able to return `application/json` when value is an object or array and fallback to `text/plain` if the value is a string/number/boolean/null.

I propose that the content negotiation algorithm work like the following:

* if attribute value is an array or object and `Accept` header contains `application/json` or `text/plain`:
     return the value as a JSON with a response type of `application/json` or `text/plain` (whichever is the first in `Accept` header).
* if attribute value is a string, number, null or boolean:
   * if `Accept` header contains `text/plain` return the value as text
   * else return a HTTP error  "406 Not Acceptable: accepted MIME types: text/plain"

Another solution would simply to remove "based on client-server HTTP negotiation" and mention that the `Accept` header only handles a single type.

**Comment by fgalan** [comment]
(Sorry for the delay answering this...)

I think that your approach improves the one currently in the NGSIv2 specifiction, so I think it would be a good idea to use it.

Only a minor detail... you say:

> (whichever is the first in Accept header)

But what to do in the cases of ties, e.g.: `Accept: */*`. In my opinion, in that case `application/json` should win (the most the server can say about the "structure" of the response, the better... and in this sense application/json is more structured data than text/plain).

**Comment by fgalan** [comment]
This question a SOF is related with this issue http://stackoverflow.com/questions/37458863/get-attribute-value-behaviour-with-accept-header/37485098#37485098 and should be edited once this issue gets closed.

**Comment by fgalan** [comment]
> But what to do in the cases of ties, e.g.: Accept: */*. In my opinion, in that case application/json should win (the most the server can say about the "structure" of the response, the better... and in this sense application/json is more structured data than text/plain).

Probably tie only can happen with `*/*`. As far as I remember, in the case of eg. `Accept: application/json, text/plain` there is no tie, as HTTP rules for Accept header state that the first element in the list take precedence over the next one (not fully sure... need to check HTTP RFC).

**Comment by fgalan** [comment]
PR with modifications to the NGSIv2 specification .apib: #2215

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2323
