### ISSUE TITLE
"JSON parse error" with valid JSON using escaped slashes

### ISSUE THREAD

**Issue by Ivan-Perez** [telefonicaid/fiware-orion#1852]
Hi!

The context broker throws an error (`400 Bad Request` - `JSON Parse Error`) if the JSON string contains escaped slashes, i.e., contains the sequence `\/` within any string. This is valid JSON, so it should be parsed normally.

For example, this is the JSON object I'm sending to the broker (the `reference` property is what is causing the parse error):

```
POST /v1/subscribeContext
```
```javascript
{
    "entities": [
        {
            "type": "Device",
            "isPattern": "false",
            "id": "1234"
        }
    ],
    "attributes": [
        "movement"
    ],
    "reference": "http:\/\/localhost:1028\/accumulate",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "movement"
            ]
        }
    ],
    "throttling": "PT1M"
}
```

This JSON was generated using the [`json_encode`](http://php.net/manual/en/function.json-encode.php)'s PHP function. I know this function accepts a parameter to avoid scaped slashes, but in this case I'm using a library which wraps the call to the JSON-encoding function internally and I don't want to modify that library.

Could the server be fixed in order to accept that valid JSON? Thanks!

**Comment by fgalan** [comment]
Thanks for the feedback!

Just to test... Could you test with the same operation in NGSIv2? 

Basically:

```
POST /v2/subscriptions

{
  "subject": {
    "entities": [
      {
        "id": "1234",
        "type": "Device"
      }
    ],
    "condition": {
      "attributes": [
        "movement"
      ]
    }
  },
  "notification": {
    "callback": "http:\/\/localhost:1028\/accumulate",
    "attributes": [
      "movement"
    ],
    "throttling": 60
  },
  "expires": "2016-03-26T15:00:00.00Z"
}
```

(NGSIv2 and NGSIv1 uses a diferent parsing logic, so the feedback is useful for debuggint).

**Comment by Ivan-Perez** [comment]
It works correctly in v2.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1860
