### ISSUE TITLE
XML support removal

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1862]
This is a big work that needs to be addressed step by step:

1. "Hack" at rest/network layer to remove XML support. All the functional test failing will be temporarly moved to a `cases_xml/` subdirectory, keeping the same directory case structure. At the end of this step, XML parsing/render code will still be there, but as dead code. This could be done in one PR.
2. Remove dead code at parsing/render stages. During the process, the "hacks" donde in step 1 will become in proper solutions. This may take several PRs, ensuring that unit test / functional test keep working after each one.
3. Once the code is ok again, look to the .test files in  `cases_xml/`. Some of the .test could be just removed (typically, the ones with a counterpart .test based in JSON), other will need adaptation (just removing XML steps) or complete rewritting (i.e. rewritte the test with the same steps but in JSON). This may take also several PRs.

The target is at least to end steps 1 and 2 by the Orion 1.0.0 release date. Step 3 could be large and posponed to post-1.0.0 releases.

As a consecuence of step 1, a drop in coverage will occur, as a consecuence of dead code (as reference, coverage at 0.28.0 releasing date is around 78.2%). The gap will be reduced upon finishing step 2 and definitively closed when .test covering missing functionality will be migrated back during step 3.

**Effort: 10 man day** (mainly due to step 3)

**Comment by kzangeli** [comment]
There are more things to consider when we remove XML.
Constructions were made just to be able to support both XML and JSON. Look for example at the "Format format", sent to all old render and check methods.
We will find things like this also to be removed when we stop supporting XML.

**Comment by fgalan** [comment]
Yes, you are right. I see this the kind of thing you mention as "spin-off" of the main task about removal parsing/rendering code in step 2. I hope to easily find that stuff as we go.

**Comment by fgalan** [comment]
Step 1 completed in PR #1864. The case_xml/ directory holds 202 .test files.

```
fermin@neodeb:~/src/fiware-orion$ find test/functionalTest/cases_xml | grep '.test' | wc -l
202
```

**Comment by fgalan** [comment]
Part of step 2 done in PR https://github.com/telefonicaid/fiware-orion/pull/1866.

As result, some XML-based unit test without JSON countepart has been DISABLED, while we decide what to do with them.

**Comment by fgalan** [comment]
After merging step 1 PR, coverage has drop 75.8%. Around 3.5% drop is not too much...

**Comment by fgalan** [comment]
Part of step 2 done in PR https://github.com/telefonicaid/fiware-orion/pull/1870. This PR adds a nue set of DISABLED unit tests.

**Comment by fgalan** [comment]
Step 3 started with PR https://github.com/telefonicaid/fiware-orion/pull/1883/files (16 .test)

**Comment by fgalan** [comment]
Step 3 continues with PR https://github.com/telefonicaid/fiware-orion/pull/1888 (33 .test)

**Comment by fgalan** [comment]
Step 2 wasn't really finished. This PR (hopefully) completes it: https://github.com/telefonicaid/fiware-orion/pull/1897

**Comment by fgalan** [comment]
Step 3 continues with PR #1953. After that PR, 111 .test remain in cases_xml/ to be reviewed.

**Comment by fgalan** [comment]
Step 3 continues with PR https://github.com/telefonicaid/fiware-orion/pull/2011

**Comment by fgalan** [comment]
Step 3 continues with PR https://github.com/telefonicaid/fiware-orion/pull/2013 (after it, 62 .test under cases_xml/ pending).

**Comment by fgalan** [comment]
Step 3 continues with PR #2044 (afert it, 30 .test under cases_xml/ pending)

**Comment by fgalan** [comment]
Step 3 finishes with PR https://github.com/telefonicaid/fiware-orion/pull/2077. All test in cases_xml/ converted into cases/ or obsolete and removed!

However that doesn't clonclude the issue. Two tasks at least remain to be done:

* Make JSON the default for `orionCurl`, to avoid using `--json` all the time. That would be a PR touching a lot of lines in .test but easy to do with IDE replacement test features.
* Do something with XML-based DISABLED unit test. That "something" will be to remove them very likely. However, before doing it I'd like to evaluate coverage. Unortunatelly Sonar is out of service so the easiest way seems to be running `make coverage` with the code before starting the XML removal task and with the code at the present moment in develop, then compare results.

**Comment by fgalan** [comment]
`--json` removal in PR https://github.com/telefonicaid/fiware-orion/pull/2096

**Comment by fgalan** [comment]
Coverage analysis:
Covearge analysis (068402 -> pre XML removal, f5f679 -> post XML removal):

* [coverage.068402.ut.zip](https://github.com/telefonicaid/fiware-orion/files/240663/coverage.068402.ut.zip) 56.8%
* [coverage.068402.full.zip](https://github.com/telefonicaid/fiware-orion/files/240664/coverage.068402.full.zip) 88.2 %
* [coverage.f5f67.ut.zip](https://github.com/telefonicaid/fiware-orion/files/240670/coverage.f5f67.ut.zip) 47.7%
* [coverage.f5f679.full.zip](https://github.com/telefonicaid/fiware-orion/files/240665/coverage.f5f679.full.zip) 87.3%

**Comment by fgalan** [comment]
Finished with PR https://github.com/telefonicaid/fiware-orion/pull/2104.

Maybe some small leftover remains in the code, but in that case they will be removed as we go. This issue can be closed.
