### ISSUE TITLE
Improve accumulator-server.py argument passing

### ISSUE THREAD

**Issue by rbl219** [telefonicaid/fiware-orion#187]
Improve the argument passing in the python script 'accumulator-server.py', to use the same style as the CB, for example:

  ./accumulator-server.py -port 1028 -url /accumulate -host 10.1.1.1 -verbose on

This issue was generated by PR:

https://github.com/telefonicaid/fiware-orion/pull/176

**Effort: 3 man day**

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/717 includes this fix, alghout unfortunatelly it also incluse things not yet working, so it cannot be merged :(

**Comment by fgalan** [comment]
Implemented by PR #2407 (using another alternative than the one proposed in PR #7179.
