### ISSUE TITLE
Implement NGSIv2 notification formats

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1875]
After merging PR https://github.com/telefonicaid/fiware-orion/pull/1761, the format for NGSIv2 notification has been defined. This issue is about supporting it, considering the four different flavors for `attrFormat`: normalized, keyValues, values and legacy (legacy is for using NGSIv1 format).

_Implementation hints_

I'd suggest to use the `format` field in csub documents (see https://fiware-orion.readthedocs.org/en/develop/admin/database_model/index.html#csubs-collection) in order to specify the format associated to the subscription. The string "JSON" will remain for NGSIv1 legacy, other formats could use: "NGSIv2-NORMALIZED", "NGSIV2-KEYVALUES" and "NGSIV2-VALUES". The file **database_model.md** document has to be edited to include the new values (either these suggested names or others).

The `attrsFormat` parameter has to be processed at subscription creation/modification to set correctly the format in DB. The notification logic needs to be modified to take this parameter into account and render the notification the right way. The key functions are processOnChangeConditionForUpdateContext() and processOnChangeConditionForSubscription(), both take format into account yet as parameter.

Note that in NGSIv2, the order in which attributes appear in the `attrs` array in csub document is important (especially in NGSIV2-VALUES) as it defines the order in which the attrs will appear.

(I'm talking all the time about "csub document" but the same applies for the cache entries, which should have the same structure as csub documents in DB).

**Comment by fgalan** [comment]
The following answer at SOF needs to be edited once this issue gets solved: http://stackoverflow.com/questions/36504230/doubts-about-notifications-format-in-orion-usin-apiv2

**Comment by kzangeli** [comment]
Stuff left of this issue after PR #2054

* Unify the two parameters 'notifyFormat' and 'renderMode' for ContextAttribute::toJson
* Order of attributes in notifications, especially if notifyFormat is "values"
* sendNotifyContextAvailabilityRequest to accept NotificationFormat instead of Format and similar stuff to align availlability notifications with context notifications
* **Add more action items here**

**Comment by fgalan** [comment]
What is pending for step III (I hope, the last one in this PR):

* sendNotifyContextAvailabilityRequest to accept NotificationFormat instead of Format and similar stuff to align availlability notifications with context notifications
 * [FGM] In particular, using NGSI_V1_JSON in the places where the NGSI9 notification code now uses JSON.

* Include ConnectionInfo::inFormat/outFormat in unification of 'notifyFormat' and 'renderMode' ?
  Probably better to use two types/params. One for 'language or mime type' (json, text, html), and another one for formating stuff inside the mime-type.
 * [FGM] The name MimeType has been suggested for the old Format (json, text) enum.

**Comment by fgalan** [comment]
I have realized that the old Format enum still there in Format.h:

```
typedef enum Format
{
  JSON     = 1,
  TEXT     = 2,
  HTML     = 3,
  NOFORMAT = 4
} Format;
```
Is that correct? I have the "feeling" that it should have been removed... maybe is part of step III.

Let's discuss but skype if you prefer.

**Comment by kzangeli** [comment]
In step 3, Format.cpp/Format.h disappear (replaced by MimeType.h/cpp)

**Comment by fgalan** [comment]
Step I and Step II done as part of milestone 1.1.0. Step III is parte of milestone 1.2.0.

**Comment by fgalan** [comment]
Step III (last one) in PR https://github.com/telefonicaid/fiware-orion/pull/2109

**Comment by fgalan** [comment]
Having completed the functionality, this issue passes to QATestPending until proper acceptance test could be implemented.

**Comment by iariasleon** [comment]
LGTM, tested in https://github.com/telefonicaid/fiware-orion/blob/develop/test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_format.feature
