### ISSUE TITLE
MongoSink - Insert error

### ISSUE THREAD

**Issue by wavyx** [telefonicaid/fiware-orion#1879]
When using Orion with Cygnus and MongoSink I get the following error:

> orion_1  | ERROR@13:02:23  safeMongo.cpp[125]: Runtime Error (field 'modDate' was supposed to be a long but type=16 in BSONObj <{ _id: { id: "PB-002", type: "Installation", servicePath: "/" }, attrNames: [ "id", "name", "latitude", "longitude", "start_date", "timestamp", "output_voltage", "output_current", "output_power", "power_status", "warmup_status", "warning_status", "pressure_h2", "electrolyzer_temperature", "electrolyzer_speed", "electrolyzer_pressure" ], attrs: { id: { type: "integer", creDate: 1457096455, modDate: 1457096455, value: "2" }, name: { type: "string", creDate: 1457096455, modDate: 1457096455, value: "Power Box #2" }, latitude: { value: "50.88623", type: "float", creDate: 1457096455, modDate: 1457096460 }, longitude: { value: "4.05801", type: "float", creDate: 1457096455, modDate: 1457096460 }, start_date: { value: "1438961009", type: "integer", creDate: 1457096455, modDate: 1457096460 }, timestamp: { value: "1457096539", type: "integer", creDate: 1457096455, modDate: 1457096539 }, output_voltage: { value: "31.308", type: "float", creDate: 1457096455, modDate: 1457096539 }, output_current: { value: "30.277", type: "float", creDate: 1457096455, modDate: 1457096539 }, output_power: { value: "947.912", type: "float", creDate: 1457096455, modDate: 1457096539 }, power_status: { value: "1", type: "integer", creDate: 1457096455, modDate: 1457096463 }, warmup_status: { type: "integer", creDate: 1457096455, modDate: 1457096455, value: "0" }, warning_status: { type: "integer", creDate: 1457096455, modDate: 1457096455, value: "0" }, pressure_h2: { value: "19.455", type: "float", creDate: 1457096455, modDate: 1457096539 }, electrolyzer_temperature: { value: "59.216", type: "float", creDate: 1457096455, modDate: 1457096539 }, electrolyzer_speed: { value: "193.974", type: "float", creDate: 1457096455, modDate: 1457096539 }, electrolyzer_pressure: { value: "9.381", type: "float", creDate: 1457096455, modDate: 1457096539 } }, creDate: 1457096455, modDate: 1457096539 }>)

I already rebuild cygnus to the latest version (0.13).
(I didn't manage to complete the build for Orion so it's still 0.28)
Anyway it looks more like a bug at MongoSink level, since "creDate" is an internal value added by cygnus.
Or do you think it's a configuration problem in my agent conf:

> cygnusagent.sources = http-source
> cygnusagent.sinks = mongo-sink
> cygnusagent.channels = mongo-channel
> 
> cygnusagent.sources.http-source.channels = mongo-channel
> cygnusagent.sources.http-source.type = org.apache.flume.source.http.HTTPSource
> cygnusagent.sources.http-source.port = 5050
> cygnusagent.sources.http-source.handler = com.telefonica.iot.cygnus.handlers.OrionRestHandler
> cygnusagent.sources.http-source.handler.events_ttl = 10
> cygnusagent.sources.http-source.interceptors = ts gi
> cygnusagent.sources.http-source.interceptors.ts.type = timestamp
> cygnusagent.sources.http-source.interceptors.gi.type = com.telefonica.iot.cygnus.interceptors.GroupingInterceptor$Builder
> cygnusagent.sources.http-source.interceptors.gi.grouping_rules_conf_file = /usr/cygnus/conf/grouping_rules.conf
> 
> cygnusagent.sinks.mongo-sink.type = com.telefonica.iot.cygnus.sinks.OrionMongoSink
> cygnusagent.sinks.mongo-sink.channel = mongo-channel
> cygnusagent.sinks.mongo-sink.enable_grouping = false
> 
> cygnusagent.channels.mongo-channel.type = memory
> cygnusagent.channels.mongo-channel.capacity = 1000
> cygnusagent.channels.mongo-channel.transactionCapacity = 100

Cygnus version:  {"success":"true","version":"0.13.0.UNKNOWN"}
Orion version: {
  "orion" : {
  "version" : "0.28.0-next",
  "uptime" : "0 d, 0 h, 5 m, 14 s",
  "git_hash" : "6954e613c6d90c5721ffe4d264f2a00a003da880",
  "compile_time" : "Tue Mar 1 08:26:47 UTC 2016",
  "compiled_by" : "root",
  "compiled_in" : "838a42ae8431"
}}

**Comment by fgalan** [comment]
The "Runtime Error" shown in the Orion log is a known issue, due to overlogging an not real Runtime Error condition. It has been fixed in this branch or release/0.28.0 hardening/remove_false_runtime_errors_logging (current HEAD: b232f65a7d2859f552091353dcc36e0695c98013). Eventually (that branch is yet ongoing work) it will be merged into develop and the fix will be available in next Orion version (1.0.0).

**Comment by wavyx** [comment]
Could you complete documentation on how to build an Orion docker image, located here http://fiware-cygnus.readthedocs.org/en/latest/installation_and_administration_guide/install_with_docker/index.html
which point out to https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/README.md

I tried to follow the guide, but didn't manage to build an Orion Docker image.
It would be nice to have something similar to http://fiware-orion.readthedocs.org/en/develop/user/docker/#3-build-a-docker-image

**Comment by fgalan** [comment]
I understand that you refer to this documentation: https://github.com/telefonicaid/fiware-orion/blob/master/docker/README.md. Maybe this section is the one most interesting for you if you want to build an specific Orion version from sources: https://github.com/telefonicaid/fiware-orion/blob/master/docker/README.md#3-build-a-docker-image

Please, don't hesitat to report any specific problem you have with that documentation as you follow it (I'd suggest to do it in a separate issue, given that the present one is about a "false" Runtime Error and has been clasified in a comments above).

**Comment by fgalan** [comment]
I understand that this issue can be closed. Please @wavyx reopen it if you feel I'm wrong. Thanks!
