### ISSUE TITLE
alphabetic order of valgrind tests

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#188]
The order of the valgrind tests in kz's machine (krasno) differs from the order in Fermin's (
oriondeb).

Using a test file, called SORT:

        convenience_ngsi10_context_entity_types_attribute_container
        convenience_ngsi10_context_entity_types_attribute
        convenience_ngsi10_context_entity_types
        convenience_ngsi10_subscriptions_onchange
        convenience_ngsi10_subscriptions
        convenience_ngsi9_subscriptions

The result of 

        $ sort SORT

in krasno is;

        convenience_ngsi10_context_entity_types
        convenience_ngsi10_context_entity_types_attribute
        convenience_ngsi10_context_entity_types_attribute_container
        convenience_ngsi10_subscriptions
        convenience_ngsi10_subscriptions_onchange
        convenience_ngsi9_subscriptions

In oriondeb, the result is different:

        convenience_ngsi10_context_entity_types_attribute_container
        convenience_ngsi10_context_entity_types_attribute
        convenience_ngsi10_context_entity_types
        convenience_ngsi10_subscriptions_onchange
        convenience_ngsi10_subscriptions
        convenience_ngsi9_subscriptions

We have tried already

        $ LANG=C sort SORT

but nothing changes.

It seems that some env var is playing us this trick, we just need to find it (and set it accordingly in valgrindTestSuite.sh) in order to get the same valgrind test file order for all our machines.

**Effort: 2 man day**

**Comment by fgalan** [comment]
At the end we have found this not important, at the test engine reports the name of the failing test, no matter the order. Closing.
