### ISSUE TITLE
[BUG] in GET "/v2/entities/<id>/attrs/<attr_name>/value" with error in URI the error returned is not the expected

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1887]
in GET `/v2/entities/<id>/attrs/<attr_name>/value` with error in URI the error description returned is not the expected.

#### Get request
```
GET http://localhost:1026/v2/entities/house_//attrs/temperature_0/value
Fiware-Service: test_id_entity_invalid
Fiware-ServicePath: /test
Accept: text/plain
```

#### Get response
```
http code: 400
date: Wed, 09 Mar 2016 09:26:49 GMT
connection: Keep-Alive
content-type: text/plain
content-length: 59
{"error":"BadRequest","description":"unrecognized request"}
```

#### Expected response
```
http code: 400
{"error":"BadRequest","description":"service not found"}
```

**Comment by kzangeli** [comment]
Not sure this is a bug ...
The // is the URL changes completely the path and the request is simply not recognized.
Let's discuss it, but in my opinion, the broker responds the way it should.

Unless of course we want to remove completely the *unrecognized request* response and replace it for a *service not found* ...

**Comment by fgalan** [comment]
The bug is that some casese description is  "service not found" and some other "unrecognized request". This should be unfied.

Which message use other well-known public REST APIs for the same case? Let's try to align with the community.

**Comment by iariasleon** [comment]
The same behaviour in error description with an attribute name as `house_/`, ex:
```
GET http://localhost:1026/v2/entities/room_1/attrs/house_//value
Fiware-Service: test_update_attr_name
Fiware-ServicePath: /test
Accept: text/plain
```
```
http code: 400
date: Wed, 09 Mar 2016 14:53:31 GMT
connection: Keep-Alive
content-type: text/plain
content-length: 59
{"error":"BadRequest","description":"unrecognized request"}
```

**Comment by fgalan** [comment]
In the last case, maybe there is an "inverleaved" bug... the response payload (due to an error) in JSON shouldn't use text/plain as Content-Type... maybe this already raised in a separated issue? (in that case, please specify number).

**Comment by iariasleon** [comment]
I think you refer to https://github.com/telefonicaid/fiware-orion/issues/1886, but both issues are different themes.
This issue is if we have a wrong URI with entity_id or attribute_name as `house_/` and the #1886 issue is that any value in Accept header different to `application/json` is assumed as `text/plain`.

**Comment by fgalan** [comment]
Already fixed (.test in PR https://github.com/telefonicaid/fiware-orion/pull/2317). Pleae @iariasleon have a look and close it if you find it ok.

**Comment by iariasleon** [comment]
LGTM to`house_/` value in "id" or "attr_name" in url `GET /v2/entities/<id>/attrs/<attr_name>/value`
```
headers:
   date: Thu, 21 Jul 2016 08:07:19 GMT
   fiware-correlator: 255c2274-4f1a-11e6-b4ed-005056a20feb
   connection: Keep-Alive
   content-type: text/plain
   content-length: 56
payload: {"error":"BadRequest","description":"service not found"}
```

**Comment by iariasleon** [comment]
But with `house_#` value in "id" or "attr_name" in url `GET /v2/entities/<id>/attrs/<attr_name>/value`, returns a 406 http code.
```
http code: 406 - Not Acceptable
headers:
   date: Thu, 21 Jul 2016 08:07:19 GMT
   fiware-correlator: 256bb928-4f1a-11e6-81d7-005056a20feb
   connection: Keep-Alive
   content-type: text/plain
   content-length: 81
payload: {"error":"NotAcceptable","description":"acceptable MIME types: application/json"}
```

**Comment by iariasleon** [comment]
LGTM
