### ISSUE TITLE
[BUG] in POST v2/enitities/ with json object in value and without keyValues activated, the error description is very generic

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1892]
in POST `v2/enitities/` with json object in value and without keyValues activated, the error description is very generic. It would be more practical something more specific? As it had before,  `no 'value' for ContextAttribute without keyValues`.

#### Create Request 
```
POST http://localhost:1026/v2/entities
Content-Type: application/json
Fiware-Service: test_key_value_mode
Fiware-ServicePath: /test
{"type": "house", "id": "room18", "temperature": {"x": "x1","x2": "b"}}
```

#### Create Response 
```
http code: 400
 {"error":"BadRequest","description":"unrecognized property for context attribute"}
```

#### Expected Response 
```
http code: 400
 {"error":"BadRequest","description":"no 'value' for ContextAttribute without keyValues"}
```

**Comment by crbrox** [comment]
After discussion, the 'value' field could be missing, taking the default value (null) and the message cannot be made more specific with the offending field for security reasons. It is left as it is. To be closed.

**Comment by iariasleon** [comment]
LGTM
```
http code: 400
date: Tue, 15 Mar 2016 16:33:41 GMT
connection: Keep-Alive
content-type: application/json
content-length: 82
{"error":"BadRequest","description":"unrecognized property for context attribute"}
```
