### ISSUE TITLE
[BUG] in PUT /v2/entities/<id>/attrs/<attr_name>/value with text/plain and json object with citation-marks

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1902]
in PUT `/v2/entities/<id>/attrs/<attr_name>/value` request with text/plain in Content-Type header and  in the payload has an json object as value but starts and ends with double quotes ("), returns an error message, when it should be accepted and taken as a string.

In the [reference](http://telefonicaid.github.io/fiware-orion/api/v2/) said:
>If the request payload MIME type is text/plain, then the following algorithm is applied to the payload:
> -  If the payload starts and ends with citation-marks ("), the value is taken as a string (the citation marks themselves are not considered part of the string)

#### Datasets
```
      | attributes_value                                                 |
      |------------------------------------------------------------------|
      | "[ "json", "vector", "of", 6, "strings", "and", 2, "integers" ]" |
      | "{"x": "x1","x2": "b"}"                                          |
```

#### Update request
```
PUT http://localhost:1026/v2/entities/room13_1/attrs/temperature_0/value
Content-Type: text/plain
Fiware-Service: test_update_content_type
Fiware-ServicePath: /test
"{"x": "x1","x2": "b"}"
```

#### Update response
```
http code: 400
 {"error":"BadRequest","description":"Invalid characters in attribute value"}
```

#### Expected response
```
http code: 204
```

**Comment by iariasleon** [comment]
Also tested with the values `"123"45"` and `"123'45"`, returning the same behavior.
We think that the problem is the forbidden chars ` " ' ` into the string.

**Comment by jmcanterafonseca** [comment]
If you want to use " (double quote) as part of the content then you should escape it i.e. the string should be 

"{\"x\": \"x1\",\"x2\": \"b\"}"

if this is not accepted as a valid string then there is a bug

**Comment by fgalan** [comment]
> We think that the problem is the forbidden chars " ' into the string.

I agree with that diagnosis. That operation attemps to set the attribute temperature_0 witth the following string `{"x": "x1","x2": "b"}` and `"` is a forbidden character as described at http://fiware-orion.readthedocs.org/en/develop/user/forbidden_characters/index.html.

I guess that using the following payload `"{x: x1,x2: b}"` (i.e. to set the attribute temperature_0 witth the following string `{x: x1,x2: b}`) will work.

Thus, I think CB is behaving correctly. Users trying to set as text something which "natural" representation form is JSON is a weird case.

**Comment by iariasleon** [comment]
Also tested with `"` escaped into the string. ex: `"{\"x\": \"x1\",\"x2\": \"b\"}"` and the behavior is the same.

**Comment by fgalan** [comment]
What about with `"{x: x1,x2: b}"`?

**Comment by iariasleon** [comment]
In this case`"{x: x1,x2: b}"` the value is replaced correctly:
```
{ "_id" : { "id" : "room", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "temperature" ], "attrs" : { "temperature" : { "value" : "{x: x1,x2: b}", "type" : "none", "creDate" : 1457970854, "modDate" : 1457970854 } }, "creDate" : 1457970854, "modDate" : 1457970854 }

```

**Comment by fgalan** [comment]
After checking this, behaviour is as expected. Closing.
