### ISSUE TITLE
make query string more compact and readable for equals operator

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1903]
currently the equal operator in simple queries is something like

```
GET /v2/entities?type=PointOfInterest&q=category==WeatherStation;stationCode==234
```

I think we can make it more compact by adopting the ':' as a synonym for equality

```
GET /v2/entities?type=PointOfInterest&q=category:WeatherStation;stationCode:234
```

That notation is something used, successfully, by other query languages, for instance ElasticSearch query language. Thus, this is something that developers would like ... 

I would kindly ask to consider this request and to know other opinions, of course. 

thanks, best

**Comment by fgalan** [comment]
What about negation? `!:` ?

**Comment by kzangeli** [comment]
I would use :!

The style tags in HTML also use this format.
Not that I think it is worth a change to save one byte in a few places ( == for :), but I do think it is more elegant  with ':', especially as it avoids the == after a =

**Comment by jmcanterafonseca** [comment]
What about 

```
q=!category:WeatherStation;a:b
```

**Comment by fgalan** [comment]
Could you "draw" some use cases with enums and ranges, for both equality and its negation, so we can see how it looks like, please?

**Comment by fgalan** [comment]
At the end `:` will be used as alias of `==`. This has to bee proberly documented in the NGSIv2 spec .apib.

Note that `!=`, `<=`, etc. don't have alias.

**Comment by fgalan** [comment]
Implemented in PR #2131

**Comment by fgalan** [comment]
Moved to the QATestPending until corresponding acceptance tests get implemented.

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/019_pep2cbv2_filteronstructuredcontent.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
