### ISSUE TITLE
NGSIv2: v2/op/query response consistency

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#1917]
In the current NGSIv2 specification, there seems to be an inconsistency in the response of the `v2/op/query` request: The two first entities are using the `keyValues` representation (without the `value` field) while the last is using the `canonical` (default) one.

Shouldn't the example response be written as :

        [
         {
            "type": "Room",
            "id": "DC_S1-D41",
            "temperature": {
                "value": 35.6
            }
         },
         {
            "type": "Room",
            "id": "Boe-Idearium",
            "temperature":  {
                "value": 22.5
            }
         },
         {
            "type": "Car",
            "id": "P-9873-K",
            "speed": {
                "value": 100,
                "type": "number",
                "accuracy": 2,
                "timestamp": {
                    "value": "2015-06-04T07:20:27.378Z",
                    "type": "date"
                }
            }
         }
        ]

**Comment by fgalan** [comment]
It seems to be a bug in the .apib. We would have a look to it and fix. Thanks!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/1938
