### ISSUE TITLE
Add "description" field to subscriptions

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1918]
Subscriptions should have an optional description field so clients can use it to annotate things about subscription (e.g. subscription purpose). This description could be added at subscription creation time, modified afterwards (updating it with "" will delete the description).

Details to be clarified at NGSIv2 .apib (the first PR for this issue).

**Comment by fgalan** [comment]
.apib changes in PR #1926

**Comment by fgalan** [comment]
Max length: 1024 characters (not in the .apib, as it is an implementation-specific aspect).

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2001#event-615592163. Moving to QATestPending while the acceptance test to cover this functionality get implemented.

**Comment by anabelengp** [comment]
related issue: #2042

**Comment by iariasleon** [comment]
LGTM
implemented in https://github.com/telefonicaid/fiware-orion/blob/develop/test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_description.feature
