### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1920]
As described in NSGIv2 specification: http://telefonicaid.github.io/fiware-orion/api/v2/

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1982

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1982. Moved to QATestPending while the acceptance test to cover this functionality gets implemented.

**Comment by iariasleon** [comment]
LGTM
issue associated: #2426
