### ISSUE TITLE
[docker] Dockerfile always points to 'Develop' branch

### ISSUE THREAD

**Issue by albertinisg** [telefonicaid/fiware-orion#1922]
I've found that, Orion's Dockerfile points to `Develop` in every release.This means that, all the tags available in Dockerhub build the image from `Develop` at the moment it's triggered. This can cause 2 issues:

- The first one is, if the image is somehow 'triggered' after the release, it will always build an image from `Develop` branch
- There's no way to know that the image built is exactly the one pointing to the right `tag`. The only way to make sure of that is building the image exactly right after the release (but the first issue still remains there).

```dockerfile
FROM centos:centos6.6

MAINTAINER FIWARE Orion Context Broker Team. Telefónica I+D

ENV ORION_USER orion
ENV GIT_REV_ORION develop
ENV CLEAN_DEV_TOOLS 1
...
```

**Comment by fgalan** [comment]
Thanks for the feedback! We have observed some weird behaviour with docker images built at Dockerhub, not matching the tag corresponding to the release they were supposed to be, but without a clear cause identification. Based in your report, we will try to fix, using `ENV GIT_REV_ORION` correctly.

**Comment by fgalan** [comment]
I have adjusted release/0.28.0 to use the right GIT_REV_ORION and now it seems to be working. In particular, after building a new 0.28 in dockerhub, then using this compose:

```
mongo:
  image: mongo:3.0
  command: --smallfiles --nojournal
orion:
  image: fiware/orion:0.28
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo
```

I get this version:

```
{
  "orion" : {
  "version" : "0.28.0",
  "uptime" : "0 d, 0 h, 0 m, 18 s",
  "git_hash" : "a9272cadf75b56e65dd1294d8a90de23982fa45e",
  "compile_time" : "Mon Mar 21 11:00:19 UTC 2016",
  "compiled_by" : "root",
  "compiled_in" : "838a42ae8431"
}
}
```

which correspondsd with the release/0.28.0 HEAD commit (see https://github.com/telefonicaid/fiware-orion/commits/release/0.28.0).

Next, I'll "manually" adjust the other tags in Dockerhub: 0.24, 0.25, 0.26, 0.26.1 and 0.27.

**Comment by fgalan** [comment]
All dockerhub tags updated:

![2016-03-21 16_13_02-mozilla firefox](https://cloud.githubusercontent.com/assets/1534240/13923954/d40962fc-ef82-11e5-8049-f5a42d5dc769.png)

@albertinisg, it would be great if you could have a look and check if now it works as expected.

Pending work: modify release.sh script to do this automatically each time a new release is generated.

**Comment by albertinisg** [comment]
Worked like a charm :smile: Checked the builds log and it checkouts the branch release:

```log
Initialized empty Git repository in /opt/fiware-orion/.git/
Switched to a new branch 'release/0.XX.Z'
Branch release/0.XX.Z set up to track remote branch release/0.XX.Z from origin.
```
Also, I've checked the `git_hash` of the image and it corresponds with the latest commit (the fix applied).

Thanks @fgalan !

**Comment by fgalan** [comment]
You're welcomed! :)

**Comment by fgalan** [comment]
release.sh fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1940. However, let's hold this issue opened until next release get generated (Orion 1.0.0, bu the end of March) to ensure it works as expected.

**Comment by fgalan** [comment]
By the step commits for

* closing 1.0.0 cycle (0.28.0-next -> 1.0.0): https://github.com/telefonicaid/fiware-orion/commit/8bd2c62366f67596d518607b8d6886bc42ec5d2e
* opening post-1.0.0 cycle (1.0.0 -> 1.0.0-next): https://github.com/telefonicaid/fiware-orion/commit/50ded30896dad09a09e22745b90694e2281273d4

it seems it is working correctly. Thus, issue is going to be closed.
