### ISSUE TITLE
[QUESTION] in v2/subscription, are mandatory or optional, the condition fields and its sub-fields?

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#1942]
in v2/subscription, are mandatory or optional, the condition fields and its sub-fields?

in [reference](http://telefonicaid.github.io/fiware-orion/api/v2/):
> condition: Condition that will trigger the notification. It can have two optional properties:
>  -   attributes: array of attribute names
>  -   expression: an expression composed of q, georel, geometry and coords (see "List entities" operation above about this field).

structure:
```
  "condition": {
          "attributes:[],
          "expression:""
  }
```

if `expression` is missing the response is 201
if `attributes` is [] the response is 201
if `attributes` is missing the response is 400:
```
{
"error": "BadRequest"
"description": "no condition attributes specified"
}
```
if `condition` is missing the response is 400:
```
{
"error": "BadRequest"
"description": "no subject condition specified"
}
```

**Comment by fgalan** [comment]
I would say that the right behavioru should be:

**Case 1**

```
{
  ...
  "conditions": { }
}
```

OK, with the interpretation: _If neither attributes or expression are used, a notification is sent whenever any of the attributes of the entity changes._

**Case 2**


```
{
  ...
  ...
}
```

(No "conditions" field). 

As in Case 1.

**Case 3**

```
{
  ...
  "conditions": {
     "atrributes": [ ]
  }
}
```
As in Case 1.


**Case 4**

```
{
  ...
  "conditions": {
     "expression": ""
  }
}
```
As in Case 1.

**Case 5**

```
{
  ...
  "conditions": {
     "attributes: [ ],
     "expression": ""
  }
}
```
As in Case 1.

**Comment by iariasleon** [comment]
I agree with Fermin.. If everyone are agree,I create the issue appropriate and close this question.

**Comment by fgalan** [comment]
Let's hold this question during the 1.0.0 development cycle, i.e. one week. If nobody provides feedback in that time, then we will proceed as @iariasleon tells.

**Comment by iariasleon** [comment]
Only a comment, now the `expression` field is:
```
"expression": {
        "q": "temperature>40"
      }
```
Is it better an string `"expression": ""` or an json object `"expression": {}`?

**Comment by fgalan** [comment]
Good point. 

I understant that `"expression": ""` should result in an "expression has to be a JSON object" (or similar text) error. In the same way using `"attributes": ""` instead of `"attributes": []` should result in a "attributes has to be a JSON array".

**Comment by iariasleon** [comment]
LGTM... Create a new issue #1946
