### ISSUE TITLE
Arithmetic and range operators in Simple Query Language also for strings

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#1945]
Current NGSIv2 specification http://telefonicaid.github.io/fiware-orion/api/v2/ allows to use `<`, `>`, `<=`, `>=` and ranges for dates an numbers.

This issue is about extensing the usage of these opertators to strings, so we can express queries like these ones:

```
GET /v2/entities?q=colour<c (returning entities with colour "black" and "blue")
GET /v2/entities?q=colour=o..s (returning entities with colour "pink" and "red")
```

Probably, the current code implementation already works with strings (as the `$lte` and similar operators used at mongoBackend are supposed to work with strings) but we would need at least to modify documentation and cover the functionality with test harness.

**Comment by fgalan** [comment]
Implemented in PR #2036 (and a little bugfix in PR #2039). Moved to QATestPending while functional tests get implemented.

**Comment by iariasleon** [comment]
E2E covered in features/pepflows/019_pep2cbv2_filteronstructuredcontent.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
