### ISSUE TITLE
Context update with Fiware-ServicePath

### ISSUE THREAD

**Issue by DmitryPranchuk** [telefonicaid/fiware-orion#1956]
**Preconditions**
I have two entities with same type and ID in orion(different service paths - /aaa and /bbb for example). 
**Action**
 I want to update(add new param “param1”) one of my entities. 
**Steps to reproduce**
1. At first I try to execute POST request with ID and Type, UpdateAction: APPEND (without ServicePath header). As result I got “OK” response and nor /aaa nor /bbb entity was changed.
2. Then I execute same update request with /aaa servicePath. Result - OK. Entity in /aaa was updated(“param1” appeared in them).
3. Then I’m repeating my update request without service path and other value of “param1”. Result - OK. Value of param1 in /aaa was updated.
**Expected result**
Entity in servicePaths  /aaa shouldn't be updated when I executed update request without servicePath header

**Comment by fgalan** [comment]
Just to have the complete information... which Orion version are you using (i.e. the output of the `contextBroker --version` command)? Thanks!

**Comment by DmitryPranchuk** [comment]
@fgalan 
```json
{
  "orion" : {
  "version" : "0.28.0-next",
  "uptime" : "0 d, 1 h, 18 m, 5 s",
  "git_hash" : "7be2fae7137feada2d273cc658e207db9173bb43",
  "compile_time" : "Tue Mar 22 09:52:06 UTC 2016",
  "compiled_by" : "root",
  "compiled_in" : "838a42ae8431"
}
}
```

**Comment by DmitryPranchuk** [comment]
@fgalan 
```json
{
  "orion" : {
  "version" : "0.28.0-next",
  "uptime" : "0 d, 1 h, 18 m, 5 s",
  "git_hash" : "7be2fae7137feada2d273cc658e207db9173bb43",
  "compile_time" : "Tue Mar 22 09:52:06 UTC 2016",
  "compiled_by" : "root",
  "compiled_in" : "838a42ae8431"
}
}
```

**Comment by fgalan** [comment]
After an early analysis or your case, this could be a bug. As you suggest, step 3 musn't update the entity at servicePath /aaa, but the one created as result of step 1 in the default service path.

Scheduled to milestone to be analyzed in deep. Thanks for the report!

**Comment by DmitryPranchuk** [comment]
There is no new created entity in step 1. It just do nothing.

**Comment by fgalan** [comment]
To ease debug, I have reproduced the bug in three steps (starting with Orion DB empty):

fermin@neodeb:~/src/fiware-orion$ sh step3.sh 

First. Create one entity in subsrv /aaa (OK)

* Step:

```
$ curl localhost:1026/v2/entities --header 'Content-Type: application/json' --header 'Fiware-ServicePath: /aaa' -d @- <<EOF
{
  "id": "E",
  "type": "T",
  "sp": { "value": "aaa" },
  "param1": {
    "value": "initial",
    "type": "T"
  }
}
EOF
```

* Result:

```
$ curl localhost:1026/v2/entities -s -S | python -mjson.tool
[
    {
        "id": "E",
        "param1": {
            "metadata": {},
            "type": "T",
            "value": "initial"
        },
        "sp": {
            "metadata": {},
            "type": "none",
            "value": "aaa"
        },
        "type": "T"
    }
]
```

Second. Create one entity in default service / (OK)

* Step:

```
$ (curl localhost:1026/v1/updateContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "contextElements": [
        {
            "type": "T",
            "isPattern": "false",
            "id": "E",
            "attributes": [
                {
                    "name": "param1",
                    "type": "Tbis",
                    "value": "new"
                }
            ]
        }
    ],
    "updateAction": "APPEND"
} 
EOF
```

* Result:

```
$ curl localhost:1026/v2/entities -s -S | python -mjson.tool
[
    {
        "id": "E",
        "param1": {
            "metadata": {},
            "type": "T",
            "value": "initial"
        },
        "sp": {
            "metadata": {},
            "type": "none",
            "value": "aaa"
        },
        "type": "T"
    },
    {
        "id": "E",
        "param1": {
            "metadata": {},
            "type": "Tbis",
            "value": "new"
        },
        "type": "T"
    }
]
```

Third. Do APPEND in the entity in default service /, but the one in /aaa gets the udate (ERROR)

* Step:

```
$ (curl localhost:1026/v1/updateContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "contextElements": [
        {
            "type": "T",
            "isPattern": "false",
            "id": "E",
            "attributes": [
                {
                    "name": "param1",
                    "type": "T",
                    "value": "new"
                }
            ]
        }
    ],
    "updateAction": "APPEND"
} 
EOF
```

* Result:

```
$ curl localhost:1026/v2/entities -s -S | python -mjson.tool
[
    {
        "id": "E",
        "param1": {
            "metadata": {},
            "type": "T",
            "value": "new"
        },
        "sp": {
            "metadata": {},
            "type": "none",
            "value": "aaa"
        },
        "type": "T"
    },
    {
        "id": "E",
        "param1": {
            "metadata": {},
            "type": "Tbis",
            "value": "new"
        },
        "type": "T"
    }
]
```

**Comment by fgalan** [comment]
Running the steps in the following order also raises de bug:

first -> third -> second

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1990. DmitryPranchuk, could you have a look in order to see if it works now? (You need to update your CB to the last one in develop branch or get the last docker available from https://hub.docker.com/r/fiware/orion/).
