### ISSUE TITLE
Support linked entity attribute type

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1958]
In API v2 we need to support the concept of linked entities. Example

`WeatherStation` and `WeatherObserved` could be two linked entities.

A weather station provides its latest observation through an instance of `WeatherObserved`. A weather observation has been gathered by a particular `WeatherStation`. 

```
WeatherStation --> lastMeasurement --> WeatherObserved --> capturedFrom --|
^                                                                                                                             |
|---------------------------------------------------------------------------------------------------------
```

This issue has been open to gather feedback on how to materialize it: 

Proposal.

Create a new built-in attribute type named 'ref:<type>'. 

Example.  

``` json
{ 
   "id": "AEMET-345",
   "type": "WeatherStation",
   "location": {
      "type": "geo:point",
      "value": "43.5, -3.8"
   },
  "lastMeasurement": {
     "type": "ref:WeatherObserved",
     "value": "WeatherObserved-456778"
   }
} 

{ 
   "id": "WeatherObserved-456778",
   "type": "WeatherObserved",
   "capturedFrom": {
     "type": "ref:WeatherStation",
     "value": "AEMET-345"
   }
} 

```

Please take into account that in principle no consistency checking will be done by the implementation, although some checking tools could appear in the future. 

When querying 

http://broker.org:1026/v2/entities?id=AEMET-345

the HTTP response will include a link header with 

Link rel="lastMeasurement" type="ref:WeatherObserved" href="http://broker.org:1026/v2/entities?id=WeatherObserved-456778&type=WeatherObserved" 

(Please note that this feature is related to JSON-LD support but we can support it without JSON-LD as well)

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
