### ISSUE TITLE
make ';' for separating coordinate pairs optional (or not needed)

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#1969]
Is ';' really needed to separate coordinate pairs when specifying lines, boxes or polygons?

Can we make it optional or even remove it?

opinions 

original discussion at

https://github.com/telefonicaid/fiware-orion/pull/1959#discussion_r57748476

**Comment by fgalan** [comment]
(Semi copy-pasted from original comment in PR #1959)

Using `;` helps to introduce some structure in the coords field, which makes them easier to read. For example comparing

```
coord=12,11,13,4,5,1,16,17,7,15,10,8,19,20,9,6,18,3,14,2
```

with

```
coord=12,11;13,4;5,1;16,17;7,15;10,8;19,20;9,6;18,3;14,2
```

The former is more difficult to read and debug. In fact, it is difficult to see looking to the bunch of numbers that you have an even number of numbers.

From a generation difficulty point of view, I think both approaches are equal, i.e. a programmatic client wouldn't have any problem to generate coords in one format or in the other.

**Comment by kzangeli** [comment]
I also prefer the ';' even though it adds a little to the size of the payload.
Much easier to read and especially, less error-prone for our users.

**Comment by fgalan** [comment]
Using two levels of separation (first one between coordinates with `,` second one between paris with `;`) is similar to the one that we are using for locations

I mean, e.g. https://github.com/telefonicaid/fiware-orion/blob/develop/doc/apiary/v2/fiware-ngsiv2-reference.apib#L458, we are using:

```
{
  "location": {
    "value": [
              "40.63913831188419, -8.653321266174316",
              "40.63881265804603, -8.653149604797363"
    ],
    "type": "geo:box"
  }
}
```

and not


```
{
  "location": {
    "value": "40.63913831188419, -8.653321266174316, 40.63881265804603, -8.653149604797363"
    "type": "geo:box"
  }
}
```

As @kzangeli says, it is easier to read and less error prone using two-levels separation.

**Comment by fgalan** [comment]
After discussion, we would keep `;` at the end.
