### ISSUE TITLE
/v2/entities/<entityId>/attrs not implemented

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2008]
as per 

http://stackoverflow.com/questions/36476300/list-all-entities-resources-functionality-seems-to-be-failing-in-api-v2/

it seems it is not implemented ...

**Comment by fgalan** [comment]
Not sure what do you mean... `GET /v2/entities/<id>/attrs` is not part (and, as far as I remember, hasn't ever been part) of the NGSIv2 API. See https://docs.google.com/spreadsheets/d/1f4m624nmO3jRjNalGE11lFLQixnfCENMV6dc54wUCCg/edit#gid=50130961

**Comment by jmcanterafonseca** [comment]
was it a mistake not to consider?

2016-04-07 17:59 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
> was it a mistake not to consider?

I don't think so...

I mean, we have an operation to get all the attributes of the entity (i.e. `GET /v2/entities/<id>`) and another operation to get a given attribute of a given entity (i.e. `GET /v2/entities/<id>/attrs/<attrName>`). So, why do we need `GET /v2/entities/<id>/attrs`?

Note that in NGSIv1 we have the convenience operation `GET /v1/contextEntities/<id>/attributes` as an alias of `GET /v1/contextEntities/<id>/attributes`. But it was deprecated at the end (see https://docs.google.com/spreadsheets/d/1f4m624nmO3jRjNalGE11lFLQixnfCENMV6dc54wUCCg/edit#gid=0 cell "D27").

**Comment by jmcanterafonseca** [comment]
seems to be a bit strange not allowing that operation it seems to be more
natural to have it

2016-04-07 18:41 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by jmcanterafonseca** [comment]
duplicate of #2028 . finally we are going to implement it.
