### ISSUE TITLE
Changes in NGSIv2 subscription payloads

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2014]
1) In subscripion payloads, in `notification` field, change:

      "callback": "http://localhost:1234",
by:

      "http": {
        "url": "http://localhost:1234"
      }

2) In subscripion payloads, in `notification` field, change `attributes` to `attrs`.

2) In subscripion payloads, in `condition` field, change `attributes` to `attrs`.

NGSIv2 specificacion needs to be changed accordintly.

**Comment by fgalan** [comment]
CC: @anabelengp (so you can be aware when this gets implemented at CB)

**Comment by fgalan** [comment]
The  websockets.md file in the feature/1811_websockets branch need also to be adjusted.

**Comment by fgalan** [comment]
4) "Move" `throttling` from `notification` to the root level (i.e. making it a "sibbling" of `status` and `expires`).

**Comment by fgalan** [comment]
Implemented in PR #2047

**Comment by fgalan** [comment]
Please @iariasleon test and close this if actually fixed.

**Comment by AlvaroVega** [comment]
In which orion version will be implemented this change?

**Comment by fgalan** [comment]
It is already implemented in develop, so it will land in the next Orion official version (1.1.0) to be released by the end of April.

**Comment by iariasleon** [comment]
LGTM
With this payload:
```
{
	"status": "active",
	"description": "my first subscription",
	"throttling": 5,
	"notification": {
		"http": {
			"url": "http://localhost:1234"
		},
		"attrs": ["temperature_0", "temperature_1", "temperature_2"]
	},
	"expires": "2016-04-05T14:00:00.00Z",
	"subject": {
		"entities": [{
			"idPattern": ".*",
			"type": "room_0"
		}, {
			"idPattern": ".*",
			"type": "room_1"
		}],
		"condition": {
			"expression": {
				"q": "temperature>40",
				"georel": "near;MinDistance:1000",
				"coords": "40.6391",
				"point": "point"
			},
			"attrs": ["temperature_0", "temperature_1", "temperature_2"]
		}
	}
}
```

returns this response
```
http code: 201
date: Thu, 21 Apr 2016 12:24:29 GMT
fiware-correlator: fea703ba-07bb-11e6-a633-005056a20feb
connection: Keep-Alive
content-length: 0
location: /v2/subscriptions/5718c67d23a6c39cc9ed0dc6
```
