### ISSUE TITLE
NGSIv2 notification templates

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2015]
CC: @mrutid , @jmcanterafonseca 

Apart from the different notification formats defined in NGSIv2, we should implement the capability of customizing notifications.

Related with the changes in #2014, the `http` field will be expanded in the following way, to support additional sub-fields to `url`:

      "http": {
        "url": "http://localhost:1234",
        "headers": {
          "X-MyHeader": "foo"
        },
        "method": "PUT",
        "qs": {
          "authToken": "bar"
        }
        "payload": <...>
      }

Fields description (all them optionals):

* `headers`: a key-map to build the HTTP headers to include in the subscription
* `method`: method to use (by default POST is used, but this field would allow to change)
* `qs`: a key-map used to build the query parameter that are appended to the URL. Note that query parameters cannot be used directly in the `url` field, as `=` is a forbidden char.
* `payload`: the payload to use. If omitted, the regular payload according to NGSIv2 is used.

All them should implement a template language that enables to use of variable values. The details of this template language are still pending (suggestions are welcome!).

**Comment by jmcanterafonseca** [comment]
maybe we can use the templating mechanism as well for other notification channels, namely web socket.

so the template would be part of the notification object and not the http object. For instance

```json
{ 
   "notification": {
      "attrs": ["temperature", "humidity"]
      "template": [{
         "id": "$id",
         "t":  "$(temperature)",
         "h": "$(humidity) * 100",
         "custom": "my own key"
      }]
   }
}
````

another nice to have for the templating mechanism is the capability of specifying the container for the elements, it could be an array or a keyValue object, ex.

```json
{ 
   "notification": {
      "attrs": ["temperature", "humidity"]
      "template": {
         "$id": {
            "t":  "$(temperature)",
            "h": "$(humidity) * 100"
         }
      }
   }
}
````

**Comment by mrutid** [comment]
I may want to templatize a header content for example. I don't see how your proposal cover this aspect.

**Comment by fgalan** [comment]
Another interesting case is to templatize URL, e.g:

```
"url": "http://example.com:8080/processEntity/${id}"
```

**Comment by jmcanterafonseca** [comment]
oh yes. we can have template at payload level, or at HTTP request level

2016-04-12 13:31 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
> oh yes. we can have template at payload level, or at HTTP request level

So you mean to move "payload" to "notification" and keep "url", "method", "headers" and "qs" under "http" so at the end templates can be applied to the following fields:

notification.payload
notification.http.url
notification.http.headers
notification.http.qs

Is that correct?

**Comment by jmcanterafonseca** [comment]
payload is something not only related to the HTTP channel but to any notification channel, so yes, instead of calling the property 'template', we can call it payload and use templates there as suggested in the first comment I made, templates could also be used at URL level, headers or whatever, provided we use the same language and templating conventions

**Comment by mrutid** [comment]
.... but we are foreseeing interesting use cases that are transport specific. I.E use templates to specify MQTT topic. I don't see the point of templatize al notification level, but see advantages to do it at transport level.

**Comment by fgalan** [comment]
Some implementation considerations.

Template implementation should be based in a extension of the current `Http` struct (currently in Subscriptions.h). In fact, probably it makes sense to spin off to a separate module (Http.h/cpp) (maybe the name should be also changed).

```
struct Http
{
  std::string url;       // The only one in the current implementation
  std::map<std::string, std::string> headers;
  std::map<std::string, std::string> qs;
  std::string method;
  std::string payload;
  // The only one in the current implementation, for rendering csub object in GET /v2/subscriptions and so
  std::string toJson();

  // To make implementation work (and PR reviews :) easier, first implementation of the get*(const Entity& en) 
  // will return just the plain strings/maps. In a second phase the actual replacement will be implemented.
  // const X& in the following method is a nice-to-have, more "relaxed" alternatives (or even
  // result in function argument, as pointer) could be also used. Entity is pased as const references
  // as it is a read only parameter

  // Returns URL after replacing ${..} macros based on 'en' parameter
  const std::string& getUrl(const Entity& en);

  // Return headers map after replacing ${..} macros based on 'en' parameter
  const std::map<std::string, std::string>& getHeaders(const Entity& en);

  // Returns query string map after replacing ${..} macros based on 'en' parameter
  const std::map<std::string, std::string>& getQs(const Entity& en);
  
  // Returns HTTP method after replacing ${..} macros based on 'en' parameter
  const std::string method& getMethod(const Entity& en);

  // Returns HTTP method after replacing ${..} macros based on 'en' parameter
  const std::string payload& getPayload(const Entity& en);
};
``` 

In addition, the sendNotifyContextRequest() needs to be changed. In particular, the `url` parameter should be "generalized" to the notification template. Internal usage of template (by the get*() methods) to generate the subscription will be done at Notifier scape.

```
void Notifier::sendNotifyContextRequest
(
  NotifyContextRequest*            ncr,
  const std::string&               url,   // -> this would be now "const Http& template,"
  const std::string&               tenant,
  const std::string&               xauthToken,
  const std::string&               fiwareCorrelator,
  RenderFormat                     renderFormat,
  const std::vector<std::string>&  attrsOrder
)
```

**Comment by fgalan** [comment]
Now let's consider how this would be persisted in DB (csubs collection):

Let's consider the csub model at DB described at: https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/database_model.md#csubs-collection. On this model:

* Existing **reference** field will store Http.url This field is a string at MongoDB level.
* New **headers** field will store Http.headers. This field is a JSON object at MongoDB level.
* New **qs** field will store Http.qs. This field is a JSON object at MongoDB level.
* New **method** field will store Http.method. This field is a string at MongoDB level.
* New **payload** field will store Http.payload. This field is a string at MongoDB level.

Note that all them are located at first level in the csub document. We could consider to use a container field, but this would make more complex to read/write them at DB, without no added value (at least I cannot see any worth enough value).

**Comment by fgalan** [comment]
Ah, and cache, of course... `CachedSubscription` struct should be expanded to hold all these new fields. Two alternatives can be followed:

* Replace `reference` field by a `Http*` holding a template object. Less DB-cache similarity, but maybe smarter.
* Use 4 new fields (for headers, qs, method and payload). Full DB-cache similarity, but maybe less smart.

**Comment by kzangeli** [comment]
If there is more than one ContextElementResponse in a Notification, then the substitution gets complicated, so we will split the notification into N notifications, one notification per ContextElementResponse.

Of course, if the subscription doesn't make use of substitution/templates, the notification should **not** be split.

**Comment by kzangeli** [comment]
The **method** in the Http structure (called HttpInfo in the source code) MUST be in all uppercase, like:
* PUT
* POST
* etc

**Comment by fgalan** [comment]
Documentation PR: https://github.com/telefonicaid/fiware-orion/issues/2015

**Comment by fgalan** [comment]
Documentation PR for this issue: https://github.com/telefonicaid/fiware-orion/pull/2153

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/2192. Moved to "QATestPending" milestone.

**Comment by iariasleon** [comment]
LGTM
