### ISSUE TITLE
HTTP headers in orion documentation

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2027]
We don't have a 'central' place for all the HTTP headers that Orion accepts and sends.
The info is there (in the documentation) but in many different places.

It wouldn't hurt to create a new chapter, explaining all the HTTP headers ...

**Comment by jmcanterafonseca** [comment]
+1

**Comment by ArqumFarooqui-NEC** [comment]
Hi @kzangeli sir,
I have started working on this issue.
As per my understanding : "All the HTTP Headers that are used by orion should be  in a single document  with their description." 
As all the HTTP headers are defined in ```rest/HttpHeaders.h``` file, so I'll have to just place them in a single file and add the description for all HTTP Headers. Some HTTP Header descriptions are present in  fiware-orion/documents and some are not.
Please confirm the above understanding and approach.

And please provide me some valuable guidance on this.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
The PR on this issue has been raised by @ArqumFarooqui-NEC, I request you to please assign this issue to him.

**Comment by fgalan** [comment]
> @fgalan
> The PR on this issue has been raised by @ArqumFarooqui-NEC, I request you to please assign this issue to him.

Done! :)

**Comment by Chandradeep-NEC** [comment]
> @fgalan
> The PR on this issue has been raised by @ArqumFarooqui-NEC, I request you to please assign this issue to him.
> 
> Done! :)

Thanks for your quick response :)
The PR #3576  has already been reviewed and verified. Request you to please merge the PR.

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan sir, As PR for this issue i.e. #3576 has been merged. So kindly close this issue.
Thank you:)

**Comment by fgalan** [comment]
Thanks for noticing! Closing.
