### ISSUE TITLE
Docker is built on the develop branch

### ISSUE THREAD

**Issue by drasko** [telefonicaid/fiware-orion#2038]
Why is Docker image built on develop branch: https://github.com/telefonicaid/fiware-orion/blob/develop/docker/Dockerfile#L62

Would it not make more sense to default to a stable master branch for deployment (I think in a scenarios like this Docker is mostly used for production deployment, not during the development phase)?

**Comment by drasko** [comment]
Whoops, sry, did not saw that default branch on GitHub was `develop`. Switching on `master` I saw that Dockerfile differs.

**Comment by fgalan** [comment]
As additional information, note that our relesing procedure ensures that the GIT_REV_ORION environement variable is aligned with the branch of the corresponding Dockerfile.

For example, in release/1.0.0 the Dockerfile uses GET_REV_ORION set to release/1.0.0: https://github.com/telefonicaid/fiware-orion/blob/release/1.0.0/docker/Dockerfile#L6

...but in release/0.28.0 Dockerfile uses a GET_REV_ORION set to release/0.28.0: https://github.com/telefonicaid/fiware-orion/blob/release/0.28.0/docker/Dockerfile#L6

That ensures that the docker images at https://hub.docker.com/r/fiware/orion/ always point to the right version, e.g. `docker pull fiware/orion:1.0` will use Orion version 1.0.0 (at release/1.1.0 branch) and `docker pull fiware/orion:0.28` will use version 0.28.0 (at release/0.28.0 branch).
