### ISSUE TITLE
URI PATH is case insensitive, URI PARAMS are case sensitive

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2057]
We should make the URI PATH case sensitive as well, but only for NGSIv2

 **Effort: 1 man day**

**Comment by fgalan** [comment]
Only for NGSIv2 (NGSIv1 cannot be touched in order not breaking backward compatibility).

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2330
