### ISSUE TITLE
How is the message pushed towards subscriber?

### ISSUE THREAD

**Issue by drasko** [telefonicaid/fiware-orion#2066]
This has been discussed here: http://stackoverflow.com/questions/36754847/orion-pub-sub-protocol, but not answered.

As can be seen here: https://github.com/slact/nchan#subscriber-endpoint, when dealing with HTTP connection and you want to do push from server to the subscriber you have to use one of the several standardized HTTP methods:
- Long Polling
- Interval-polling
- EventSource
- HTTP multipart/mixed
- HTTP Chunked Transfer

Which one is used in Orion?

Where exactly in the code can we see how messages are pushed to HTTP connection towards subscriber?

**Comment by fgalan** [comment]
Details of incoming HTTP request are in the [rest module](https://github.com/telefonicaid/fiware-orion/tree/develop/src/lib/ngsiNotify). Details of HTTP notifications are in the [ngsiNotify module](https://github.com/telefonicaid/fiware-orion/tree/develop/src/lib/ngsiNotify).

In the second case (I think the one you refer by the issue descriptino) we are using libcurl for sending outgoing HTTP requests.

**Comment by fgalan** [comment]
From (http://stackoverflow.com/questions/36754847/orion-pub-sub-protocol/36764834):

> @fgalan I know that the code is open. I just wanted to hear from developers where to look exactly in the code to find subscription push from the server via HTTP req that has been open. I also want to know how you keep the connection open and how exactly you send HTTP message from the server towards subscriber (Long Polling, Interval-polling, EventSource, HTTP multipart/mixed or HTTP Chunked Transfer). There is not much comments in the code, and it is diffcult to figure out without the maintainers help.

**Comment by drasko** [comment]
@fgalan is connection closed after server push, and has to be explicitly re-opened by the client (case of long polling), or is it kept open (in which case it is some kind of HTTP streaming)?

**Comment by fgalan** [comment]
In depends of the notification mode, which is a configurable CLI parameter at startup time. Please have a look to the documentation about it https://fiware-orion.readthedocs.org/en/develop/admin/perf_tuning/index.html#notification-modes-and-performance

**Comment by drasko** [comment]
@fgalan thanks for this link!

I would say that the `transient` notification mode corresponds to long polling. `permanent` mode would correspond to HTTP streaming (I do not know how otherwise you could keep HTTP connection open). I'll just have to find in the code where this connection is opened and look at the HTTP headers to conclude what is the type of connection...

**Comment by drasko** [comment]
@fgalan I actually missinterpreted the mechanism - it is much simpler than i thought...

Actually, I thought that the information about updates are pushed in the same connection that used to issue `subscribeContext` (i.e. towareds the same caller of this function, as I thought that he was the subscriber).

Instead - subscriber just leaves `reference` URL and leaves (closes this connection), so when new information is ready it is not pushed to the previous connection, but simply POST-ed over `reference` URL (via new HTTP connection).

This also implies that every subscriber must be a server, i.e. that it ust be listening on the provided `reference` URL for a notification to come.

**Comment by fgalan** [comment]
Let's start by the end :)

> This also implies that every subscriber must be a server, i.e. that it ust be listening on the provided reference URL for a notification to come. 

That's correct. Currently, the notification API is based in invoking a REST service in the receiver, so the receiver has to run a server to listen for request. However, as it was explained in the SOF post which originates the present issue (http://stackoverflow.com/questions/36754847/orion-pub-sub-protocol), we developing a WebSocket interface that will allow recivers to get notifications without needeing a sever (currently WS work is experimental, it can be monitored in this issue: https://github.com/telefonicaid/fiware-orion/issues/1181).

Regarding how the different notification modes "map" into the source code.

* Transient and permanent mode use the `Notifier` class

**Comment by fgalan** [comment]
(Wrongly closed. Reopening. Sorry...).

**Comment by drasko** [comment]
@fgalan thanks, it is much clearer now!

**Comment by fgalan** [comment]
(Note that my previous comment was cut while I was editing it. You can have now a look to the complete version above)

**Comment by drasko** [comment]
Wow, thanks for the detailed explanation! I guess that it will be useful to all the people looking at Orion internals.

**Comment by fgalan** [comment]
If you think the question is solved, please close the issue. Thanks!
