### ISSUE TITLE
Duplicated attributes

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2074]
If a request to create/modify an Entity contains more than one attribute with the same name, right now  (probably) the broker just accepts the request and creates two attributes with the same name.

Same thing for subscriptions, both in attribute list 'to notify' and attribute list 'to monitor for notifications'.

The broker should a little bit be more intelligent and detect duplicated attributes and return an error.

400 Bad Request ?

 **Effort: 2 man days**

**Comment by kzangeli** [comment]
See issue #2101.
Clearly Entity creation/modification is more severe than subscriptions.
Personally I would forget about subscriptions and return an error for Entity creation/modification, in case of duplicated attributes. Same goes for duplicated metadata.

**Comment by fgalan** [comment]
I agree. The subscription case here is similar to the #2101, which is very corner case.

**Comment by arigliano** [comment]
Hello, I would like to work on this issue. Can you assign it to me?

**Comment by fgalan** [comment]
Done!

Focus on NGSIv1 request. No need to fix in NGSIv1, as it is decrecated.

**Comment by arigliano** [comment]
It seems that this issue was covered in early versions. Indeed, if I try a POST to **v2/entities** with this payload:
```
{
	"A1" : {

    	"type": "TA1",
	"value": "value1"    
	},
	"A1": {
		"type": "TA2",
		"value": "value2"
	},
   "type": "T1",
   "id": "E1"
}
```
I (correctly) get:
```
{
    "error": "BadRequest",
    "description": "duplicated attribute /A1/"
}
```
***
In case of modification, if i make a PUT to **v2/entities/E1/attrs** with this payload:
```
{
  "a": {
      "type": "string",
       "value": "value1"
   },
  "a": {
      "type": "string",
       "value": "value2"
   }
}
```
I (correctly) get:
```
{
    "error": "BadRequest",
    "description": "duplicated attribute /a/"
}
```

If I well understood the issue request, it should be closed.

**Comment by fgalan** [comment]
I agree. Closing.

Thanks for checkint it!
