### ISSUE TITLE
in PUT/v2/entities/<id>/attrs/<name> if name is empty and it is used options query parameter, all attributes are replaced in the entity

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2080]
in `PUT/v2/entities/<id>/attrs/<name>` if name is empty and it is used `options` query parameter, all attributes are replaced in the entity. Redirect to the replace operation as ``PUT/v2/entities/<id>/attrs/` 

Initially this entities has 4 attributes
#### attr update request
```
PUT http://localhost:1026/v2/entities/room/attrs/?options=keyValues
 {"value": "25"}
```

#### attr update response
```
 http code: 204
  content-length: 0
```

#### doc in mongo
```
> db.entities.find()
{ "_id" : { "id" : "room", "type" : "house", "servicePath" : "/test" }, "attrNames" : [ "value" ], "attrs" : { "value" : { "type" : "none", "creDate" : 1461574838, "modDate" : 1461574838, "value" : "25", "md" : [ ] } }, "creDate" : 1461574838, "modDate" : 1461574838 }
```

#### Options:
1. leave it as it is (and assume that it is user  responsibility use correctly)
2. eliminate the equivalence between "attrs/$" and "attrs$" (possibly extended to another operations XXXX/$  and XXXX$, for consistency in the API) that allows easily detect this error. Also read: https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/ 
3. add controls to `attr_name`  and will be valued what is necessary at the time, because it is probable that the request uses the incorrect operation and the `attr_name` could does not exist

**Comment by fgalan** [comment]
Assigned to milestone 1.2 (this issues should be solved, in a way or the other before losing the first production-ready block of NGSIv2).

**Comment by fgalan** [comment]
Not closed at the end in 1.2.0. Moving to 1.3.0...

**Comment by fgalan** [comment]
It has decided that as general rule in all the operations of the NGSIv2 API, an URL ended in "/" is interpreted as the same URL without "/".

Under this assumption, it is not possible to distinghish between a right use of `PUT/v2/entities/<id>/attrs/` and a wrong usage of `PUT/v2/entities/<id>/attrs/<attrName>` in which the client misses ´<attrName>`.

**Comment by fgalan** [comment]
Thus, option: "leave it as it is (and assume that it is user responsibility use correctly)". Closing.
