### ISSUE TITLE
NGSIv2 In queries a trailing ';' raises error 400

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2086]
A query like 

```
q=addressLocality==Santander;addressCountry==ESP;
```
now is returning 400 HTTP error. Previous version didn't . We need to decide. I'm in favour of allowing trailing ';'

**Comment by kzangeli** [comment]
Yes, this seems to be an error introduced in the complete rewrite of this part.
One trailing ';' should be allowed, but not more than one.

Also, we need a functest to capture this situation.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2326
