### ISSUE TITLE
NGSIv2: Optional features

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#2110]
Optional features can hurt interoperability of systems compliance, but I still feel that NGSIv2 could benefit from having features made optional to lower the implementation cost and have more systems adopt the specification.

I propose these sections of the specification be made optional to implementations:
- Support for Simple Query Language
- Support for geo filtering
- Support for GeoJSON (use only Simple Location Format)
- Support for Simplified Representation (keyvalue and value modes)

This would result in implementations not having to support:
- query filtering `q=` in `/v2/entities` and `/v2/subscriptions`
- geo query filtering `georem=`, `geometry=`, `coords=` in `/v2/entities` and `/v2/subscriptions`
- `options=keyValues` on all requests
- `options=values` on all requests

Implementation not supporting these parameters would return a `501 Not Implemented` HTTP response code for such requests.
## A light profile ?

Maybe these features could be made optional in a "light" (in opposite to the default "full") profile of the specification.

Systems implementing only the "light profile" would expose the `/v2` endpoint with a `profile` set to `light`:

``` json
{
  "profile": "light",
  "entities_url": "/v2/entities",
  "types_url": "/v2/types",
  "subscriptions_url": "/v2/subscriptions",
  "registrations_url": "/v2/registrations"
}
```

**Comment by fgalan** [comment]
I agree in the idea of "profiling" to reduce implementation barrier in the case of a particular implementors not interested in the full NGSIv2 API.

I'd suggest to identify each one of the capabilities with a "keyword" (your list seems to be a good starting point), then `GET /v2` should return the list of supported capabilities. I think this is more explicit than `profile`. Each capability and associated keyword must be properly described in the NGSIv2 specificacion document.

E.g:

```
{
  "capabilities": [ "simpleQueryLenguage", "geoFiltering", "keyValues" ]
  "entities_url": "/v2/entities",
  "types_url": "/v2/types",
  "subscriptions_url": "/v2/subscriptions",
  "registrations_url": "/v2/registrations"
}
```

would mean that the implementation support Simple Query Lengauge, Geo Filtering and keyValues rendering mode, but not the other capabilities (i.e. it doesn't support GeoJSON nor values rendering).

If `capabilities` is omitted, it meanas that the implementation provides full NGSIv2 support.

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
