### ISSUE TITLE
Throttling set to -1 at creating v2 subscriptions

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2114]
It seems we have a bug in the sub-cache with newly created subscriptions in v2.

What seems to be a method meant only for v1 subscriptions is called in subCacheItemInsert:

    cSubP->throttling = scrP->throttling.parse();

This method parses the string of the Throttling of the subscription, and as in v1 the throttling comes in as a string, this makes sense. In v2 however, throttling is an integer and the parsing stops making sense.

**Comment by fgalan** [comment]
Just to understand the problem from an user perspective... does this bug mean that thorttling was not correctly stored in cache when the user used NGSIv2 subscription API? 

E.g. user creates a subscription with `throttling: 5`, then the subscriptions is stored in cache as -1. Thus, when a updateCtx arrives, throtlling has no effect, as -1 means "no thottrling" in the mongoBackend/Notifier logic that evaluates if the throttling blocks a notification or not. Is this correct?

**Comment by fgalan** [comment]
Fixed in PR #2116
