### ISSUE TITLE
Problems with pattern entity ids including backslashes

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2142]
It has been found in the NGSIv1 API that using pattern entity ids can be problematic, as the `\` is not correctly interpreted.

Although the problem has been detected in NGSIv1, the NGSIv2 equivalent functionality should be also checked (and covered with tests).

**Comment by dmoranj** [comment]
An example that has been proved to fail in verison 0.26 is the following: MOBA_[23]\d{2}

**Comment by kzangeli** [comment]
The following payload gives a JSON parse error, also in jsonlint.com:

    {
	"id": "MOBA_[23]\d{2}",
	"type": "T1"
    }

**Comment by kzangeli** [comment]
I'm having some kind of deja-vu here ...
Sure we've discussed this before.

JSON accepts backslash only if followed by one of the following chars:

    "\/bfnrtu

Any other char after `\` provokes a parse error as it is incorrect JSON.

Now, if I change the 'd' for a 'b' in the example supplied by @dmoranj, the broker no longer complains about JSON parse error but about **invalid chars** in payload ...
Actually, just **MOBA_\b** gives invalid chars in payload ...

**Comment by iariasleon** [comment]
This behavior with a backslash is the same when we try to create a new subscription using NGSI v2. It is a restriction of json (http://www.json.org/ )
```
after of the backslash only are allowed: ", \, /, b, f, n, r, t, u
```
returning an error `"Errors found in incoming JSON buffer"`, if we use regexp chars as: \a, \e, \v, \x, \d, \w, \s, \D, \W, \S, \A, \Z, \B

**Comment by fgalan** [comment]
Let's try to define the expected behaviour. Starting with a clean CB (i.e. empty database), the following entity is created:

```
curl -v 'localhost:1026/v2/entities?options=keyValues' --header 'Accept: application/json' --header 'Content-Type: application/json' -d @- <<EOF
{
  "id": "MOBA_255",
  "A": 42
}
EOF
```
Now, considering the following query:

```
(curl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "isPattern": "true",
            "id": "MOBA_[23]\\d{2}"
        }
    ]
} 
EOF
```

1. Payload is legal JSON (checked with jsonlint.com)
2. After un-scaping the slash (i.e. after the parsing layer) regex is: `MOBA_[23]\d{2}`. This match `MOBA_255`, so that entity should be included in the queryContext response.

As far as I have cheched (reference CB version: 1.2.0-next git version: 85aa85df71c04a3260a9cf14f8bbf2a1385c112e) the result of the above queryContext is:

```
{
    "errorCode": {
        "code": "400",
        "details": "JSON Parse Error",
        "reasonPhrase": "Bad Request"
    }
}
```

So it seems we are now blocked at point 1. Once point 1 get solved, let's see what happens at point 2...

**Comment by fgalan** [comment]
Addition fact, the following request:

```
rl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "isPattern": "true",
            "id": "MOBA_[23]\\\\d{2}"
        }
    ]
}
EOF
```

returns MOBA_255.

This is of course a consequence of how Orion is implemented right now. However, that doesn't means that it is the way we want to work in the future (neither the opposite ;)

**Comment by fgalan** [comment]
More info: similar test done in NGSIv2:

```
(curl localhost:1026/v2/op/query -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "idPattern": "MOBA_[23]\\d{2}"
        }
    ]
} 
EOF
```

The payload is valid (according with JSONLint) and CB returns "parse error".

```
(curl localhost:1026/v2/op/query -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "idPattern": "MOBA_[23]\\\\d{2}"
        }
    ]
} 
EOF
```

returns MOBA_255.

Conclusion: similar behaviour to NGSIv1.

**Comment by fgalan** [comment]
In my previous tests today I was missing an subtle but important detail: curl applies its own scaping so what you write at curl level is not the same you get "on the wire". Let's start by the beginning. We have the following:

```
curl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "isPattern": "true",
            "id": "MOBA_[23]\\\\d{2}"
        }
    ]
}
EOF
```

It can be checked that on the wire, what curl is sendinng is `\\` and not `\\\\`. With nc:

```
fermin@neodeb:~$ nc -l -p 1026
POST /v2/op/query HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost:1026
Content-Type: application/json
Accept: application/json
Content-Length: 85

{    "entities": [        {            "idPattern": "MOBA_[23]\\d{2}"        }    ]}
```

With Wireshark:

![2016-06-23 15_58_30-debian8 2 - vmware player non-commercial use only](https://cloud.githubusercontent.com/assets/1534240/16306051/b4270d08-395c-11e6-87b3-d3e4cf570048.png)

Thus, on the wire CB gets `MOBA_[23]\\d{2}` which the JSON parser translates to `MOBA_[23]\d{2}`, which is a valid expression. As has been tested (see above) the result if MOBA_255 (i.e. correct behaviour).

The case for "JSON parser error" makes also sense: at curl level we have `MOBA_[23]\\d{2}` with on the wire is `MOBA_[23]\d{2}` which is a wrong string in JSON, detected by the parser (as been already explained by @iariasleon and @kzangeli, is is not legal that a `\` in JSON is followed by `d`).

**Comment by fgalan** [comment]
Another test, being payload.json 

```
{
    "entities": [
        {
            "idPattern": "MOBA_[23]\\d{2}"
        }
    ]
} 
```
With:

```
curl localhost:1026/v2/op/query -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' -d @payload.json
```

sends (at nc):

```
POST /v2/op/query HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost:1026
Content-Type: application/json
Accept: application/json
Content-Length: 85

{    "entities": [        {            "idPattern": "MOBA_[23]\\d{2}"        }    ]}
```

I.e. in the case of using a file to hold the payload, the "shell scaping effect" is avoided.

**Comment by fgalan** [comment]
In sum, it seems that the CB behaviour is correct right now, but documentation should be improved to include some comment regarding this stuff.

**Comment by fgalan** [comment]
Documentation clarifications add to doc/manuals/user/regex_in_payload.md file (PR #2333).
