### ISSUE TITLE
CB crashes when several regexp in q parameter and ~= operator

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-orion#2164]
When retireving the list of entities with several regexp as follows:

DEBUG >>>>>>>>>>>>>	 Data sent:     	>>>>>>>>>>>>> 
	> Comp: CB
	> Url: http://192.168.21.64:1026/v2/entities
	> Method: get
	> Headers: {'fiware-service': 'eeee', 'fiware-servicepath': '/uuu', 'Accept': 'application/json'}
	> Params sent: {'q': 'humidity~=100;temperature>10', 'limit': 3, 'type': 'Room5'}

The CB crashes.

The oposite way ({'q':temperature>10;'humidity~=100', 'limit': 3, 'type': 'Room5'}) it works fine

{
  "orion" : {
  "version" : "1.1.0_20160520020628",
  "uptime" : "0 d, 0 h, 2 m, 31 s",
  "git_hash" : "c96ceaf0437c989a21c388c5015fe4059f3bccff",
  "compile_time" : "Fri May 20 02:08:44 CEST 2016",
  "compiled_by" : "develenv",
  "compiled_in" : "ci-iot-deven-01"
}
}

**Comment by fgalan** [comment]
Fixed in PR #2183

**Comment by fgalan** [comment]
Candidate fix landed in develop. Waiting for CI report this night in order to know if this is actually fixed.

CC: @manucarrace

**Comment by iariasleon** [comment]
@manucarrace 
Could you confirm these values in the "query parameters" expression, below? 
` Params sent: {'q': 'humidity~=100;temperature>10', 'limit': 3, 'type': 'Room5'}`

?q=humidity~=100;temperature>10&limit=3&type=Room5

I assume that humidity="100" is `string` type not `Int` type

**Comment by iariasleon** [comment]
LGTM, verified in the version
```
  "version" : "1.1.0_20160531020227",
  "git_hash" : "e8fb906dc7278b2799698eb917edde8b2da3e700",
  "compile_time" : "Tue May 31 02:05:08 CEST 2016"
```
