### ISSUE TITLE
incorrect error response when running invalid query

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2174]
running 

http://192.168.59.103:1026/v2/entities/?type=Restaurant&georel=near;maxDistance=1000&geometry=point&coords=43.42015,-2.761160&options=keyValues

results in

{
  "error": "InvalidModification",
  "description": "Query not supported: Invalid selector in georel specification"
}

error name is incorrect. description should be "invalid modifier in georel parameter" or something like that

**Comment by fgalan** [comment]
I undertand that `error` should be "BadRequest" instead of "InvalidModification".

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2301
