### ISSUE TITLE
inconsistent behaviour when asking for a value

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2175]
let entity be

```json
{
  "id": "d7fafe27f0416d9ee89ebd2ab42baaddc746fa47",
  "type": "Restaurant",
  "address": {
    "type": "PostalAddress",
    "value": {
      "streetAddress": "Zarate Bidea",
      "addressRegion": "Gipuzkoa",
      "addressLocality": "Zizurkil",
      "postalCode": "20159"
    },
    "metadata": {}
  },
  "capacity": {
    "type": "PropertyValue",
    "value": 200,
    "metadata": {}
  }
}
````

if I run http://192.168.59.103:1026/v2/entities/d7fafe27f0416d9ee89ebd2ab42baaddc746fa47/attrs/capacity/value

response is 

```json
{
  "error": "NotAcceptable",
  "description": "accepted MIME types: text/plain"
}
````
but if I run 

http://192.168.59.103:1026/v2/entities/d7fafe27f0416d9ee89ebd2ab42baaddc746fa47/attrs/address/value

response is

```json
{
  "streetAddress": "Zarate Bidea",
  "addressRegion": "Gipuzkoa",
  "addressLocality": "Zizurkil",
  "postalCode": "20159"
}
````

in the first case response should be 

```json
{
   "value": 200
}
````

**Comment by fgalan** [comment]
Which `Accept` header is being used in each case?

**Comment by fgalan** [comment]
Which `Accept` header is being used in each case?

**Comment by jmcanterafonseca** [comment]
none

**Comment by jmcanterafonseca** [comment]
I think this is a bug, right?

**Comment by fgalan** [comment]
Not sure... we need to research on this a bit to diagnose.

**Comment by kzangeli** [comment]
This bug is being fixed in a current branch, PR soon to be sent.
However, the spec says only compound values can retuen JSON. In the case of String, Number Bool, and Null, only text/plain is accepted.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2323.
