### ISSUE TITLE
when asking for a number value in text/plain spurious decimals are added

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2176]
let entity be the same as described in #2175

If 

http://192.168.59.103:1026/v2/entities/d7fafe27f0416d9ee89ebd2ab42baaddc746fa47/attrs/capacity/value

is run (accept text/plain)

result is 

200.000000

instead of 200.

**Comment by fgalan** [comment]
Related with https://github.com/telefonicaid/fiware-orion/issues/2207

**Comment by fgalan** [comment]
Fixed by PR #2410
