### ISSUE TITLE
record timestamp of attribute creation / update

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2182]
this feature is being discussed by GSMA and other operators. It seems that it is considered a nice feature to have that the platform automatically records creation and update timestamps of each entity attribute. Following a NGSI data model those timestamps should be part of the metadata of an attribute.

**Comment by fgalan** [comment]
I think what you mention is part of https://github.com/telefonicaid/fiware-orion/issues/876 (still open)

**Comment by jmcanterafonseca** [comment]
yup

**Comment by fgalan** [comment]
So maybe this issue should be closed as duplicated of the other?

**Comment by fgalan** [comment]
Closing (duplicated)
