### ISSUE TITLE
Docker-ize accumulator-server.py + clean argument passing

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2189]
As the title says :)

**Comment by jmcanterafonseca** [comment]
a quick and dirty docker for accumulator

````
FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["./accumulator-server.py"]
CMD ["1028", "/accumulate", "0.0.0.0", "on"]
````

**Comment by fgalan** [comment]
Clean argurment passing already implemented as part of https://github.com/telefonicaid/fiware-orion/issues/187

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,
I would like to know this issue is still valid or not, so that I will start working on it.

**Comment by fgalan** [comment]
I think this issue needs to be re-analized.

We already have a Dockerfile for Orion and another Dockefiles (+ build-dep.sh) for CI. Ading a third one could be somehow confusing.

Maybe a better approach is to solve this through documentation, including in some .md file the procedure to build de docker container locally, in this part: https://github.com/telefonicaid/fiware-orion/tree/master/test/functionalTest#how-to-install-accumulator-serverpy

I'll take care of it, taking into account PR #4034 but waiting first to merge PR #4035 to have the newest version based in Python 3.

**Comment by fgalan** [comment]
> Maybe a better approach is to solve this through documentation, including in some .md file the procedure to build de docker container locally, in this part: https://github.com/telefonicaid/fiware-orion/tree/master/test/functionalTest#how-to-install-accumulator-serverpy

At the end we have opted for this solution. PR https://github.com/telefonicaid/fiware-orion/pull/4081
