### ISSUE TITLE
Assessment of NGSIv2 query/update redirect to CPrs (it was: Problem mixing NGSIv2 queries with faulty CPrs)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2193]
If clients uses NGSIv2 query which result to being forwareded due to registrations and the CPr doesn't reponds or does in a faulty way, then CB responds to the client in NGSIv1 format.

This is probably a side-effect of not having pay attention yet to NGSI9 functionality in NGSIv2. CPrs functionality *shouldn't* use NGSIv2 until we define NGSI9 functionality in NGSIv2 (at spec level) and implement it (at Orion code level).

Some information about the query used to test this:

 > Url: http://192.168.21.64:1026/v2/entities
 > Method: get
 > Headers: {'fiware-service': 'city012', 'fiware-servicepath': '/electricidad', 'Accept': 'application/json'}
 > Params sent: {'q': 'dateCreated>2016-04-04T14:00:00.00Z', 'options': 'dateCreated'}

CC: @mcarracedo

**Comment by fgalan** [comment]
We have a large batery of CPr test in cases/0787_cprs_full_functional. It would be a good idea to create a version of such .tests using NGSIv2 query/post operations in order to ensure that the NGSIv2 query/post functionality keeps working for CPrs registed using NGSIv1.

**Comment by kzangeli** [comment]
I was pretty sure that the service routines that issue the forwarding to CPrs (serviceRoutines/postUpdateContext and postQueryContext) looked at the API version and did not forward anything if API v2 ...  Perhaps this is broken?

However, we could of course support forwarding (in V1) even though the petitions are made with V2, just sending the forward in V1 and receiving the response of the forward also in V1 to finally respond to the client using V2 ...

So, two possible fixes to this problem.
First, let's investigate a little and estimate effort for the two options.

**Comment by fgalan** [comment]
Whatever the conclusion be, the doc at https://fiware-orion.readthedocs.io/en/develop/user/v1_v2_coexistence/index.html should include a paragraph regarding this explaining if it is advisable to use NGSIv2 query/udpates with CPRs registred using NGSIv1.

**Comment by kzangeli** [comment]
Some info on this after some testing:

First of all, forwarding on queries in NGSIv2 is **not** capped and it works just fine. The query is sent in NGSIv2 and its response comes in NGSIv2. The forwarding messages are all done in NGSIv1.

After some slight modification of the broker, I managed to make the same thing happen for Updates also, using the following request:

    PATCH /v2/entities/<eid>/attrs?type=<type>

Work to be done to include this change: copy 24 functests from `test/functionalTest/cases/0787_cprs_full_functional` and make them use NGSIv2 updates and queries. Then to document the whole thing, of course.

Time estimation for all this:  4 days

[ Simply capping forwards for V2 would require no modification in tests and much less documentation, if any. Time estimate: 1 day ]

**Comment by fgalan** [comment]
Implemented (for release/1.2.0) in PR #2243

**Comment by fgalan** [comment]
After PR #2243, what is still pending to cover:

After analyzing the spec, the following operations have not been already covered and probably they should:

  - GET /v2/entities (+ ?type=T1 + ?options=keyValues)
  - GET /v2/entities/E1?options=keyValues. Same operation without params and with ?type already covered.
  - GET /v2/entities/E1/attrs (+ ?type=T1 + ?options=keyValues)
  - PATCH /v2/entities/E1/attrs. Same operation with ?type and options=keyValues already covered.
  - GET /v2/entities/E1/attrs/A1. Same operation with ?type param already covered.
  - PUT /v2/entities/E1/attrs/A1 (+ ?type=T1).
  - GET /v2/entities/E1/attrs/A1/value (+ ?type=T1). We have decided to leave appart from #2193 the PUT case on the same op URL, but
    testing GET could make sense in the scope of #2193. Given that we have found with PUT that behaviour could be different depending
	on JSON or text, both alteratives should be covered.
  - POST /v2/op/update?options=keyValues

For all operations that accept ?options=keyValues, we can consider to cover also the ?options=values and ?options=unique modes, but probably that will be overhelming. Other opinions are welcome.

**Comment by fgalan** [comment]
Pending .test in PR #2271 (only to develop, as there isn't any change to code, so no need to merge into release/1.2.0).
