### ISSUE TITLE
Second mongoSubCacheItemInsert doesn't use complete HttpInfo

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2203]
We have two functions called mongoSubCacheItemInsert in mongoSubCache.cpp.
The first of them was modified to get the complete HttpInfo from mongo, during issue #2015.

Fixing a leak, I just stumbled upon the **second** mongoSubCacheItemInsert and that function only retrieves httpInfo.url from mongo.

This is clearly a 'bug', or at least something missing from #2015.
We need a new functest for #2015, to capture this bug and then to fix this possible bug.

**Comment by fgalan** [comment]
Fixed (maybe) in PR https://github.com/telefonicaid/fiware-orion/pull/2211

**Comment by fgalan** [comment]
.test to ensure that PR #2211 fixed the problem included in PR https://github.com/telefonicaid/fiware-orion/pull/2213
