### ISSUE TITLE
Excessive decimal digits in number values when substituted in custom payload

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2207]
Replacing attribute values in a Custom template

Excesive decimal digits in number values when substituded in custom payload template

if we try to replace a integer value (34), This is rounded to 6 decimal (34.000000). 

Whit this payload `The temperature is ${temperature} degrees` using `text/plain`. We get these answers for these values.
```
  The temperature is 34.123457 degrees   - (value is 34.12345678)
  The temperature is 34.000000 degrees   - (value is 34)
  The temperature is 34.400000 degrees   - (values is 34.4)
```

Any correction will penalize the performance.

**Comment by fgalan** [comment]
Very similar to https://github.com/telefonicaid/fiware-orion/issues/2176

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2410

**Comment by fgalan** [comment]
Please, @iariasleon close this if you find it fixed (after PR merge, of course ;)

**Comment by fgalan** [comment]
Until https://github.com/telefonicaid/fiware-orion/issues/2425 can be addressed, the right value for the first case would be:

```` 
The temperature is 34.12345700 degrees
```

**Comment by iariasleon** [comment]
```
    | attr value           |          payload                                  |
    |----------------------|---------------------------------------------------|
    | 34                   | The temperature is 34 degrees celsius             |
    | 33.3                 | The temperature is 33.3 degrees celsius           |
    | 34.54654654654654646 | The temperature is 34.5465 degrees celsius        | 
    | 3434534000000        | The temperature is 3.43453e+12 degrees celsius    |
```
