### ISSUE TITLE
asking value of non existent attr returns invalid error response

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2220]
http://{{host}}:1026/v2/entities/d7fafe27f0416d9ee89ebd2ab42baaddc746fa47/attrs/removeMe/value

`removeMe` does not exist

response is `404` but payload is

```json
{
  "error": "NotFound",
  "description": "The requested entity has not been found. Check type and id"
}
``` 

but entity does exist

**Comment by fgalan** [comment]
Fixed IN pr #2302
