### ISSUE TITLE
NGSI v2 : Allow type versioning

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2230]
Now that we are working on data model harmonization and exposing data APIs using NGSIv2 to developers it would be nice to have type versioning in NGSI v2. Type versioning allow developers to stick to a certain data model for the same conceptual entity. It is expected that data models could evolve and change so it would be nice to allow type versioning. 

so a type can be specified as it is type=`StreetParking` or with a type type=`StreetParking;version=3` . If no version is specified it could refer to the last version. Last version can be the unversioned one when a type has not been versioned.

**Comment by jmcanterafonseca** [comment]
other ways to solve this:

+ `version` attribute at entity level
+ Fiware-Datatype-Version header

...

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
