### ISSUE TITLE
improve error response when incorrect URL used

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2231]
Currently, an incorrect URL such as 

http://{{host}}/v2entities/?type=StreetParking 

results in

``` json
{
  "error": "BadRequest",
  "description": "service not found"
}
```

It would be nice to respond with a clearer description. 

"service not found. Check your URL as probably it is wrong. "

**Comment by fgalan** [comment]
This issue is not especifically related with NGISv2, so APIv2 label is removed. The issue keeps opened.

CC: @jmcanterafonseca

**Comment by rajeswar-NEC** [comment]
Hi  @jmcanterafonseca @fgalan 

I would like to work on this issue, please let me know if no one is working on this.

**Comment by fgalan** [comment]
> I would like to work on this issue, please let me know if no one is working on this.

Assigned. Thanks!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3691
