### ISSUE TITLE
UTC time format in log lines

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2232]
The log library right now outputs CEST times to the logfile.
Better would be to use UTC.

**Comment by kzangeli** [comment]
As it seems, the log library has always spitted out UTC, just that it then adds the name of the time-zone of the node it runs in.
Quick fix: remove the time-zone and hardcode the string UTC.

**Comment by fgalan** [comment]
Implemented (for develop) in PR https://github.com/telefonicaid/fiware-orion/pull/2233

**Comment by fgalan** [comment]
Implemented (for release/1.2.0) in PR https://github.com/telefonicaid/fiware-orion/pull/2233
