### ISSUE TITLE
Attribute type overwritten with 'none' on forwarding updates

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2240]
If we have an attribute A1: "value": "a1", "type": "string" in a context provider (CP1), and updates that attribute via the 'main broker' CB and forwarding, using options=keyValues, the type of the attribute is modified to "none" - its type is overwritten.

**Comment by fgalan** [comment]
From "Partial Representations" at NGSIv2 specification (http://telefonicaid.github.io/fiware-orion/api/v2/latest/):

> Attribute/metadata `type` may be omitted in requests. When omitted in attribute/metadata creation or in update operations, the default string value `none` is used for the type.

Thus, it seems that the described behaviour is as expected and this shouldn't be an issue.

**Comment by fgalan** [comment]
After dicussing with all stakeholders ( @dmoranj , @mcarracedo , @kzangeli ) the conclusion is that this is a expected functional behaviour in the NGSIv2 API. In the case attribute type is needed for sending commands to IOTA another update operation (of the rich set provided by NGSIv2) can be used.

Closing.
