### ISSUE TITLE
Involuntary change of attribute::type, in local operation

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2246]
Changing the value of an attribute, using the operation `PUT /v2/entities/<eid>/attrs/<attr-name>/value`, with the value as a JSON, the type of the attribute is modified to `none`.
The idea with that operation is to change **only** the value of the attribute, nothing else.

**Comment by fgalan** [comment]
Just to clarify to other readers... "in local operation" implies that no register (thus, no potential forwarding to CPr) is interfering.

**Comment by fgalan** [comment]
Just to remark that with values different to JSON (i.e. text/plain) it seems that the type is not changed. Actually, the examples in the README.md at https://github.com/telefonicaid/fiware-orion#api-overview illustrate that it working correctly in this case (using a number as example).

**Comment by fgalan** [comment]
Fixed in PR #2253 (release/1.2.0) and PR #2254 (develop)
