### ISSUE TITLE
Forwarding Updates overwrites the types of attributes

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2248]
When doing a `PUT /v2/entities/<eid>/attrs/<attrName>/value`, no attribute type is given and the default value of the attribute - `none` - is used in the forwarded request, and this makes the remote (in context provider) attribute change type to `none` - overwriting its correct type.

Must be tested both with JSON values and other types (String, Number, Bool, etc)

**Comment by fgalan** [comment]
Actualy fixed along with PR #2253 (release/1.2.0) and PR #2254 (develop), but CNR/test where added in PR #2258 (release/1.2.0) and PR #2259 (develop).
