### ISSUE TITLE
in the cookbook GeoJSON coordinates are wrong

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2249]
be careful! a GeoJSON coordinates is [longitude, latitude] and some examples in the cookbook are mistakenly coded. 

/cc @FiwareULPGC

**Comment by FiwareULPGC** [comment]
Thanks for reporting the issue.

We have identified that latitude and longitude are swapped in the operation **Georeferencing using GeoJSON**, we are fixing it along with a deep revision. 

During the revision we notice that the format used by Orion for representing geometries uses  `"latitude, longitude"` while GeoJSON uses `[longitude, latitude]`.

**Comment by fgalan** [comment]
Fixed by PR #2266
