### ISSUE TITLE
More detail on error responses per operation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2316]
Currently, specification uses this generic text in almost (or all?) operations:

> Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

A precise description (operation per operation) should be include in the spec .apib

**Comment by sabrine2020** [comment]
hello, 
Is there any deadline for updating the specicification.
Thanks!

**Comment by fgalan** [comment]
Currently we have an stable release candidate version RC-2016.05 (http://fiware.github.io/specifications/ngsiv2/stable/, have a look to "Status" section to understand what we mean by "release candidate version") but the deadline for the final release has not been yet decided.

It is difficult to commit to a date, as it depend on the pace we discuss and implement changes... However, we keep working on this (the work-on-proggress version is always available in the next link: http://fiware.github.io/specifications/ngsiv2/latest/).

If you are interested in news on NGSIv2 progress, I'd suggest you to subscribe to the NGSI discussion mailing list: https://lists.fiware.org/listinfo/fiware-ngsi.

**Comment by fgalan** [comment]
"Error Response" section has been re-written in PR https://github.com/telefonicaid/fiware-orion/pull/3226, providing more detail. At the end, it seems to be simlper to include the detail in a general section instead that operation by operation.

CC: @jmcanterafonseca
