### ISSUE TITLE
ngsi9 registrations (NGSIv1) doesn't fail when isPattern is set to TRUE

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2332]
id-patterns for registrations is not implemented in the broker in NGSIv1, but still no error is returned when a registration is done using isPattern=TRUE.
It hasn't always been like this. The implementation is prepared to return an error and it used to return an error.
Something must have changed and this has to be fixed.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2334
