### ISSUE TITLE
Errors traitement priority

### ISSUE THREAD

**Issue by sabrine2020** [telefonicaid/fiware-orion#2342]
Hello,

What is the priority between the errors proceeding?
For example if we have a BadRequest error (such us an invalid URL instead of /v2/entities we have /v2/eeeentities) and Content length required error (no payload in the POST request) in the same request which one shall be raised?
In general if we have more than one error in the request what is the order of errors treatment?

Thanks and best regards,
Sabrine.

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the FIWARE platform become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, could you ask your question using that platform, please?   Use the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

**Comment by fgalan** [comment]
Moved (in copy-paste way) to http://stackoverflow.com/questions/38347441/errors-traitement-priority.

**Comment by sabrine2020** [comment]
Thanks for your reply.
I am sorry I have not specifiied that it is about NGSI v2 specifications and not orion implementation. I was looking at this list : 
https://github.com/telefonicaid/fiware-orion/issues?q=is%3Aopen+is%3Aissue+milestone%3ANGSIv2SpecPending 
and when I opened the issue I thought it will be on it.
I need the clarification on the specification, I dont know how to relate this issue to NGSI v2 specification.

**Comment by fgalan** [comment]
Answered in a comment of the question on StackOverflow.
