### ISSUE TITLE
MIME Types requierement

### ISSUE THREAD

**Issue by sabrine2020** [telefonicaid/fiware-orion#2343]
Hello,

I have doubt concerning the MIME types requirement:
In the spec we have in the section MIME Types the following: "the response payloads other than application/json and test/plain are not accepted."

Although the MIME types requierement was only mentionned on the following operation:
*section: Attribut Value, operation: Get attribute value 
*section: Attribut Value, operation: Update attribut value 

So does the MIME Types requierement shall be taken into consideration in all requests having a payload response or only on the operations mentionned above.

Thanks and best regards,
Sabrine

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the FIWARE platform become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, could you ask your question using that platform, please?   Use the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

**Comment by fgalan** [comment]
Moved (copy-paste) to http://stackoverflow.com/questions/38347542/mime-types-requierement
