### ISSUE TITLE
NGSI v2 console examples

### ISSUE THREAD

**Issue by sabrine2020** [telefonicaid/fiware-orion#2344]
Hello,

Just for clarification,

Does the examples given on the spec console is part of NGSI specification or it is only given as an example of implementation?

Thanks and best regards,
Sabrine

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the FIWARE platform become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, could you ask your question using that platform, please?   Use the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

**Comment by fgalan** [comment]
In a second thougth, this is not probably the kind of programming question that SOF addressed, so I'll answer here.

I understand you refer to the console examples in the NGSIv2 specification at http://fiware.github.io/specifications/ngsiv2/stable. These examples *conform* with the NGSIv2 specification. In that sense, they are *part* of thes specification.

Having said that, note the existence of the http://fiware.github.io/specifications/ngsiv2/stable/cookbook/, which is focused on examples.
