### ISSUE TITLE
GET /admin/log operation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2352]
Implement the admin API to get current log level. This is:

```
GET /admin/log

{
   "level": "INFO"
}
```
In addition, it has to be documented at: https://fiware-orion.readthedocs.io/en/develop/admin/management_api/index.html#log-and-trace-levels

Note that level is returned in UPPPERCASE.

**Comment by fgalan** [comment]
Implemented in PR #2405

**Comment by fgalan** [comment]
Assigned to @iariasleon for final QA verification before closing it.

(If this cannot be checked withitn the 1.3.0 development cycle, it will be moved to QATestPending milestone)

**Comment by iariasleon** [comment]
LGTM
```
http code: 200 - OK
headers:
   date: Tue, 02 Aug 2016 10:06:50 GMT
   fiware-correlator: d4972040-5898-11e6-b287-005056a20feb
   connection: Keep-Alive
   content-type: application/json
   content-length: 17
payload: {"level":"DEBUG"}
```
