### ISSUE TITLE
Alling log format with other IoTP components

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2353]
In particular:

- Use the following field order in traces:

![2016-07-12 13_44_04-formato de logs plataforma iot - documentos de google](https://cloud.githubusercontent.com/assets/1534240/16765835/be41878a-4836-11e6-96c8-6ff67bea4cbb.png)

- Use `op=` instead of `function=`.

Documentation changes (mainly in logs.md) should be also done:

**Comment by fgalan** [comment]
In addition, X-Real-IP should have preference over X-Forwarded-From for the `from=` field.

**Comment by fgalan** [comment]
Implemented in PR #2400

**Comment by fgalan** [comment]
Assigned to @iariasleon for final QA verification before closing it.

(If this cannot be checked withitn the 1.3.0 development cycle, it will be moved to QATestPending milestone)

**Comment by iariasleon** [comment]
LGTM
```
time=2016-08-01T13:06:25.517Z | lvl=INFO | corr=c080bd9c-57e8-11e6-9bdd-005056a20feb | trans=1470056783-441-00000000027 | from=10.95.233.196 | srv=test_log_traces | subsrv=/test | comp=Orion | op=logMsg.h[1892]:lmTransactionEnd | msg=Transaction ended
```
