### ISSUE TITLE
pidfile '/var/log/contextBroker/contextBroker.pid' does not exist

### ISSUE THREAD

**Issue by MJCR** [telefonicaid/fiware-orion#2354]
I installed the new version of ContextBroker:

curl localhost:1026/version
>  {
>  "orion" : {
>  "version" : "1.2.1",
>  "uptime" : "0 d, 0 h, 7 m, 58 s",
>  "git_hash" : "af44fd1fbdbbfd28d79ef4f929e871e515b5452e",
>  "compile_time" : "Thu Jun 16 15:46:51 CEST 2016",
>  "compiled_by" : "fermin",
>  "compiled_in" : "centollo"
>  }
>  }

Then I installed the [watchdog](https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/admin/watchdog.md) and verifying the file /var/log/contextBroker/monitBROKER.log , I encounter the following error:

> error    : 'contextBroker' failed to start (exit status 1) -- /etc/init.d/contextBroker: Starting...

> contextBroker está parado
> Starting contextBroker...                         pidfile not found[FALLÓ]

> debug    : Socket test failed for [::1]:1026 -- HTTP error: Regular expression doesn't match: No match
> debug    : Socket test failed for [127.0.0.1]:1026 -- HTTP error: Regular expression doesn't match: No match
> error    : 'localhost' failed protocol test [HTTP] at [localhost]:1026/version [TCP/IP] -- HTTP error: Regular expression doesn't match: No match
> info     : 'localhost' exec: /etc/init.d/contextBroker
> debug    : 'monitBROKER.log' file exists
> debug    : 'monitBROKER.log' is a regular file or socket
> debug    : 'monitBROKER.log' size check succeeded [current size=19.5 kB]
> debug    : pidfile '/var/log/contextBroker/contextBroker.pid' does not exist
> error    : 'contextBroker' process is not running
> info     : 'contextBroker' trying to restart
> debug    : pidfile '/var/log/contextBroker/contextBroker.pid' does not exist
> debug    : pidfile '/var/log/contextBroker/contextBroker.pid' does not exist
> info     : 'contextBroker' start: /etc/init.d/contextBroker
> debug    : pidfile '/var/log/contextBroker/contextBroker.pid' does not exist
> debug    : Starting...
> contextBroker está parado
> Starting contextBroker...                         pidfile not found[FALLÓ]
> debug    : pidfile '/var/log/contextBroker/contextBroker.pid' does not exist

Preventing the operation of watchdog.

Could you please tell how to fix it?

**Comment by fgalan** [comment]
We provide support on Orion Context Broker through StackOverflow http://stackoverflow.com. This way, all the Q&A about the FIWARE platform become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, could you ask your question using that platform, please?   Use the “fiware-orion” tag (this is important: using this tag in your question is the only way our support staff realizes a new question on Orion has been posted). Any further interaction will be carried out through answers and comments to your question.

Thanks!

**Comment by fgalan** [comment]
I understand this was finally moved to http://stackoverflow.com/questions/38477148/pidfile-var-log-contextbroker-contextbroker-pid-does-not-exist. Thanks!

Thus, this issue is closeable.
