### ISSUE TITLE
More readable code for #223

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#237]
### Description
Look at a way to make the fix in #223 more readable.
It is about detecting vectors with '[' instead of '{' and especially about converting a plural name to a singular one.

**Effort: 5 man day**

**Comment by fgalan** [comment]
This is about refactoring a part of the code related with NGSIv1. Thus, it seems to invest time and effort in something that sooner or later will be deprecated. Closing.
