### ISSUE TITLE
Entity geo:json type rounds geometry coordinate precision

### ISSUE THREAD

**Issue by LeonanCarvalho** [telefonicaid/fiware-orion#2383]
I'm trying to create (and update) a context with geo:json attribute  type with precision of seven decimals but always it's rounded to 4 decimals somehow.

Operation: `POST http://localhost:1026/v2/entities/Device813/attrs?type=Devices&option=append`

Payload:  
```json
{
    "location": {
        "value": {
            "type": "Point",
            "coordinates": [
                -42.5124478,
                -22.3006726
            ]
        },
        "type": "geo:json"
    }
}
```

- Result:
```json
{
    "id": "Device813",
    "type": "Devices",
    "location": {
        "type": "geo:json",
        "value": {
            "type": "Point",
            "coordinates": [
                -42.5124,
                -22.3007
            ]
        },
        "metadata": {}
    }
}
```

> 1.2.1 (git version: af44fd1fbdbbfd28d79ef4f929e871e515b5452e)

**Comment by fgalan** [comment]
I'll have a look.

Which Orion version are you using, please? (i.e. output of the `contextBroker --version` command).

**Comment by LeonanCarvalho** [comment]
@fgalan 

> 1.2.1 (git version: af44fd1fbdbbfd28d79ef4f929e871e515b5452e)

**Comment by fgalan** [comment]
Just curiosity... How much is the error in physical longitude (e.g. meters) corresponding to a +-0.0001 error in GPS coordinates?

**Comment by LeonanCarvalho** [comment]
Well,  [The Wikipedia page Decimal Degrees has a table on Degree Precision vs. Length.](https://en.wikipedia.org/wiki/Decimal_degrees) .
Accordance with this page , the fourth decimal place is worth up to 11m, it can identify a parcel of land or a street.

**Comment by fgalan** [comment]
I have done some tests with Orion 1.2.1 to diagnose the problem.

First, entity creation request, using 7 decimals:

```
curl -v localhost:1026/v2/entities -s -S --header 'Accept: application/json' --header 'Content-Type: application/json' -d @- <<EOF
{
    "id": "E",
    "type": "T",
    "location": {
        "value": {
            "type": "Point",
            "coordinates": [
                -42.5124478,
                -22.3006726
            ]
        },
        "type": "geo:json"
    }
}
EOF
```

Next, check in the DB how this looks like:

```
> db.entities.findOne()
{
	"_id" : {
		"id" : "E",
		"type" : "T",
		"servicePath" : "/"
	},
	"attrNames" : [
		"location"
	],
	"attrs" : {
		"location" : {
			"type" : "geo:json",
			"creDate" : 1469787987,
			"modDate" : 1469787987,
			"value" : {
				"type" : "Point",
				"coordinates" : [
					-42.5124478,
					-22.3006726
				]
			}
		}
	},
	"creDate" : 1469787987,
	"modDate" : 1469787987,
	"location" : {
		"attrName" : "location",
		"coords" : {
			"type" : "Point",
			"coordinates" : [
				-42.5124478,
				-22.3006726
			]
		}
	}
}
```

Thus, **the creation request stores in DB with all decimals.**

Next, retrieve the entity:

```
curl localhost:1026/v2/entities/E
{"id":"E","type":"T","location":{"type":"geo:json","value":{"type":"Point","coordinates":[-42.5124,-22.3007]},"metadata":{}}}
```

Thus, **the problem could be in the retrieve entity logic**.

**Comment by fgalan** [comment]
Side-note: given the entity is correctly stored in DB, it is very probable (although I haven't checked) that geo-queries will behave correctly, i.e. without the up to 11 meters errors in entity locations.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2410

**Comment by fgalan** [comment]
Pending on @LeonanCarvalho validation. Please, @LeonanCarvalho close this issue if you find it solved. Thanks!

**Comment by fgalan** [comment]
After positive feedback from @LeonanCarvalho by email, this issue can be closed.

**Comment by LeonanCarvalho** [comment]
Just a note:

It's only keep next value after 8 decimals if it is not zero. For example:

-42.5124400904332206 -> -42.51244009
-42.5124400914332206 -> -42.512440091
-22.00000901- > -22.00000901
-22.000009001- > -22.000009

I think it related to #2425

For a real usage of GPS coords 8 decimals is good enough.

**Comment by fgalan** [comment]
Yes, it seems to be related. Although we have improve the float rendering mechanism, it seems that is not perfect enough (it would be perfect once #2425 would be implemented).

Thanks again for the feedback! :)
