### ISSUE TITLE
NGSI v2 specification: RequestEntityTooLarge 

### ISSUE THREAD

**Issue by sabrine2020** [telefonicaid/fiware-orion#2395]
Hello,

--This question is not a programming question, it is destinated to NGSI v2 specification.--

Can't find in the specification what does it mean that the request is too large.
I know that in Orion the maximum payload is 1MB but can't find this information in the specification.

Regards,
Sabrine

**Comment by fgalan** [comment]
Which size is considered "too large" should be something to be chose by the particular implementations. A given implementation (e.g. Orion) could use a 1MB limit but another implementation (using a different technology) could use 500KB or 2MB.

In other words, the NGSIv2 API should standarize the mechanism to report client that a given payload is too large, but the particular value is a matter of the implementation.

However, maybe this should be more clear in the specification, i.e. use the follwoing wording:

> RequestEntityTooLarge (413). Payload is too large (the specific limit to consider a payload too large depends on the particular implementation).

**Comment by fgalan** [comment]
Change in doc implemented in PR #2428
