### ISSUE TITLE
Geospatial types should be included in "Special Attribute Types" into FIWARE-NGSI v2 Specification

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2427]
Geospatial types should be included in **"Special Attribute Types"** into  [FIWARE-NGSI v2 Specification](http://telefonicaid.github.io/fiware-orion/api/v2/latest/). See `Geospatial properties of entities`.

**Comment by fgalan** [comment]
Documentation changes inmplemented in #2429
