### ISSUE TITLE
[NGSIv2] Attribute Type coherence checking : Provide uniform behaviour

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2444]
Now that we have well recognized attribute types (`Text`, `Number`, `DateTime`, ...), we need to decide what to do when an attribute value does not match the attribute type, for instance:

```
{ 
   "value": "hola, que tal?",
   "type": "DateTime"
}
```

should we raise an error? should we leave as it is? should we perform a type coercion operation if it is possible?, for instance 

from 

```
{
   "value": "4",
   "type": "Number"
}
```

to 

```
{
   "value": 4,
   "type": "Number"
}
```

**Comment by kzangeli** [comment]
My doubt here is, should we give total freedom to our users, or should we try to 'detect their errors'.
The broker can't know who its users are so it's a bit difficult to detect their errors.

For example, one user might want to use JSON strings AND the type Number, who are we to decide that the user cannot do that?

In other cases, like DateTime, it is pretty clear. DateTime is a predefined type that needs a corresponding date, in the format that the broker defines.
If the user doesn't like that, he'll have to use another name for the type, like "TimeDate", or whatever.

This last opinion could of course be also applied to "Number", "Boolean", etc ... :-)

One thing that I feel strongly about:

Never silently modify the users input. Better to return an error.
To avoid confusion.

**Comment by fgalan** [comment]
In my opinion, it is better to give total freedom to users. That way the API is more flexible and easy to use. If the use want to implement "strong typing" rules (whatever they are in his/her context) he/she has the possibility of doing so.

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
