### ISSUE TITLE
in PUT v2/entities/:id/attrs/:attr_name set type to "none" if it's not explicit  in the body

### ISSUE THREAD

**Issue by LeonanCarvalho** [telefonicaid/fiware-orion#2448]
In a case that I would like to update value and metadata, if I not set the attribute type in the request body it will update attribute type to "none" and I'll lose the information.

I'm not sure if it's should happens. 
This endpoint not allow PATCH requests.

OCB Info:
```
{
  "orion" : {
  "version" : "1.2.0-next",
  "uptime" : "9 d, 17 h, 27 m, 37 s",
  "git_hash" : "c1a224db08086751f05d471a8b52c0eaec15f3a5",
  "compile_time" : "Thu Aug 4 09:04:12 BRT 2016",
  "compiled_by" : "root"
}
}
```

**Comment by fgalan** [comment]
It may depend on the operation you are using. Could you provide the details in a new comment, please? I mean: verb + url + payload. Thanks!

**Comment by LeonanCarvalho** [comment]
There is no much details, it's just a request with Content-Type: application/json to update attribute value:

```
PUT http://localhost:1026/v2/entities/Room1/attrs/temperature?type=Room
Body:
{
"value": 20
}

```
In curl it will be something like that:

```
curl -X PUT -H "Fiware-Service: teste_1" -H "Content-Type: application/json" -d '{
"value": 20
}' "http://localhost:1026/v2/entities/Room1/attrs/temperature?type=Room"
```

**Comment by fgalan** [comment]
I think I have and answer for this behaviour but given that it could be of general interest, could you post the question in SOF so its answer may benefit the whole community, please? (As you did for http://stackoverflow.com/questions/24789244/orion-geo-located-query-returns-internal-server-error-when-use-longitude-values/25002552#25002552 time ago ;)

**Comment by LeonanCarvalho** [comment]
@fgalan 
Sure, 
Please make revisions as necessary to issue become clearer.
http://stackoverflow.com/questions/39176663/fiware-orion-context-broker-set-entity-type-to-none-if-its-not-explicit-in-th
Thank you

**Comment by fgalan** [comment]
Given that it has been moved to SOF (I'll try to answer there as soon as possible), this issue can be closed.
