### ISSUE TITLE
Delayed response to sensor when there are a massive amount of subscriptions

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/fiware-orion#245]
#ContextBroker   <version>0.10.0</version>

Checking the limits of the subscriptions ONCHANGE, has been noticed that the response time is increased according to the amount of subscriptions created. 

For instance when we have 5k subscriptions the response (to the monitored sensor) takes 8seconds, when we have 10k subs the response took 16s. 15k tooks 31seconds. 

It could show that the priority in the notification process first try to sent all the notifications instead of sent the response to the sensor and then send the notifications. This response time could cause timeouts in the sensor updates.

**Comment by fgalan** [comment]
A long time has passed, including important optimizations in regex subscriptions implementing a cache in Orion 0.24.0. Thus, this issue is somehow obsolete. It will be closed (if similar problems happen again, new issues will be created).
