### ISSUE TITLE
make simpler entity's attribute dates / metadata management

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2450]
to list entity attributes now we have two different options

options=dateCreated, dateModified , 

perhaps we can just have `options=entityDates` to simplify. Or even `options=entityMeta` to list all the attributes which are actually entity level metadata.

**Comment by fgalan** [comment]
Related with this, virtual attribute probably should use its own URI param. Not sure if overloading options with this is a good idea. E.g:

`?virtAttrs=dateCreate`.

My only concern if that this breaks the stable NGSIv2 spec. It is clear this is a case of "slight modifications in the functionality currently specified" but not sure if this the change is "completely justified" or a "matter of taste" (in the later case, it shouldn't be implemented).

**Comment by jmcanterafonseca** [comment]
yes, `extraAttrs` would be nice and would leave an extensible API

**Comment by fgalan** [comment]
This issue has probably be surpassed by #2455. Maybe it should be closed.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2590
