### ISSUE TITLE
update batch operation is underspecified

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2454]
the text should precisely describe what are the semantics of 'UPDATE', 'APPEND', 'STRICT_APPEND' and 'DELETE'

**Comment by jmcanterafonseca** [comment]
we need as well to document `REPLACE` action (intended to replace the content of an entity with another entity)

**Comment by fgalan** [comment]
Regarding REPLACE, is probably just a matter of documentation, i.e. current /v2/op/update implementation is supposed to support REPLACE.

**Comment by fgalan** [comment]
Currently in https://fiware.github.io/specifications/ngsiv2/latest/ se have:

![imagen](https://user-images.githubusercontent.com/1534240/41724823-b5d00d58-756e-11e8-8894-0b3b510be9cb.png)

Which I understand covers this issue. @jmcanterafonseca what do you think? Could it be closes or you miss something?

**Comment by jmcanterafonseca** [comment]
we can close
