### ISSUE TITLE
by default list dateCreated and dateModified for entities?

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2455]
I was wondering if we can save some syntax and API complexity if by default `dateCreated` and `dateModified` always appear. All in all the API user can use the `attrs` filter to list only the attributes she wants. It is a bit of an anomaly to have some attributes that are not listed by default, even if they are automatically generated by the implementation. Treating them as regular attributes would save us work.

**Comment by kzangeli** [comment]
For tiny systems this overhead might be a problem.
An important part of NGSIv2 is to minimize payload.
If we do this, we'd need some mechanism to avoid the rendering of these attributes.
However, as @jmcanterafonseca mentions, this mechanism already exists, as `attrs` ...

**Comment by fgalan** [comment]
Appart of the concern described by @kzangeli, there is a "coherence" reasons.

For example, I create an entity with atributes A and B. What should I expect if I retrieve the entity? Just A and B. However, I'm also getting two unwanted attributes named dateCreated and dateModified.

Thus, in my opinion dateCreated and dateModified (and any other potential similar "virtual" attribute that we could define in the future) should be rendered only if the user explicitly mandates so.

**Comment by jmcanterafonseca** [comment]
then, lets use this feature consistently and have an `extraAttrs` query param to allow to list extra (you named virtual) attributes provided by implementations.

**Comment by fgalan** [comment]
At the end it seems that we can solve this using "*" as alias for "all the regular (i.e. not reserved/virtual) attributes". In that case:

* If the user wants to get only dateCreated and filter out everything else then `attrs=dateCreated`.
* If the user wants to get only dateCreated along with all the other attributes `attrs=dateCreated,*`
* If the user wants to get only dateCreated and some other attribute (temperature) then `attrs=dateCreated,temperature`
* If the user wants to get only a given regular attribute `attrs=temperature`.

(Obviously, `attrs=*` hasn't any sense, as the result is the same than not usin `attrs=` at all, but it should be also supported for coherence).

This way, we don't need either `extraArgs` (as mentioned in https://github.com/telefonicaid/fiware-orion/issues/2455#issuecomment-244057906) or "overloading" `options` with virtual attribute names (however note that although this usage of `options` get removed from NGSIv2 spec documents, Orion  must continue to support it to keep backward compability).

(All the above regarding `attrs=` in synchronous queries applies in a similar way to `notification.attrs` in subscriptions. This issue must cover also the usage of `*` in that case).

**Comment by fgalan** [comment]
By the way, thi `*` for attrs is the same that has been recently proposed fo metadata (see https://github.com/telefonicaid/fiware-orion/pull/2518)

**Comment by jmcanterafonseca** [comment]
yes, using the '*' for meaning any attribute solves the issue with dateCreated and dateModified not requiring extra API syntax. so a big +1 to incorporate this to attributes as well.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2590
