### ISSUE TITLE
change in the value of an attribute vs attribute change 

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2456]
It is necessary to have in the API a mechanism that allows to differentiate between a change in the value of an attribute (in comparison with the previous attribute value) and a change in the attribute content, which might update the attribute value but could be the same value.

**Comment by jmcanterafonseca** [comment]
My proposal for fixing this is to always notify if conditions are met even if values didn't change. Additionally, I propose to add to the notification payload a field called reason, as:

```
"data": [],
"reason": [
   "temperature": {
       "old": { },
        "new": { }
    },
    "relativeHumidity": {
       "old": { },
       "new": { } 
    }
]
```

**Comment by kzangeli** [comment]
As always, I would prefer it to be the users to take these decisions, not the broker.
Some option to turn on/off  'always notify'.

About the new field, 'reason', seems like a good idea.
But, probably not for everybody. Most applications probably don't care about the old value, they only want to see the new one. So, again, good, but let's have users decide, not the broker.
[ Especially tiny devices that need small payloads. ]

Perhaps we could fit in "reason" somehow in customized notifications?

**Comment by jmcanterafonseca** [comment]
+1 for reason to be optional!

**Comment by fgalan** [comment]
This would be a new requirement for the NGSIv2 API and Orion reference implementation. Re-labing with "backlog" and moving to the NGSIv2SpecPending milestone.

**Comment by fgalan** [comment]
I understand that with the introduction of `previousValue` this issue is already covered. Thus, I'm closing it.
