### ISSUE TITLE
In the specification is not referenced the "legacy" format in the Subscriptions section

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2459]
In [FIWARE-NGSI v2 Specification](http://telefonicaid.github.io/fiware-orion/api/v2/latest)  is not referenced the "**legacy**" format in the Subscriptions section:

*"attrsFormat (optional): specifies how the entities are represented in notifications. Accepted values are normalized (default), keyValues or values. If attrsFormat takes any value different than those, an error is raised. See detail in "Notification Messages" section."*

Legacy format: if we create a subscription using NGSI v2, but with `attrsFromat`=`legacy`, the notification will be send in NGSI v1 format.

**Comment by fgalan** [comment]
It is ok not mentioning legacy format in the NGSIv2 as it is a legacy feature in Orion only. Note that a "pure" NGSIv2 implementation will not implement that legacy thing. Thus, it cannot be part of the NGSIv2 specification document.

However, note also that it is mentioned in the Orion specific implementation docuementation: https://fiware-orion.readthedocs.io/en/develop/user/ngsiv2_implementation_notes/index.html
