### ISSUE TITLE
if attribute not present in entity invalid JSON is rendered

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2461]
have a context broker with entities which all of them publish the same set of attributes except 1 which publishes an additional attribute. Ask for a listing of all entities indicating the attribute only published by one of the entities, for example

http://{{host}}:1026/v2/entities/?attrs=removeMe

then JSON response string is invalid and something like

````
{"id":"0115206c51f60b48b77e4c937835795c33bb953f","type":"Restaurant",},{"id":"34f036f9eef1f403c0ea66c55b8cdbace4b5f7a6","type":"Restaurant",},{"id":"92e960de796a8cc48ed7c784119f7d5628e31a6f","type":"Restaurant",},
````

**Comment by kzangeli** [comment]
Some more info is needed for this issue.
I just created a new functest, creating three entities:

    E1: A1=11,A2=12
    E2: A1=21,A2=22
    E3: A1=31,A2=32,A3=33

Then a GET the entities using:

    GET /v2/entities?attrs=A3

I get the correct response:

    HTTP/1.1 200 OK
    Content-Length: 125
    Content-Type: application/json
    Fiware-Correlator: REGEX([0-9a-f\-]{36})
    Date: REGEX(.*)

    [
      {
        "id": "E1",
        "type": "none"
      },
      {
        "id": "E2",
        "type": "none"
      },
      {
     	"A3": {
            "metadata": {},
            "type": "none",
            "value": 33
        },
        "id": "E3",
        "type": "none"
      }
    ]

**Comment by jmcanterafonseca** [comment]
and what do you get if 

you issue 

GET /v2/entities?attrs=A4 ??

**Comment by kzangeli** [comment]
Good question.
That seems to work too:

    [
      {
        "id": "E1",
        "type": "none"
      },
      {
        "id": "E2",
        "type": "none"
      },
      {
       "id": "E3",
        "type": "none"
      }
  ]

**Comment by jmcanterafonseca** [comment]
but what is your environment, are you working with an installed version clean?

I'm using 1.2.1 through Docker, please can QA try to reproduce?

**Comment by kzangeli** [comment]
I'm using 'develop' as of today

**Comment by jmcanterafonseca** [comment]
happens in 1.2.1 and 1.2.0 not in develop

**Comment by fgalan** [comment]
As far as I understand, this doesn't happend in develop, so it isn't any bug in the newest version of the code. Thus closing.
