### ISSUE TITLE
if attribute does not exist an error message is provided incorrectly

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2464]
using orion 1.2.1

http://{{host}}:1026/v2/entities/d7fafe27f0416d9ee89ebd2ab42baaddc746fa47?attrs=n

and n does not exist on the entity

````
{
  "error": "NotFound",
  "description": "The requested entity has not been found. Check type and id"
}
`````

The entity type and id should be returned and not an error message

```
{
  "id": "d7fafe27f0416d9ee89ebd2ab42baaddc746fa47",
   "type": "Restaurant"
}
```

**Comment by jmcanterafonseca** [comment]
this happens in 1.2.1 not in develop

**Comment by fgalan** [comment]
If develops is ok, then this issue should be closed.
