### ISSUE TITLE
gmock repository changed and Docker build fails

### ISSUE THREAD

**Issue by Miguelos** [telefonicaid/fiware-orion#2470]
Google Mock repository has been completely moved to [Github](https://github.com/google/googletest). 

Docker fails due to broken url: http://googlemock.googlecode.com/files/gmock-1.5.0.tar.bz2

This is related with the issue #1872 .

**Comment by fgalan** [comment]
I understand that the new location of the package is: 

https://github.com/google/googletest/archive/release-1.5.0.tar.gz

However, some testing needs to be done before.

This problem affect not only to docker but also:

* Documentation at https://fiware-orion.readthedocs.io/en/develop/admin/build_source/index.html needs to be updated
* FIWARE Lab image building script needs to be fixed (unsure)

**Comment by fgalan** [comment]
This query on repository files could help to find problematic places: https://github.com/telefonicaid/fiware-orion/search?utf8=%E2%9C%93&q=googlemock

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/2476 implements a temporal fix that makes docker build work again.

However, a definitive solution is needed. Any pull request contribution modiying CMakeFile.txt files and makefile to fix this in the way #1872 describes is highly welcomed.

**Comment by fgalan** [comment]
Finally, this has been workarounded puting the required packages in the public FIWARE web server. PR https://github.com/telefonicaid/fiware-orion/pull/2492 fixes URLs in all places in the repository.

Regarding Dockerfile, actually gmock is not needed to build the CB binary, so it has been removed.

FIWARE Lab image building script didn't need fix at the end, as the installation procedure it uses relies on yum and gmock library is no directly used.

Thus, I understand this issue could be closed. A definitive solution will come when #1872 gets implemented.
