### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jrluisrojo** [telefonicaid/fiware-orion#2521]
- Orion Context Broker Quick Start Guide (https://fiware-orion.readthedocs.io/en/develop/quick_start_guide/index.html) broken link to registration (https://account.lab.fiware.org/users/sign_up)

- Introduction (https://fiware-orion.readthedocs.io/en/develop/user/index.html) broken link to feedback on Github (https://gituhb.com/telefonicaid/fiware-orion.git)

**Comment by fgalan** [comment]
It will be fixed soon. Thanks for the feedback!

**Comment by jrluisrojo** [comment]
One more:

- FIWARE NGSI APIv2 Walkthrough Introduction (https://fiware-orion.readthedocs.io/en/develop/user/walkthrough_apiv2/index.html) broken link to presentation (http://bit.ly/fiware-orion)

**Comment by fgalan** [comment]
> FIWARE NGSI APIv2 Walkthrough Introduction (https://fiware-orion.readthedocs.io/en/develop/user/walkthrough_apiv2/index.html) broken link to presentation (http://bit.ly/fiware-orion)

However, http://bit.ly/fiware-orion is working (checked right now)... Maybe it has been a glitch?

**Comment by jrluisrojo** [comment]
It shows this
![screenshot from 2016-09-15 12-59-17](https://cloud.githubusercontent.com/assets/8008773/18546020/a7d8f76e-7b33-11e6-9f34-dd9e1179c887.png)

**Comment by fgalan** [comment]
Note the "Unable to locate the server; the server does not have a DNS entry"... it could be a local network problem.

**Comment by jrluisrojo** [comment]
Yes, in fact I was checking, I cannot access Slideshare dont know why, sorry for reporting to you :P

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2539. Thanks!
