### ISSUE TITLE
In dockerized version when accesing IP:PORT without arguments the container crashes

### ISSUE THREAD

**Issue by nkittsteiner** [telefonicaid/fiware-orion#2523]
Hello there. I've done some test using a OSX with Docker Machine 0.8.1 and when I do ```docker-compose up´´´ and then access vía cURL ex: SomeIP:1026 (without /version) , the container crashes.

**Comment by fgalan** [comment]
Has you tested in a host systems different to OSX? E.g. Windows or Linux. It would be great to know what happen in that cases.

**Comment by nkittsteiner** [comment]
I also tried in a CentOS virtual machine (v6) installing OCB as a service and performing a cURL. Same problem.

**Comment by fgalan** [comment]
Could you provide the following information regarding your CentOS environment, please?

* CentOS exact version, i.e. `cat  cat /etc/redhat-release `
* Kernel version, i.e. `uname -ra`
* Docker version, i.e. `docker --version`

**Comment by nkittsteiner** [comment]
In a VM wit VirtualBox I have the same behaviour . 

- CentOS release 6.8 (final)
- Linux fiware.inacap 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x8664 x86_64 GNU/Linux
- No docker, only a VM

**Comment by fgalan** [comment]
Seems to be a duplicated of https://github.com/telefonicaid/fiware-orion/pull/2528
