### ISSUE TITLE
System versus user attribute / metadata

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2535]
It would be nice to polish documentation terminology to distinguish between system and user metadata and attributes. From the top of my head we have the following system attributes:

`dateCreated` , `dateModified` 

and the following system metadata: 

`previousValue`, `actionType`

**Comment by kzangeli** [comment]
Builtin is a good word here also.

    System Metadata/Attributes   vs  Builtin Metadata/Attributes.

I'd vote for Builtin. Seems clearer to me

**Comment by kzangeli** [comment]
* means 'all normal attributes', excluding system/builtin attributes (or metadata).

Perhaps we'd like a wildcard for all builtins as well?

Perhaps even '*' should mean both normal and builtins, and another reserved word for the current meaning of '*' ?  [ I never really liked the "*", "dateCreated" ] ...

Hey, what if we copy the idea from the unix file system and name all system attrs beginning with '.'.

Compare:

    % ls *
    % ls .*

Like this, to see ALL attributes, you'd need [ "*", ".*" ] ...

Of course, users could create their own hidden attrs, unless we forbid the names to start with a dot.

**Comment by fgalan** [comment]
> I'd vote for Builtin. Seems clearer to me

+1

Used at the end in PR #3225, which closes the issue.
