### ISSUE TITLE
Metadata filtering in retrieve operation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2544]
Metadata filtering has been implemented for subscriptions (as part of #2507). This issue is about implementing the same feature for all retrieve operations when it make sense (I think that almost all), e.g.

```
GET /v2/entities/E/attrs?metadata=M1,M2
```

The .apib need to be modified to include the new parameter.

**Comment by kzangeli** [comment]
The requests are:

    GET /v2/entities
    GET /v2/entities/{entity-id}
    GET /v2/entities/{entity-id}/attrs
    GET /v2/entities/{entity-id}/attrs/{attr-name}

The request **POST /v2/op/query** has the attribute list in the payload already so, not interesting for the *metadata URI param*.

**Comment by fgalan** [comment]
Maybe we should expand POST /v2/op/query also with an attribute for metadata in the payload, to follow the same pattern. What do you think?

**Comment by fgalan** [comment]
Implemented by PR #2561
