### ISSUE TITLE
`lastNotification` --> `dateLastNotification`

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2551]
it would be clearer the notification payload if we rename `lastNotification` to `dateLastNotification`.

**Comment by fgalan** [comment]
`lastNotification` is part of RC 2016.05 stable. Taking into account:

> Slight modifications in the functionality currently specified by this document, as a consequence of ongoing discussions. Backward compatibility will be taken into account in this case, trying to minimize the impact on existing software implementations. In particular, only completely justified changes impacting backward compatibility will be allowed and "matter of taste" changes will not be allowed.

In my opinion, this is not a "completely justificied change" but a "matter of taste". So I think we shouldn't change.

**Comment by jmcanterafonseca** [comment]
well I think makes it clearer and auto-descriptive the meaning of the
attribute ... and backwards compatibility implementation will be trivial

2016-09-29 11:54 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by kzangeli** [comment]
While @jmcanterafonseca is right, @fgalan is even more so ...

We can't support both strings, that would be ridiculous, so, better not to change anything.

What we should do, perhaps, is to maintain a list of these 'matter of taste' changes to perhaps implement in the future, all at once ...

**Comment by fgalan** [comment]
I understand that at the end this is not going to change (as argued above) so this issues is being closed.

**Comment by jmcanterafonseca** [comment]
I would suggest to track this issue some way as @kzangeli  suggested so that we can reopen in the future this change request, for instance during standardisation processes.

**Comment by fgalan** [comment]
We cannot support both strings, as @kzangeli correctly explains. And changing the string (as changing any field name in general in any place of the API) to a new name will have a severe impact in backward compability with no gain.

**Comment by jmcanterafonseca** [comment]
well, we need to be open for changes if an standardisation process polishes
our APIs ...

just my two cents ...

2016-10-14 11:27 GMT+02:00 Fermín Galán Márquez <notifications@github.com>:
