### ISSUE TITLE
build-fiwarelab-image.sh installs obsolete Node.js version

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2556]
Currently build-fiwarelab-image.sh installs node in the following way:

```
# Install Node
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
sudo rpm -i epel-release-6-8.noarch.rpm
rm epel-release-6-8.noarch.rpm
sudo yum -y install nodejs npm
```

This ends with a Node version 0.10.x, which is deprecated.

The following installation procedure will install Node 4.5:

```
# Install Node
curl -sL https://rpm.nodesource.com/setup_4.x | bash -   # to configure yum repo
sudo yum -y install nodejs npm
```

Before implementing this change, make sure that Rush and PEP implementations will work with Node >= 4.5.

**Comment by dmoranj** [comment]
In the case of Rush the behavior with versions of Node.js above 0.10 has not been tested and, since there is no active support to that project, tests covering that scenario are not expected in the near future. With that in mind, I would suggest to stick to the 0.10 version for as long as possible.

**Comment by fgalan** [comment]
build-fiwarelab-image.sh was removed in PR https://github.com/telefonicaid/fiware-orion/pull/4030. Thus, this issue is no longer valid and it will be closed.
