### ISSUE TITLE
APIv2: Context Providers feature dropped ?

### ISSUE THREAD

**Issue by marcc-orange** [telefonicaid/fiware-orion#2558]
Is the [Context Providers](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/context_providers.md#registering-context-providers-and-request-forwarding) (registration of an _external_ entity with a `providingApplication`) being dropped for APIv2 ?

The [IoT Agent node library](https://github.com/telefonicaid/iotagent-node-lib) is currently using this feature in NGSIv1 to receive _commands_ through entity updates and answer to queries.

Is Orion/APIv2 going to support this or would you suggest to use a subscription/notify approach for such scenarios (even if does not cover 100% of the use-cases) ?

**Comment by marcc-orange** [comment]
Answering myself: the [latest spec](http://fiware.github.io/specifications/ngsiv2/latest/) has this... I was looking at the [stable spec](http://telefonicaid.github.io/fiware-orion/api/v2/stable/).

**Comment by fgalan** [comment]
You are right... NGIS9 functionality (CPrs, registries, etc.) has not been droped. It is in the "latest" version of the spec and will be eventually part of "stable" once we work on it.
