### ISSUE TITLE
Custom notifications: simplifying sending JSON requests

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2560]
Currently is complex to use JSON in custom notifications payload (i.e. `payload` field in `httpCustom`) as this field is string-based, so JSON has to be encoded. E.g. (for a current .test):

```
"payload": "{ %22A1%22: %22${A1}%22, %22A2%22: %22${A2}%22, %22A3%22: %22${A3}%22, %22step%22: %2203%22 }",
```

Thus, we could adopt a "dual-field" approach as the one in Perseo CEP in the HTTP action, which uses `template` for string-based coding and `json` for JSON based encoding. 

Only one of boths (`payload` or the new field `json`) must be used at a time (error returned in other case).

**Comment by fgalan** [comment]
Out of the scope of NGSIv2, althouth it is a good idea that could (potentially) be included in a later version of the API (v2.1) in a backward compatible way.

CC: @jmcanterafonseca

**Comment by danielvillalbamota** [comment]
This should consider the possibility of "null" values which should not include double quotes. As @fgalan says following the approach of casting in Perseo: 

```When using NGSI-v2 in the update actions, the value field perform [string substitution](https://github.com/telefonicaid/perseo-fe/blob/master/docs/API/plain_rules.md#string-substitution-syntax). If value is a String, Perseo will try cast value to number, boolean or null (without paying attention to the attribute type). If the casting fails then String is used. Boolean and None types.```

**Comment by fgalan** [comment]
PR #4157

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/4239 adds more tests and documentation fixes
