### ISSUE TITLE
Update to Figway page

### ISSUE THREAD

**Issue by cezane** [telefonicaid/fiware-orion#2566]
https://www.fiware.org/tag/figway/

The link about Orion Context Broker must be changed: "...Orion ContextBroker as described in this manual". The link placed in "this manual" is pointing to: https://forge.fi-ware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#FI-LAB_context_management_platform

**Comment by fgalan** [comment]
Strictly speaking, this is not part of this repository, but the FIWARE web site. I have moved the issue to the administrator of tha page, hopping they can fix it.

Thanks for the feedback

**Comment by fgalan** [comment]
Figway has its own repository at github (https://github.com/telefonicaid/fiware-figway) so I suggest you report the problems you have found there.
