### ISSUE TITLE
Unresponsive broker after error in mongo

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2571]
After sending an important amount of GET /v1/contextEntities, with URI param offset 0, 100, 200, etc upto 44000, the broker stops responding.
Research has shown that this is a semaphore problem.
The 'req' semaphore is taken and due to an exception the semaphore is not given back.
After this, the broker responds to GET /version and all other requests that do not need to take the 'req' semaphore. But, when trying top take the 'req' semaphore, the thread waits forever as the semaphore is eternally taken.

We need to **give** that semaphore.

**Comment by fgalan** [comment]
Fixed in:

- PR #2572 (master)
- PR #2574 (release/1.4.0)
- PR #2575 (release/1.2.0)
