### ISSUE TITLE
Is the Simple Location Format (Geo-location) supported in APIv1?

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2606]
Is it supported the Simple Location Format (Geo-location) en v1?

In another components (CEP, Cygnus, STH, etc) only receive notification in V1 format, but the V2 subscription has the "attrsFormat" field as `legacy` value and the notificaction are sent as V1 format. 

In V2 subscriptions are supported both geo-location format (GeoJSON and Simple Location Format), so both formats are notified. See [notifications](https://gist.github.com/iariasleon/0dd65d70c4a6e3e2ef758f1bc6325dc1) in both formats.

Second question if the response is No:
If Simple Location Format is not supported by v1 should be notified in v2 using legacy format?

**Comment by fgalan** [comment]
> Is it supported the Simple Location Format (Geo-location) en v1?

In the case of syncronous queries, you can use the Simple Location Format using queryContext scopes, in particular `"FIWARE::StringQuery"` and `"FIWARE::StringQuery::Metadata" see: https://fiware-orion.readthedocs.io/en/master/user/filtering/index.html#string-filters. The similar applies to "NGSIv2 style" geolocation, with the `"FIWARE::Location::NGSIv2"` scope (see last section in https://fiware-orion.readthedocs.io/en/master/user/geolocation/index.html).

Regarding subscriptions, no filtering or geolcation support is provides in NGSIv1 subscriptions. However, you can create the subscreiption using NGSIv2 with filter and geolocation and generate notifications using the NGSIv1 format, with the `legacy` feature you mention.

**Comment by iariasleon** [comment]
LGTM
