### ISSUE TITLE
DockerBUG: GIT_REV_ORION variable at Dockerfile links to develop instead of master

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-orion#2607]
https://github.com/telefonicaid/fiware-orion/blob/master/docker/Dockerfile#L6

develop is not used any more.
Dockerhub is  already creating orion images using develop

**Comment by AlvaroVega** [comment]
I'm not sure if we are dhttps://github.com/telefonicaid/fiware-orion/blob/master/docker/Dockerfile#L50
https://github.com/telefonicaid/fiware-orion/blob/master/docker/Dockerfile#L50

**Comment by cesarjorgemartinez** [comment]
Solved in https://github.com/telefonicaid/fiware-orion/pull/2608
