### ISSUE TITLE
log format: traces to stdout should have the same format as those to file

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-orion#2609]
`-fg` argument is used by docker image: 
https://github.com/telefonicaid/fiware-orion/blob/master/docker/Dockerfile#L115

log format, according with https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/logs.md#log-format,  by default should be: 

```
time=2014-07-18T16:39:06.265Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1217]:main | msg=Orion Context Broker is running
```

instead of

```
INFO@08:27:43  connectionOperations.cpp[79]: Database Operation Successful (query: {})
```

**Comment by iariasleon** [comment]
`-fg` parameter is to start the broker in Foreground. It is mainly used for debugging. I think dockerfile should not have this parameter.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/2645. Please @AlvaroVega have a look with newest docker version ("latest" tag) to check that now is ok with you.

**Comment by AlvaroVega** [comment]
@fgalan it works fine!
