### ISSUE TITLE
More code sharing during payload parse

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#261]
### Description
Right now, the XML and JSON parsing have a different set of functions for each request that needs parsing. For example, there is one function to treat the leaf 'entityId/id' in ngsi9 registerContextRequest and another function to treat 'entityId/id' in ngsi10 subscribeContextRequest. These functions are very similar. All 'entityId/id' functions could be 'merged' into one unique function (there are 18 copies :-().

Many many parse functions could be removed if we decide to go this way. Unit tests would be greatly simplified.

However, if we do this, the now extremely readable parsing functions would be a bit complex and the parsing time would increase.

Almost all of the auxiliar functions for XML could be used during JSON parsing; just a minor modification would be necessary.
Part one would be to unify its parameters.
Part two: create a 'parse' library with all unified functions, first the xxxInit, xxxRelease etc, after that the static entityIdId etc.
A few functions are different between xml and json but really not so many.

So, there is still no decision made whether we will implement this 'proposal'.

**Effort: 15 man day**

**Comment by fgalan** [comment]
This issues doesn't make sense in NGSIv2. Closing.
