### ISSUE TITLE
Threadpool is not used

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2622]
Some problems has been recently found with regards to threadpool notification mode:

In particular, the threadpool is not actually used, due to a dynamic linking fail, i.e. transient mode is used even if `-notificationMode threadpool:n:q` is used at CB startup time.

**Comment by fgalan** [comment]
Partial fix in PR https://github.com/telefonicaid/fiware-orion/pull/2623 for Orion 1.5.0. However, the work will continue for a definitive fix in 1.6.0.

**Comment by fgalan** [comment]
The partial fix has been also included in release/1.4.0 branch, in PR https://github.com/telefonicaid/fiware-orion/pull/2625

**Comment by iariasleon** [comment]
LGTM
Tested with 100 recurrent threads and only V2 requests

**Comment by fgalan** [comment]
Definitive fix (master branch) PR https://github.com/telefonicaid/fiware-orion/pull/2636

**Comment by fgalan** [comment]
Definitive fix (release/1.4.0) PR https://github.com/telefonicaid/fiware-orion/pull/2640
