### ISSUE TITLE
cache ERROR with soak test

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2626]
We have realized a soak test (NGSI v1 and NGSI V2 requests) with two days of duration getting this [CB statistics](https://gist.github.com/iariasleon/6b78ec3585c6339bee605bc000d46dbb).

This error message has occurred 78840 times:
```
time=2016-10-30T04:27:39.838Z | lvl=ERROR | corr=2c7d648a-9e59-11e6-aa0f-005056a21638 | trans=1477652268-315-00195231796 | from=10.95.168.143 | srv=soak_test_1_4_0_next | subsrv=/ | comp=Orion | op=MongoCommonUpdate.cpp[2095]:processSubscriptions | msg=Runtime Error (cached subscription '58155c692eae55c19051497c' for tenant 'soak_test_1_4_0_next' not found)
```

With a error rate by requests:
```
78840 / 225778157 * 100 = 0.0349 %
```

The CB config:
```
  version: 1.4.0_20161028113340
  git_hash: 4d8c0fc1fccfb3cb27b8e8b65b26d04ebb8189d7 
  BROKER_EXTRA_OPS="-reqMutexPolicy none -writeConcern 0 -notificationMode threadpool:60000:300 -statTiming -statSemWait -statCounters -statNotifQueue -multiservice -subCacheIval 5"
```

Aditional info: [soak report](https://docs.google.com/spreadsheets/d/18MiL9LkQZ2YC3QT5RC57CQXZxC4_ix21WGmJDKeHhPg/edit#gid=1690281399).

**Comment by fgalan** [comment]
This is the logic in processSubscriptions() corresponding to this trace.

```
      //
      // Saving lastNotificationTime and count for cached subscription
      //
      if (tSubP->cacheSubId != "")
      {
        cacheSemTake(__FUNCTION__, "update lastNotificationTime for cached subscription");

        CachedSubscription*  cSubP = subCacheItemLookup(tSubP->tenant.c_str(), tSubP->cacheSubId.c_str());

        if (cSubP != NULL)
        {
          cSubP->lastNotificationTime = rightNow;
          cSubP->count               += 1;

          LM_T(LmtSubCache, ("set lastNotificationTime to %lu and count to %lu for '%s'", cSubP->lastNotificationTime, cSubP->count, cSubP->subscriptionId));
        }
        else
        {
          LM_E(("Runtime Error (cached subscription '%s' for tenant '%s' not found)",
                tSubP->cacheSubId.c_str(), tSubP->tenant.c_str()));
        }

        cacheSemGive(__FUNCTION__, "update lastNotificationTime for cached subscription");
}
```

**Comment by fgalan** [comment]
Maybe this is due to some race condition, during the processing of an update context:

1. The addTriggeredSubscription function add the subscription to the triggered subscriptions list
2. Before processing the triggered subscriptions list, the subscription is deleted, so it is no longer searchable in the cache.
3. At processSubscription() time the subCacheItemLookup() is not able to recover the subscription, as actualy it no longer exists in the cache.

If the above is correct, then this is expected behaviour. However, it is difficult to know what actually happened during soak...

I'm suggest to keep this in quarentine and check again in the next soak.

**Comment by fgalan** [comment]
If the theory above is correct, the the bug is probably to log this a lvl=ERROR. It should be lvl=WARN, probably.

**Comment by iariasleon** [comment]
The same error is returned in 1.6.0
```
time=2016-12-01T17:53:40.902Z | lvl=ERROR | corr=1417f248-b7ef-11e6-8de3-005056a21638 | trans=1480605447-096-00016876538 | from=10.95.168.143 | srv=soak_test_1_5_0_next | subsrv=/ | comp=Orion | op=MongoCommonUpdate.cpp[2103]:processSubscriptions | msg=Runtime Error (cached subscription '58406393cab560c15aa826f4' for tenant 'soak_test_1_5_0_next' not found)
```
#### CB version
```
        "git_hash": "27998e256e26e76b8232f7b63b41b1d41589f994",
        "version": "1.5.0_20161201131833"

```

**Comment by fgalan** [comment]
After more than a year withoug activity, this quarentine issue can be closed.
