### ISSUE TITLE
q filtering not working

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2627]
using Orion 1.5.0 

given

curl -S -s --Header 'Fiware-Service:AirQuality' --header 'Fiware-Servicepath:/Spain/Barcelona' "http://130.206.83.68:1026/v2/entities/Barcelona-AirQualityObserved-08019050-2016-10-31T10:00:00?options=keyValues&attrs=measurand,stationCode,address" | python -mjson.tool

returns 

```
{
    "address": {
        "addressCountry": "ES",
        "addressLocality": "Barcelona",
        "streetAddress": "Parc de la Ciutadella, entrada del zool\u00f2gic"
    },
    "id": "Barcelona-AirQualityObserved-08019050-2016-10-31T10:00:00",
    "measurand": [
        "O3,19,GQ,Ozone",
        "NO,20,GQ,Nitrogen Monoxide",
        "NO2,40,GQ,Nitrogen Dioxide"
    ],
    "stationCode": "08019050",
    "type": "AirQualityObserved"
}
```

now the query 

curl --header 'Fiware-Service:AirQuality' --header 'Fiware-Servicepath:/Spain/Barcelona' "http://130.206.83.68:1026/v2/entities/?options=count,keyValues&attrs=measurand,stationCode,address&q=stationCode:08019050"

returns [] 

a bug seems to be present in filtering

**Comment by fgalan** [comment]
Try with

```
...&q=stationCode:'09019050'
```

or use the same filter but using a number instead of a string for `stationCode` attribute.

**Comment by jmcanterafonseca** [comment]
that works but should it be really necessary?

**Comment by fgalan** [comment]
From NGSIv2 spec (http://telefonicaid.github.io/fiware-orion/api/v2/stable/):

> The simple quote syntax can be also used to force string interpretation in filters, e.g. `q=tittle=='20'` will match string "20" but not number 20.

**Comment by jmcanterafonseca** [comment]
but my attribute is already a string so quote should not be needed in that
case

2016-10-31 16:40 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
After dicussing with @jmcanterafonseca at skype, we conclude this issue can be closed.
