### ISSUE TITLE
Little update in walkthrough_apiv2.md file

### ISSUE THREAD

**Issue by cezane** [telefonicaid/fiware-orion#2630]
Suggestion for "Starting accumulator" section:
"In case you are not running the Orion Context Broker on localhost, specify the IP with your host IP (i.e. the IP where your accumulator will be listening to port 1028)."

**Comment by jmcanterafonseca** [comment]
@cezane it would great if you can make a PR to solve the issue

thanks!

**Comment by fgalan** [comment]
Fixed by https://github.com/telefonicaid/fiware-orion/pull/2739
