### ISSUE TITLE
If no time is specified in date filters nothing is returned

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2631]
Example

curl -s -S --header 'fiware-service:AirQuality' --header 'fiware-servicepath:/Spain/Barcelona' http://130.206.83.68:1026/v2/entities/?q=dateObserved>2016-10-31

returns 0 records

however 

curl -s -S --header 'fiware-service:AirQuality' --header 'fiware-servicepath:/Spain/Barcelona' http://130.206.83.68:1026/v2/entities/?q=dateObserved>2016-10-31T0:0:0

returns a result set. 

We need to define clearly the behaviour when no time specified. Options are:

A/ Consider the whole day, so, in the example above, we will provide all the entities which have a date starting from 1st of November. 

B/ Default to, when no time is specified, 0 hours UTC of the corresponding day 

I tend to prefer option B/ as we will dealing seamlessly with use cases like `dateObserved>=2016-11-01` (all the records from the 1st of November on).

**Comment by fgalan** [comment]
I also prefer option B.

**Comment by fgalan** [comment]
Interesting link with a similar problem: http://stackoverflow.com/questions/26895428/how-do-i-parse-an-iso-8601-date-with-optional-milliseconds-to-a-struct-tm-in-c

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2660
