### ISSUE TITLE
[Bug] Context broker does not respect DateTime timezone

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2632]
how to reproduce:

create an entity with an attribute of type `DateTime` coded as an ISO8601 string, for instance

2016-11-01T19:00:00+01:00

Perform a query which lists the referred entity. The attribute value is now expressed incorrectly in UTC:

2016-11-01T19:00:00.00Z

**Comment by fgalan** [comment]
As far as I understand by https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators, the following timezone designators should be supported

```
<time>Z
<time>±hh:mm
<time>±hhmm
<time>±hh
```

But not strings like "UTC", "CET", "PDT", etc.

Is my interpretation correct?

**Comment by fgalan** [comment]
Interesting link with a similar problem: http://stackoverflow.com/questions/26895428/how-do-i-parse-an-iso-8601-date-with-optional-milliseconds-to-a-struct-tm-in-c

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2660
