### ISSUE TITLE
Fix rotate logs to avoid null bytes in logrotate

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-orion#2637]
Fix rotate logs to avoid null bytes in logrotate

**Comment by cesarjorgemartinez** [comment]
Fix in master: https://github.com/telefonicaid/fiware-orion/pull/2639

**Comment by fgalan** [comment]
Fix in release/1.4.0: PR https://github.com/telefonicaid/fiware-orion/pull/2641

**Comment by fgalan** [comment]
Fix in release/1.4.0: PR https://github.com/telefonicaid/fiware-orion/pull/2641

**Comment by cesarjorgemartinez** [comment]
Fix in release /1.4.0 https://github.com/telefonicaid/fiware-orion/pull/2641

**Comment by cesarjorgemartinez** [comment]
Fix in release/1.2.0: PR https://github.com/telefonicaid/fiware-orion/pull/2644
