### ISSUE TITLE
"ISO8601" as alias for "DateTime"

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2654]
In order to ease integration with IOTA versions using TimeInstant of type ISO8601, Orion should support this late string as an alias of DateTime.

This would be something to mention in the "NGSIv2 implementation notes" document, but it shouldn't be included as part of NGSIv2 specification (which should stick to "DateTime").

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/2775. @iariasleon pls have a look and close if you find it ok.

**Comment by iariasleon** [comment]
This issue will be passed to the `QATestPending` milestone.

Tested in [INT](https://pdihub.hi.inet/fiware/iotp-pqa/blob/master/tests/features/pepflows/024_pep2cbv2_iso8601support.feature) but still in component.

**Comment by fgalan** [comment]
Other times we have wait to the end of the sprint before moving QA pending issues of backlog type to QATestPending milestone. However, it you are sure at the present moment of that (because there is no time for testing it within the sprint or you plan to use the time to test other more important issues already in QATestPending) is also ok with me.

**Comment by iariasleon** [comment]
covered in E2E in features/pepflows/024_pep2cbv2_iso8601support.feature

**Comment by fgalan** [comment]
Issues in milestone QATestPendingE2ECovered are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeled with QATestPending label in the case things change and we need to recover it.
