### ISSUE TITLE
Support ISO8601 intervals

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/fiware-orion#2662]
Some of the harmonized datamodels (http://schema.fiware.org) use ISO8601 intervals. 

It would be great to support them (using the same type `DateTime`)

https://en.wikipedia.org/wiki/ISO_8601#Time_intervals

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
