### ISSUE TITLE
The REPLACE actionType for update batch operation is not included in the reference

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2672]
The `REPLACE` actionType for update batch operation (**v2/op/update**) is not included in the [fiware-ngsiv2-reference](http://telefonicaid.github.io/fiware-orion/api/v2/latest/).

Current info regarding actionType:
```
actionType, to specify the kind of update action to do: either APPEND, APPEND_STRICT, UPDATE, DELETE.
```

**Comment by crbrox** [comment]
Indeed, the section can be improved with a more detailed explanation of the batch update operations

**Comment by fgalan** [comment]
It should be explained that the batch is like spliting in N operations, each one addressed to one entity. The "mapping" depending to the actionType (UPDATE, REPLACE, APPEND, APPEND_STRICT, DELETE) to non-batch PATCH/PUT/POST on the entity resource URL can be also described to make it more clear.

**Comment by fgalan** [comment]
Fixed by https://github.com/telefonicaid/fiware-orion/pull/2739

**Comment by iariasleon** [comment]
LGTM
