### ISSUE TITLE
UpdateContext values for UpdateActionType

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#269]
### Description
Currently, the orion context broker accepts more strings that the XSD permits for UpdateActionType, namely:
- All uppercase
- All lowercase
- Capitalized.

The XSD only permits the uppercase version of { 'UPDATE', 'APPEND', 'DELETE' }.
The change in the code is very straightforward, the problem is that we have users out there that might be using lowercase of capitalized version of these keywords and for these users, a parse error would be returned.

Question number one:
What do we change, our code or the XSD ?

**Effort: 2 man day**

**Comment by fgalan** [comment]
NGSIv2 doesn't uses (yet) an XSD, so this issue doesn't make sense in such context.
