### ISSUE TITLE
Use "expression" instead of "scope" in POST /v2/op/query

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2706]
Currently spec (WIP version) and walthorught API v2 use `scope` for `POST /v2/op/query`:

```
POST /v2/op/query
{
  "entities": [
    {
      "idPattern": ".*",
      "type": "Room"
    }
  ],
  "scopes": [
    {
      "type": "FIWARE::StringQuery",
      "value": "temperature>40"
    },
    {
      "type" : "FIWARE::Location::NGSIv2",
      "value" : {
        "georel": [ "near", "maxDistance:20000" ],
        "geometry": "point",
        "coords": [ [40.31,-3.75] ]
      }
    }
  ]
}
```

However, `scope` is basically a legacy from NGSIv1 that we don't need in NGSIv2. A simpler alternative, fully aligned with how filters works in subscriptions (which is good, so userse doesn't need to learn two mechanism for the same thing) would be using `expression` in the following way:

```
POST /v2/op/query
{
  "entities": [
    {
      "idPattern": ".*",
      "type": "Room"
    }
  ],
  "expression": {
    "q": "temperature>40",
    "georel": "near;maxDistance:2000",
    "geometry": "point",
    "coords": "40.31,-3.75"
  }
}
```

**Comment by kzangeli** [comment]
Sounds like a good idea.
Only problem is about breaking the current spec ...

**Comment by jmcanterafonseca** [comment]
what about `filter`? but any of them better than `scope` ...

**Comment by fgalan** [comment]
Between `filter` and `expression` I prefer the second, as it is the one we already are using in subscriptions. Using `filter` here and `expressions` in subscription could be a bit crazy... and we cannot change `expressions` to `filter` in subscription (as that would break backward compatibility).

**Comment by fgalan** [comment]
> Only problem is about breaking the current spec ...

We took the caution of not mencioning anything about `scope` in the stable version of the spec (RC-2016.10, by the time being). In only apperas in the WIP version. Thus, no problem at all about spec breaking.

**Comment by jmcanterafonseca** [comment]
then a good reason for using `expression`

**Comment by jmcanterafonseca** [comment]
by the way are we going to allow to have multiple expressions, so that we can have a "union" functionality? because it seems currently multiple scopes are possible ... 

that would allow to support 'or' queries ... as well

**Comment by fgalan** [comment]
Could you provide an example, pls?

**Comment by jmcanterafonseca** [comment]
I want to query for rooms which capacity is greater than 20 or temperature is lower than 25. 

```
POST /v2/op/query
{
  "entities": [
    {
      "idPattern": ".*",
      "type": "Room"
    }
  ],
  "expression": [{
    "q": "temperature<25"
  },{
    "q": "capacity>=20"
  }]
}
```

**Comment by fgalan** [comment]
That could be solved with:

```
POST /v2/op/query
{
  "entities": [
    {
      "idPattern": ".*",
      "type": "Room"
    }
  ],
  "expression": {
    "q": "temperature<25;capacity>=20"
  }
}
```

Not sure if a slight improvement in flexibility justifies the complexity it would involve...

**Comment by jmcanterafonseca** [comment]
well we don't currently have 'or' query support and that's something that
sooner or later will be requested.

2016-11-24 17:56 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/3223
