### ISSUE TITLE
Many calls to gettid from the logMsg library

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2716]
I just found out that a call to gettid() has mistakedly been put inside a loop, causing many many calls (108 in the case of the broker) to gettid() which is a system call, for each log message.
This must be removed, as to only call gettid(), when needed.

Actually, it should be called only once and then saved as a thread variable.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2734
