### ISSUE TITLE
Payload files for XML

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#274]
### Description
We have a number of payload files for unit testing and all of those whose file name ends in 'valid.xml' are checked for XSD validity.
Now, we also have many files named '*.invalid.xml'.  Perhaps too many.

Especially, all files that compare with the output of the broker cannot be 'invalid'.
If an output file is invalid (and its unit test works), it means that the broker gives invalid XML responses. That is of course not very good.

All output payload files should be called ngsi*.*Response.*.valid.xml.

We should go through all the unit tests and make sure this is fulfilled and after that make sure that the XSD check works for all the output files.

As an additional exercise, all invalid input files should be tested for XSD validity and changed to 'valid' in case they pass the test.

Same thing for JSON once we have a validator tool for JSON.

**Effort: 10 man day**

**Comment by fgalan** [comment]
This doesn't make sense any longer for XML. Regarding 

> Same thing for JSON once we have a validator tool for JSON.

Since time ago, we heavily relay on functional tests (test harness) to test "extrernal" layers (rest, parsers, serviceRoutines, etc.).

In sum, this issue may be closed.
