### ISSUE TITLE
crash in subCacheItemLookup

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2740]
It seems the broker crashes in subCacheItemLookup.
This is not really possible, looking at the implementation.
We might have a memory corruption ... Let's hope not!!!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2743 (let's hope... ;)

**Comment by fgalan** [comment]
For the records: at the end, it wasn't memory corruption, but a problem with sem synchronization.
