### ISSUE TITLE
versions of used libs in --version

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2745]
It would be useful to add the versions of the library that the broker uses, in the output of --version.
Some day perhaps even to invent a new REST request:   `GET /admin/dependencies` or something similar.

**Comment by kzangeli** [comment]
Implemented in branch feature/2745_lib_versions, found in origin.
Not complete, as two of the libraries presented difficulties to give up their versions ...

**Comment by fgalan** [comment]
Helpful link to compare with master in just a click: https://github.com/telefonicaid/fiware-orion/compare/feature/2745_lib_versions

**Comment by Anjali-NEC** [comment]
Hi @kzangeli, @fgalan sir,

I have added new REST request: GET /admin/dependencies to get library dependencies in my PR #3737. If it is ok then please merge the PR in master branch.

**Comment by fgalan** [comment]
Library information is already provided in the GET /version operation (done in your other PR https://github.com/telefonicaid/fiware-orion/pull/3709, thanks! :). Thus, GET /admin/dependencies would be redundant.

I'd suggest to close PR #3737

(We should have closed this issue when we merge #3709, but we didn't realize about it. Sorry for the incoveniences)

**Comment by fgalan** [comment]
Overriden by issue #3681 (PR #3709). Closing.
