### ISSUE TITLE
Orion GUI?

### ISSUE THREAD

**Issue by cdupont** [telefonicaid/fiware-orion#2758]
Hello,
is there any plan to create a GUI for Orion?
My use case is for IoT, I would like to see a list of sensors for example.

**Comment by fgalan** [comment]
Currently there isn't any "official" Orion GUI publicly available ("official" in the sense of being developed/mantained by the same team that develops/mantains Orion itself) but there are some projects addressing this this topic.

Maybe the most salient one is Orion Explorer. You can have a look (even a demo) at https://github.com/VM9/fiware-orion-explorer.

CC: @LeonanCarvalho (as far as I know, involved in Orion Explorer development)

**Comment by LeonanCarvalho** [comment]
I had the same problem when started to develop with Orion.  So I had the idea to build a simple way to explore my available data on Orion CB. 

This is a second version, complete refactored to be more easy to developers colaborate and improve this tool. This new version works only as a local website, you can also publish as a website like our [demo](https://orionexplorer.vm9it.com) but nothing is stored on server side, all data (headers, ip, ports,etc) are stored on client site using [HTML5 Local Storage](http://www.w3schools.com/html/html5_webstorage.asp), it helps to keep privacity.

So far, the current functionalities already fit to our necessities. There are some improvements that we need to do like Entity C~~R~~UD, subscription management, and Map Explorer for geo-entities.
![image](https://cloud.githubusercontent.com/assets/3593706/21138729/902c37e2-c116-11e6-9d61-97d07ca368b9.png)


Only thing thats run on backend is the communication between the Orion Explorer and the Orion CB instance using our [Orion PHP Framework](https://github.com/VM9/orion-explorer-php-frame-work) as a client to consume NGSI calls, the current verssion is stable for NGSI v2 calls. So we can comunicate to a local or private network instance like http://localhost or http://10.0.1.123.

**Comment by fgalan** [comment]
I undertand that the answer provided by @LeonanCarvalho solves this issue, so I'm closing it. If I'm wrong, please tell about it @cdupont . Thanks!

**Comment by cdupont** [comment]
@fgalan yes we are investigating it.
