### ISSUE TITLE
broker doesn't respond if not able to read all of the incoming payload

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2761]
In a functest where we needed to check error for TOO BIG payload size, we got the problem that the broker is unable to respond with a 'nice error' when this occurs.

To provoke the problem, we simply lie to the broker, saying that the incoming payload is bigger than it really is:

    payload='{ "id": "E1", "type": "T1" }'
    orionCurl --url /v2/entities --payload "$payload" -H "Content-Length: 6000000"

In `connectionTreat`, an attempt to send a decent response is done, but due to a limitation in libmicrohttpd, the response isn't sent.

A question to be sent to the mailing list of MHD.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2774
