### ISSUE TITLE
hardcoded mhd connection timeout

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2762]
Currently (Dec 14 2016), the broker has no connection timeout for MHD, which means that clients will wait forever if the broker doesn't respond to their requests.

As of PR #2764, a connection timeout for MHD is added, but hardcoded to 6 seconds.
With this timeout, MHD closes the connection after the timeout expires and at least the clients now gets the 'connection closed', instead of waiting forever for a 'non-coming' response.

We might want to use a CLI option for this in the future.

[ 6 seconds is used as we use 5 seconds as default for 'internal timeouts', e.g. forwarding of messages ]

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2779

**Comment by kzangeli** [comment]
This seems to not have been such a good idea after all.
We need to be a little smarter, so that the connection is not closed while the broker is still working on the response.
Perhaps what we should do is to start measuring time after the broker has sent the response ans if the connection is still not closed after a few seconds, the broker closes it ...

First step would be to go back to 'as it was' => default value 0 for -reqTimeout

**Comment by kzangeli** [comment]
After making sure that the broker (really MHD does it) closes the connection regardless of what the client is doing after sending a response, it is enough to set back the MHD request timeout to infinite (zero).
We leave the CLI parameter -reqTimeout to give freedom for our users that use their own copy of the broker to play with this timeout, but the default value must be zero (wait forever).

**Comment by fgalan** [comment]
Re-fixed in PR https://github.com/telefonicaid/fiware-orion/pull/2851
