### ISSUE TITLE
Erroneous API v2 request receives API v1 response

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2765]
This functest:
 
    payload='"a string"'
    orionCurl --url /v2/entities --payload "$payload" --out "bad-mime-type"  --servicePath /error

receives this response:

    HTTP/1.1 406 Not Acceptable
    Content-Length: 145
    Content-Type: application/json
    Fiware-Correlator: REGEX([0-9a-f\-]{36})
    Date: REGEX(.*)

    {
        "orionError": {
            "code": "406",
            "details": "no acceptable mime-type in accept header",
            "reasonPhrase": "Not Acceptable"
        }
    }

Which is of type API v1.
This is a bug and it should be fixed.

**Comment by fgalan** [comment]
Fixed by PR #2789 

(I didn't plan to fix this, but I needed for https://github.com/telefonicaid/fiware-orion/issues/2760)
