### ISSUE TITLE
NGSI v1 could return ! 200 OK for errors

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2777]
Right now, in compliance with NGSI v1, requests with errors get a response of `200 OK` and the error code is part of the payload. In V2 this has changed completely and perhaps we should make V1 work like V2 for errors.

As an example of an error, take a Service-Path with a component that is too long:
```
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 140
< Content-Type: application/json
< Fiware-Correlator: d7750198-c692-11e6-bb35-a088b41ff018
< Date: Tue, 20 Dec 2016 09:01:06 GMT
< 
{
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "component-name too long in ServicePath"
  }
}
```

It would be better to see a `400 Bad Request` instead of the `200 OK`.

If we go through with this change, as the broker has worked like this since its very first release, we might want to invent a CLI parameter to override the change.

**Comment by fgalan** [comment]
NGSIv1 is deprecated (and this issue doesn't have an equivalency in NGSIv2 world). Thus, I'm closing.
