### ISSUE TITLE
More order in service path

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2786]
Right now, ConnectionInfo has three different fields to hold the service path:

1. ciP->httpHeaders.servicePath (The incoming value of the HTTP header)
2. ciP->servicePathV  (vector of service paths)
3. ciP->servicePath     (a copy of httpHeaders.servicePath that we don't really need)

This 'disaster' makes the broker more complex that it needs to be and it should be fixed.
Item 3 should be removed and item 1, that is destroyed when item 2 is created should not be destroyed.

Item 1 is needed for forwarding requests, *an untouched service path*, while for metrics we need item 2, to be specific, the first member of the vector: ciP->servicePathV[0].

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/2787
