### ISSUE TITLE
Use empty() for checking zero-length strings

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2791]
(Raised at https://github.com/telefonicaid/fiware-orion/pull/2790#discussion_r94306733)

As discussed in http://stackoverflow.com/questions/41425569/checking-for-empty-string-in-c-alternatives, `empty()` is the best way of checking for zero-length strings.

Thus:

1. Add that rule in the coding style guide
2. Search (e.g. grep) for all checkings with `""` and usages of `length()`, replacing with `empty()`

**Comment by kzangeli** [comment]
As the issue in SOF doesn't give much info, I did a quick test myself.
This is the source code:

```
#include <stdio.h>
#include <time.h>
#include <string>

// -----------------------------------------------------------------------------
//
// clock_difftime -
//
void clock_difftime(struct timespec* start, struct timespec* end, struct timespec* diff)
{
  diff->tv_sec  = end->tv_sec  - start->tv_sec;
  diff->tv_nsec = end->tv_nsec - start->tv_nsec;

  if (diff->tv_nsec < 0)
  {
    diff->tv_sec  -= 1;
    diff->tv_nsec += 1000000000;
  }
}

// -----------------------------------------------------------------------------
//
// main -
//
// Testing 5 ways of checking for empty string:
//
// 1. (s == "")
// 2. (s.length == 0)
// 3. (s.empty())
// 4. (s.c_str()[0] == 0)
// 5. (*cP == 0)
// 6. nothing - just setting 'b = true', which is 'extra' in each test case
//
int main(int argC, char* argV[])
{
  std::string      s  = "";
  char*            cP = (char*) "";
  struct timespec  startTime[6];
  struct timespec  endTime[6];
  struct timespec  diffTime[6];
  bool             b;
  const char*      testDescription[] =
    {
      "s == \"\"",
      "s.length == 0",
      "s.empty()",
      "s.c_str()[0] == 0",
      "*cP == 0",
      "b = true"
    };

  clock_gettime(CLOCK_REALTIME, &startTime[0]);
  b = (s == "");
  clock_gettime(CLOCK_REALTIME, &endTime[0]);

  clock_gettime(CLOCK_REALTIME, &startTime[1]);
  b = (s.length() == 0);
  clock_gettime(CLOCK_REALTIME, &endTime[1]);

  clock_gettime(CLOCK_REALTIME, &startTime[2]);
  b = (s.empty());
  clock_gettime(CLOCK_REALTIME, &endTime[2]);

  clock_gettime(CLOCK_REALTIME, &startTime[3]);
  b = (s.c_str()[0] == 0);
  clock_gettime(CLOCK_REALTIME, &endTime[3]);

  clock_gettime(CLOCK_REALTIME, &startTime[4]);
  b = (*cP == 0);
  clock_gettime(CLOCK_REALTIME, &endTime[4]);

  clock_gettime(CLOCK_REALTIME, &startTime[5]);
  b = true;
  clock_gettime(CLOCK_REALTIME, &endTime[5]);

  int ix;

  for (int ix = 0; ix < 6; ++ix)
  {
    struct timespec  diffTime;

    clock_difftime(&startTime[ix], &endTime[ix], &diffTime);
    printf("%d: %20s: %d nanosecs\n", ix, testDescription[ix], diffTime.tv_nsec);
  }

  return 0;
}
```

Here is how to compile/link it (assuming the source code file is called emptyStringTest.cpp):

```
g++ emptyStringTest.cpp -o emptyStringTest -lrt
```

And here are the results:
```
kz@hoppe:Cosas> emptyStringTest
0:              s == "": 2069 nanosecs
1:        s.length == 0: 1223 nanosecs
2:            s.empty(): 1118 nanosecs
3:    s.c_str()[0] == 0: 4029 nanosecs
4:             *cP == 0: 185 nanosecs
5:             b = true: 220 nanosecs
```

Case 2 is almost twice as fast as case 0 ...
Still, not sure this is enough to make the source code of orion less readable.
Remember, std::string comparison in 20 times slower than in C (strcmp), but we still use std::string comparisons as they are much easier to understand/read ...

**Comment by Anjali-NEC** [comment]
Hi @fgalan  @kzangeli sir,

I am working on this issue.
Below are the modifications i have done for all checkings with "" and usages of length().

1. (s == "") to s.empty()
2. (s.length == 0) to s.empty()
3. (s != "") to !s.empty()
4. (s.length != 0) to !s.empty()

Please confirm the above modifications.

Currently the testing of above modification is in progress once it is done i will raise the PR.

**Comment by Anjali-NEC** [comment]
Hi @fgalan @kzangeli sir,

I've fixed the issue. Please check PR #3685 and if it is ok then please merge the PR in master branch.
