### ISSUE TITLE
Overlogging metadata abscense in csub docs

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2796]
Orion shows this message in logs:

```
time=2016-11-28T15:43:51.854Z | lvl=ERROR | corr=8539470c-e112-42ab-8ff6-160062f172d8 | 
trans=1480318521-946-00000025921 | from=10.0.0.1 | srv=bar| subsrv=/foo | comp=Orion | 
op=safeMongo.cpp[297]:setStringVector | msg=Runtime Error (object field 'metadata' is 
missing in BSONObj <> from caller setNotification:141)
```

(The setNotification:141 and safeMongo.cpp:[297] line references work at 1.4.6 85ffcff5bdd506cbb6de1fd348bbbbf1293af65c)

This is not actually a lvl=ERROR trace. In fact, is shouldn't even appear in the logs. It is just that csub document lack of the metadata field (which is optional).

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2800

**Comment by fgalan** [comment]
Ready for QA Comp testing, @iariasleon

**Comment by iariasleon** [comment]
LGTM...Tested in CB version:
```
  "version" : "1.6.0-next",
  "git_hash" : "6232159b397f40aff97abd497b1e142a510e3e6d",
```
