### ISSUE TITLE
Possible strange behaviour on too long tenants

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2811]
Some strange behaviour has been detected, creating a subscription with a long Service/Subservice, via 'portal' without  getting any error but the subscription is later not found.

Also, in the traces of the broker, the following line is detected:

```
op=mongoSubCache.cpp[468]:mongoSubCacheRefresh | msg=Runtime Error (exception in nextSafe(): nextSafe(): { $err: "Invalid ns [orion-dddddddddddddddddddddddddddddddddddddddddddddddddd/.csubs]", code: 16256 } at mongoSubCacheRefresh:466 - query: {})
```

The trace line is seen once every ~60 seconds and all points to the refresh of the sub cache.
#### Note
this trace line may not have anything to do with the problem of not creating the subscription, but, an error is detected and a strange trace is there ... might not be a coincidence ...

**Comment by kzangeli** [comment]
Doing tests creating a subscription with a long name of tenant, I have seen that the broker accepts tenants of up to 50 chars in length, but after that some internal buffer of only 51 chars (50 + zero termination) is too small and the sub creation seems to fail, even though the broker responds with `200 OK`.

If the tenant is > 50 chars long, the broker correctly responds with an error.

Now, remember that the tenant name is added to the database name (which is "orion" by default but that can be changed with the `-db` CLI option).

Tenant 'T1' yields the database name "orion-T1".

So, that buffer of 51 chars needs to be larger:
```
50 + 1 + strlen(database-name)
```

Again, this may have nothing to do with the problem described in this issue (the error in the log file is a different one), but ...

This here is the error in the orion log file by the way:
```
... comp=Orion | op=string.cpp[631]:strToLower | msg=Runtime Error (cannot copy 52 bytes into a buffer of 51 bytes)
```

**Comment by fgalan** [comment]
PR solving the sub-issue at https://github.com/telefonicaid/fiware-orion/issues/2811#issuecomment-272406993: https://github.com/telefonicaid/fiware-orion/pull/2812

**Comment by fgalan** [comment]
After skype discussion, to be closed by @ jcanonav with about brief comment about the reason for doing so.

**Comment by jcanonav** [comment]
Check in tenant with 50 chars long. Buffer size has increased  to 61 ("db-prefix"+"-"+"tenant_name") and works rigth

**Comment by fgalan** [comment]
Closing on behalf @jcanonav
