### ISSUE TITLE
Forbidden Char checks in /v2/op/query and NOT in typePattern as URI param

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2819]
Searching for the usage of forbidden chars, we have found two obvious mistakes:

- POST /v2/op/query  doesn't use forbiddenChars at all
- ?typePattern=XXX as URI param suffers forbiddenChars which it should not

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2820
