### ISSUE TITLE
Subscriptions with https in the url field

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2844]
What seems to be a bug was found in a test installation.
A subscription with its 'callback' url being https, or http but with port 443 (default port for https), when triggering a notification for this subscription the broker dies with a SIGSEGV inside libcurl.
The stack trace in gdb indicates a problem with ssl/https

To be fixed first in the branch release/1.4 and then in master

**Comment by kzangeli** [comment]
After running some tests, we have discovered that the broker doesn't try to send anything over https.
If a subscription is created with `"http": { "url": "https://xxx/yyy" }`, then the broker will 'strip off the 's' in https and simply send a 'normal http notification'.

Seemed like an easy fix (avoid accepting https for subs/notifs) but ... now it seems we have already thought about this ... Not sure how to continue, just hope it's not a memory corruption!

**Comment by fgalan** [comment]
Fixec by PR https://github.com/telefonicaid/fiware-orion/pull/2852
