### ISSUE TITLE
in GET /admin/metrics using "reset=true" param, all services are not removed

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#2846]
in GET /admin/metrics using "reset=true" param, all services are not removed

With a previous  "metrics" request using "reset=true".

In the next metrics request, the latest services are initialized but not removed: 
See the "test_incomingtransactions_1" and the "test_incomingtransactions_2" services
```
{
    "services":{
        "default-service":{
            "subservs":{
                "root-subserv":{
                    "incomingTransactionResponseSize":2406,
                    "serviceTime":0.000479000,
                    "incomingTransactions":3
                }
            },
            "sum":{
                "incomingTransactionResponseSize":2406,
                "serviceTime":0.000479000,
                "incomingTransactions":3
            }
        },
        "test_incomingtransactions_1":{
            "subservs":{
            },
            "sum":{
            }
        },
        "test_incomingtransactions_2":{
            "subservs":{
            },
            "sum":{
            }
        }
    },
    "sum":{
        "subservs":{
            "root-subserv":{
                "incomingTransactionResponseSize":2406,
                "serviceTime":0.000479000,
                "incomingTransactions":3
            }
        },
        "sum":{
            "incomingTransactionResponseSize":2406,
            "serviceTime":0.000479000,
            "incomingTransactions":3
        }
    }

}
```

**Comment by kzangeli** [comment]
Probably at doing reset, the map is not cleared ...
Wait, deja-vu ... I think we do it like this on purpose, to save the time of creating again after reset ...
However, when presenting if size == 0, the field should not be included.

[ It's not *that* easy, as we'll need to look down two indirections to decide not to render ... ]

I agree it is a bug, no doubt

**Comment by iariasleon** [comment]
Tested the DELETE request and the behavior is the same  (the lastest services are initialized but not removed)

**Comment by fgalan** [comment]
Just keeping a pair of `needToPrint` boolean variables as you cross the double map would solve the problem.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2856. @iariasleon pls re-check.

**Comment by iariasleon** [comment]
LGTM

tested with GET ?reset=true and DELETE requests

```
{"services":{"default-service":{"subservs":{"root-subserv":{"serviceTime":0.000225000,"incomingTransactions":1}},"sum":{"serviceTime":0.000225000,"incomingTransactions":1}}},"sum":{"subservs":{"root-subserv":{"serviceTime":0.000225000,"incomingTransactions":1}},"sum":{"serviceTime":0.000225000,"incomingTransactions":1}}}
```
