### ISSUE TITLE
Check for service name too long at subCacheRefresh

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2848]
A recent fix (#2812) makes sure that the name of a tenant (service) cannot be more than 44 chars, depending on the prefix ('orion-' by default - 44 is for the default prefix).

However, prior to this fix, the broker did accept tenants of up to 50 chars and so, old databases may reside on the harddisk with a total database name of up to 61 chars (as max longitud for the prefix is 10, not including the hyphen).

subCacheRefresh asks `bool getOrionDatabases(std::vector<std::string>& dbs)` in mongoBackend/MongoGlobal.cpp for the list of databases and to complete the fix in #2812, we should probably add a check in getOrionDatabases for databases with long names (> 50 chars in total, prefix included).

**Comment by ArqamFarooqui110719** [comment]
Hi @kzangeli Sir, @fgalan Sir,
Is this issue still valid?

**Comment by fgalan** [comment]
Not sure...

The issue is pretty old (more than 7 years) but probably it's still valid.

Reading the old description, it seems to be a minor thing, so maybe it is easy to implement. I'd suggest you to create the pull request and let's see at that moment the suitability of the fix or not. What do you think?

**Comment by fgalan** [comment]
Yes, I think you are right.

Not sure what to do in the "false" case. Some options:

1. Log an error (LM_E macro) but still processing the database
2. Log an error (LM_E macro) and not process the database

I think we should go for option 2.

**Comment by fgalan** [comment]
As reference, longest case in production environment of `orion-xxxxx` database is 31 chars long, which involves service of 25 chars longs (`orion-` is 6 chars long).

**Comment by fgalan** [comment]
PR #4297
