### ISSUE TITLE
How to send command to a device through Orion Context broker

### ISSUE THREAD

**Issue by linhndk94** [telefonicaid/fiware-orion#2872]
Hi,

I tried to look for a solution to send a command to device through Orion Context broker but i could not seem to find a solution.

Is there a way to send a command to a device through Orion Context broker ?
If there is, please write an example of doing it or a link of instruction.
If there is not, please explain to me what functionality of Orion Context broker is or a link explaining,

Thank you!

**Comment by fgalan** [comment]
There are questions at SOF that deal with this topic:

* http://stackoverflow.com/questions/42231943/send-commands-to-context-broker-using-iotagent-ul
* http://stackoverflow.com/questions/42182084/checking-command-from-orion-to-iot-agent-in-fiware

Please check them. In the case they don't suffice your doubt, plase ask at StackOverflow, using the "fiware-orion" label.

Thanks!
