### ISSUE TITLE
Allow '=' in subscription callback

### ISSUE THREAD

**Issue by cdupont** [telefonicaid/fiware-orion#2878]
Currently the '=' sign is forbidden in Orion:
http://fiware-orion.readthedocs.io/en/1.5.0/user/forbidden_characters/index.html

But this prevents to make a subscription with a query string:
```
$ (curl broker.waziup.io/v1/subscribeContext -s -S --header 'Content-Type: application/json' \
--header 'Accept: application/json' --header 'Fiware-Service:waziup' --header 'Fiware-ServicePath:/TEST' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "SensingDevice",
            "isPattern": "false",
            "id": "Sensor1"
        }
    ],
    "attributes": [
        "temperature"
    ],
    "reference": "http://localhost/v1/sms/send?contact=0039&msg=Sensor1",
    "duration": "P1M",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "temperature"
            ]
        }
    ],
    "throttling": "PT1S"
}
EOF
```

The query string is used to pass parameters to the callback server (I don't see other ways to do it).

**Comment by fgalan** [comment]
This is a perfect question for StackOverflow (http://stackoverflow.com). Would you be so kind of posting the question there, using "fiware-orion" tag, please? Once you have done it, please add the link to the question as comment in this github issue, then close the githubs issue.

Thanks!

**Comment by cdupont** [comment]
@fgalan done: https://stackoverflow.com/questions/43282845/fiware-orion-use-query-string-in-subscription-payload
