### ISSUE TITLE
The variable paUsageProgName is not set to NULL after being freed

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2926]
In `paParse()` the buffer that the variable `paUsageProgName` references is freed but the variable is not set to NULL. It still points to the freed buffer and because of this it is used later. Only luck makes the whole thing work (more or less) but this must be fixed.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/2927
