### ISSUE TITLE
Wrong "max one service-path allowed for subscriptions" in NGSIv2 subscription operation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2948]
Attemping to subscribe using `POST /v2/subscriptions` with multiple service paths, the following error message is returned:

```
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 184
< Content-Type: application/json
< Fiware-Correlator: 3fab418c-5a4f-11e7-9af0-000c29173617
< Date: Mon, 26 Jun 2017 09:10:07 GMT
< 
{
  "subscribeError" : {
    "errorCode" : {
      "code" : "400",
      "reasonPhrase" : "Bad Request",
      "details" : "max one service-path allowed for subscriptions"
    }
  }
}
```

The semantics of the error are ok. However, the syntax is not correct for a NGSIv2 message:

1. Payload should be based on `error` and `description`.
2. Response code should be 400 and not 200.

**Comment by kzangeli** [comment]
My guess is that this error is detected before we detect that it is a APIv2 request.
The fix should be to simply delay the check of multiple service path until *after* the detection of API v1/v2.

**Comment by arigliano** [comment]
As I can see, both **postSubscriptions** (V2) and **postSubscribeContext** methods fill the **SubscribeError** struct. This provides only a render() method, printing out in both cases the same V1 response. Then a **toJson()** method that prints out V2 messages, should be implemented.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3034
