### ISSUE TITLE
Typo errors 

### ISSUE THREAD

**Issue by saurabhjangir** [telefonicaid/fiware-orion#2957]
There are few typo mistakes in page 
https://github.com/telefonicaid/fiware-orion/blob/master/README.md
Under Support section.
To be more specific, search for " thorough programmming ".

**Comment by fgalan** [comment]
Thanks for the feedback! We welcome any pull request with typo-fixing in the documentation, in the case you want to help us to improve the Orion Context Broker documentation :)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3052
