### ISSUE TITLE
Compile with ssl 

### ISSUE THREAD

**Issue by beho1der** [telefonicaid/fiware-orion#2962]
Good afternoon, compiling contexBroker from the source on centos7. For the introduction of everything was assembled and launched, but when I connect to the mongoDB 3.2 оn another host, get error:
`msg=Database Startup Error (authentication fails: db=admin, username='contextbroker', password='*****', expection='SCRAM-SHA-1 mechanism support not compiled into client library. (Some mechanisms require the driver be compiled with the flags --ssl or --use-sasl-client)')
`
I Issues i find that no ssl librarry, i recompile legacy-1.1.2 with parametr:
```
scons --use-sasl-client --ssl                                        
scons install --prefix=/usr/local --use-sasl-client --ssl
```
all good, but when i recompile contexbroker get error:
```
/usr/bin/ld: /usr/local/lib/libmongoclient.a(crypto_openssl.o): неопределённая ссылка на символ «EVP_DigestInit_ex@@libcrypto.so.10»
/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line
```
whats wrong ?

**Comment by fgalan** [comment]
It could be related with https://github.com/telefonicaid/fiware-orion/issues/1061

**Comment by beho1der** [comment]
I find it, but there is no solution. On this issue i take compiling mongodb legacy driver with ssl,but contexbroker don't compile with mongodb driver ssl,error text above.

**Comment by mathi123** [comment]
+1 same error here.

**Comment by mathi123** [comment]
Would it be possible to provide a docker file for a compilation with SSL flag?

**Comment by fgalan** [comment]
It would be great! Any volunteer out there? :)

**Comment by arigliano** [comment]
I'm here :) I could work both on this and #3243, since both are almost related to the same thing.

**Comment by mathi123** [comment]
Yes, the only difference is that this issue talks about mongo 3.2,
I would prefer mongo 3.4 😄 

But I'm guessing a fix will work for both!

**Comment by mathi123** [comment]
You can fix this by modifying the CMake file, see: https://github.com/telefonicaid/fiware-orion/pull/3244/commits/39dc2aaded07556f3a26766a7332fbfd8095cb7d.

**Comment by fgalan** [comment]
Thanks @mathi123 for your answer!

I understand that such modification solvese the issue and it could be closed. @beho1der could you confirm, pls? Thanks!

**Comment by beho1der** [comment]
I confimed
