### ISSUE TITLE
Orion chronological consultation

### ISSUE THREAD

**Issue by Maurocruzter** [telefonicaid/fiware-orion#2965]
Hello.

I would like to know if it is possible to consult older data using orion Context Broker.

EG: I have a temperature attribute and the value is constantly changing (4,5,9,10,30,2). In the examples and specification i had the impression it is only possible to consult the latest value (in this case 2).

Is this accurate? if so is the older data deleted?

**Comment by fgalan** [comment]
A SOF question with exactly the same text exits at https://stackoverflow.com/questions/45786520/orion-chronological-consultation. Thus, we are closing this issue and continue discussion there.
