### ISSUE TITLE
"Bodiless" HTTP Methods should not have body in notification message.

### ISSUE THREAD

**Issue by LeonanCarvalho** [telefonicaid/fiware-orion#2968]
I realized today that subscriptions with httpCustom object with custom  HTTP Verb/Method are content body although it's not necessary.

According with [rfc7231](https://tools.ietf.org/html/rfc7231),  some request must not send payload body like [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1) and [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) that "MUST NOT send a message body". 

> A payload within a GET request message has no defined semantics;
>    sending a payload body on a GET request might cause some existing
>    implementations to reject the request.

> The HEAD method is identical to GET except that the server MUST NOT
>    send a message body in the response

The GET request there is no definition of payload body semantics, also in these other requests :  [OPTIONS](https://tools.ietf.org/html/rfc7231#section-4.3.7) , [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5) and  [CONNECT](https://tools.ietf.org/html/rfc7231#section-4.3.6) are also sending payload body message.
In this case, may we can keep it optional if payload attribute is present. 
But the HEAD request must not send a body, this method could be used to send a simple live signal with fewer data just exchanging header data.

Subscription example
```

{
  "description": "Update descr",
  "status": "inactive",
  "subject": {
    "entities": [
      {
        "idPattern": ".*",
        "typePattern": ".*"
      }
    ],
    "condition": {
      "attrs": []
    }
  },
  "notification": {
    "exceptAttrs": [],
    "httpCustom": {
      "url": "http://example.com:81",
      "method": "HEAD",
      "qs": {
        "id": "${id}",
        "type": "${type}"
      },
      "headers": {
        "header_custom_value": "${value}"
      }
    }
  },
  "throttling": 10
}

```

**Comment by fgalan** [comment]
Could you include a subscription example (using httpCustom) that raises this situation, please?

**Comment by LeonanCarvalho** [comment]
The example has included, please check it out.

**Comment by LeonanCarvalho** [comment]
My suggestion is to change the Notifier to do not send  [httpInfo.payload](https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/ngsiNotify/Notifier.cpp#L228) when [Verb/Method](https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/ngsiNotify/Notifier.cpp#L205) is HEAD, GET,  OPTIONS , DELETE, CONNECT unless it was explicitly requested by subscription attribute payload, may be necessary to create a flag to send default payload(JSON) for this verbs.

**Comment by fgalan** [comment]
Some more question, to know precicessely the current behaviour...

Which payload is sent in the case of the custom notification you have posted (which doesn't have httpCustom.payload field)? Which Content-Lenght has the notification message in this case? Is the result the same if you use `httpCustom.payload: ""`?

**Comment by LeonanCarvalho** [comment]
The behavior is the same, using `httpCustom.payload: "" ` or omitting it from the subscription object. 

> Which payload is sent in the case of the custom notification you have posted (which doesn't have httpCustom.payload field)? 

The default JSON is sent,

> Which Content-Length header has the notification message in this case? Is the result the same if you use httpCustom.payload: ""?

 ```
            "User-Agent": "orion\/1.7.0-next libcurl\/7.29.0",
            "Host": "example.com:81",
            "fiware-service": "i_15",
            "Fiware-ServicePath": "\/",
            "Accept": "application\/json",
            "Content-length": "2074",
            "Content-type": "application\/json; charset=utf-8",
            "Fiware-Correlator": "7ea2dd6c-89db-11e7-8be4-0cc47a95bb68",
            "Ngsiv2-AttrsFormat": "normalized"
```

**Comment by fgalan** [comment]
I understand that the 2074 bytes correspond to a notification payload encoded in NGSIv2 normalized format, isn't it?

**Comment by LeonanCarvalho** [comment]
That's correct, 
I'm not sure if the server should transfer content body or not.  There are contraversions about that, take a look.  https://stackoverflow.com/questions/3854842/content-length-header-with-head-requests

To send a HEAD request with curl is common to set the option "NOBODY" to 1:
```
 curl_easy_setopt(ctx,CURLOPT_NOBODY ,1 );
```

> A long parameter set to 1 tells libcurl to not include the body-part in the output when doing what would otherwise be a download. **For HTTP(S), this makes libcurl do a HEAD request.** For most other protocols it means just not asking to transfer the body data.

**Comment by fgalan** [comment]
> [it] may be necessary to create a flag to send default payload(JSON) for this verbs.

Another maybe simpler posibility (as it does not need an additional flag) is to use `httpCustom.payload`in the following way:

```
"httpCustom": {
   ...
   "payload": null,
   ...
}
```

so `null` meaning that the notification must not include any payload.

**Comment by fgalan** [comment]
> If the implementation of "payload: null " do exactly the behavior of not include any payload it should be enough to supply this requisite.

Note that what I'm exposing is the intented way of working (i.e. upon implementation of this issue), not the how it works right now. However, it doesn't seem to be difficult to implement.

------------

Moreover, reviewing your cites from HTTP RFC:

> A payload within a GET request message has no defined semantics;
> sending a payload body on a GET request might cause some existing
> implementations to reject the request.

Thus, HTTP RFC doesn't forbbids using GET without payload. I agree it is a weird usage, but "within" the disclaimer that NGSIv2 spec (http://telefonicaid.github.io/fiware-orion/api/v2/stable) includes in the "Custom notifications" section: *It is the NGSIv2 client's responsability to ensure that after substitution, the notification is a correct HTTP message"*. Thus, default behaviour can be as it is now (always better in general to keep existings behaviours from backward compatibility point of view).

> The HEAD method is identical to GET except that the server MUST NOT
> send a message body in the response

Note that is the *response* to HEAD what must be without payload. It is the responsability of the HTTP server to which Orion sends the notification to honour this behaviour, out of the scope of Orion. From a *request* point of view, HEAD is exactly as GET as far as I understand, so it might have payload, as explained in the previous parragraph and there is no need of making null the default value for httpCustom.payload  instead of empty string in this case (having httpCustom.payload with a default depending of another paramerter, httpCustom.method in not in general a good idea... it make usage more complex).

**Comment by fgalan** [comment]
Similar issue #3272

**Comment by fgalan** [comment]
I understand PR https://github.com/telefonicaid/fiware-orion/issues/3272 (associated to issue #3272) solves this in Orion 3.1.0. As current documentation explains (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/ngsiv2_implementation_notes.md#custom-notifications-without-payload):

> If `payload` is set to `null` within `httpCustom` field in custom notifcations, then the notifications
associated to that subscription will not include any payload (i.e. content-length 0 notifications).
>
> Note this is not the same than using `payload` set to `""` or omitting the field. In that case,
the notification will be sent using the NGSIv2 normalized format.

Thus I understand we can close this issue. @LeonanCarvalho if I'm wrong just tell me :)
