### ISSUE TITLE
Invalid description in POST /op/query error response

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#2991]
Orion 1.8.0-next (31f6c9692eccc7a0d38ba639bc8c4301e40db74a)

Request (metadata is wrong, it should be an array):

```
POST /v2/op/query
{"entities": [{"idPattern": ".*", "typePattern": ".*"}], "metadata": "*", "attributes": []}
```

Response:

```
{"error":"BadRequest","description":"the field /attributes/ must be a JSON array"}
```

Bug: it should be `/metadata/` in the error message, not `/attribute/`

**Comment by arigliano** [comment]
@fgalan , I would like to start working on this issue, can you assign it?

**Comment by fgalan** [comment]
Of course! Done

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3056
