### ISSUE TITLE
Workaround: Delayed calls to release for ContextElementResponseVector objects

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#2994]
The premature releasing of `ContextElementResponseVector` objects in the function `processOnChangeConditionForSubscription()` provokes errors (detected by valgrind) when using these objects at creating the payload for notifications (using the objects after they've being freed).

A real solution is yet to be found, but we have a workaround, implemented in the PR #3009 .
This workaround consists in delaying the calls to release() of these ContextElementResponseVectors, saving pointers to the vectors and then at the end of the request (after the notification has been sent), all of them are released.

This issue is to _not forget about this workaround_, and that it would be better to find a real solution to the problem.

The implementation is in `mongoGlobal.cpp` (saving) and in `rest.cpp` (delayed release of the objects).

**IMPORTANT**
A thread variable holds a pointer to the ContextElementResponseVector objects to "delay-release", so the releasing function (`delayedReleaseExecute`) **must** be called from the _same thread_ as the "populating function" (`delayedReleaseAdd`).

**Comment by fgalan** [comment]
> ...at creating the payload for subscriptions

I guess you refer to

> ...at creating the payload for notifications

**Comment by kzangeli** [comment]
Of course,
Fixed, thanks!

**Comment by fgalan** [comment]
Initial notification functionality has been deprecated in Orion 3.1.0 (to be release soon). Thus, taking into account the rules at https://fiware-orion.readthedocs.io/en/master/deprecated/index.html

> Bugs or issues related with deprecated features and not affecting any other feature are not addressed (they are closed in github.com as soon as they are spotted).

This issue is being closed.
