### ISSUE TITLE
Subscription to Cygnus Agent not working

### ISSUE THREAD

**Issue by swtcwj** [telefonicaid/fiware-orion#2999]
Hi,

I´m running the docker Image for Orion CB with integrated MongoDB, Cygnus Agent is started in bash.
Both Tools are working fine from CLI (responses are as expected), but the subscription for Cygnus doesn´t seem to work, as there is 1 invalid attribute defined.
Also, when I add a new subscription to the same context, I get a 200 (OK) response with a new SubscriptionID (last digit increments on every call), but if I´m using "curl localhost:1026/v2/subscriptions" I only get 1 dataset returned (which is the first subscription I´ve created).
I couldn´t find any Information about the login credentials to the MongoDB as I tried to look up the subscriptions in the DB.

Can you provide any help on those issues?

Many thanks in advance,
Jordy

**Comment by fgalan** [comment]
This is a perfect question for StackOverflow (http://stackoverflow.com). Would you be so kind of posting the question there, using "fiware-orion" tag, please? Once you have done it, please add the link to the question as comment in this github issue, then close the githubs issue.

Thanks!

**Comment by fgalan** [comment]
@swtcwj not sure if you finally posted the question in StackOverflow (did you?). It has passed almost a year since last comment, so I understand this issue can be closed.
