### ISSUE TITLE
WARN about insecureNotifications mode

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3013]
It would be nice to print a WARN level log trace about insecure notification mode (-insecureNotif) is activated at Context Broker start up. This is a common trend in other software componentes when they communicate with HTTPS peers without valid certificate.

**Comment by saurabhjangir** [comment]
Hello, 
I am Saurabh and I would to be a part FIWARE community team and wants to contribute in FIWARE somehow. Any Help and direction would be highly Appreciable. Thank you :)

**Comment by fgalan** [comment]
Contributions to Orion repository are always welcome! :)

Please, have a look to the following pieces of documentation in order to be prepared to contribute to Orion code:

* FIWARE Development Guidelines https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Developer_Guidelines, with considerations that apply to all FIWARE project (Orion included).
* Orion specific Contribution Guidelines https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md, which are based on the former. Please, pay special attention to
     * The pull request protocol: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md#pull-request-protocol
     * Code style guidelines: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md#code-style-guidelines
* Orion Developers Manual https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/README.md, in order to understand how Orion is built.

Once you have read and assimilated these documents, you are in a good position to start contributing. Tell me so when you reach that point or ask doubts you could have during the process.

@jmcanterafonseca any other recommendation I may be missing, pls?

**Comment by jmcanterafonseca** [comment]
yes, if you want to be part of the Community the best thing is to contribute with source code, blog posts, documentation improvements. 

The main projects are Orion, Cygnus, IoT Agents, Wirecloud, Knowage, ...

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I am working on this issue. and i am suggesting the below warning message in case if contextBroker  is started in insecure mode.

"contextBroker is started in insecure mode (-insecureNotif)"

**Comment by fgalan** [comment]
> 
> 
> Hi @fgalan sir,
> 
> I am working on this issue. and i am suggesting the below warning message in case if contextBroker is started in insecure mode.
> 
> "contextBroker is started in insecure mode (-insecureNotif)"

Great! Just a minor suggestion to the text:

"contextBroker is started in insecure notifications mode (-insecureNotif)"

(to make clearer which aspect is insecure)

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/3677
