### ISSUE TITLE
Add support for accessing response headers when making CORS requests

### ISSUE THREAD

**Issue by aarranz** [telefonicaid/fiware-orion#3030]
Current CORS support provided in #501 (although it is still WIP) doesn't allow reading headers from context broker responses. This will affect clients trying to access not only to the `Fiware-Correlator` header that is always returned by orion, but also to other headers used in the different API endpoints (e.g. The `Fiware-Total-Count` header returned when using the `count` option).

So, currently, listing entities by making a `GET` request to `/v2/entities` is working (using CORS), but if the JavaScript client tries to access the `Fiware-correlator` header the following error is raised (using Chrome):

```
Refused to get unsafe header "Fiware-correlator"
```

As, said before, this error is also raised when trying to access the `Fiware-Total-Count` header when using `options=count`.

**Comment by McMutton** [comment]
Thanks for the suggestion @aarranz, although initially planned to be discussed, I had completely forgot about this. 

We can fix this by adding Access-Control-Exposed-Headers to the response with the header values the client would access.

**Comment by jmcanterafonseca** [comment]
yes, totally agree. We need this. @McMutton please ensure you fix that in the last CORS PR.

**Comment by fgalan** [comment]
@McMutton once PR https://github.com/telefonicaid/fiware-orion/pull/3032 is finished, do you plan continue with this issue? I think it would be great, in order to complete (as much as we now) the CORS issues for next Orion release (1.10.0).

**Comment by McMutton** [comment]
@fgalan Now that #3032 is merged, I will be working on this, you can assign the issue to me.

**Comment by fgalan** [comment]
Assigned. Thx!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3043

@aarranz as original issue reported, do you want to test before closing the issue, please? You can compile Orion from master branch or use "fiware/orion:latest" from docker hub.

**Comment by aarranz** [comment]
I will test ASAP, probably today :)

**Comment by aarranz** [comment]
I have make several tests creating, deleting and listing entities using services, servicepaths, correlators, ... and seems that everything is working as expected 👍.
