### ISSUE TITLE
Unhardwire HTTP headers strings

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3035]
Raised in https://github.com/telefonicaid/fiware-orion/pull/3032#issuecomment-343135450

Headers names are now being defined at `HttpHeaders.h`. Thus, we have to tasks to do:

1. Look for ocurrences of these headers in order to replace the literal string by the define constant
2. Look for other headers literals, to enrich the current set in `HttpHeaders.h`

The final goal is not having any literal string for HTTP headers (in the same way we don't have any literal for MongoDB field, all them defined at `dbConstants.h`).

**Comment by McMutton** [comment]
Hi @fgalan, I can work on this issue.

By the way, if there are any issues that you think I should prioritize over this one, please let me know.

**Comment by fgalan** [comment]
Let me have a look... but on the meanwhile, it would be great if you could fix this. I have assigned to you

Thanks!

**Comment by McMutton** [comment]
Hi @fgalan, sorry for the delay, I have just sent the PR for this.
