### ISSUE TITLE
OPTIONS /v2/registrations and OPTIONS /v2/registrations/<id>

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3049]
The two operations referred in the tittle of this issue has to be implemented in the same way OPTIONS on other recourses.

Instead of defining a new directory in cases/ for the test on this issue, just add new steps to the existing .test in cases/0501_cors/ along with the other OPTIONS steps.

**Comment by fgalan** [comment]
All the registration features share the same common base branch: **feature/ngsiv2_registrations**.

Thus, this issue should be implemented in a branch splited from feature/ngsiv2_regsitrations (instead of master), using the task/ prefix in the new branch name, and the PR done using feature/ngsiv2_registrations as base branch (instead of master).

feature/ngsiv2_registrations will be update regularly with master, to keep it as synced as possible and ease the final feature/ngsiv2_registrations -> master merge once all the NGSIv2 registrations management  functionality gets completed.

**Comment by McMutton** [comment]
@fgalan can you please assign this issue to me?

**Comment by fgalan** [comment]
@McMutton done!

Remember this time the PR's branch is taken from feature/ngsiv2_registrations, not master.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/3146
