### ISSUE TITLE
Add registrations_url to GET /v2

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3050]
Just add 

```
"registrations_url": "/v2/registrations"
```

to the output of GET /v2 operation

No need of new .test, just adjusted the existing ones on GET /v2

**Comment by fgalan** [comment]
All the registration features share the same common base branch: **feature/ngsiv2_registrations**.

Thus, this issue should be implemented in a branch splited from feature/ngsiv2_regsitrations (instead of master), using the task/ prefix in the new branch name, and the PR done using feature/ngsiv2_registrations as base branch (instead of master).

feature/ngsiv2_registrations will be update regularly with master, to keep it as synced as possible and ease the final feature/ngsiv2_registrations -> master merge once all the NGSIv2 registrations management  functionality gets completed.

**Comment by kzangeli** [comment]
Was about to implement this, but it is already implemented :-)
