### ISSUE TITLE
Service Path as part of the response in GET /v2/registration/XXX

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#3051]
Related to #3008 
The _Service Path_ of the reg is not mentioned in the example responses in #3008.
As the SP is an important part of the registration, we should probably include this piece of information in the response

**Comment by fgalan** [comment]
An important functional aspect to take into account is that entities _belongs to the service path_, while csubs and registrations _belong to the service_. In other words, an entity is charactericed by its id+sp while a csub/reg is only characterized by its id.

The service path associated to a csub/registration is _not_ the location of the csub/sregistarion in the service path tree. It is a description of the scope on which the csub/registration is evaluated. In other words, the service path of a registration _is not used to place the registration on the service path tree, is used to search entities on the tree_, which is different.

So, when a client does something like this:

```
GET /v2/registrations
Fiware-ServicePath: /A
```

The Fiware-ServicePath is interpreted as a selection criteria to retrieve all the registrations (in the service) which service *query path* (not location!) is exactly `/A`. It is not used to search on an hypoteticall tree of registrations becauese, as I mention before, that tree doesn't exist for registrations.

As far as I remember, this is the way in which it works in NGSIv1.

Thus, if we include Fiware-ServicePath in the response, it will be only to "echo" the request.  Not very useful, although it doesn't hurt, anyway...

**Comment by fgalan** [comment]
In fact, considering `GET /v2/registrations/<id>`, the `Fiware-ServicePath` is pretty useless... The id fully characterized the registration that hat to be retrieved.

**Comment by kzangeli** [comment]
The example above mentions
```
Fiware-ServicePath: /A
```
Sure, I agree.

Now, what about a GET with
```
Fiware-ServicePath: /#
```
?
Now it doesn't just echo the request, does it?

We will support this, right?

**Comment by fgalan** [comment]
Let's consider an example. In a given service (S1) you have registrations

id: a

- bcd, covering entities in SP: /A
- id: efgh, covering entities in SP: /B
- id: ijlk, covering entities in SP: /#

ering entities in SP: /#

Client request:

```
GET /v2/registrations/<id>
Fiware-Service: S
Fiware-ServicePath: /#
```

will return only registration whic id is ijlk

**Comment by kzangeli** [comment]
I am about to surrender on this issue (and open a new one :-)).
I didn't consider the fact that you can actually create a registration with a wildcard in the Service Path.

Something that in my (humble) opinion is a bit insane ...
Might be easier for clients, but ... that is not always a good thing ...
How can anybody possibly promise that 'everything that falls under service path /x/y (/x/y/#) is mine ?
What if some other player appears, three years later and offers more things under that /x/y service path?

The likelihood of this to happen is probably very low so ...
at least for now I hereby withdraw my concern for this issue.

**Comment by fgalan** [comment]
With regards to `/#`, it can be supported in registrations. In fact, they are quite common, a Let's consider the following example.

No local entity created in CB and the following registration is in place:

- SP: `/#`, entity: E, attributes: A1, provider: CP1

Let's consider the following queries:

- Query on E-A1 in SP /A: it triggers forward to CP1 (as /A matches /#)
- Query on E-A1 in SP /B: it triggers forward to CP1 (as /B matches /#)
- Query on E-A1 in SP /: it triggers forward to CP1 (as / matches /#)

I guess we should have some .test covering this for NGSIv1... probably

**Comment by fgalan** [comment]
I think the issue is valuable to harden the documentation in the manual about service path. Opining it while we can evaluate it and eventually merge text into documentation.

**Comment by fgalan** [comment]
After the new findings in https://github.com/apinf/fiware-orion/pull/13#discussion_r154753512, let's solve this issue as follows:

* Entities belongs to services *and* servicepaths, regs/subs belong *only* to the service. The servicepath in reg/sub doesn't denotes sense of belonging, but express the query associated to the reg/sub.
* Service path is ignored in GET /v2/registrations/id and GET /v2/subscriptions/id, as id fully qualified the reg/sub to get
* Service path is taken into account in GET /v2/registrations and GET /v2/subscriptions in order to narrow down the results to reg/subs that use *exactly* the servicepath provided in the request.

Documentation service_path.md will be updated consecuencly.

**Comment by fgalan** [comment]
Documentation added in PR https://github.com/telefonicaid/fiware-orion/pull/3062. Clossing issue.
