### ISSUE TITLE
contextBroker shuts down when passing inappropriate parameter in query context payload

### ISSUE THREAD

**Issue by saurabhjangir** [telefonicaid/fiware-orion#3055]
```
[root@localhost scripts]# (curl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json'  --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
 {
     "entities": [
         {
             "type": "Room",
             "isPattern": "false",
             "id": "Room1"
         }
     ],
     "attributes": [
         "temperature"
     ],
     "value": [
         "700"
     ]
 }
 EOF
**curl: (52) Empty reply from server**
**No JSON object could be decoded**
```

@fgalan : After this response, fiware orion stops. It is due to providing "value" parameter in payload.

**Comment by fgalan** [comment]
Thanks for the report! I have labeles this issue as bug, while we can have a closer look to it.

Hint: it is better to use code style for curl fragments instead of quote style. I have edited your report to show what I mean :)

**Comment by saurabhjangir** [comment]
Thanks @fgalan for your review and editing this report. For next time, I'll keep your suggestions i mind. :)

**Comment by saurabhjangir** [comment]
In my investigation, I found that in this case Orion is trying to write inside a NULL pointer at line number 175 in file "src/lib/parse/compoundValue.cpp". Here _parseDataP->lastContextAttribute_  is NULL.
Hope this might help.

**Comment by saurabhjangir** [comment]
PULL request #3064 is raised as the fix of this issue. 

Earlier we were getting a segmentation fault for the request mentioned in this issue.
REQUEST:
```
(curl localhost:1026/v1/queryContext -s -S --header 'Content-Type: application/json' \
    --header 'Accept: application/json' -d @- | python -mjson.tool) <<EOF
{
    "entities": [
        {
            "type": "Room",
            "isPattern": "false",
            "id": "Room1"
        }
    ],
    "attributes": [
        "temperature"
	],
	"value": [
		"23"
	]
} 
EOF
```
RESPONSE
```
curl: (52) Empty reply from server
No JSON object could be decoded
```

By making this change now we are getting appropriate error message shown below:

```
{
    "errorCode": {
        "code": "400",
        "details": "JSON Parse Error: unknown field: /value",
        "reasonPhrase": "Bad Request"
    }
}
```

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3064
