### ISSUE TITLE
JsonHelper::addNumber to be removed

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#3058]
The class `JsonHelper` contains a method called `addFloat` and instead of another method `addInt`, ghere is a method called `addNumber`, meant for integers.

This is pretty confusing as a Number is Either a Float or an Int ...

We should rename the `addNumber` method to `addInt`.

A start has been made in https://github.com/apinf/fiware-orion/pull/13, introducing `addInt`.

**Comment by fgalan** [comment]
JSON spec (https://www.json.org/) doesn't distinghuis among int or float, it always used number. Thus, I'd suggest to keep JsonHelper aligned with the spec and have two addNumber() functions, one for addNumber(int) and other for addNumber(float).

**Comment by kzangeli** [comment]
That is another way of getting the same result.
No probs, let's have two `addNumber` instead of `addInt/addFloat`.

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3252
