### ISSUE TITLE
notifications and authentication / authorisation

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/fiware-orion#3063]
It is unclear from the documentation what are the best practises for notification endpoints that requires  authentication / authorisation.
I suppose the only supported way is via a token / api key in the headers using httpCustom. Which may work only if there is no expiration on the token side.

Any additional hint?

**Comment by fgalan** [comment]
I think the answer I provide to this question at SOF may help https://stackoverflow.com/questions/40999447/fiware-how-to-integrate-keyrock-idm-wilma-pep-proxy-and-orion-context-broker

In particular, see section "Regarding notification API - Authentication & authorization"

**Comment by fgalan** [comment]
(Anyway, I think this kind of questions is better placed at SOF. Github issues are more related with reported issues/bug, feature requests, backlog items, etc. For general questions I think SOF is better)

**Comment by fgalan** [comment]
I understand the question has been solved, so I'm closing. Please, reopen the issue if I'm wrong.
