### ISSUE TITLE
MongoDB 3.6 support

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3070]
Most of the functional test works with MongoDB 3.6, but the following ones are failling:

```
----------- Failing tests ------------------
  o  0117_convop_using_standard_ops/getAttributesForEntityType.test
  o  0117_convop_using_standard_ops/getEntityTypes.test
  o  0519_ngsi10_entity_types_listing/contextEntityTypeAttributes.test
  o  0519_ngsi10_entity_types_listing/contextEntityTypes.test
  o  0676_servicepath_context_types/servicepath_context_types.test
  o  0676_servicepath_context_types/servicepath_default_context_types.test
  o  0676_servicepath_context_types/servicepath_sametype.test
  o  0676_servicepath_context_types/servicepath_specific_sametype.test
  o  0686_contextTypes_with_no_attributes/contextTypes_with_no_attributes.test
  o  0740_crash_with_json_object_for_attributes/json_object_format.test
  o  1027_get_all_entity_types/get_all_entity_types.test
  o  1028_get_entity_type/get_entity_type.test
  o  1170_get_types_values_option/get_types_values_option.test
  o  1170_get_types_values_option/get_types_values_option_with_empty_type_entities.test
  o  1170_get_types_values_option/get_types_values_option_with_null_and_empty_types.test
  o  1170_get_types_values_option/get_types_values_option_with_null_type_entities.test
  o  1367_time_measures/time_measure_stats.test
  o  2073_uri_param_to_disable_type_detail/uri_param_to_disable_type_detail.test
  o  2115_wrong_count_no_entity_types/wrong_count_no_entity_types.test
```

My guess is that something has changed at DB level that makes some usages incopatible. Log traces may help to find the causes. For instance, the log trace for 0117_convop_using_standard_ops/getAttributesForEntityType.test shows the following message:

```
time=2018-01-09T16:42:19.317Z | lvl=ERROR | corr=0edb97fc-f55c-11e7-be7c-000c29173617 | trans=1515516138-264-00000000001 | 
from=0.0.0.0 | srv=<default> | subsrv=<default> | comp=Orion | op=safeMongo.cpp[315]:getField | 
msg=Runtime Error (field 'result' is missing in BSONObj <{ ok: 0.0, errmsg: "The 'cursor' option is required, except for 
aggregate with the explain argument", code: 9, codeName: "FailedToParse" }> from caller mongoAttributesForEntityType:624)
```

Ideally, code should be adapted to work for both MongoDB 3.4 and MongoDB 3.6.

**Comment by LeonanCarvalho** [comment]
The request to `GET / v2/types`  results into an internal error that stops the Orion context broker process. When it's happening is necessary to manually delete the .pid file and start it again.

I think it's relative to test described by @fgalan  above:
> 0117_convop_using_standard_ops/getEntityTypes.test


I have a message on `/var/log/contextBroker/contextBroker-error.log`:

> terminate called after throwing an instance of 'mongo::MsgAssertionException'
>   what():  field not found, expected type 4

At the /var/log/contextBroker/contextBroker.log the result is the same described below

`lvl=ERROR | corr=6fb30ccc-15a0-11e8-bf2c-0cc47a95bb68 | trans=1519063925-897-00000000013 | from=127.0.0.1 | srv=i_5 | subsrv=<default> | comp=Orion | op=safeMongo.cpp[315]:getField | msg=Runtime Error (field 'result' is missing in BSONObj <{ ok: 0.0, errmsg: "The 'cursor' option is required, except for aggregate with the explain argument", code: 9, codeName: "FailedToParse" }> from caller mongoEntityTypes:394)`

As an addiction, this endpoint is used on the main call of [Orion context explorer](https://github.com/VM9/fiware-orion-explorer), on supported versions, build entity types list.

Since it's crash the process I recommend avoid use it if your MongoDB is the version 3.6

**Comment by fgalan** [comment]
From https://github.com/telefonicaid/fiware-orion/issues/3132#issuecomment-377217215

> But to tell you, I've tested with an empty database and mongo 3.6 (mean created from scratch), and the crash with request /v2/types is still there ! I copy @Grenouille06 for him to stay in the loop (with the problem of mongo cluster which require mongo 3.6

CC: @LeonanCarvalho

**Comment by mathi123** [comment]
From the documentation: https://docs.mongodb.com/manual/reference/command/aggregate/#dbcmd.aggregate it seems you need to add an extra parameter (cursor: {}) to the aggregation operation.

**Comment by fgalan** [comment]
Thanks for the feedback!

Aggretation operation is used in only 3 places of the code (all them within src/lib/mongoBackend/mongoQueryTypes.cpp, look for `BSON("aggregate"` string). Thus, maybe is a matter of adjusting only that three points adding the `cursor: {}` part.

Somebody should look into this. @arigliano could you have a look to this, pls? No need of new .test this time ;), only to check that the existing ones will pass ok with a MongoDB 3.6. instance.

**Comment by mathi123** [comment]
Yes, I have modified it here: #3248.

**Comment by fgalan** [comment]
I have looked to the changes proposed in #3248 and, although maybe they are not enough to support MongoDB 3.6, I think the addition of cursor to aggregation commands is a good idea. This is based on the  documentation for 3.4 (https://docs.mongodb.com/v3.4/reference/command/aggregate) which deprecates the usage of aggregation without cursor field.

(It seems that 3.6 documentation goes a step further, so this usage is not only deprecated but forbidden https://docs.mongodb.com/v3.6/reference/command/aggregate).

@mathi123 , let me do a final trial, based in your investigation and code change proposal.

**Comment by fgalan** [comment]
White regards to comment from #32348

> Currently [MongoDB 3.6 support] not possible without mongo driver update!

Initially I also thougth that way. Looking to the compatibility matrix at https://github.com/mongodb/mongo-cxx-driver/tree/legacy-1.1.3, MongoDB 3.6 lies out legacy driver reach.

However, I have doubts due to two facts:

1. Of the around ~1020 regression test only around 20 are failing. Curioslty, all them related with aggregation queries. If MongoDB 3.6 is not supported at all by the legacy driver, I have expected a massive fail (i.e. all the ~1020) tests failing.
2. According to the compatiblity matrix for legacy driver, it shouldn't be working for MongoDB 3.4. But it works. Full regression, all the ~1020 tests. No fails. Thus, in a similar fashion, why shouldn't it work for MongoDB 3.6?

**Comment by mathi123** [comment]
If only 1 regression test fails, due to a problem in the driver, that is enough to be a blocking factor. No change in Orion can ever fix that, and no new legacy driver is available that is 3.6 compatible.

**Comment by fgalan** [comment]
> If only 1 regression test fails, due to a problem in the driver, that is enough to be a blocking factor. No change in Orion can ever fix that, and no new legacy driver is available that is 3.6 compatible.

That would depend on whether addapting the queries which make that regression to fail solve the failing regression cases or not. I haven't checked yet that evidence.

**Comment by mathi123** [comment]
You can derive this from the last test run of #3248 on travis (raw logs):

```
Stack trace:

INFO@15:08:14  unitTest: Database Operation Successful (command: { aggregate: "entities", cursor: {}, pipeline: [ { $match: { _id.servicePath: { $in: [ /^/.*/, null ] } } }, { $project: { _id: 1, attrNames: 1 } }, { $project: { attrNames: { $cond: [ { $eq: [ "$attrNames", [] ] }, [ null ], "$attrNames" ] } } }, { $unwind: "$attrNames" }, { $group: { _id: "$_id.type", attrs: { $addToSet: "$attrNames" } } }, { $sort: { _id: 1 } } ] })

ERROR@15:08:14  unitTest: Runtime Error (field 'result' is missing in BSONObj <{ cursor: { id: 0, ns: "utest.entities", firstBatch: [ { _id: "Car", attrs: [ "colour", "pos", "fuel", "temp", "plate" ] }, { _id: "Lamp", attrs: [ "status", "battery" ] }, { _id: "Room", attrs: [ "humidity", "temp", "pos" ] } ] }, ok: 1.0 }> from caller mongoEntityTypes:398)

terminate called after throwing an instance of 'mongo::MsgAssertionException'

  what():  field not found, expected type 4

```

Meaning: mongo is now correctly called (with cursor), but the result cannot be parsed by the drive.

Do you agree on that conclusion? I'm always open to help getting it fixed, if its not to hard ;)

**Comment by fgalan** [comment]
As far as I understand, that "Runtime Error" message is not provided by the driver itself, but the Orion code interpreting the results of the query.

Based on your first attemp on PR #3248 I have tried this new PR https://github.com/telefonicaid/fiware-orion/pull/3251 which, in addition to adapting the call also adapt the way results are processed. I  have checked this PR works for MongoDB 3.4 (travis CI will re-check, glitches appart ;).

@mathi123 could you test if modifications in #3251 also work for MongoDB 3.6, pls?

**Comment by mathi123** [comment]
That looks promising :)

**Comment by mathi123** [comment]
Modifications are OK and backwards compatible.

PR to upgrade test framework: #3269 

After that I will modify the documentation.

**Comment by fgalan** [comment]
The three PRs were just merged. MongoDB 3.6 support has been consolidated in master branch. Closing issue. Thanks to everybody! :)

**Comment by agaldemas** [comment]
Hi, 
Nice news, I've just tested latest version of Orion and Mongo 3.6.8, and now request "/v2/types" doesn't crash Orion.
Well done !
thanks to everybody
I copy @grenouille06
