### ISSUE TITLE
centos6:  cat: /var/log/contextBroker/contextBroker.pid: No such file or directory

### ISSUE THREAD

**Issue by anaselli** [telefonicaid/fiware-orion#309]
I stopped context broker and dropped the database following the instructions here:
https://forge.fi-ware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_Installation_and_Administration_Guide#Delete_complete_database

when i restarted the service i got:
service contextBroker start
Starting contextBroker...                         cat: /var/log/contextBroker/contextBroker.pid: No such file or directory
Fail
but:
ps -edlaf | grep orion
1 S orion     3355     1  0  80   0 - 32515 hrtime 11:03 ?        00:00:00 /usr/bin/contextBroker -port 1026 -logDir /var/log/contextBroker -pidpath /var/log/contextBroker/contextBroker.pid -dbhost localhost -db orion
0 S root      3366  2384  0  80   0 - 25815 pipe_w 11:05 pts/0    00:00:00 grep orion

As an additional note, I'm not sure it's a problem or not, the orion db in mongo is created without any collections

**Effort: 3 man day**

**Comment by fgalan** [comment]
The cat error message output is no longer printed after the fix in PR https://github.com/telefonicaid/fiware-orion/pull/1270
