### ISSUE TITLE
Subscription types

### ISSUE THREAD

**Issue by cdupont** [telefonicaid/fiware-orion#3097]
Hi guys,
we use Orion to register subscriptions.
There are two kinds of subscriptions:
- user subscriptions: they are created by the user using our GUI.
- internal subscriptions: they are used by the system for communication between the components.

The problem is to distinguish the two, in order to present the user with only user-oriented subscriptions.
Which field of the subscriptions can I use? It would be nice to have a field "type", for instance.

**Comment by fgalan** [comment]
This is not actually an issue but a question about Orion functionality, so I think is should be better to post it in StackOverflow.

Could you do so, please? Use the "fiware-orion" tag in your question. Once done please add the link to the question as comment to this issue, then close the issue.

Thanks!

**Comment by cdupont** [comment]
Done here: https://stackoverflow.com/questions/48683736/fiware-orion-filter-subscriptions
