### ISSUE TITLE
NGSIv1 autocast for numbers, datetime and booleans

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3112]
Due to parsing technology, NGSIv1 is limited when processing attributes that represent non-string types (e.g. numbers), as they are always string-fied. This issues describes a functionality to impove that.

Orion Context Broker will interpret the following attribute types in NGSIv1 create/update operations:

* "Quantity" (*)
* "DateTime" (or "ISO8601", which is a valid alias see https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/user/ngsiv2_implementation_notes.md#datetime-support)
* "Boolean"

(*) To be aligned with NGSIv2 types, this should be "Number" better than "Quanity". However, most of the implementation that would benefit from this functionality use "Quantity". Maybe we could take into account both "Number" and "Quantity" (as we do with "DateTime" and "ISO8601").

Different cases:

* At attribute creation time, if the attribute type _in the request_ is one of the above, a casting to the right type is done before inserting the attribute at DB.
* At attribute modification time, involving such modification _both attribute value and type_, if the attribute type _in the request_ is one of the above, a casting to the right type is done before inserting the attribute at DB.
* At attribute modification time, involving such modification _only attribute value,_ if the attribute type _in the DB_ is one of the above, a casting to the right type is done before inserting the attribute at DB.

If cast fails, ~~then a 400 Bad Request error should be returned~~ then the attribute is stored as string (in order to prevent malfunction on existing clients using the above type literal in a different way).

This only applies to NGSiv1 create/update operations. NGSIv2 functionality remaing unaltered.

This functionality will be activable by CLI with `-ngsiv1autoCast` parameter to ensure backward compatibility.

**Comment by mrutid** [comment]
LGTM

**Comment by kzangeli** [comment]
+1

**Comment by kzangeli** [comment]
About "if cast fails", remember that `atoi("12XXX")` returns 12, which is probably not what we want here.

We have a function `str2double()` in `lib/common/string.cpp` that fixes this problem, but for floats, not for integers. Hopefully the function can be used to steal ideas, at least ...

**Comment by fgalan** [comment]
If `endptr` points to != 0, then it is not an integer and there is some rubbish at the end.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/3116 (for master)
