### ISSUE TITLE
terminate called after throwing an instance of 'mongo::MsgAssertionException'

### ISSUE THREAD

**Issue by LeonanCarvalho** [telefonicaid/fiware-orion#3113]
I'm deploying an update from 1.8.0 to 1.10.0 and it's crashes when receiving a request to get an entity.

I also used the bleeding edge(master) and the problem persists.

I do not have any more information to provide(I guess) than these logs:
/var/log/contextBroker/contextBroker-error.log
```
terminate called after throwing an instance of 'mongo::MsgAssertionException'
  what():  field not found, expected type 4

```
/var/log/contextBroker/contextBroker.log
```
lvl=ERROR | corr=6fb30ccc-15a0-11e8-bf2c-0cc47a95bb68 | trans=1519063925-897-00000000013 | from=127.0.0.1 | srv=i_5 | subsrv=<default> | comp=Orion | op=safeMongo.cpp[315]:getField | msg=Runtime Error (field 'result' is missing in BSONObj <{ ok: 0.0, errmsg: "The 'cursor' option is required, except for aggregate with the explain argument", code: 9, codeName: "FailedToParse" }> from caller mongoEntityTypes:394)
```

Info:
OS: RHEL/CentOS 7
Orion dist. Build from source

**Comment by fgalan** [comment]
: O

Two questions, please:

* Do you have the "killer request" that causes the crash so we can reproduce the problem (verb + URL + headers + payload), pls?
* Which version of MongoDB are you using?

**Comment by fgalan** [comment]
I've realized of the clue in the log file. Let's see what we have in mongoEntityTypes:394

https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/mongoBackend/mongoQueryTypes.cpp#L394

It could be a problem due to using MongoDB 3.6, see issue https://github.com/telefonicaid/fiware-orion/issues/3070. Note the error trace shown here match the one you are getting in this issue description.

**Comment by LeonanCarvalho** [comment]
> Do you have the "killer request" that causes the crash so we can reproduce the problem (verb + URL + headers + payload), pls?
GET /v2/entities
> Which version of MongoDB are you using?
Here the problem the version was migrated to version 3.6 

For sure is related to #3070 .

**Comment by fgalan** [comment]
GET /v2/entities or GET /v2/types... ?

The program flow at CB never reaches mongoEntityTypes:394 in the first case (except bug I cannot ever imagine right now :)

**Comment by LeonanCarvalho** [comment]
It's GET / v2/types, my mistake.

**Comment by fgalan** [comment]
I propose to close this issue (adding a comment at #3070 about it), so we can keep all the conversation in the same place (that is #3070). What do you think @LeonanCarvalho ?

**Comment by LeonanCarvalho** [comment]
Yes, I totally agree.
I'll add a comment there about this specific issue. 
Thanks.
