### ISSUE TITLE
Java POST to Orion

### ISSUE THREAD

**Issue by zlash87** [telefonicaid/fiware-orion#3140]
Hello!
I'm trying to create a new Entity in Orion using the example from the fiware-orion cookbook 
(http://telefonicaid.github.io/fiware-orion/api/v2/stable/cookbook/), by executing this code: 

![pos](https://user-images.githubusercontent.com/37518214/37572402-2792c026-2b13-11e8-8685-39b79410923d.PNG)
but as a result i get this error: "error":"ParseError","description":"Errors found in incoming JSON buffer"

On the other hand, the GET example works fine. Is something not working as it is described or am I doing something wrong here?

**Comment by fgalan** [comment]
I'd suggest to move this question to StackOverflow. Thus, could you post there using the "fiware-orion" label (just copy-paste the same  content ;) then add the link to the question in this issue, then close the issue, please? Thanks!

**Comment by zlash87** [comment]
This question is moved to StackOverflow  in [https://stackoverflow.com/questions/49360834/post-entity-to-fiware-orion-with-java](https://stackoverflow.com/questions/49360834/post-entity-to-fiware-orion-with-java) and the issue is closed

**Comment by zlash87** [comment]
Ok, I moved the question to https://stackoverflow.com/questions/49360834/post-entity-to-fiware-orion-with-java and closed the issue!

Sent from Mail for Windows 10
