### ISSUE TITLE
Accumulation Server - no action

### ISSUE THREAD

**Issue by szymonCaban** [telefonicaid/fiware-orion#3144]
Hi, 

I have difficulties with making the accumulation server to work. I started it, however it doesn't give any results if OCB receive for example new subscription. The process looks like this:

I start acc. server as told in 
_http://fiware-orion.readthedocs.io/en/latest/user/walkthrough_apiv2/#starting-accumulator-server-for-the-tutorials_
 from freshly cloned repo of OCB. As a result i get in console:

> tmp@tmp-VirtualBox:~/fiware-orion/scripts$ ./accumulator-server.py --port 1028 --url /accumulate --host ::1 --pretty-print -v
verbose mode is on
port: 1028
host: ::1
server_url: /accumulate
pretty: True
https: False
Running on http://[::1]:1028/ (Press CTRL+C to 

And after this nothing at all happens. If I make a subscription (the most basic one from the tutorial) I get response in the medium from which i made the request:

> < HTTP/1.1 201 Created
< Connection: Keep-Alive
< Content-Length: 0
< Location: /v2/subscriptions/5ab5248e50bfc821d0a1b1e0
< Fiware-Correlator: 45df4ff6-2eb3-11e8-912c-0242ac110003
< Date: Fri, 23 Mar 2018 16:00:14 GMT

However, and that might be the culprit, status of subscription is set on failed (checked with asking for listing all subscriptions and in Orion Context Explorer). And cannot be changed to inactive for instance. Everything is running as intended (I guess). OCB is running as a container in docker which is installed on LUbuntu, and is working really well. It might be my error, cuz I'm using Insomnia to communicate with OCB and could mixed something, but the response from OCB is that everything is allright. Any help will be appreciated

**Comment by fgalan** [comment]
I'd suggest to move the question to StackOverflow. Please, re-post there (it is just basically a copy paste ;) using the "fiware-orion" label. After that, please include the link to the question as a new comment to this issue, then close the issue.

Thanks!

**Comment by szymonCaban** [comment]
https://stackoverflow.com/questions/49458811/accumulation-server-no-action
