### ISSUE TITLE
Notification bug 

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#3147]
Preparing a demo for the Hannover Messe, a bug was discovered in notification of an entity with a geo-located attribute.
Two bugs actually:
1. The coordinates vector is a vector of Number but when rendered for notification, it seems it is rendered as a vector of strings.
2. After an update, the notify message (the second notify message) gets an error as somehow the name of the attribute (`location`) seems to have been lost in the federated broker (the one receiving the notification) and the update fails as the broker understands the modification in the "location" attribute as attempt to add a second attribute with metadata.

**Comment by kzangeli** [comment]
After looking into the issue it's clear it's not a bug, just "bad usage".
Attempt to use apiv2 notifications in a federated scenario when it is not implemented (partly implemented)

**Comment by taliaga** [comment]
@kzangeli what do you mean by partly implemented? Do we have an issue for that? If so, we could link it here.

**Comment by kzangeli** [comment]
partly implemented: V2 subscriptions are implemented but (as of a few weeks ago), the broker is unable to parse v2 notifications. It notifies with V2 notifications it is itself unable to understand those notifications.
This was fixed a few days ago, in master branch, still not in any release. It is not especially tested ...
