### ISSUE TITLE
Enable logging to stdout&stderr only

### ISSUE THREAD

**Issue by ddmitrii** [telefonicaid/fiware-orion#3155]
In the case when Orion works in a docker container, it's not very easy to rotate log, it's better to use only stdout&stderr and enable rotation by docker itself. So, please, add the functionality to disable writing  in /tmp/contextBroker.log

**Comment by fgalan** [comment]
It already works that way. Just use `-logLevel NONE` and log tracing will be disabled at all. More info at https://fiware-orion.readthedocs.io/en/master/admin/logs/index.html#log-file
