### ISSUE TITLE
Installation issue using RHEL 7.2 and YUM

### ISSUE THREAD

**Issue by preetha2711** [telefonicaid/fiware-orion#3183]
Hi I am unable to install the Orion Context Broker. I am using RHEL 7.2 and am following the instructions in this manual : https://fiware-orion.readthedocs.io/en/master/admin/yum/index.html

However, after successfully downloading it from the Fiware repository, RHEL shows me "No package contextBroker available. Error: Nothing to do"

**Comment by fgalan** [comment]
Thanks for the report! @Dmitrii, could you have a look?

**Comment by caa06d9c** [comment]
PR with fix provided: https://github.com/telefonicaid/fiware-orion/pull/3184
@preetha2711, thanks for the repo.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3184
