### ISSUE TITLE
Notify only attributes that change

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3190]
We can define the list of attributes to include in the notification using the notification.attrs field or use `[ ]` to mean "any attribute". We can also use notification.exceptAttr to do it in the oposite way: notifica all except a subset of attributes.

It would be great to have a way to notify not the full set specified by notification.attrs or notification.exceptAttrs but only the one that has changed, e.g. `notification.onlyChanging: true|false` (default is false, to keep backward compatibility).

Note that since the implemenation of `previousValue`, notification receiver can do this work. However, this issues goes a step further and would allow simplify receivers.

**Comment by fgalan** [comment]
The following question in SOF should be edited once this issue gets implemented:

https://stackoverflow.com/questions/51144046/can-i-create-a-subscription-that-notifies-only-those-context-attributes-that-has/51153650#51153650

**Comment by fgalan** [comment]
Thanks for the feedback @efviodo !

Depending on your interest in the feature and your development skills (Orion is written in C/C++)it would be possible to include your contribution to implement this feature as pull request. In this case, please tell me and I'll add some implementation hints to this issue to provide some guidance.

**Comment by jmcanterafonseca** [comment]
definitely something to be included on the ETSI Standard

**Comment by efviodo** [comment]
I accept the challenge @fgalan. Drop me some lines with implementation hints and I'll see if I can handle it.

**Comment by fgalan** [comment]
@efviodo I haven't forgot about this... ;) I'm afraid is taking some time to answer, sorry...

**Comment by fgalan** [comment]
Out of the scope of NGSIv2, althouth it is a good idea that could (potentially) be included in a later version of the API (v2.1) in a backward compatible way.

CC: @jmcanterafonseca

**Comment by fgalan** [comment]
The implementation can be split in two stages:

1. A first stage is to correctly parse/render the new field in JSON request/reponse for subscription management operations of the REST API. In order to do so, a new field should be added to the Notification class (in Subscription.h) to hold this aspec, eg:
2. A second stage, once the above gets completed, is to effectively use the new attribute in order to do its function so notifications associated to the subscription only include the attributes that have changed.

**Comment by fgalan** [comment]
*Implementation Notes (Stage 1)*

```
bool   onlyChanged;
```

The new parameter at JSON API level should be parsed correctly (parseSubscription.cpp/h) and stored correctly in the DB (a new field name should be defined for that in dbConstants, e.g. CSUB_ONLYCHANGED) in subscription creation/update operations (POST /v2/subscription or PATCH /v2/subscription/{subId}). Similarly, if the new field is found in DB when rendering a subscription (GET /v2/subscriptions or GET /v2/subscriptions/{subId}), it should be rendered in the output (key method is Notification::toJson()).

I'm not going to go into details for the sake of briefness, but the implementation should be similar to the one done for `blacklist` in Notification class. It is also a boolean parameter, although its parsing/rendering is a bit different (because `blacklist` it is not directly used as boolean in JSON, but to "choose" between to possibilities mutually exclusive, either having the "attrs" field or the "exceptAttrs"  field) but appart from that difference it should be pretty much the same.

**Comment by fgalan** [comment]
@efviodo I have include some implementations notes for the stage 1 of the functionality. Once stage 1 gets completed, I can continue with notes about the stage 2, but by the moment I think is enough. Let's go step by step (however, tell me if I'm wrong and you prefer to procced in a different way).

Before starting to touch Orion code, I'd strongly recommend you to have a look to the [Developers Manual](https://github.com/telefonicaid/fiware-orion/tree/master/doc/manuals/devel), in order to get a general idea about how Orion internal architecture works (overview of the different libraries, main interaction flows, etc.).

Don't hesitate to ask doubt you may have in the process! :)

**Comment by fgalan** [comment]
@efviodo no news since July last year... :)

Any update on this please? Thanks!

**Comment by efviodo** [comment]
@fgalan: Sadly at this moment I am quite away from this project and without personal time to make a contribution with quality. 

I would be glad if someone else with more active participation would take it.

My apologies!

**Comment by fgalan** [comment]
@SourabhChourasiya-NEC what do you think about this? Would you like to implement this? Taking into account your last contributions I would say you are now an expert in Orion subscription/notification stuff :D

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan  Sir,

I would be happy to work on it. Please assign this feature implementation to me.
Also, provide your valuable guidance on the same if any.

Thank you

**Comment by fgalan** [comment]
Thanks! :)

This issue has been assigned to @SourabhChourasiya-NEC 

With regards guidance, please have a look to above comments, from this point on: https://github.com/telefonicaid/fiware-orion/issues/3190#issuecomment-405636909

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,

I have completed the stage-1 implementation. 
Now I am working on stage-2.

Thank you

**Comment by fgalan** [comment]
Great! Thank so muchy @SourabhChourasiya-NEC for your efforts.

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,

I have implemented the stage-2 and made some modification in the subscription creation request payload.

for this, we have to create a subscription by the following request:
```
{
  "description": "A subscription to get info about Room1",
  "subject": {
    "entities": [
      {
        "id": "Room1",
        "type": "Room"
      }
    ],
    "condition": {
      "attrs": [
        "pressure",
        "temperature"
      ]
    }
  },
  "notification": { 
    "http": {
      "url": "http://localhost:1028/notify"
    },
    "onlyChangedAttrs": "true"
  },
  "expires": "2040-01-01T14:00:00.00Z",
  "throttling": 5
}
```
According to this whenever onlyChangedAttrs value is true it will notify the only those attributes which are changed from condition.attrs. 

Note: It will not send the initial notification, a first notification will be sent on an update of any of the attribute. 

Please provide your opinion for the same, or should we carry on to implement this.

Thanks

**Comment by fgalan** [comment]
Some feedback regarding your proposal:

1. JSON support bolean types, so better to use `true` and `false` instead of string `"true"` and `"false"` for `onlyChangedAttrs` value.
2. If notification.attrs is provided, it should act as a filter. I mean, for instance we have:

```
{
  "description": "A subscription to get info about Room1",
  "subject": {
    "entities": [
      {
        "id": "Room1",
        "type": "Room"
      }
    ],
    "condition": {
      "attrs": [ "A", "B", "C" ]
    }
  },
  "notification": { 
    "http": {
      "url": "http://localhost:1028/notify"
    },
    "attrs": [ "B, "C", "D" ],
    "onlyChangedAttrs": "true"
  },
}
```

and the updates changes A and B then only B will be notified  (as it is the one that match the conditions "has changed" and "is in notification.attrs filter" at the same time).

Thanks for your contribution!

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3490

**Comment by fgalan** [comment]
Extra documentation added in PR https://github.com/telefonicaid/fiware-orion/pull/3528

**Comment by mkavipriya** [comment]
Hi fgalan,

**Comment by mkavipriya** [comment]
Hi fgalan,

I am using "onlyChangedAttrs" = true in my Draco subsciption, but it doesn't seem to be working. It is still sending all the attributes irrespective of it is modified or not. Does this feature work in a particular version of Orion? However I am using the latest version of Orion "2.4.0-next". Can you please help me fix this. Thanks for your help!

Attached below my Draco Subscription;
curl -iX POST \
  'http://localhost:1026/v2/subscriptions' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: takenaka' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Notify Draco of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "onlyChangedAttrs":true,
    "http": {
      "url": "http://52.172.34.29:3003/v2/notify"
    }
  },
  "throttling": 0
}'

**Comment by fgalan** [comment]
I'm not fully sure but I suspect this is related with your subscriptions in Orion more than to an actual issue in the software. But I would need to know more details of the case to be sure. In order to do so, I'd suggest to post your problem in StackOverflow (please use "fiware-orion" label) so we can debug there. Please add the link to the question in SOF as comment in this issue.

If at the end of the investigation in SOF there is any bug in Orion, then and (new) issue will be opened for that.

Thanks!

**Comment by mkavipriya** [comment]
Hi Fermin,

Thanks for your reply.  All the other parameters in our Draco subscription are working fine, like if we give a list of attributes in the "conditions", then only those attributes are sent to Draco.  "onlyChangedAttrs" is the only parameter which is not working and has no affect whatsoever on the JSON sent to Draco.
Also as per your recommendation, I have posted the problem in StackOverflow.  Link below:

https://stackoverflow.com/questions/61591877/onlychangedattrs-boolean-flag-in-fiware-draco-subscription-not-working

Can you please help us resolve this issue?
Thanks so much for your help and support!
Kavipriya M

**Comment by fgalan** [comment]
Let's move the discussion to SOF post comments.
