### ISSUE TITLE
Are present() methods dead code and should be removed?

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3199]
Raised at https://github.com/telefonicaid/fiware-orion/pull/3197#discussion_r192198098

Thus, we should check if present() methods are actually used (i.e. are they invoked from some point in the parsing logic or any other inner layer?). In negative case, they are "dead code" and should be removed, along with other related stuff (e.g. `LmtPresent` tracelevel).

**Comment by kzangeli** [comment]
They might be called, but even though, let's remove all calls and all methods.
It's easy. Remove all of them and compile. If the compilation fails, remove the calls.
It's so easy I could even do it myself :)

**Comment by fgalan** [comment]
If I remember correctly, present*() methods were used to debug request/response payload in log traces. But if we are getting traces with the same information using another mechanism (probably another tracelevel lo log requests/responses?), then they can be deleted. But I'd suggest to check that other mechanism, just to be sure we are not "decapitalizing" the code.

Regarding who should do the changes, I'd suggest to mark this with the "good first issue" label, as it would be pretty easy as you say so it is perfect for rookie developers.

**Comment by kzangeli** [comment]
The thing is, the only one who was using those 'present()` methods is
myself, and I no longer use them.
Let's remove this old debugging help, it is no longer used, nor is it
needed.
I should have removed them years ago ...

And yes, a good issue for orion beginners.
Edit a little, and learn how to compile and test.

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir and @kzangeli  Sir 

I can work on this issue, and update you in some time. Just for information, I'd like to confirm that does this removal of all the "*present*()" methods calls, have impact on all the present FT test suite? 

If you want to add something more in it, please guide me for that. 

Thank you

**Comment by kzangeli** [comment]
No functests use the output from the present methods, afaik.
It would surprise me a lot if you found a case of "present dependency"

**Comment by fgalan** [comment]
I agree with @kzangeli 

However, maybe there are some unit test covering present() methods. In that case, the solution is just removing these test cases.

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3202
