### ISSUE TITLE
Use nc instead of GET /version in valgrind-broker-start

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3201]
Raised at https://github.com/apinf/fiware-orion/pull/30#discussion_r193110610:

> Better would be to use nc instead of GET /version inside 'valgrind-broker-start

.test should be adjusted, removing all the "orionCurl --url /version" that were added (in that PR and others before)  just to make statistics work also when under valgrind.

**Comment by fgalan** [comment]
The touched tests should be checked for thinks like this:

```
 HTTP/1.1 200 OK
-Content-Length: 842
+Content-Length: REGEX((842|850))
```

removing the REGEX() in Content-Length and make it more deterministic

**Comment by fgalan** [comment]
... along with other REGEX() in the "orionCurl --url /admin/metrics" steps.

**Comment by kzangeli** [comment]
When the *version request* is removed from 'valgrind startup', all affected tests will fail under valgrind, so it will be easy to find them.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3255
