### ISSUE TITLE
More 'present' functions

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#3206]
In total we have 18 **present functions** for V1 json parse, all called `jsonXxxxPresent`, e.g.:
`src/lib/jsonParse/jsonUpdateContextResponse.cpp:void jsonUpcrsPresent(ParseData* reqDataP)`

 In `src/lib/subCache` we also find present functions: 

* `subCacheEntryPresent`
* `subCachePresent`

If no longer used, we should remove all of them

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3202
