### ISSUE TITLE
Avoid bool& usage in mongoBackend

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3218]
(I have spotted this while I reviewed PR #3173)

We have serveral occurrences (seven) of `bool&` in function parameters in mongoBackend library. This goes againts code style and there usages should either `bool` (for read-only parameters) or `bool*` (for parameters used as output).

This has to be reviewed and solved.

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,
I can work on this issue, and update you in some time.
Thanks

**Comment by fgalan** [comment]
@SourabhChourasiya-NEC great! Thanks!

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3222
