### ISSUE TITLE
length of dbName is max 10

### ISSUE THREAD

**Issue by mathi123** [telefonicaid/fiware-orion#3234]
Why is there a such a short maximum length for the used database?
I'm considering a pull request to make it larger, but I would like to know the reason for this.

**Comment by fgalan** [comment]
Would you mind to use [StackOverflow](https://www.stackoverflow.com) to ask this question, please? Use the "fiware-orion" label.

Once you publish the question there, please add the link as comment in this issue, then close the issue. Thanks!

**Comment by mathi123** [comment]
[Link](https://stackoverflow.com/questions/51140211/length-of-dbname-is-max-10)
