### ISSUE TITLE
extract tenant seperator as startup parameter

### ISSUE THREAD

**Issue by mathi123** [telefonicaid/fiware-orion#3235]
**Current behaviour**

In a multi tenant setup, the database name is formed as _dbName_-_tenant_

This requires the database name to contain a dash, which might break company policy.

**Proposal**

New startup flag: 

_-tenantSeperator_ : seperator used to form the mongo database name from the Fiware-Service header. The max length for this argument is 1. (e.g. '-' or '_')

**Comment by fgalan** [comment]
> This requires the database name to contain a dash, which might break company policy.

In order to understand the use case behind this proposal of change... could you elaborate on this or provide some examples in which haing a dash could be a problem, please? Thanks!

**Comment by mathi123** [comment]
Currently, all company databases use underscores. We will have to break our (internal) standard for database naming, in order to use Orion. 

I realize thats not a big problem, but it is a bit strange that you can not fully customize your database name, no?

**Comment by fgalan** [comment]
Just to comment that the "ambiguety" previously mentioned is from the point of view of the DBA or DB operator. I mean, from a Orion point of view, there is no ambiguety as Orion knows the `-db` prefix so it is able to know how to solve it (at least in theory... code should be checked in order to see if my guessing is correct).

**Comment by mathi123** [comment]
I think a DBA generally doesn't care as much about that ambiguity,  he cares that:

- Orion doesn't automatically make databases, he sets them up for us
- All databases follow the same naming protocol

Although I find the current setup a bit constraining (I would just drop the constraints for -db and seperator, and leave it to the user to configure that (possibly with errors and/or ambiguity)), I realise its a bit far-fetched and will close this issue.

Thanks for the response and feedback! 👍
