### ISSUE TITLE
federation mode, geo:json format fails

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/fiware-orion#3265]
Orion (1.15.1) doesn't propagate geo:json Point in federation mode, here is the [test](https://nexus.lab.fiware.org/repository/raw/public/storage/test.json)

**Comment by fgalan** [comment]
Maybe is a particular case of the problem described at https://github.com/telefonicaid/fiware-orion/issues/3162. What do you think?

**Comment by fgalan** [comment]
It seems the link the issue body has broken... (I get a 404).

I think we are close to fix #3162 and given this issue could be related, I'd like to have a look. @caa06d9c  could you include the .test in a comment to this issue or include a new working link, please? Thanks!

**Comment by caa06d9c** [comment]
This PR implementing test, that was in the broken link, so the issue can be closed.
Thanks!
