### ISSUE TITLE
About contributing Orion Japanese document

### ISSUE THREAD

**Issue by fisuda** [telefonicaid/fiware-orion#3284]
Hi @fgalan ,

I have translated `.md` files in doc/manuals directory into Japanese.
Before sending a PR, may I ask something?

1. May I put Japanese document in this repository?

2. Where directory should the files be put?
   My proposal is to make `manuals.ja` in doc directory and put the files in it.

3. Is it better to send my PR after PR #3279 is merged?

**Comment by fgalan** [comment]
Thank your for your initiative! Please find my comments inline

> May I put Japanese document in this repository?

Yes, of course :)

> Where directory should the files be put? My proposal is to make `manuals.ja` in doc directory and put the files in it.

I understand you mean `doc/manuals.ja`, in parallel of existing `doc/manuals` with English documentation. I think is a good place to put the documentation.

> Is it better to send my PR after PR #3279 is merged?

Good question. In my opinion I think it depends on wether the documentation in Japanese is already translated or not.

* If already translated, then I'd recommend do the PR now, before merging PR #3279 (note that PR #3279 has a merging deadline around September 15th). However, in this case, note the translation would need to be updated after merging PR #3279 to keep in sync with English doc.
* If not translated, then I'd recomment to wait. Note that PR #3279 remove some .md files, so translation will be easier as the number of files to translate would be smaller.

Please, don't hesitate to ask again if you have more doubts. Thanks!

**Comment by fgalan** [comment]
Just a little extra comment...

Maybe better to use `manuals.jp` instead of `manuals.ja`. We are already using "(jp)" for Japanese slides in the top level README.md in the repository.

**Comment by fgalan** [comment]
> But, I probably won't be able to translate the .md files in dev by September 15th.
Is this all right?

It's all right. Note that PR #3279 doesn't touch `dev` (except in some minor points), so translation of that manual can wait from my point of view.

Thanks!

**Comment by fisuda** [comment]
I understand. I will be able to send a PR with the translated files by September 15th. This issue will be closed by the PR.

Thank you.
