### ISSUE TITLE
Associations - mandatory for next IoT integration

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#334]
### Description
During the integration meeting in Madrid, April 2014, we found a few irregularities in associations (ngsi9 discovery requests).
1. The attribute list MUST be included in a discovery request using associations. If there is no attribute list / an empty attribute list, the discovery finds nothing.
2. When nothing is found, instead of returning an ErrorCode, the broker returns an empty list of context registration responses. Not exactly empty, there is a default response containing 'http://www.fi-ware.eu/NGSI/association' as providingApplication, but nothing more.

We need to fix this, and to add harness tests to test these cases.

Actually, there are 12 combinations here (2*2*3):

    1. Association FOUND / NOT FOUND
    2. Responding entity FOUND /NOT FOUND
    3. AttributeList NOT THERE / THERE WITH OK ATTR / THERE WITH 'BAD' ATTR

Optionally, a harness test with all 12 combinations could be implemented,

**Comment by fgalan** [comment]
Associations are a deprecated feature since Orion 0.21.0 (see https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Deprecated_Features) thus this issues is going to be closed.
