### ISSUE TITLE
Info geolocation

### ISSUE THREAD

**Issue by Carmelo10** [telefonicaid/fiware-orion#3359]
Hi I'm a student and I'm working for the first time on the broker. I understood how the creation of entities works and their updating through "update" queries. My question is: you can create an entity that contains variables (eg geolocation) defined with value "null" or "zero" and then initialize them with values that interest me. So as to have dynamic and non-static variables (ie that require user update)?
Or do we need interaction with the CEP to do this?

**Comment by fgalan** [comment]
Github issues are typically for identified issues in the software (e.g. a bug report). However, I understand this is a question thus it should be better posted in http://www.stackoverflow.com

Could you post the question there, please? It is just a matter of copy-paste the existing text :). Please don't forget to include the "fiware-orion" label in the question post.

Once posted, please add the link to the question in SOF as a link in this issue, then close the issue, please? 

Thanks!

**Comment by Carmelo10** [comment]
https://stackoverflow.com/questions/53534914/fiware-orion-geolocation
