### ISSUE TITLE
README problem ?

### ISSUE THREAD

**Issue by Glagnar** [telefonicaid/fiware-orion#3362]
The readme states that:
`However, note that Orion doesn't work yet with MongoDB 3.6. Have a look to issue https://github.com/telefonicaid/fiware-orion/issues/3070`
However, I read somewhere else that 3.6 was the only supported version.

**Comment by Glagnar** [comment]
https://github.com/Fiware/tutorials.Step-by-Step/blob/master/docs/getting-started.md
This guide uses 3.6

**Comment by fgalan** [comment]
You are right, MongoDB 3.6 support was recently added (https://github.com/telefonicaid/fiware-orion/blob/master/CHANGES_NEXT_RELEASE#L3).

I have looked to https://github.com/telefonicaid/fiware-orion/blob/master/README.md file and there is no reference to MongoDB there... Could you tell me in which document you have find the wrong statement, please?

**Comment by fgalan** [comment]
Thanks for the clarification.

I understand PR https://github.com/telefonicaid/fiware-orion/pull/3394 solves is. Is that correct?

**Comment by fgalan** [comment]
PR #3364 has been merged. This issue is going to be closed.

@Glagnar if you think this is not ok and something is yet pending, please tell us about. Thanks!
