### ISSUE TITLE
Deb based image for Orion

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/fiware-orion#3364]
I've prepared image based on Debian (~112mb). I can refactor CI too. Is is a good idea?
[Link](https://github.com/caa06d9c/fiware-orion/tree/docker/docker)

`docker build -t fiware/orion:deb --build-arg REV=master`

**Comment by fgalan** [comment]
Thanks for the link! I'll have a look as soon as I can.

For the records: current Orion image (https://hub.docker.com/r/fiware/orion/tags/) is around 105-108 MB

**Comment by caa06d9c** [comment]
This size is compressed, real size at local storage ~280MB, so dev version in compressed size ~ 45mb, in real - 112
