### ISSUE TITLE
Duplication of IDs - Conflict Error when obtaining attributes in FIWARE Orion Context Broker

### ISSUE THREAD

**Issue by karaleina** [telefonicaid/fiware-orion#3374]
**PROBLEM SUMMARY:**

I get Conflict Error when I obtain attributes in FIWARE Orion Context Broker after registering Context Provider. When I try to get an attribute (location) without registered context, it works fine for me, but after context registration it fails (I get 409 Conflict Error). On the other hand, I can remove entity by id and then I can get temperature for not existing object.

I have discribed similar problem also here (https://stackoverflow.com/questions/53710837/conflict-error-when-obtaining-attributes-in-fiware-orion-context-broker).

**SETUP:**

```
docker pull mongo:3.6
docker pull fiware/orion:2.0.0
docker network create fiware_default

docker run -d --name=mongo-db --network=fiware_default \
  --expose=27017 mongo:3.6 --bind_ip_all --smallfiles

docker run -d --name fiware-orion -h orion --network=fiware_default \
  -p 1026:1026  fiware/orion:2.0.0 -dbhost mongo-db
```

**EXPOSED PROVIDER:**
I exposed locally my Context Provider (exposed by my SpringBoot application written in Java 10) at http://192.168.xxx.xxx:8080/temperature/1/queryContext. The JSON data (returned in html body) is in NSGI v1 format and looks like that:

```
{
  "contextResponses": [
    {
      "contextElement": {
        "attributes": [
          {
            "name": "temperature",
            "type": "float",
            "value": "-10"
          }
        ],
        "id": "urn:nsgi-ld:Car:001",
        "isPattern": "false",
        "type": "Car"
      },
      "statusCode": {
        "code": "200",
        "reasonPhrase": "OK"
      }
    }
  ]
}
```

**HEALTH CHECK:**

`curl -iX GET 'http://localhost:1026/version'
`

Response:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 357
Content-Type: application/json
Fiware-Correlator: cba93142-fd25-11e8-a371-0242ac130003
Date: Tue, 11 Dec 2018 09:19:00 GMT

```
```
{
"orion" : {
  "version" : "2.0.0",
  "uptime" : "0 d, 0 h, 4 m, 31 s",
  "git_hash" : "485128e135f4225040841f5ab3b85d42cfe68f55",
  "compile_time" : "Fri Sep 28 09:56:56 UTC 2018",
  "compiled_by" : "root",
  "compiled_in" : "4852e5bea506",
  "release_date" : "Fri Sep 28 09:56:56 UTC 2018",
  "doc" : "https://fiware-orion.readthedocs.org/en/2.0.0/"
}
}
```

**ADD ENTITY:**
```
curl -iX POST \
  'http://localhost:1026/v2/entities' \
  -H 'Content-Type: application/json' \
  -d '
{
    "id": "urn:ngsi-ld:Car:001",
    "type": "Car",
    "brandName": {
        "type": "Property",
        "value": "Mercedes"
    },
    "location": {
        "type": "geo:json",
        "value": {
             "type": "Point",
             "coordinates": [0.00, 0.00]
        }
    },
    "name": {
        "type": "Text",
        "value": "MyCar"
    }
}'
```

Response:
```
HTTP/1.1 201 Created
Connection: Keep-Alive
Content-Length: 0
Location: /v2/entities/urn:ngsi-ld:Car:001?type=Car
Fiware-Correlator: b57acae8-fd25-11e8-823d-0242ac130003
Date: Tue, 11 Dec 2018 09:18:23 GMT
```

**OBTAIN LOCATION VALUE:**

`curl -iX GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Car:001/attrs/location/value'
`
Response:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 36
Content-Type: application/json
Fiware-Correlator: 1f118ebe-fd27-11e8-8d99-0242ac130003
Date: Tue, 11 Dec 2018 09:28:30 GMT

{"type":"Point","coordinates":[0,0]}
```

**ADD CONTEXT PROVIDER:**
```
curl -iX POST \
  'http://localhost:1026/v2/registrations' \
  -H 'Content-Type: application/json' \
  -d '
{
  "description": "Temperature",
  "dataProvided": {
    "entities": [
      {
        "id": "urn:ngsi-ld:Car:001",
        "type": "Car"
      }
    ],
    "attrs": [
      "temperature"
    ]
  },
  "provider": {
    "http": {
      "url": "http://192.168.xxx.xxx:8080/api/cars/temperature/1"
    },
     "legacyForwarding": true
  }
}'
```

Response:
```
HTTP/1.1 201 Created
Connection: Keep-Alive
Content-Length: 0
Location: /v2/registrations/5c0f836ff87f0348a7992ca6
Fiware-Correlator: af9fad40-fd26-11e8-a4c3-0242ac130003
Date: Tue, 11 Dec 2018 09:25:23 GMT
```

**OBTAIN LOCATION QUERY:**
`curl -iX GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Car:001/attrs/location/value'`

Response:
```
HTTP/1.1 409 Conflict
Connection: Keep-Alive
Content-Length: 98
Content-Type: application/json
Fiware-Correlator: 509119fa-fd27-11e8-922c-0242ac130003
Date: Tue, 11 Dec 2018 09:29:53 GMT

```
**OBTAIN TEMPERATURE QUERY:**

`curl -iX GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Car:001/attrs/temperature/value'`

Response:
```
HTTP/1.1 409 Conflict
Connection: Keep-Alive
Content-Length: 98
Content-Type: application/json
Fiware-Correlator: 41fb2858-fd28-11e8-b427-0242ac130003
Date: Tue, 11 Dec 2018 09:36:38 GMT

{"error":"TooManyResults","description":"More than one matching entity. Please refine your query"}
```
When I make get all entities query, I get a list of entities with duplicated ids:

**GET ALL CAR ENTITIES QUERY:**
`curl GET -iX 'http://localhost:1026/v2/entities?type=Car&options=keyValues'`

Response:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 155
Content-Type: application/json
Fiware-Correlator: a7f2597a-fd27-11e8-8b30-0242ac130003
Date: Tue, 11 Dec 2018 09:32:19 GMT

[{"id":"urn:ngsi-ld:Car:001","type":"Car","brandName":"Mercedes","location":,"name":"MyCar"},{"id":"urn:nsgi-ld:Car:001","type":"Car","temperature":"-10"}]
```

After deleting an entity, I can obtain temperature for not existing entity as it is below:

**DELETE ENITITY:**

`curl -iX DELETE 'http://localhost:1026/v2/entities/urn:ngsi-ld:Car:001'`

```
Response:
HTTP/1.1 204 No Content
Connection: Keep-Alive
Content-Length: 0
Fiware-Correlator: f448a0de-fd29-11e8-82a9-0242ac130003
Date: Tue, 11 Dec 2018 09:48:46 GMT
```

**OBTAIN TEMPERATURE:**
`curl -iX GET 'http://localhost:1026/v2/entities/urn:ngsi-ld:Car:001/attrs/temperature/value'`

Response:
```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 5
Content-Type: text/plain
Fiware-Correlator: 0de19b36-fd2a-11e8-8abe-0242ac130003
Date: Tue, 11 Dec 2018 09:49:29 GMT

"-10"
```

**SUMMARY:**
When I have both entity ("urn:ngsi-ld:Car:001") and context provider for this entity registered and I make query to get all Car entities (presented above), I recieve list of objects with duplicated ids instead of merged object, which, after lecture of FIWARE tutorial (https://github.com/Fiware/tutorials.Context-Providers), I assume, should be expected . 

What should I do to prevent this id conflict? How to prevent having two objects with the same id when registering context provider?

**Comment by fgalan** [comment]
StackOverflow is definitively the way to go with this kind of questions. Thanks for posting there!

Let's continue discussion in SOF and close this issue.
