### ISSUE TITLE
Orion Docker container: problems in notification subscriptions

### ISSUE THREAD

**Issue by tmontanaro** [telefonicaid/fiware-orion#3378]
I'm using Orion on my own server (through the provided Docker container (container Orion at version 1.14.0-next)).
Everything works except the subscriptions.
I found a lot of possible contents to send to Orion to submit a subscription but I continue to see "status": "failed" when I query the list of subscriptions (and, in any case, no data is received). Do you have any idea on how to solve such a problem?

In the following you can find the links to the different versions I tried
[http://telefonicaid.github.io/fiware-orion/api/v2/stable/](http://telefonicaid.github.io/fiware-orion/api/v2/stable/)
[https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html#subscriptions](https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html#subscriptions)
and also (even though it is for a different purpose):
[https://fiware-orion.readthedocs.io/en/master/user/initial_notification/index.html](https://fiware-orion.readthedocs.io/en/master/user/initial_notification/index.html)

and finally one of subscriptions
```
(curl localhost:1026/v2/subscriptions -s -S --header 'Content-Type: application/json' -d @-) <<EOF
{
  "description": "A subscription to get info about Compartment",
  "subject": {
    "entities": [
      {
        "id": "Compartment",
        "type": "Compartment"
      }
    ],
    "condition": {
      "attrs": [
        "lastUpdate"
      ]
    }
  },
  "notification": {
    "http": {
      "url": "http://0.0.0.0:1028/accumulate"
    },
    "attrs": [
    ]
  },
  "expires": "2040-01-01T14:00:00.00Z",
  "throttling": 1
}
EOF
```

**Comment by fgalan** [comment]
This is more a question than an issue so it would be better placed in SOF (http://www.stackoverflow.com). Thus, could you create a question post there (it is a matter of basically copy-pasting the same text :), please? Don't forget to add the label "fiware-orion" to your questions.

Once posted in SOF, please add the link to the question as a comment in this issue, then close the issue, Thanks!

**Comment by tmontanaro** [comment]
Ok, thanks!

https://stackoverflow.com/questions/53746833/fiware-orion-docker-container-problems-in-notification-subscriptions
