### ISSUE TITLE
Forced update option

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3389]
When Orion recieves an update if the value of an attribute is the same as the previous value then it is not considered and actual update so:

* Subscriptions covering the attribute are not triggered
* dateModified metadata for that attribute (and possibly dateModified attribute for the containing entity) are not updated

This issues is about implementing an extension option in the NGSIv2 API that allows clients to specify that the previous value should be ignored and the updated interpreted with "actual update" semantics (i.e. triggering any potential subscription and modifying dateModified accordingly).

For instance `?options=forcedUpdate`. The new option could be used in any of the operations with update semantics, i.e.

* PUT /v2/entities/E/attrs/A?options=forcedUpdate
* PUT /v2/entities/E/attrs/A/value?options=forcedUpdate
* POST /v2/entities/E?options=forcedUpdate
* POST /v2/entities/E?options=append,forcedUpdate
* PATCH /v2/entities/E?options=forcedUpdate
* PUT /v2/entities/E?options=forcedUpdate
* POST /v2/op/update?options=forcedUpdate

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,
I can work on this feature. Please assign this to me.
Thanks

**Comment by SourabhChourasiya-NEC** [comment]
Hi @fgalan Sir,
Should I update the document if any or create a new document for the same with updating NGSIv2 implementation notes.
Thanks

**Comment by fgalan** [comment]
Depends on the document, but in general for small additions (like this one) it is better to modify existing documents.

I'd suggest first complete the implementation, then I can suggest at PR time how to edit the documentation (which documents to modify and how). Makes sense?

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #3413

**Comment by fabiocabrini** [comment]
thanks
