### ISSUE TITLE
Documentation: context information - what is the definition

### ISSUE THREAD

**Issue by ilarimikkonen** [telefonicaid/fiware-orion#3400]
the documentation refers at many points to "context information" but it's not defined anywhere. Could you please add a short section to Readme explaining what "context information" means?

**Comment by fgalan** [comment]
Thanks for the feedback. Pull request https://github.com/telefonicaid/fiware-orion/pull/3406 addresses it. Please tell us what do you think, so the PR can be merged to solve this issue.
