### ISSUE TITLE
[MUST] Remove anchor tags from docs

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-orion#3405]
The use of `<a>` anchor tags within the documentation can cause issues within the Readthedocs documentation. They are usually unnecessary since the headings create their own references anyway which can be used.

All anchor tags should be removed from the documentation. If navigation is still required, the internal links will also need to be updated.

* MUST Requirement from TSC

**Comment by fgalan** [comment]
I'm not sure if removing `<a>` anchors would break the Japanese translation...

For instance looking to https://raw.githubusercontent.com/telefonicaid/fiware-orion/master/doc/manuals.jp/user/walkthrough_apiv2.md we have:

![imagen](https://user-images.githubusercontent.com/1534240/51536645-905ef200-1e4c-11e9-97fb-b16df583b9f1.png)

which is linked this way (in the same file):

![imagen](https://user-images.githubusercontent.com/1534240/51536681-a7054900-1e4c-11e9-9509-5be561c2756f.png)

How do you solve this situation without using `<a>` anchor?

If no solution is possible, then TSC should include an expection to this rule for documentations in languages which include chars beyond plain ASCII.

CC: @fisuda

**Comment by fisuda** [comment]
@jason-fox  If <a> anchor tags can't be used, I have to give up the internal links in jp doc or have to use the captions written in English. This issue is not only in orion jp document but also in other jp documents.

**Comment by jason-fox** [comment]
Let's relax the rule then.

**Clarification:* The requirement should only apply for Documentation in English.

**Comment by fgalan** [comment]
Great!

I understand the amendment should be pushed to https://github.com/Fiware/contribution-requirements/

**Comment by fisuda** [comment]
I appreciate your understanding.
