### ISSUE TITLE
Wrong error code (204) when idPattern is used in POST /v2/op/update (should be 501)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3427]
(Related with https://github.com/telefonicaid/fiware-orion/issues/2389)

Currently idPattern is not supported in `POST /v2/op/update` operation. However, if we attemp to use it:

```
$ curl -v localhost:1026/v2/op/update -s -S -H 'Content-Type: application/json' -d @- <<EOF
{
  "actionType": "append",
  "entities": [
    {
      "type": "Room",
      "id": "Room1",
      "temperature": {
        "value": 21.2,
        "type": "Float"
      },
      "pressure": {
        "value": 722,
        "type": "Integer"
      }
    }
  ]
}
EOF
```

we get:

```
< HTTP/1.1 204 No Content
< Connection: Keep-Alive
< Content-Length: 0
< Fiware-Correlator: 079e83d2-2a30-11e9-b95d-000c29173617
< Date: Wed, 06 Feb 2019 16:55:38 GMT
< 
* Connection #0 to host localhost left intact
```

instead of a 501 Not Implemented.

The DB is not touched anyway.

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan / @kzangeli sir,
I have started working on this issue.
As per my understanding : "for batch operation `POST /v2/op/update` (with actionType : append, appendStrict, update, delete, replace), `idPattern` is not implemented yet. When we are using the same we are getting response as `204 No Content`, But it should be `501 Not Implemented`.
For that I'll have to identify the file from where response `204 No Content` is coming and add/change the code as per, when `idPattern` is used response should be `501 Not Implemented`. After that I'll have to test the above changes."
Please confirm the above understanding and approach.

And please provide me some valuable guidance on this.

**Comment by fgalan** [comment]
My understanding is the same as yours :)

Maybe it is a good idea to have a look to the Developers Manual (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/README.md) and Contribution Guidelines (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md) in the case you didn't know these documents.

Regarding testing, you should include a functional test to cover the new case (this reference, part of the Developer Manual, may help: https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/cookbook.md#adding-a-functional-test-case)

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan  sir,
 
I've fixed the issue#[3427]( https://github.com/telefonicaid/fiware-orion/issues/3427) and it is working fine in my local repo. I've also created new test cases for the same that is successfully executed. But during running of functional tests, there are 6 existing test cases are failing,for which errors are showing as` VALIDATION ERROR: input file and reference file have different line count.`

**The name of failed test files are as:**
1. 3068_cprs_full_functional/fwd_v2_query_with_contextElement_providingApplicationList.test
2. 3068_cprs_full_functional_v2/fwd_v2_ngsiv2_query_double_forward.test
3. 3068_cprs_full_functional_v2/fwd_v2_ngsiv2_query_one_forward_query.test
4. 3068_cprs_full_functional_v2/fwd_v2_ngsiv2_query_shadowed_attribute.test
5. 3068_ngsi_v2_based_forwarding/forwards_with_providers.test
6. 3068_ngsi_v2_based_forwarding/fwd_ngsv1_ngsv2_interoperability.test

**Couse of error:**
As per my investigation the cause of above error messages, is mismatching of line of code where comparison has been done between two files i.e. input_file and ref_file same are defined in `test/functionalTest/testDiff.py` file. While debugging the code, then content of the both files returns as empty.

The test files are written for the scenario i.e. v2/Registration and v1/(operations), but modification in code for issue#[3427](https://github.com/telefonicaid/fiware-orion/issues/3427) has been done for v2/(Operations i.e. update).

Kindly suggest if we can raise the PR on above status.

![Screenshot (42)](https://user-images.githubusercontent.com/55977298/71405756-526ddd80-265c-11ea-839f-11158c9ff828.png)

**Comment by fgalan** [comment]
Happy to know the solution to this issue is progressing!

I'd suggest to create a PR with the proposed fix. This is the best way of analyzing the problems you mentions on 3068 cases and provide feedback.

Thanks!

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/3617
