### ISSUE TITLE
"Special Metadata Types" in NGSIv2 specification

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3434]
Looking to the [NGSIv2 specification](http://fiware.github.io/specifications/ngsiv2/stable/) we have a section for "Special Attribute Types". 

However, we don't have a section for "Special Metadata Types". The DateTime attribute type is the only one to be included there (note that in "Builtin Metadata" section we mention DateTime).

NGSI v2.0 was already released so in theory no new version can be done without changing the spec. But maybe a v2.0.1 with errata-like modifications (like this one) is aceptable.

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan sir,
I’ve started working on this issue. Please assign this issue to me.
As per my understanding: I’ll have to add a doc section for `Special Metadata Types` i.e. only `DateTime` attribute.
Please confirm the above understanding??
As per my investigation, this new section can be added in `fiware-orion/blob/master/doc/manuals/user/metadata.md` file?

**Comment by fgalan** [comment]
Of course, I can assign this issue to you if you want to work on it... however, maybe it is not a very interesting issue. Let me explain myself.

Note we don't plan to release NGSIv2 errata version soon, so maybe your changes in the .apib file (the one that should be modified) will not appear in places like this one http://telefonicaid.github.io/fiware-orion/api/v2/stable in the next future.

Thus, I'd recommend to leave this issue on hold and choose another more profitable one. What do you think?

**Comment by ArqumFarooqui-NEC** [comment]
I've done some investigation on this and I think I'm bit closure. Once I'll raise the PR and then I'll pick another one. 
What do you think like this, please let me know your opinion?

**Comment by fgalan** [comment]
If you have started the work and are close to the finish, then I think the best idea is to raise the PR (my comment arrived late... sorry for that ;)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3654
