### ISSUE TITLE
HTTPS notification doesn't reach cygnus

### ISSUE THREAD

**Issue by StephaneRouxNCA** [telefonicaid/fiware-orion#3446]
Orion version is 2.1.0
Orion is started in HTTPS using the -https option

We use the "HTTPS" protocol schema in URL in our subscriptions --> reference" : "https://cygnus.domain.com/notify"

When we insert an Entity matching the subscrition, the ### Entity is created in Orion, **but not in STH**

However Orion Logs return: **Notification Successfully Sent to https://cygnus.domain.com:443/notify**

If we use the "HTTP" protocol schema in URL in our subscriptions **it works**
If we use curl to notify dirctly Cygnus in HTTP or HTTPS **it works**

Thanks for your help

Orion Logs bellow:
time=Friday 22 Feb 11:24:28 2019.158Z | lvl=INFO | corr=N/A | trans=1550831768-689-00000000058 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=logMsg.h[1832]:lmTransactionStart | msg=Starting transaction to **https://cygnus.domain.com:443/notify**
time=Friday 22 Feb 11:24:28 2019.159Z | lvl=INFO | corr=6a8319ac-3694-11e9-872e-0242c0a81006 | trans=1550831768-689-00000000056 | from=10.6.11.36 | srv=svctestnca | subsrv=/svcpath/testnca | comp=Orion | op=logMsg.h[1916]:lmTransactionEnd | msg=Transaction ended
time=Friday 22 Feb 11:24:28 2019.177Z | lvl=INFO | corr=N/A | trans=1550831768-689-00000000057 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=httpRequestSend.cpp[615]:httpRequestSendWithCurl | msg=**Notification Successfully Sent to https://cygnus.domain.com:443/notify**
time=Friday 22 Feb 11:24:28 2019.159Z | lvl=INFO | corr=N/A | trans=1550831768-689-00000000058 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=httpRequestSend.cpp[594]:httpRequestSendWithCurl | msg=Sending message 20 to HTTP server: sending message of 826 bytes to HTTP server
time=Friday 22 Feb 11:24:28 2019.176Z | lvl=INFO | corr=N/A | trans=1550831768-689-00000000058 | from=pending | srv=pending | subsrv=pending | comp=Orion | op=logMsg.h[1916]:lmTransactionEnd | msg=Transaction ended

**Comment by fgalan** [comment]
This is more related with a support case than with a confirmed issue in Orion. Thus, I think it would be better to post the question in http://stackoverflow.com (basically a copy-paste there :). Could you do that, please? Use the "fiware-orion" and "fiware-cygnus" labels.

Once done, please add the link to the question as comment in this issue. Then, close the issue.

Thanks!

**Comment by StephaneRouxNCA** [comment]
see https://stackoverflow.com/questions/55868359/https-notification-doesnt-reach-cygnus
