### ISSUE TITLE
Notification blacklist CLI

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3451]
A new CLI option to specify a comma separated notification blacklist. If a given notification match one of the pattern (regex will be supported) then the notification is not send and a INFO message is logged.

For instance:

```
-notificationBlacklist .*.foo.com,example.bar.com:9999
```

avoids notifications to the foo.com domain (any port) and to port 9999 in example.bar.com.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I would like to work on this issue. Please assign this issue to me.

Thanks

**Comment by fgalan** [comment]
Not sure if this issue is longer interesting... long time has passed and maybe the use case that motivates has disappear.

@danielvillalbamota what do you think, please?

(In the meanwhile @Anjali-NEC maybe you could take another issue to work on it :)

**Comment by danielvillalbamota** [comment]
Not needed by now

**Comment by fgalan** [comment]
Thanks for the feedback!

Thus, I'm closing the issue.
