### ISSUE TITLE
IsPattern set to false in legacy forwarding request

### ISSUE THREAD

**Issue by fdelavega** [telefonicaid/fiware-orion#3458]
I am using Orion v2.1.0,  I have created a registration using v2 providing entity info with idPattern. In particular, I have created the following one:

    {
        "dataProvided": {
                "entities": [
                  {
                    "type": "Weather",
                    "idPattern": ".*"
                  }, {
                  	"type": "OffStreetParking",
                  	"idPattern": ".*"
                  }
                ],
                "attrs": [
                  "temperature",
                  "humidity",
                  "availableSpotNumber"
                ]
              },
              "provider": {
                "http": {
                  "url": "http://subscriber.docker:1234"
                },
                "legacyForwarding": true
              }
            } 

Then, I try to query all the Weather entities with the following queries:

    GET http://orion.docker:1026/v2/entities?type=Weather

As the legacy forwarding is set to true I would expect the following query to have been sent to the context provider:

    POST /queryContext
    {
         "entities": [{
             "type": "Weather",
             "isPattern": "true",
             "id":".*"
        }],
        "attributes":["temperature","humidity","availableSpotNumber"]
    }

But instead the following query is being sent:

     {
        "entities":[{
            "type":"Weather",
            "isPattern":"false",
            "id":""
        }],
        "attributes":["temperature","humidity","availableSpotNumber"]
    }

Note that the isPattern is being set to false, and id is empty.

**Comment by fgalan** [comment]
According to https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html#registrations, `isPattern` and `typePattern` are not supported.

> `idPattern` and `typePattern` are not implemented.

In fact, the proper behaviour should be return 501 Not Implemented when the registration attemp is done.

The unsupport for this is due to an old and yet unsolved problem comming from the NGSIv1 days: given a regex (the one in the registration, let's name it RegR), how to know if another regex (the one in the query, let's name it RegQ) matches? For instance, imagine you do the registration with pattern `[a-r]*`  (i.e. RegR = `[a-r]*`). How do you programatically know that a query with pattern `[s-z]*` (RegQ = `[s-z]*`) doesn't match but one with pattern `[d-w]*` (i.e. RegQ = `[d-w]*`) *partially* matches in the sub-pattern `[d-r]*`?

Appart from some trivial cases (such the one described above RegR = `.*` and RegQ = `.*`) there isn't any solution to the problem (at least to the best of my knowledge... I'll be more than happy to know a solution for this problem :)

(In fact, maybe there is some old issue about this problem, but I haven't found it...)

**Comment by kzangeli** [comment]
Perhaps we need to put some restriction on the idPattern for registrations.
We could start with only allowing '.*' and nothing else for idPatterns.
That way, at least we get somewhere until we have a final decision, which seems difficult to find. It is a complex problem ...

**Comment by fdelavega** [comment]
The general case for supporting regex might not be a priority, but a mechanism for specifying in the registration that it is being provided all the entities of a given type would be important in my opinion

**Comment by jmcanterafonseca** [comment]
that can be done using just a type and avoiding using any idPattern. probably the spec should be updated for not allowing idPattern.

**Comment by kzangeli** [comment]
So, allowing for '.*' only as idPattern in the registration, and then using the entity id/idPattern from the request in the forwarded query would work for that part, right?

**Comment by kzangeli** [comment]
"avoiding using any idPattern" would be equivalent to allow only ".*" as idPattern.
Any of the two options are OK in my opinion.

**Comment by jmcanterafonseca** [comment]
we can do the following: 

if `supportedForwardingMode` is different than none, then idPattern can only be '.*'

**Comment by kzangeli** [comment]
Sounds good.

And if `none`, giving idPattern would give an error (when registering) ?
And if !`none`, any value != .* of idPattern would also be an error (when registering)

**Comment by jmcanterafonseca** [comment]
if supportedForwardingMode is none `idPattern` can be anything

**Comment by jmcanterafonseca** [comment]
by the way, the problem of checking whether two RegExp intersect is not trivial as pointed out by @fgalan . That's (one more) corner case of Context Forwarding and providers. Maybe `idPattern` is a parameter that should be removed from Registrations.

**Comment by jmcanterafonseca** [comment]
so here we have two options, remove idPattern or go for my previous proposal.

**Comment by kzangeli** [comment]
Sounds ok to me to remove idPattern, for now. Perhaps forever.
If entity id is not given (or empty?), all entities of the 'entity type' match.
'entity type' would be mandatory if there is no 'id'.
And, what is later forwarded in the query would be the ID in the query.
That I think sums it up.

**Comment by jmcanterafonseca** [comment]
OK to remove `idPattern` forever and also to discuss the issue at NGSI-LD level ... 

yes but when forwarding I think it is safer to forward both `type` and `id` (if both exist) or only `type` or  `id`

**Comment by jmcanterafonseca** [comment]
@fgalan do you agree?

**Comment by kzangeli** [comment]
And @fdelavega, does this proposal cover your immediate needs, at least?

**Comment by fdelavega** [comment]
I think so, what I need at this stage is just having the possibility of create a registration, providing only the type, with the meaning of '.*', so all the entities of a given type

**Comment by fgalan** [comment]
From [NGSIv2 spec](http://telefonicaid.github.io/fiware-orion/api/v2/stable/) with regards to `entities` in registration payload:

> `id` or `idPattern`: Id or pattern of the affected entities. Both cannot be used at the same time, **but one of them must be present.**

So removing `idPattern` forever is not a valid option. Doing so will involve to change a specification that is frozen or to produce a new version (NGSIv2.1) that will not be backward compatible with the former (NGSIv2.0).

However, allowing a subset of regex in registrations (in particular a subset of just one element: `.*`) is fine with me. For that particular case, the problem of "regex intersection" is trivial: any ReqQ will match RegR = `.*`. I think this will sufice the @fdelavega use case.

In that case, the work to be done is as follows:

*  Change documentation so "`idPattern` and `typePattern` are not implemented." reads now:
    * The only allowed `idPattern` is `.*`
    * `typePattern` is not implemented
* Ensure that any attemp to create registrations outside that returns in 501 Not Implemented response
* Modify the implementation to allow `idPattern` = `.*` in registrations
* Provide functional test to check that the forwarding works in the following cases, e.g.:
    * RegQ = `.*` (I understand this is the @fdelavega use case)
    * RegQ = `[a-s]*`
    * Query not using regex but regular `id`.

Some final remarks:

* From my point of view this issue has no relation with `supportedForwardingMode `. This field is aimed at configuring the forwarding associated to a given registration (either all, update, query, none). It is orthogonal to the discussion we are having here.
* This issues is described has been described terms of NGSIv1 forwarding, which is deprecated. Maybe it is better to address first the implementation of NGSIv2 forwarding (described [in this comment and the following ones](https://github.com/telefonicaid/fiware-orion/issues/3068#issuecomment-468584414)), then reformulate this issue in terms of NGSIv2 and solve in that scenario. That way you will save the work to develop NGSIv1 specific tests.

**Comment by kzangeli** [comment]
About NGSIv1 or v2, can't say I really care. Some functests we already have implemented and the rest will be very easy to implement. The main difference (apart from extras included in v2, like the Via HTTP header etc) is the routine used for rendering the payload for the forward + the Verb+URI Path.
Apart from that, the changes  for v1 should be perfectly valid also for v2, so, I'd go that way.

So:
* idPattern stays, but if present must be '.*', else error (501 Not Implemented)
* typePattern, if used will result in a 501 Not Implemented
* The id/idPattern for forwarded queries is taken from the URI param id/idPattern of the query
* If supportedForwardingMode == none - no forward is made (which is probably not implemented)
* Empty/Missing entity id in query (and no idPattern) => idPattern '.*'
* 'entity type' mandatory if there is no 'entity id' (no wildcard).
* Anything else?

**Comment by fgalan** [comment]
> 'entity type' mandatory if there is no 'entity id' (no wildcard).

you mean

> 'entity type' mandatory **in the forwarded query** if there is no 'entity id' (no wildcard) in the **orignal query**

?

**Comment by kzangeli** [comment]
No, what I meant was:
If the original query doesn't contain an entity ID, the it *must* contain an entity type.
This to avoid that idPattern are used without entity type.

What is forwarded will of course follow the same rule, as it is "copied" from the original query.

**Comment by fgalan** [comment]
In general I agree with the "So:" list from @kzangeli . Some comments follow.

> If supportedForwardingMode == none - no forward is made (which is probably not implemented)

This has its own issue https://github.com/telefonicaid/fiware-orion/issues/3106 and should be in a separate PR for the sake of the mental health of the reviewer :D

> If the original query doesn't contain an entity ID, the it _must_ contain an entity type.

In NGISv2, not always is the case. For instance:

```
GET /v2/entities
```

doesn't contain an entity ID and doesn't contain an entity type.

In NGSIv1 whatever may happen :) The query syntax is pretty relaxed.

**Comment by jmcanterafonseca** [comment]
that's  why LD requires at least a type or some attributes in a query ...

providing a query with no parameters would mean that you would need to fwd
it to all registered providers, a big deal ...

**Comment by kzangeli** [comment]
Would such an open query really make forwards?
Will look it up.
If it does, it's a bit crazy. I am sure pagination will not work for such a query ...

**Comment by jmcanterafonseca** [comment]
yes, many issues. that's why LD is restricting that with good criteria, I
think.

**Comment by fgalan** [comment]
> Would such an open query really make forwards?
> Will look it up.
> If it does, it's a bit crazy.

From a point of view of fowarding logic there isn't any problem. If the original query doesn't have entity ID and doesn't have type, then you can forward it anyway in the case of matching.

For instance if you have a query without ID and wihout type, a registration with pattern `".*"` and type "A" will match (and the query will be forwarded, filtering by type A). A registration with pattern `".*"` and no type also will match (and the query will be also forwarded as is).

Yes, it may be crazy, but that's the problem of the user that is using such wide registrations. Orion shouldn't limit that.

> I am sure pagination will not work for such a query ...

What about the queries that will be supported after implementing this issue? The problem will be basically the same, "all entities in a type" can be also very large (not as large as "all entities no matter the type" but very large after all). But again, it's up to the user to use that kind of registrations.

And yes, pagination in general is problematic with CPrs. Basically a "sort & merge" problem from information comming from different sources. By the way, already identified time ago along with some, in issue https://github.com/telefonicaid/fiware-orion/issues/847. But let's leave it out of the scope by the moment and solve problems one by one (first this issue, then the next one, then the next... and, eventually, the one related with pagination if we have time for that).

**Comment by kzangeli** [comment]
Here's a proposal that seems doable.
The drawback is that there will probably be too many queries to mongo.
To use this proposal, I'd suggest to implement a registration cache, very similar to the subscription cache. I guess the sub-cache implementation could be made a little more generic and be valid for both. Shouldn't be too costly to implement ...

The idea is that if the entity id of the registration and the entity id of the query match until the end of the shorter of the two (stripping away trailing `.*`), then the longer of the two can be used in the forwarded message. Only valid if the idPatterns end in `.*` (no just simple ids) and no other types of REGEX.

![Forwarding with id patterns](https://user-images.githubusercontent.com/5338380/54520297-b397b080-4968-11e9-88e5-ae54cb515678.jpg)

**Comment by fgalan** [comment]
Note we have reduce the scope of the requirement some comments above to:

> The only allowed `idPattern` is `.*`

which perfectly covers the @fdelavega use case.

So rows 2, 5, 8 and 11 can be left out and the matching algorithm.

>  The drawback is that there will probably be too many queries to mongo.

Not sure off understaing this... Why do you expect too many queries to mongo? Could you elaborate on this, please?

> To use this proposal, I'd suggest to implement a registration cache, very similar to the subscription cache. I guess the sub-cache implementation could be made a little more generic and be valid for both. Shouldn't be too costly to implement

I'd suggest to open a new issue (maybe we have it already?) about registration cache. For the basic implemetation/fix of this issue that cache is not needed.

**Comment by kzangeli** [comment]
Yes, we talked about reducing the scope. This is a new proposal with which perhaps we don't need to reduce it that much.

About many queries to mongo, to match the entity id (simple id or idpattern) of the query to the ids of the registrations there are many combinations - see the table I drew. Is it possible to create a single query to mongo to cover all that???   I kind of doubt it.  If we had the registrations in RAM (cache), it would be fairly simple to do this complex comparison.
This is why I propose to add a cache for the registrations.
If the algorithm can instead be covered with a single request to mongo, then the reg-cache wouldn't be necessary (at least not to cover *this* problem). However, as registrations seems to be gaining in importance, perhaps it's a good idea anyway to implement a reg-cache ...
And yes, that would be treated in a different issue, of course.

@fgalan , did this answer your question?

**Comment by kzangeli** [comment]
One detail:
If both query and registration use ID and not ID-pattern, they must be an exact match for a forward to be sent.

**Comment by fgalan** [comment]
I haven't thought on the details but in general MongoDB query language (either `find()` or `aggregate()`) is quite powerfull and it seems doable in the same query. Maybe an ugly and long query, but a query after all :) Remember that the reason that motivates the csub cache wasn't a problem with MongoDB queries but the usage of `$where` operator to solve "reverse regex" which is considered an antipattern in MongoDB usage. The situation is not the same for registrations.

However, after the conclusion we have reach at skype today of reducing the possibilities to just `.*` both the issue would discapear so no need to worry about it.

**Comment by kzangeli** [comment]
The "conclusion" about only allowing `.*` as idPattern for registrations is just the first step.
Some day, hopefully soon, something better will be implemented.
That day we'll go back to my proposal and continue the discussions.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3459

@fdelavega could you confirm it works and close the issue, pls?

We have covered the most basic case in this issue, some other has been spined off in this other issue:

**Comment by fgalan** [comment]
> @fdelavega could you confirm it works and close the issue, pls?

Having passed 6 months without news :) and close to the Orion 2.3.0 release date, I understand we can close this issue.
