### ISSUE TITLE
GET /v2/entities doesnt return 500 Internal Sever error when DB is failing

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3460]
Orion returns 200 OK and `[]` for GET /v2/entities when DB fails. It should return 500 Internal Server Error.

Note that GET /v2/subscriptions is behaving correctly in this aspect (have a look and copy the same behaviour).

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan  @kzangeli sir

As per my investigation, `500 Internal Server Error` is returning as response when the queries `GET /v2/subscriptions`, `GET /v2/subscriptions/<subID>` and `GET /v2/entities/<entID>` passed to Orion where DB is failing.

As the behavior of `GET /v2/entities/<entID>` is also correct so I'm following current implementation of the same and will implement the similar behavior to `GET /v2/entities`

Please confirm my understanding and approach and please assign this issue to me.

**Comment by fgalan** [comment]
I think your understanding it correct. Thanks!

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan sir,
As I have commented on [PR](https://github.com/telefonicaid/fiware-orion/pull/3616#issuecomment-920617623) of this issue, that this issue has been fixed by other PR and currently `GET v2/entities` API is returning `500 Internal Server Error` when DB fails.
So this issue should be closed.

**Comment by fgalan** [comment]
> Hi @fgalan sir,
> As I have commented on [PR](https://github.com/telefonicaid/fiware-orion/pull/3616#issuecomment-920617623) of this issue, that this issue has been fixed by other PR and currently `GET v2/entities` API is returning `500 Internal Server Error` when DB fails.
> So this issue should be closed.

I agree. Closing.

Thanks!
