### ISSUE TITLE
POST /v2/registrations allows forbidden attribute names in NGSIv2

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3468]
(This comes from https://github.com/telefonicaid/fiware-orion/issues/3068#issuecomment-481668521)

According to that report, CB is allowing a POST /v2/registration with attribute `luminescence att` and it must not, given the whitespace is forbidden in attribute names in NGSIv2 according the spec.

Probably it is a matter of adjusting the parsing logic to be more strict. Let's have a look to the parsing for create entity logic, where I think these cheking are already in place and working.

CC: @dcalvoalonso

**Comment by rajeswar457** [comment]
CC : @Chandradeep-NEC 

Hi @fagalan, 

I’m not able to reproducing this issue in my local environment. Following error is returned “error: bad request”.
When I tried with attribute name like ”luminescence” in this case I’m able to register. As per NGSIv2 specifications context broker is failed to detect if attribute name included whitespace. Such types of attributes are forbidden as per ngsiv2 spec.

Please confirm me the issue

**Comment by fgalan** [comment]
@rajeswar-NEC not sure of fully understand you comment...

Could you provided the exact request you are using (e.g. `curl` command) and the response you get? With that information I think it would be more clear.

**Comment by rajeswar-NEC** [comment]
Hi @fgalan 

please find the below attached screenshots and explanation.

Case 1: I had used in  json payload with id: test3468    type: light and attribute names ‘luminescence’ & ‘pressure’ in this case 
            I’m successfully executed and attributes were registered.
Case 2: I had used in json payload with id: test3468:whitespace    type: light and attribute names ‘luminescence attribute’ & 
            ‘pressure’ in this case I’m getting following error like { “error” : “BadRequest”,    
          “description” : “Invalid characters in attribute name” }

![3468-testing](https://user-images.githubusercontent.com/55490519/87783621-7b50fc80-c852-11ea-8a1b-e7d60af61a32.png)

Please find “case:1” result in below screenshot and also I had tried with attribute name like “luminescenceattribute” in this case also successfully registered.

![3468-testing result](https://user-images.githubusercontent.com/55490519/87784468-f961d300-c853-11ea-8dd7-1677bbfa22be.png)

**Comment by rajeswar-NEC** [comment]
Hi @fgalan 

I am able to reproduce the issue on my environment, please find the below screenshot for the same.
![Screenshot (1)](https://user-images.githubusercontent.com/55490519/87822274-d0126880-c88e-11ea-99bc-4b0f96a8a12d.png)

**Comment by fgalan** [comment]
I think your way of reproducing the error is correct. Instead of 201 Created, Orion should report a 400 Bad Request with this payload:

```
{"error":"BadRequest","description":"Invalid characters in attribute name"}
```

Similarly, if the problem is in the entity id or entity type (check for instance with "the 3468" instead of "3468" and with "the ligth" instead of "light") a 400 Bad Request with these payload should be returned:

```
{"error":"BadRequest","description":"Invalid characters in entity id"}
{"error":"BadRequest","description":"Invalid characters in entity type"}
```

Maybe it can help how Orion behaves with the following request for entity creation, that are working well and return the proper 404 error response:

```
curl localhost:1026/v2/entities -s -S -H 'Content-Type: application/json' -d @- <<EOF
{
  "id": "the Room1",
  "type": "Room",
  "temperature": {
    "value": 23,
    "type": "Float"
  }
}
EOF
```

```
curl localhost:1026/v2/entities -s -S -H 'Content-Type: application/json' -d @- <<EOF
{
  "id": "Room1",
  "type": "the Room",
  "temperature": {
    "value": 23,
    "type": "Float"
  }
}
EOF
```

```
curl localhost:1026/v2/entities -s -S -H 'Content-Type: application/json' -d @- <<EOF
{
  "id": "Room1",
  "type": "Room",
  "the temperature": {
    "value": 23,
    "type": "Float"
  }
}
EOF
```

**Comment by rajeswar-NEC** [comment]
Hi @fgalan 

>Similarly, if the problem is in the entity id or entity type (check for instance with "the 3468" instead of "3468" and with "the light" instead of "light") a 400 Bad Request with these payload should be returned:
{"error":"BadRequest","description":"Invalid characters in entity id"}
{"error":"BadRequest","description":"Invalid characters in entity type"}

Yes, I had tried in both ways and the returned response was same as like expected result ” 400 Bad Request”, please find the  below attached screenshots for the same

Case 1: entity id included with whitespace 
![Screenshot (2)](https://user-images.githubusercontent.com/55490519/88029711-fa4a7b80-cb57-11ea-8e68-9b9464e04057.png)

Case 2: entity type included with whitespace
![Screenshot (3)](https://user-images.githubusercontent.com/55490519/88029824-1cdc9480-cb58-11ea-866e-c8d3a7064654.png)

>Maybe it can help how Orion behaves with the following request for entity creation, that are working well and return the proper 404 error response:

Also I had tried with these payloads, please find the below screenshots for the same.

Case 1: entity id with whitespace
![Screenshot (4)](https://user-images.githubusercontent.com/55490519/88030357-c15ed680-cb58-11ea-9758-d7bbcc388726.png)

Case 2: entity type with whitespace
![Screenshot (5)](https://user-images.githubusercontent.com/55490519/88030442-db98b480-cb58-11ea-8a08-320ebfb61128.png)

Case 3: attribute name with whitespace
![Screenshot (6)](https://user-images.githubusercontent.com/55490519/88030492-eeab8480-cb58-11ea-9353-3955afde314d.png)

curl -v localhost:1026/v2/entities -s -S -H 'Content-Type: application/json' -d @- <<EOF

As per the above result of of curl command, 400 Bad request returned as output. But you mentioned as 404 error code. May be it was a Typo. Please confirm.
The expected output of POST /v2/registration request with whitspace in attribute should be “400 Bad request”.
Please confirm my understanding.

**Comment by fgalan** [comment]
> As per the above result of of curl command, 400 Bad request returned as output. But you mentioned as 404 error code. May be it was a Typo. Please confirm.

Confirmed. I was a typo. My comment above has been edited to fix it.

> The expected output of POST /v2/registration request with whitspace in attribute should be “400 Bad request”.
> Please confirm my understanding.

Your understanding is correct. It should be easy: just a matter of checking that situation at parsing stage and return the proper error response.

Thanks!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/3682
