### ISSUE TITLE
 ONANYCHANGE subscriptions

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#350]
NGSI standard ONCHANGE subscription always need a list of "triggering" attributes (see section 5.5.10 in the OMA spec). Thus, it is not possible to specify that the subscriber wants to be notified each time any of the attributes of the entities change without a previous knowledge of the list of attributes of the entity. This is a limitation on some scenarios.

This issue is about to enhance the ContextBroker, including a new type of subscriptions for changes in any attribute (let's name them ONANYCHANGE). In this case the condValue element is not required (this fits in NGSI spec, as this element is optional in subscribeContextRequests according to OMA spec).

Regarding implementation, it would be a matter of tuning the query done to MongoDB in the addTriggeredSubscriptions() function at mongoBackend. It also will involve changes in the processConditionVector(), taking into account the new subscription change (and using the corresponding query for that).

**Comment by ImanolBarba** [comment]
+1

**Comment by alexferreiros** [comment]
+1

**Comment by goofyahead** [comment]
+1

**Comment by dmoranj** [comment]
+1

**Comment by frbattid** [comment]
+1

**Comment by fgalan** [comment]
The following answer at SOF should be edited when this issue gets implemented: http://stackoverflow.com/questions/31826459/fiware-context-broker-can-we-subscribe-to-all-the-context-updates/31831730?noredirect=1#comment53804184_31831730

**Comment by silva96** [comment]
:+1:

**Comment by c-castillo** [comment]
+1

**Comment by dimh** [comment]
+1

**Comment by diogonunes92** [comment]
+1

**Comment by fgalan** [comment]
Implemented (finally!) in PR https://github.com/telefonicaid/fiware-orion/pull/1679. Once that PR gets merged, it will be available in develop branch. In addition, it would be available in the next official release (0.27.0), which is expected by the end of January / beginning of February.

**Comment by goofyahead** [comment]
Yay! :dancer:

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
