### ISSUE TITLE
API to read multiple sensor measurements via Orion+keyrock?

### ISSUE THREAD

**Issue by nalexopo** [telefonicaid/fiware-orion#3503]
Hello, 
 I am a hardware developer  and I have multiple sensors communicating with the framework. I also have deployed the system until cygnus and keyrock components. Currently I have also developed a client that mines time series data straight from connecting on the mongo database.  I know this is a crude way of doing things and if I want to play with roles and permissions I have to do it through Orion.  The only way you provide for us to read sensor data via Orion is reading the last measurement with this command:

`curl -G -X GET \
  'http://localhost:1026/v2/entities/urn:ngsi-ld:Motion:001' \
  -d 'type=Motion' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'`

   Is there a way to mine time series data between dates (or N measurements back from now) via orion so i can secure time series data mining and assign it to a role with permission?

I know there is STH-Comet to read time series data but from reading the tutorials I understand that cannot connect sth-comet with keyrock.

**Comment by fgalan** [comment]
Github issues are more related to identified issues/bugs in the software or with new backlog features. For a question like yours, I think it would be better to use StackOverflow (http://stackoverflow.com/). Could you post your question there, please? Basically a copy-paste of the same text :) Please use relevant tabs such as "fiware-orion", "fiware" and "fiware-sth-comet".

Once done, please add a comment to this issue with the link to the question in SOF. Then, close the issue.

Thanks!

**Comment by nalexopo** [comment]
https://stackoverflow.com/questions/56473264/api-to-read-multiple-sensor-measurements-via-orionkeyrock-or-connect-sth-comet
