### ISSUE TITLE
Cookbook: The section "Adding a REST service" is outdated

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#3506]
The part "Adding a REST service" describes how it worked (to add a REST service) before a pretty important change and is no longer valid. Needs to be rewritten.

**Comment by Pradyumn-NEC** [comment]
Hi @kzangeli, @fgalan. 

I've gone through this issue #3506, and according to the description, the "Adding a REST service" section has become outdated due to some significant changes. It seems like it's in need of a rewrite.

It's been a while since this was reported, could you confirm if this issue is still valid? Please provide your opinion. If this issue is still valid, I'd be happy to contribute to updating it based on the current state of things.

Looking forward to your guidance on this!

**Comment by Pradyumn-NEC** [comment]
Yes, that's the document I'm referring to: [Cookbook - Adding a REST service] (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/cookbook.md)

**Comment by fgalan** [comment]
That document is part of our Development Manual, which is part of our active documentation. Thus, if you have found it outdated, any help updating it will be welcomed :)

**Comment by Pradyumn-NEC** [comment]
I have observed that, there are some points in the [[CookBook]](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/cookbook.md) document i.e. not in sync. Please find below points:
 
1. In `struct RestService` within `src/lib/rest/RestService.h`, I believe the documentation mentions `std::string payloadWord;`, which is removed from the file.

```
typedef struct RestService  
{  
  RequestType   request;          // The type of the request  
  int           components;       // Number of components in the URL path  
  std::string   compV[10];        // Vector of URL path components. E.g. { "v2", "entities" }  
  std::string   payloadWord;      // No longer used, should be removed ... ?  
  RestTreat     treat;            // service function pointer  
} RestService;
```
 
2. The documentation references `putMetadata()` in `src/lib/serviceRoutinesV2/putMetadata.h/cpp`, but the `putMetadata()` is not present.
 
Please provide your opinion, whether my observation is correct or not.

**Comment by Pradyumn-NEC** [comment]
Hi @fgalan, please provide your opinion, whether above observation is correct.

**Comment by fgalan** [comment]
> 1. In `struct RestService` within `src/lib/rest/RestService.h`, I believe the documentation mentions `std::string payloadWord;`, which is removed from the file.

You are right.

**Comment by fgalan** [comment]
> 2\. The documentation references `putMetadata()` in `src/lib/serviceRoutinesV2/putMetadata.h/cpp`, but the `putMetadata()` is not present.

Note that documentation is illustrating how a new hypothetical request would be implemented. Thus, it makes sense that in the current code base we don't have an existing `putMetadata()`. The documentation is fine regarding this.
