### ISSUE TITLE
Create a subscription returns empty

### ISSUE THREAD

**Issue by abrahamSecmotic** [telefonicaid/fiware-orion#3518]
When I create a subscription with this request:

```javascript
method: POST
body:{
	"description": "Example subscription",
        "subject": {
          "entities": [{
            "idPattern": ".*"
          }],
          "condition": {
            "attrs": []
          }
        },
        "notification": {
          "http": {
            "url":"http://localhost:3000/notification"
          }
        },
        "throttling": 3
}

```

This request returns 201 with body empty.
It would be convenient in our use case to return the subscription id, in order to have better control of them and reuse the response. Would this be useful to be implemented via PR?

**Comment by kzangeli** [comment]
Check the HTTP header "Location"

**Comment by abrahamSecmotic** [comment]
Perfect, thank you very much
