### ISSUE TITLE
Query entities by the logical operator OR 

### ISSUE THREAD

**Issue by olivertem** [telefonicaid/fiware-orion#3523]
I dont be able to retrieve entities form Orion querys with 2 conditions by the logical operator OR.

For example, if I want to retrieve the entities that have temperature>20 OR humidity<50. But I only can retrieve the query by the logical operator AND:

http:// localhost:1026/v2/entities?q=temperature>20;humidity<50

Also I try with | to separate the conditions, like this:

http:// localhost:1026/v2/entities?q=temperature>20|humidity<50

But gived me the next error:

{ "error": "BadRequest", "description": "forbidden characters in String Filter" }

How I could to retrieve queries to Orion by te logical operator OR?

**Comment by fgalan** [comment]
I understand this question was posted (and answered) in SOF at https://stackoverflow.com/questions/56886734/query-entities-by-the-logical-operator-or-with-fiware-orion so this issue could be closed.

If I'm wrong, please tell me so we can reopen it.
