### ISSUE TITLE
Simple Query Language returning entities with empty attributes (whenever there is no match)

### ISSUE THREAD

**Issue by rrc2soft** [telefonicaid/fiware-orion#3525]
We are doing a course on FIWARE, and while following the instructor instructions we found a bug on the simple query language (through the JSON interface). In particular: if we send a query that has no hits (i.e. no entity complies with the query), yet there are entities whose attributes are empty, then the query will return all those entities plues their empty attributes instead of an empty list.

For example, if we launch the following query, and the database of entities has entities whose temperature is not greater than 150 but has empty atributes:

https://{{host}}:{{cb_port}}/v2/entities?q=temperature>150

...then the answer to the query will return all entities with empty attributes:

`
[
    {
        "id": "myEntity",
        "type": "myType",
        "luminosity": {
            "type": "Number",
            "value": "",
            "metadata": {}
        },
        "turn": {
            "type": "command",
            "value": "",
            "metadata": {}
        }
    }
]
`

For the sake of completeness, here is the entitity "myEntity":

`
{
    "id": "myEntity",
    "type": "myType",
    "TimeInstant": {
        "type": "DateTime",
        "value": "2019-07-15T10:20:44.00Z",
        "metadata": {}
    },
    "description": {
        "type": "Text",
        "value": "My even more happy entity",
        "metadata": {}
    },
    "humidity": {
        "type": "Number",
        "value": 98,
        "metadata": {
            "TimeInstant": {
                "type": "DateTime",
                "value": "2019-07-15T10:20:44.00Z"
            }
        }
    },
    "serialID": {
        "type": "Text",
        "value": "02598347",
        "metadata": {
            "TimeInstant": {
                "type": "DateTime",
                "value": "2019-07-15T10:20:44.00Z"
            }
        }
    },
    "status": {
        "type": "Text",
        "value": "active",
        "metadata": {}
    },
    "temperature": {
        "type": "Number",
        "value": 99,
        "metadata": {
            "TimeInstant": {
                "type": "DateTime",
                "value": "2019-07-15T10:20:44.00Z"
            }
        }
    },
    "turn_info": {
        "type": "commandResult",
        "value": " ",
        "metadata": {}
    },
    "turn_status": {
        "type": "commandStatus",
        "value": "PENDING",
        "metadata": {
            "TimeInstant": {
                "type": "DateTime",
                "value": "2019-07-15T10:17:29.00Z"
            }
        }
    },
    "luminosity": {
        "type": "Number",
        "value": "",
        "metadata": {}
    },
    "turn": {
        "type": "command",
        "value": "",
        "metadata": {}
    }
}
`

**Comment by fgalan** [comment]
It's weird, because that entity has temperature=99 so it doesn't match the filter...

Do you have any registration in place (i.e. the result of `GET /v2/registrations`)? If so, please tell us the result of that request, please.

**Comment by rrc2soft** [comment]
Sorry for the late reply. This was during a one-day course, and I no longer have access to the platform.

**Comment by fgalan** [comment]
Oh... what a pity!

In this situation (inability of reproducing the case) I'd suggest to close the issue. What do you think?

**Comment by rrc2soft** [comment]
Ok. Hopefully someone with more access to the platform will find the bug and solve it.
