### ISSUE TITLE
Switch to disable refresh cache traces

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3535]
Subscription sincronization traces are shown in INFO level. Each subscription typically generate four traces

```
time=2019-07-29T23:59:42.677Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[449]:collectionUpdate | msg=Database Operation Successful (update: <{ _id: ObjectId('57ff51d3db8215be30eed3b4'), $or: [ { lastSuccess: { $lt: 1564440957 } }, { lastSuccess: { $exists: false } } ] }, { $set: { lastSuccess: 1564440957 } }>)

time=2019-07-30T14:45:46.487Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[449]:collectionUpdate | msg=Database Operation Successful (update: <{ _id: ObjectId('5a8d57468167586338fe324c'), $or: [ { lastFailure: { $lt: 1561836566 } }, { lastFailure: { $exists: false } } ] }, { $set: { lastFailure: 1561836566 } }>)

time=2019-07-30T14:45:46.486Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[449]:collectionUpdate | msg=Database Operation Successful (update: <{ _id: ObjectId('5a8d57468167586338fe324c'), $or: [ { lastNotification: { $lt: 1564497927 } }, { lastNotification: { $exists: false } } ] }, { $set: { lastNotification: 1564497927 } }>)

time=2019-07-30T14:45:46.485Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=connectionOperations.cpp[449]:collectionUpdate | msg=Database Operation Successful (update: <{ _id: ObjectId('5a8d57468167586338fe324c') }, { $inc: { count: 2 } }>)
```

This is a bit annoying especially if you have a large setup (tens of services with hundreds of subscriptions each one) and a short refresh interval. In those cases, it would be nice to have a switch to disable them, i.e. `-noCacheLog`.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I would like to work on this issue. Please assign this issue to me.

As per my understanding  we need to add CLI `-noCacheLog` which is used to disable the INFO level traces. Currently each subscription generate four traces of INFO. These traces are generated from https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/mongoDriver/connectionOperations.cpp So, we need to add the logic when we run contextBroker with `-noCacheLog` no INFO level traces in that case.

Please confirm my above understanding.

**Comment by fgalan** [comment]
I think that after the changes in PR https://github.com/telefonicaid/fiware-orion/pull/3696 this is no longer an issue. Now there is a specific tracelavel (LmtOldInfo) in DEBUG mode to show these traces, which no longer are shown in INFO log level.

Thus, this is is going to be closed. Thanks for raising this!
