### ISSUE TITLE
Slow Orion/Create entity

### ISSUE THREAD

**Issue by helderalvesoliveira** [telefonicaid/fiware-orion#3537]
Hello,
When i have a lot information in Context Orion Broker ( in mongoDB), when i try insert more information increasingly your insertion is more slower.
e.g :
In this moment basically i have in Orion 3GB of information and when i try to send more information to Orion, i'm waiting more less 15' minutes to send 50MB, however, if i send the same information when the Orion was empty this process finish in 1' minute.

Is normally this process ? "... increasingly your insertion is more slower..."

Thank you very much.

Best Regards.

P.s . 
VPS linux with **2 cores** and **8gb ram**.

**Comment by fgalan** [comment]
I'd suggest dealing with this question in SOF (https://stackoverflow.com). Could you post there, please? Basically, a copy-paste of your question here :). Please include the "fiware-orion" label.

Once the post at SOF has been created, please include the link to it in this issue as a comment. Then, close this issue. Thanks!

**Comment by fgalan** [comment]
I understand this question has been posted at https://stackoverflow.com/questions/57496918/entity-slow-orion-create. Let's continue the discussion there. Closing this issue.
