### ISSUE TITLE
Subscription that pass to inactive state after a limit of failed connection attemps

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3541]
A new optional field would be used (in the subscription payload) to specify a limit of connection attempts, so when that number of failing notifications is reached, then the subscription passes automatically to inactive state. The counter is reset in the following situations:

* When a successful notification is sent
* When the subscription is modified to pass from inactive to active state

**Comment by tomsluyts** [comment]
It might be useful to qualify the cause of the "inactive" state - for example with an additional value or something, else you wouldn't know that the "inactive" state was triggered by reaching the max. number of connection tries. Somebody could have done it "manually" or something.

This could also allow for monitoring applications to pick up faulty endpoints.

**Comment by fgalan** [comment]
Good point.

Currently status enumeration is: "active", "inactive", "oneshot", "expired" and "failed". The new status, in fact, would be a specialization of "failed"... maybe "failedMaxReached" (I would prefer a shorter name, in the same style of the other, but I don't find a good alternative right now... any suggestion? :) )

**Comment by tomsluyts** [comment]
I've got "connectionsfailure", "failedevents", "failedconnections" or "unhandledevents" as possibilities

**Comment by Anjali-NEC** [comment]
Hi @fgalan @tomsluyts Sir,

I hope this is and old issue like  #3451 is it still need to be fixed ? if yes then I will try to analyze whether I could finish it under my bandwidth before start working on it.

**Comment by fgalan** [comment]
I think this would be an interesting feature, so the issue is still valid.

In a first iteration, I'd suggest you to focus on the simple case: just only one "inactive" status, without taken into account the cause of the fail. Probably with the existing `lastFailureReason` field is enough to know that was the cause of the problem.

**Comment by tomsluyts** [comment]
Thanks for picking this up. We've had a lot of issues with inactive subscriptions eating up system resources with retries, unless you have a closely managed system where people spend time to see if everything is still up and running on the subscriber side as expected, this quickly becomes a serious issue if you have a lot of subscribers and you lose track.

**Comment by fgalan** [comment]
Related issue: https://github.com/telefonicaid/fiware-orion/issues/930

**Comment by Anjali-NEC** [comment]
Please assign this issue to me.

Thanks

**Comment by fgalan** [comment]
Thanks for your willingness to work on this! Assigned.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I have added A new optional field in the subscription payload just like other optional fields (throttling). Now I am applying the condition when the maximum limit number of failing notifications is reached, then the subscription passes automatically to inactive state. For this I am trying to add the code in `src/lib/rest/httpRequestSend.cpp` in function `httpRequestSendWithCurl`. please confirm my understanding and approach.

**Comment by kzangeli** [comment]
Not sure that `httpRequestSend()` is the best function for dealing with the DB.
Perhaps delay it to where the notification was requested?

**Comment by fgalan** [comment]
> I have added A new optional field in the subscription payload just like other optional fields (throttling). Now I am applying the condition when the maximum limit number of failing notifications is reached, then the subscription passes automatically to inactive state. For this I am trying to add the code in `src/lib/rest/httpRequestSend.cpp` in function `httpRequestSendWithCurl`. please confirm my understanding and approach.

Rather than `httpRequestSendWithCurl` itself, maybe it's better to call the subscription de-activation logic in the places where `httpRequestSendWithCurl` is called, upon checking in the return value if the notification were fine or not. With regards to the de-activation logic itself, not sure right now what is the best place... put it by the moment in the place you consider better but be prepared to refactor and move upon PR review.

However, It's hard to me to provide good feedback without known the modifications you are doing. In this sense, I'll be able to provide better feedback once the PR gets created.

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I have added the code changes to fix issue in my PR #3890 it is not complete fix as I have not found the subscription de-activation logic. I have tried to modify the `src/lib/mongoBackend/MongoCommonUpdate.cpp` in function `processSubscriptions` where the notificationSent logic is written. In line 1984 I have added the else block in case the notificationSent is false but I am not able to de-active the subscription. Please guide me further.

Thanks

**Comment by fgalan** [comment]
> 
> 
> Hi @fgalan sir,
> 
> I have added the code changes to fix issue in my PR #3890 it is not complete fix as I have not found the subscription de-activation logic. I have tried to modify the `src/lib/mongoBackend/MongoCommonUpdate.cpp` in function `processSubscriptions` where the notificationSent logic is written. In line 1984 I have added the else block in case the notificationSent is false but I am not able to de-active the subscription. Please guide me further.
> 
> Thanks

Please find my feedback in the PR itself.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/3962 (continuation of PR #3890)
