### ISSUE TITLE
Special attribute type to skip forbidden chars

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3550]
Context Broker doesn't allow forbidden charts (https://fiware-orion.readthedocs.io/en/master/user/forbidden_characters/index.html) in attribute values. This can be restrictive in some scenarios.

We could define an special attributeType (for instance, "TextUnrestricted") so ContextBroker broker will not do checks on it. Eg:

```
"description": {
   "type": "TextUnrestricted",
   "value": "I'm a description (and I'm using forbidden chars)"
}
```

Of course, the user should know the potential security implications of this and assume them in his client code.

This would be backward compatible and enhance Orion.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/3592

**Comment by fgalan** [comment]
@pcanoesp could you provide the request you are sending to the CB, pls? verb + url + payload

**Comment by pcanoesp** [comment]
In our real case of use, payload filed is the one including forbiden characters (base64 coding)
