### ISSUE TITLE
Yum repository does not work

### ISSUE THREAD

**Issue by achiancone** [telefonicaid/fiware-orion#3555]
There is a problem with the YUM repository.
When I put the command 
`yum install contextBroker`
the repository does not work.
If I go to the link
[https://nexus.lab.fiware.org/repository/raw/public/repositories/el/7/x86_64/fiware-release.repo](https://nexus.lab.fiware.org/repository/raw/public/repositories/el/7/x86_64/fiware-release.repo)
I see the configuration, but if I follow the baseurl
[https://nexus.lab.fiware.org/repository/el/7/x86_64/release](https://nexus.lab.fiware.org/repository/el/7/x86_64/release)
there are some problems.

thank you for your support.

**Comment by fgalan** [comment]
Could you provide the link to the page in which you have found Orion installation instructions, please? Just in case we need to review the procedure described there... Thanks!

**Comment by achiancone** [comment]
I found the instructions in the official documentation.
[https://fiware-orion.readthedocs.io/en/latest/admin/yum/index.html](https://fiware-orion.readthedocs.io/en/latest/admin/yum/index.html)
Do you have the same problem? Are you able to fix?

thank you ;-)

**Comment by fgalan** [comment]
I didn't manage the yum repositories. Is people from FIWARE Foundation which does that. Maybe they changed some URL...

(I typically get Context Broker compiling from sources or by dockerhub, so I'm afraid I cannot confirm the problem or possible fixes)

I'm CCing @caa06d9c (from FIWARE Foundation) so he can help with this.

**Comment by fgalan** [comment]
It seems that @caa06d9c is no longer in charge of this. CC: @flopezag

**Comment by flopezag** [comment]
I was checking the issue and now it should be working again. There where some issues due to infrastructure migration. Please, try again and let us know.

**Comment by achiancone** [comment]
Sorry @flopezag but it doesn't work.
The link
[https://nexus.lab.fiware.org/repository/el/7/x86_64/release](https://nexus.lab.fiware.org/repository/el/7/x86_64/release)
is broken (Error 404).
The Repository [https://nexus.lab.fiware.org/](https://nexus.lab.fiware.org/) seems to be online, but empty.

**Comment by flopezag** [comment]
Are you trying to execute the yum install contextBroker after the configuration of the public repository?

**Comment by caa06d9c** [comment]
@achiancone  this endpoint doesn't provide an http browse function, only directs link are accessible, and entry point for yum is [repomd.com](https://nexus.lab.fiware.org/repository/el/7/x86_64/release/repodata/repomd.xml).

**Comment by achiancone** [comment]
Thank you @caa06d9c and @flopezag. I understand now.
I'm trying to install the Context Broker directly from rpm. Probably the problem is that the online documentation is not clear at this point (with non browsable page):
[https://fiware-orion.readthedocs.io/en/latest/admin/install/index.html#using-rpm-file](https://fiware-orion.readthedocs.io/en/latest/admin/install/index.html#using-rpm-file)

**Comment by flopezag** [comment]
You are right @achiancone, the issue that you identify means that the documentation was not so clear in this point and we need to update accordingly.

**Comment by fgalan** [comment]
Thanks for the feedback!

Maybe @achiancone you could propose a documentation change based in your experience so it gets more clear, please? Do it as pull request modifying the file https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/install.md

Thanks!

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I am working on this issue and as per my understanding we need to update the document of installation USING RPM FILE
in https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/install.md

I have a concern regarding this:

We need to Update the link for Download the package directly from the FIWARE Yum repository i.e
https://nexus.lab.fiware.org/service/rest/repository/browse/el/7/x86_64/ But currently it is disable and we are not able to download RPM file from the same link.
And also I am not getting the link from any other source for downloading RPM package. Please guide me on this.

**Comment by fgalan** [comment]
> Please guide me on this.

Not sure of what documentation fix should be done... This issue is based in the feedback from @achiancone,

> I'm trying to install the Context Broker directly from rpm. Probably the problem is that the online documentation is not clear at this point (with non browsable page):
> https://fiware-orion.readthedocs.io/en/latest/admin/install/index.html#using-rpm-file

But I'm not sure which particular fix should be done in the documentation.

Maybe @achiancone could you guide @Anjali-NEC to implement the fix, please? Thanks!

**Comment by raiuli** [comment]
Hi,
The fiware public repository is giving 404.
https://nexus.lab.fiware.org/repository/raw/public/repositories/el/7/x86_64
I cannot download and install  orion broker

**Comment by fgalan** [comment]
I'm not related with fiware.org domain, so I'm afraid I cannot provide support on this...

Maybe @flopezag could provide some feedback.

**Comment by raiuli** [comment]
But how can we install using rpm?

**Comment by flopezag** [comment]
Could you try it again. We have resolve an issue in our Nexus instance.

**Comment by jicarretero** [comment]
It works. ContextBroker install using that repo.

**Comment by fgalan** [comment]
Maybe this issue can be closed if yum repository is ok now? @achiancone @raiuli what do you think?

**Comment by raiuli** [comment]
yup
