### ISSUE TITLE
Update Invalid Characters

### ISSUE THREAD

**Issue by c0nb4** [telefonicaid/fiware-orion#3557]
Error Message: [INFO]: HTTP response: {"error":"BadRequest","description":"Invalid characters in entity id"}

Used Entity Id: "urn:ngsi-ld:SensorB-#HP-K12_____"

Invalid Character: "#"

As soon as I got raid of "#" Code worked fine.

**Comment by fgalan** [comment]
I think this question should be posted using StackOverflow (https://stackoverflow.com). Please, don't forget to include the "fiware-orion" label.

In addition, when you do that I'd kindly ask you to detail your case a little bit, eg: "I'm using CB and when I send (a given request you should detail) then I get this error: etc.".

Once you have created the question at SOF please add the link in the present issue as a comment. Then, close the issue.

Thanks!

**Comment by c0nb4** [comment]
https://stackoverflow.com/questions/58197309/entity-id-invalid-in-fiware-orion 

Sorry for the Konfusion.
