### ISSUE TITLE
Cannot query some Entities

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/fiware-orion#3567]
Hi
I'm having some issues querying some entities. I have an implementation, in which I have this sample of Entities

`GET {ORION}/v2/entities/`: (Fiware-Service and **Fiware-ServicePath: /farmacias/1**)
``` json
[
    {
        "id": "heladera2",
        "type": "PT100",
        "temperatura": {
            "type": "Float",
            "value": 9,
            "metadata": {}
        }
    },
    {
        "id": "heladera1",
        "type": "PT100",
        "temperatura": {
            "type": "Float",
            "value": 13,
            "metadata": {}
        }
    },
    {
        "id": "Ambiente",
        "type": "Ambient",
        "humedad": {
            "type": "Float",
            "value": 60,
            "metadata": {}
        },
        "temperatura": {
            "type": "Float",
            "value": 13,
            "metadata": {}
        }
    },
    {
        "id": "heladera4",
        "type": "PT100",
        "temperatura": {
            "type": "Float",
            "value": 4,
            "metadata": {}
        }
    }
]
```

However, I have an application that gets the entire list of entities of the service, by querying the endpoint without setting the ServicePath header. In this case I only get a sublist of the entities.
For example `heleadera4` or `Ambiente` do not show up in the list.

Here's a DB sample of the entities shown in the first query:
`
> db.entities.find({"_id.id":"heladera1"})
{ "_id" : { "id" : "heladera1", "type" : "PT100", "servicePath" : "/farmacias/1" }, "attrNames" : [ "temperatura" ], "attrs" : { "temperatura" : { "type" : "Float", "creDate" : 1572369745, "modDate" : 1572369745, "value" : 13, "mdNames" : [ ] } }, "creDate" : 1572369745, "modDate" : 1572369745, "lastCorrelator" : "acf9ae18-fa70-11e9-b2d8-0242ac110005" }
> db.entities.find({"_id.servicePath":"/farmacias/1"})
{ "_id" : { "id" : "heladera1", "type" : "PT100", "servicePath" : "/farmacias/1" }, "attrNames" : [ "temperatura" ], "attrs" : { "temperatura" : { "type" : "Float", "creDate" : 1572369745, "modDate" : 1572369745, "value" : 13, "mdNames" : [ ] } }, "creDate" : 1572369745, "modDate" : 1572369745, "lastCorrelator" : "acf9ae18-fa70-11e9-b2d8-0242ac110005" }
{ "_id" : { "id" : "heladera2", "type" : "PT100", "servicePath" : "/farmacias/1" }, "attrNames" : [ "temperatura" ], "attrs" : { "temperatura" : { "type" : "Float", "creDate" : 1572369734, "modDate" : 1572369734, "value" : 9, "mdNames" : [ ] } }, "creDate" : 1572369734, "modDate" : 1572369734, "lastCorrelator" : "a68a79c2-fa70-11e9-b2d8-0242ac110005" }
{ "_id" : { "id" : "Ambiente", "type" : "Ambient", "servicePath" : "/farmacias/1" }, "attrNames" : [ "temperatura", "humedad" ], "attrs" : { "temperatura" : { "type" : "Float", "creDate" : 1572370866, "modDate" : 1572370866, "value" : 13, "mdNames" : [ ] }, "humedad" : { "type" : "Float", "creDate" : 1572370866, "modDate" : 1572370866, "value" : 60, "mdNames" : [ ] } }, "creDate" : 1572370866, "modDate" : 1572370866, "lastCorrelator" : "48ca008e-fa73-11e9-b2d8-0242ac110005" }
{ "_id" : { "id" : "heladera4", "type" : "PT100", "servicePath" : "/farmacias/1" }, "attrNames" : [ "temperatura" ], "attrs" : { "temperatura" : { "type" : "Float", "creDate" : 1572371018, "modDate" : 1572371018, "value" : 4, "mdNames" : [ ] } }, "creDate" : 1572371018, "modDate" : 1572371018, "lastCorrelator" : "a3e96b62-fa73-11e9-b2d8-0242ac110005" }

` 

Im running Orion in Docker, `fiware/orion@sha256:fe7e9966fa96caa6d786dd0beb89321c07ab080e9297956c10f997a88e05a66d`
Is there any reason I'm not seeing for this weird behaviour? 
Thanks in advance

**Comment by jmezzera** [comment]
I deleted some entities I was not using and then Orion responded with the ones I was looking for.
Could it be that the query response was so long that it was trimmed, leaving some entities behind?

**Comment by Siedlerchr** [comment]
Have you looked into the pagination? You could add the count option in your query to see how  many results you really have for that query and If I remember correctly, orion has a limit (can be configured) how many entities are returned in one  query.
https://fiware-orion.readthedocs.io/en/master/user/pagination/index.html

**Comment by jmezzera** [comment]
Thank you very much, I did not know about that option.
