### ISSUE TITLE
Some possible Null Pointer Dereference bugs

### ISSUE THREAD

**Issue by Enkelmann** [telefonicaid/fiware-orion#3578]
Hi there!
I am currently running some static analysis tools over the code and I already found some Null Pointer Dereference bugs in the code (using [Infer](https://fbinfer.com)) that you might want to replace with proper error handling.
```
src/lib/metricsMgr/MetricsManager.cpp:204: error: NULL_DEREFERENCE
  pointer `spath` last assigned on line 186 could be null and is dereferenced at line 204, column 7.
```
The return value of `strdup` is not checked.
```
src/lib/parseArgs/paUsage.cpp:254: error: NULL_DEREFERENCE
  pointer `spacePad` last assigned on line 253 could be null and is dereferenced by call to `strlen()` at line 254, column 32.
```
Again `strdup`.
```
src/lib/parseArgs/paUsage.cpp:360: error: NULL_DEREFERENCE
  pointer `spacePad` last assigned on line 359 could be null and is dereferenced by call to `strlen()` at line 360, column 32.
```
Again `strdup`.
```
src/lib/parseArgs/paParse.cpp:489: error: NULL_DEREFERENCE
  pointer `progName` last assigned on line 488 could be null and is dereferenced by call to `strdup()` at line 489, column 20.
  488.       progName     = strdup(paProgNameSet(argV[0], level, pid, extra));
  489. >     paProgName   = strdup(progName);
```
If the first `strdup` fails, the second one will get a Null pointer as input.
```
src/lib/jsonParse/jsonParse.cpp:443: error: NULL_DEREFERENCE
  pointer `newContent` last assigned on line 436 could be null and is dereferenced at line 443, column 
```
```
src/lib/logMsg/logMsg.cpp:2772: error: NULL_DEREFERENCE
  pointer `line` last assigned on line 2769 could be null and is dereferenced by call to `fgets()` at line 
```
This time an unchecked `calloc` call.
```
src/lib/logMsg/logMsg.cpp:2909: error: NULL_DEREFERENCE
  pointer `line` last assigned on line 2874 could be null and is dereferenced by call to `fgets()` at line 2909, column 11.
```
Again `calloc`.

**Comment by fgalan** [comment]
Thank you for the report!

Maybe even you could propose a pull request with the changes needed to fix these null pointer dereferences (the one finding the bug should also have the oportunity of getting the glory of solving it ;).

What do you think?

**Comment by Enkelmann** [comment]
I'll have to decline the honour of fixing them. ;-) Error management should be consistent and I am not familiar enough with the project to know the exact way the program should fail (or recover) in these cases.

**Comment by fgalan** [comment]
Ok, no problem. We will try to address them. It would be a great if you could do a new pass with your tool once we fix the code, please, to check it the tool show them as solved.

I will focus by the moment on the ones in metricsMgr and jsonParse. With regards with the ones in logMsg and parseArgs it would be great if @kzangeli could provide the fix (he knows better than me the internals of such modules).

**Comment by kzangeli** [comment]
I wouldn't mind. It is my code after all.
But, before January, impossible.
And after that we'll see.
Swamped in work lately ...

**Comment by fgalan** [comment]
The following PR https://github.com/telefonicaid/fiware-orion/pull/3579 addresses the issues detected.
