### ISSUE TITLE
Semicolon in device attribute

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/fiware-orion#3581]
I was trying to update an entity with a semicolon inside an attribute:

```json
{
    "name": "Accelerometer",
    "type": "string",
    "value": "0;0;0",
    "metadatas": [
        {
            "name": "TimeInstant",
            "type": "ISO8601",
            "value": "2019-12-17T14:13:01.398Z"
        }
    ]
}
```
and got
```json
{
    "errorCode": {
        "code": "400",
        "reasonPhrase": "Bad Request",
        "details": "Illegal value for JSON field"
    }
}
```

Removing the ; solve the error. However, is this behaviour the one expected?

Thanks

**Comment by fgalan** [comment]
Given this is more a question about Orion functionality than an issue, could you move this question to StackOverflow, please? Please use the "fiware-orion" label.

Once you create the question in SOF, please add the link to it as a comment on this issue. Then close the issue.

Thanks!

**Comment by jmezzera** [comment]
Ok, my bad!
https://stackoverflow.com/questions/59376543/are-semicolons-allowed-in-device-attributes
