### ISSUE TITLE
File "common/compileInfo.h" isn't generated by cmake.

### ISSUE THREAD

**Issue by LuisGP** [telefonicaid/fiware-orion#3583]
Hi,
If I compile using the `makefile` script everything works fine but trying to compile using `cmake` it fails with the following error message:

```bash
/fiware-orion/src/lib/serviceRoutines/versionTreat.cpp:34:10: fatal error: common/compileInfo.h: No such file or directory
 #include "common/compileInfo.h"                                                                                   
          ^~~~~~~~~~~~~~~~~~~~~~                                                                       
compilation terminated.           
```

So, it seems that the generated `common/compileInfo.h` isn't being generated when using `cmake`.
I found this issue when compiling in a Ubuntu 18.04.3 docker image.

**Comment by kzangeli** [comment]
That file is generated during the build.
Look at the toplevel makefile, target *compile_info*.

This is the script that genberates `compileInfo.h`:
`scripts/build/compileInfo.sh`

**Comment by LuisGP** [comment]
So, if I want to build using `cmake` what should I do?

**Comment by kzangeli** [comment]
I would strongly propose to use the "normal" make of orion.
We also use cmake.

If you for some reason is unable to do that, make a script that first calls `scripts/build/compileInfo.sh` and then whatever you need.   Use that script for compilation of the broker.

**Comment by LuisGP** [comment]
Ok, thank you very much.
