### ISSUE TITLE
Upgrade built-from-sources dependencies to newer version

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3612]
Orion build procedure (https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html) used the following dependencies, from sources:

* rapidjson: 1.0.2
* microhttpd: 0.9.48

They are somehow old and new versions exist today (probably even newer in the moment this issue gets implemented ;)

* rapidjson: 1.1.0
* microhttpd: 0.9.69

It would be great to upgrade. However, this involves several items:

* Dockefile
* Dockerfile-CI (and pushing the new image to dockerhub, if I'm remembering correctly)
* Building from sources documentation
* Jenkins CI

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

As per my analysis, the version of rapidjson and microhttpd need to upgraded i.e. rapidjson: v1.0.2 to v1.1.0 and microhttpd: v0.9.48 to v0.9.69. For this, version of rapidjson and microhttpd will be updated in Dockerfile, Dockerfile-CI, Building from source documentation and jenkins CI.

Regarding Dockerfile-CI, we need to push the new image to dockerhub.

Please confirm the above understanding and approach.

**Comment by fgalan** [comment]
I think your understanding is correct. Note that the original issue was written some months ago, so maybe at the present momem there are even newer versions that could be used.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/3663

Changes in Jenkins CI are pending. Let's keep the issue open the issue while this can be completed (@fgalan will deal with it)
