### ISSUE TITLE
embedded computer example for using ORION

### ISSUE THREAD

**Issue by GerfriedC** [telefonicaid/fiware-orion#3618]
The examples given for starting using the public instance of ORION are using bash, wget and other functions from a full LINUX installation (also not working on a MAC) and require manual input.
Is there an example for micropython which might be used to retrieve the token automatically at the start of the data uploading script and then every hour?
Many Thanks

**Comment by GerfriedC** [comment]
I would also appreciate PHP based examples, since translating  the given cURL commands has not been sucessful. The parameter -X  without further info stands for what kind of proxy? And the pipe to a python script is for the client side, I guess?

**Comment by fgalan** [comment]
I'd suggest to use StakOverflow (http://www.stackoverflow.com) for this kind of questions. Note that what you are describing is not actually an issue (i.e. problem on the software, case to be debugged, etc.), but a question related with Orion, so I think is better to use that platform which, in addition, is used and c checked by a large community of developers.

Thus:

1. Please open a question (or maybe two?) at SOF. Please use the "fiware-orion" label.
2. Add the link that question (or questions) as comment in this issue.
3. Close the issue

Thanks!

**Comment by GerfriedC** [comment]
> 
> 
> I'd suggest to use StakOverflow (http://www.stackoverflow.com) for this kind of questions. Note that what you are describing is not actually an issue (i.e. problem on the software, case to be debugged, etc.), but a question related with Orion, so I think is better to use that platform which, in addition, is used and c checked by a large community of developers.
> 
> Thus:
> 
>     1. Please open a question (or maybe two?) at SOF. Please use the "fiware-orion" label.
> 
>     2. Add the link that question (or questions) as comment in this issue.
> 
>     3. Close the issue
> 
> 
> Thanks!

Thanks for your hint. Could be part of the documentation adding How-Tos for different languages.

**Comment by fgalan** [comment]
Did you finally asked the questions in SOF? Do you have the links to them?

With regards to:

> Thanks for your hint. Could be part of the documentation adding How-Tos for different languages.

Currently we have a translation of the English documentation to Japanese. We are of course open to contributions of new translations (as far as there are a commitment to upgrade the translation each time the master doc in English changes ;)

Thanks!

**Comment by GerfriedC** [comment]
Languages means PHP and Python/Micropython - not only examples for the command line.

**Comment by fgalan** [comment]
Ah... you mean programming languages... I completely misunderstand your comment, sorry :D

The [API walkthrouth](https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html) was deliberately written based on curl command to be language-agnostic, as we wanted to be neutral and didn't take preference of any language/developer over any other.

However, we are open to contributions, so if somebody wants to do a version of the walkthrough based in a specific language (basically, keeping the same document structure bug changing the curls by code snippets in given languages) we would be very happy to include it in the documentation.

Maybe you want to volunteer with python and/or PHP? ;)

**Comment by GerfriedC** [comment]
Dear Fermin,

ok- unfortunately  I have one task bringing data to FIWARE. I was pointed towards Postman by your German colleague, but again that does not work. There is some fundamental difference between using curl in the terminal and PHP.
Any hints?


many thanks


best regards

Gerfried
