### ISSUE TITLE
DELETE with wrong header returns 404 although entity is existing

### ISSUE THREAD

**Issue by Siedlerchr** [telefonicaid/fiware-orion#3633]
We accidentaly inserted entities into orion using the wrong header (typo)
`fiware-service-path` instead of the correct one `fiware-servicepath` (withouht the last hyphen) and now I am unanble to delete the entities. I also tested the [python script delete_entities_by_query](https://github.com/telefonicaid/fiware-orion/blob/master/scripts/utils/delete_entities_by_query.py) direclty on the server without any authorization and that also returns a list of entities.

```
There are 61 entities
There are 0 pages of 500 entities (and a final page of 61 entities)
```

Trying to delete always result ins a 404 although the following query returns entites:

```curl --location --request GET 'https://<orion>/v2/entities?type=abc' \
--header 'fiware-service: something' \
--header 'fiware-service-path: asdf' \
--header 'Authorization: Bearer TOKEN'
```
e.g. returns an entity 
`id:urn:ngsi-ld:6c99ecaa-5cee-4f27-b936-3ccbe8c42d66`

DELETE: 
```
curl --location --request DELETE 'https://<orion>/v2/entities/urn:ngsi-ld:6c99ecaa-5cee-4f27-b936-3ccbe8c42d66' \
--header 'fiware-service: something' \
--header 'fiware-service-path: asdf' \
--header 'Authorization: Bearer TOKEN'
```
returns a 404.
`{"error":"NotFound","description":"The requested entity has not been found. Check type and id"}`

**Comment by fgalan** [comment]
I think this is more a question about functionality than an identified issue/bug. Thus, I'd suggest to move it to http://www.stackoverflow.com and deal with it there.

Thus, could you create the corresponding question in SOF (mostly a copy paste), please? Please add "fiware-orion" label.

Once done, add a link to the question in this issue, then close the issue.

Thanks!

**Comment by Siedlerchr** [comment]
https://stackoverflow.com/q/60544817/3450689

**Comment by Siedlerchr** [comment]
I posted this on SO, but I nonetheless think it's a bug. I mean the entities are there and found, but can't be deleted.

**Comment by fgalan** [comment]
> I posted this on SO, but I nonetheless think it's a bug. I mean the entities are there and found, but can't be deleted.

If at the end this is confirmed as a bug (after discussing it at SOF) then this issue can be reopened.
