### ISSUE TITLE
statistics in multi-tenancy mode

### ISSUE THREAD

**Issue by fabiocabrini** [telefonicaid/fiware-orion#3648]
I would like to know if there is a way to extract the statistics for each client, when Orion is running in multi-tenancy mode?

**Comment by fgalan** [comment]
I think I can provide some feedback on it but, not I think is better to do it using StackOverflow (http://www.stackoverflow.com), as this is not really an issue (bug, etc.) on the software. 

Could you post your question in SOF, please? By doing a copy-paste of your original question it should be inexpensive :) Please use the "fiware-orion" label.

Once done, please add the link to SOF question as comment in this issue. Then close the issue.

Thanks!

**Comment by fabiocabrini** [comment]
Done

**Comment by fgalan** [comment]
Link to question: https://stackoverflow.com/questions/61624953/statistics-in-multi-tenancy-mode-on-cef-context-broker/61628888#61628888
