### ISSUE TITLE
Case sensitive issue in querying

### ISSUE THREAD

**Issue by rvnair10** [telefonicaid/fiware-orion#3649]
How I can ignore case, by doing query in Fiware Context Broker.

For example I have a query like:

v2/entities/?options=keyValues&type=Room&q=name==xyz

But this query doesn't return all the Rooms which names includes Xyz,XYZ,XyZ etc.

Could you please advice me, how we can do ignore case here.

**Comment by fgalan** [comment]
I think this is more a question about functionality than an issue on the software. So, it would be better deal with this question in http://www.stackoverflow.com. Could you post the question there (basically, a copy-paste of the above text), please? Please use the "fiware-orion" label.

Once done, please add a link to the question in a new comment in this issue, then close the issue.

Thanks!

**Comment by rvnair10** [comment]
Done. Link to Stackoverflow [here](https://stackoverflow.com/questions/61768303/ignore-case-in-fiware-queries).

**Comment by rvnair10** [comment]
@fgalan , could you please share a solution in stackoverflow?

**Comment by fgalan** [comment]
Looking to SOF, I see that @jmcanterafonseca already provided an answer. Have you have a look to it? Is not correct?

Just to understand the case here...

**Comment by rvnair10** [comment]
I tried the option already and it ia not working. Since we have limited documentation available on idPattern, it would be really helpful if you could give a sample. Thanks.
