### ISSUE TITLE
Not equal condition not working with ID

### ISSUE THREAD

**Issue by rvnair10** [telefonicaid/fiware-orion#3650]
Lets assume I have three Room entities with ids

- urn:ngsi-Id:Room:Room1
- urn:ngsi-Id:Room:Room2
- urn:ngsi-Id:Room:Room3

Now I want to query all entities where id not equal urn:ngsi-Id:Room:Room2.

I tried != operator - not working. Also tried idPattern - not working.

Could you please advice how we can do this?

**Comment by fgalan** [comment]
I think this is more a question about functionality than an issue on the software. So, it would be better deal with this question in http://www.stackoverflow.com. Could you post the question there (basically, a copy-paste of the above text), please? Please use the "fiware-orion" label.

Once done, please add a link to the question in a new comment in this issue, then close the issue.

Thanks!

**Comment by rvnair10** [comment]
Done. Link to Stackoverflow [here](https://stackoverflow.com/questions/61695007/fiware-context-brocker-how-to-query-entities-with-not-equal-condition-to-its-id).

**Comment by rvnair10** [comment]
@fgalan could you please provide a solution in stackoverflow?

**Comment by fgalan** [comment]
Looking to SOF, I see that @jmcanterafonseca already provided an answer. Have you have a look to it? Is not correct?

Just to understand the case here...

**Comment by rvnair10** [comment]
I tried the first option already but its not working. For idPattern option, I didn't get much detail to do so from fiware docs. It would be really helpful if you can give a sample.
