### ISSUE TITLE
Update entity type

### ISSUE THREAD

**Issue by abrahamSecmotic** [telefonicaid/fiware-orion#3651]
Hi,

I'd like to update the entity type, but couldn't find the request to do so. It may not be possible, but I don't understand the reason.

I tried updating the entity type with IoTA. The IoTA was updated but Orion was not.

Is this a issue to fix ? or I dont understand the funcionality of entityType.

Thanks.

**Comment by fgalan** [comment]
I think this is more a question about functionality than an issue on the software. So, it would be better deal with this question in http://www.stackoverflow.com. Could you post the question there (basically, a copy-paste of the above text), please? Please use the "fiware-orion" label.

Once done, please add a link to the question in a new comment in this issue, then close the issue.

Thanks!

**Comment by abrahamSecmotic** [comment]
Ok @fgalan .

Here the question: https://stackoverflow.com/questions/61884909/fiware-orion-why-is-the-entity-type-inmutable

Thanks!
