### ISSUE TITLE
Build orion for raspberry

### ISSUE THREAD

**Issue by JackMind** [telefonicaid/fiware-orion#3662]
Hello,

I'm trying to build an orion image to run on a raspberry, I used the Dockerfile on the repo and change the label of the centos image to 7, an go this error (below):

Error: Nothing to do
The command '/bin/sh -c adduser --comment "${ORION_USER}" ${ORION_USER} &&     yum -y install epel-release &&     yum -y install       boost-devel       bzip2       cmake       gnutls-devel       libgcrypt-devel       libcurl-devel       openssl-devel       libuuid-devel       make       nc       git       gcc-c++       scons       tar       which       cyrus-sasl-devel &&     cd /opt &&     curl -kOL http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.48.tar.gz &&     tar xvf libmicrohttpd-0.9.48.tar.gz &&     cd libmicrohttpd-0.9.48 &&     ./configure --disable-messages --disable-postprocessor --disable-dauth &&     make &&     make install &&     ldconfig &&     cd /opt &&     curl -kOL https://github.com/mongodb/mongo-cxx-driver/archive/legacy-1.1.2.tar.gz &&     tar xfz legacy-1.1.2.tar.gz &&     cd mongo-cxx-driver-legacy-1.1.2 &&     scons --use-sasl-client --ssl &&     scons install --prefix=/usr/local --use-sasl-client --ssl &&     cd /opt &&     curl -kOL https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz &&     tar xfz v1.0.2.tar.gz &&     mv rapidjson-1.0.2/include/rapidjson/ /usr/local/include &&     cd /opt &&     git clone https://github.com/${GIT_NAME}/fiware-orion &&     cd fiware-orion &&     git checkout ${GIT_REV_ORION} &&     make &&     make install &&     strip /usr/bin/contextBroker &&     mkdir -p /var/log/contextBroker &&     mkdir -p /var/run/contextBroker &&     chown ${ORION_USER} /var/log/contextBroker &&     chown ${ORION_USER} /var/run/contextBroker &&     cd /opt &&     if [ ${CLEAN_DEV_TOOLS} -eq 0 ] ; then yum clean all && exit 0 ; fi &&     rm -rf /opt/libmicrohttpd-0.9.48.tar.gz            /usr/local/include/microhttpd.h            /usr/local/lib/libmicrohttpd.*            /opt/libmicrohttpd-0.9.48            /opt/legacy-1.1.2.tar.gz            /opt/mongo-cxx-driver-legacy-1.1.2            /usr/local/include/mongo            /usr/local/lib/libmongoclient.a            /opt/rapidjson-1.0.2            /opt/v1.0.2.tar.gz            /usr/local/include/rapidjson            /opt/fiware-orion            /usr/share/cracklib            /usr/share/i18n /usr/{lib,lib64}/gconv            &&     yum -y erase git perl* rsync         cmake libarchive         gcc-c++ cloog-ppl cpp gcc glibc-devel glibc-headers         kernel-headers libgomp libstdc++-devel mpfr ppl         scons boost-devel libcurl-devel gnutls-devel libgcrypt-devel         clang llvm llvm-libs         CUnit-devel CUnit         autoconf automake m4 libidn-devel         boost-wave boost-serialization boost-python         boost-iostreams boost boost-date-time         boost-test boost-graph boost-signals         boost-program-options boost-math         openssh openssh-clients libedit hwdata dbus-glib fipscheck* *devel sysvinit-tools         &&     rpm -qa groff | xargs -r rpm -e --nodeps &&     yum clean all && rm -rf /var/lib/yum/yumdb && rm -rf /var/lib/yum/history &&     rpm -vv --rebuilddb &&     find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name 'en_US' ! -name 'locale.alias' | xargs -r rm -r &&     bash -c 'localedef --list-archive | grep -v -e "en_US" | xargs localedef --delete-from-archive' &&     /bin/cp -f /usr/lib/locale/locale-archive /usr/lib/locale/locale-archive.tmpl &&     build-locale-archive &&     rm -f /var/log/*log' returned a non-zero code: 1

**Comment by fgalan** [comment]
Did you follow the procedure described at https://github.com/telefonicaid/fiware-orion/blob/master/docker/raspberry_pi.md ?

**Comment by fgalan** [comment]
No feedback has been received on this in many months.

Thus, we would assume that the procedure described in the above link is correct and solve this issue. Please tell us @JackMind if we are wrong so this issue can be reopened. Thanks!
