### ISSUE TITLE
Add attribute to multiple created entities with same id pattern

### ISSUE THREAD

**Issue by JorgeSilva7** [telefonicaid/fiware-orion#3678]
Hi,

I didn't found in documentation or source code the specifications to add attribute to multiple created entities with same id pattern. Only found the method for add attr to entity one by one (with array), but [this method ](https://fiware-orion.readthedocs.io/en/1.2.1/user/append_and_delete/index.html) doesn't work (lazy method) when need add attribute to 100+ entities with id pattern (idIot:1, ... , idIot:N).

Any help?

**Comment by fgalan** [comment]
This is more a support question than an actual issue on the Orion Context Broker software. Thus, could you pot is at https://www.stackoverflow.com, please? Use "fiware-orion" tab.

Once published at SOF, add the link to the question as comment in this issue. Then, close the issue.

Thanks!

**Comment by JorgeSilva7** [comment]
https://stackoverflow.com/questions/63177898/add-attribute-to-multiple-created-entities-with-same-id-pattern
