### ISSUE TITLE
Orion returns data from context provider for entities filtered out by query

### ISSUE THREAD

**Issue by LarsNorlander** [telefonicaid/fiware-orion#3689]
## Steps to Reproduce
1. Start up the context provider example as specified on the [NGSI Step-by-Step Context Providers](https://fiware-tutorials.readthedocs.io/en/latest/context-providers/index.html#start-up) page.
2. With the provided [Postman Collection](https://app.getpostman.com/run-collection/7c9bed4bd2ce5213a80b), under the folder "Context Provider Registration Actions", run the request "Register a Context Provider - Weather".
3. Make the following request request to `http://localhost:1026/v2/entities?type=Store&q=name=='Bösebrücke'`. Which is a query for all Stores, where the name is exactly equal to `"Bösebrücke"`.

## Expected Result
Since there are no stores with the exact name `"Bösebrücke"` (the store that actually exists is named `"Bösebrücke Einkauf"`), it should return an empyt array as a response.

## Actual Result
The context broker still gives back the data from the context provider, which is the temparature and relative humidy attributes for Store:001, which is the store named `"Bösebrücke Einkauf"`.
```json
[
    {
        "id": "urn:ngsi-ld:Store:001",
        "type": "Store",
        "temperature": {
            "type": "Number",
            "value": 9,
            "metadata": {}
        },
        "relativeHumidity": {
            "type": "Number",
            "value": 34,
            "metadata": {}
        }
    }
]
```
---
Another request to try is `http://localhost:1026/v2/entities?type=Store&q=name=='Tower Trödelmarkt'`, where you request for all Stores with the exact name of `"Tower Trödelmarkt"`.

Surely enough, you get the information for the store named "Tower Trödelmarkt" (Store:004). But you also get the data provided by the context provider for the store "Bösebrücke Einkauf" (Store:001).

```json
[
    {
        "id": "urn:ngsi-ld:Store:004",
        "type": "Store",
        "address": {
            "type": "PostalAddress",
            "value": {
                "streetAddress": "Panoramastraße 1A",
                "addressRegion": "Berlin",
                "addressLocality": "Mitte",
                "postalCode": "10178"
            },
            "metadata": {}
        },
        "location": {
            "type": "geo:json",
            "value": {
                "type": "Point",
                "coordinates": [
                    13.4094,
                    52.5208
                ]
            },
            "metadata": {}
        },
        "name": {
            "type": "Text",
            "value": "Tower Trödelmarkt",
            "metadata": {}
        }
    },
    {
        "id": "urn:ngsi-ld:Store:001",
        "type": "Store",
        "temperature": {
            "type": "Number",
            "value": 24,
            "metadata": {}
        },
        "relativeHumidity": {
            "type": "Number",
            "value": 14,
            "metadata": {}
        }
    }
]
```

And so it seems as if the context broker request for data from the context providers despite an entity being filtered out by the query, and then providing that data in the response when it shouldn't be there.

## Affected Versions
* [fiware/orion:latest](https://hub.docker.com/layers/fiware/orion/latest/images/sha256-1d546240c4b1c8d340e7c8e158545ae87d7da4ea8b3c213e23c841a7ca26e994?context=explore) – I have first noticed the issue in this version working on my own project.

**Comment by fgalan** [comment]
Thank you for so detailed report.

Maybe is the same issue described at https://github.com/telefonicaid/fiware-orion/issues/3676 and/or https://github.com/telefonicaid/fiware-orion/issues/2282 ?

**Comment by LarsNorlander** [comment]
Ahh, it seems to match #3676 but just worded differently. And I suppose #2282 is the root issue. So I suppose you'd prefer to have this issue closed then?

**Comment by fgalan** [comment]
> Ahh, it seems to match #3676 but just worded differently. And I suppose #2282 is the root issue.

If you find this issue is fully covered by some other one, maybe is a good idea to close it as a duplicate. That way we reduce the issue entropy in the repository :)

**Comment by LarsNorlander** [comment]
Sure, I'll do that then.
