### ISSUE TITLE
logLineMaxSize and logLineMaxSize in the log admin REST API

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3707]
In the re-work done in issue https://github.com/telefonicaid/fiware-orion/issues/3694 the following parameters were introduced in the CLI:

* `-logLineMaxSize`
* `-logInfoPayloadMaxSize`

It could be a good idea to include them in the log admin API, so they can be dyncamically changed, allowing things like this:

```
PUT /admin/log?infoPayloadMaxSize=10240
```

```
GET /admin/log

{
   "level": "INFO"
   "infoPayloadMaxSize": 10240,
   "lineMaxSize": 32768
}
```

Each setting is associated to a global variable, so connect them with the existing management API shouldn't be difficult.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I would like to work on this issue, Please assign this issue to me. Thank you.

**Comment by fgalan** [comment]
Assigned. Thank you very much!

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I have done investigation on this issue. As per my understanding we need to add PUT and GET method for logLineMaxSize and logInfoPayloadMaxSize in log admin API.

To GET logLineMaxSize and logInfoPayloadMaxSize we need to modify serviceRoutinesV2/logLevelTreat.cpp and add "lmLogLinesGet" method for getting logLineMaxSize but I have not found something for PUT method. 

Currently I am leaving this issue, and working on another issue.

**Comment by Anjali-NEC** [comment]
Hi @fgalan Sir,

I am not working on this issue as mention in comment https://github.com/telefonicaid/fiware-orion/issues/3707#issuecomment-740019821

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan Sir, I would like to work on this issue, Please assign this issue to me. 

I have started the investigation.
Thank you:)

**Comment by fgalan** [comment]
@ArqamFarooqui110719 you have been assigned

Thanks for your willingness to work on this issue!

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan Sir,
As per my investigation, mainly below 2 functions need to be modified for this issue i.e.
```
changeLogLevel() and getLogLevel()
```
in `src/lib/serviceRoutinesV2/logLevelTreat.cpp` file.

I think these function names were given only for the "Log Level" functionality. As now we are modifying the functions and adding new details so these function names should also be change. For e.g.
```
changeLogDetails() and getLogDetails() respectively.
```

Please let me know your opinion?

**Comment by fgalan** [comment]
I'd suggest the following names:

* changeLogConfig()
* getLogConfig()

**Comment by ArqamFarooqui110719** [comment]
> I'd suggest the following names:
> 
> * changeLogConfig()
> * getLogConfig()

It looks better. Thanks:)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/4289
