### ISSUE TITLE
Auth fail at recoverOntimeIntervalThreads() should be properly logged

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-orion#373]
In an environment with a balancer with 3 Nodes and a replica set to mongodB, we had problem when installing CB in each node.
Steps:
1- try to run contextBroker normally and show ok, but the service isn't running (service contextBroker start)

2- show the status of contextBroker Service (service ContexBroker status) and return this message:
      Checking contextBroker...                         Process dead but pidfile exists

3- Remove redirection to "/dev/null" in etc/init.d/contextBroker:
       if [ -x /usr/bin/${NAME} ]; then
        su $BROKER_USER -c "/usr/bin/${NAME} ${BROKER_OPTS} > /dev/null 2>&1"

     and show that:
Starting contextBroker...                         log directory: '/var/log/contextBroker'
Ok
[sysadmin@qa-orion-fe-01 ServerAgent]$ F@11:40:02  ***[600]: Connected to mongo at qa-orion-be-02:orion
Mon May 12 13:40:02 Assertion: 13111:field not found, expected type 7
terminate called after throwing an instance of 'mongo::MsgAssertionException'
  what():  field not found, expected type 7

    in  log (/var/log/contextBroker/contexBtokerLog) :
Started Monday 12 May 11:40:02 2014
Cleared at ...
F:Monday 12 May 11:40:02 2014(391):contextBroker-/contextBroker.cpp[600] ***: Connected to mongo at qa-orion-be-02:orion

4- After using gdb these results were obtained: 

```
(gdb) r -fg -db orion -dbhost qa-orion-be-02
Starting program: /usr/bin/contextBroker -fg -db orion -dbhost qa-orion-be-02
[Thread debugging using libthread_db enabled]
[New Thread 0x7ffff52cf700 (LWP 21651)]
[Thread 0x7ffff52cf700 (LWP 21651) exited]
F@09:32:56  ***[600]: Connected to mongo at qa-orion-be-02:orion
Tue May 13 11:32:56 Assertion: 13111:field not found, expected type 7
terminate called after throwing an instance of 'mongo::MsgAssertionException'
  what():  field not found, expected type 7

Program received signal SIGABRT, Aborted.
0x00007ffff6a9b925 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6a9b925 in raise () from /lib64/libc.so.6
#1  0x00007ffff6a9d105 in abort () from /lib64/libc.so.6
#2  0x00007ffff7355a5d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
#3  0x00007ffff7353be6 in ?? () from /usr/lib64/libstdc++.so.6
#4  0x00007ffff7353c13 in std::terminate() () from /usr/lib64/libstdc++.so.6
#5  0x00007ffff7353d0e in __cxa_throw () from /usr/lib64/libstdc++.so.6
#6  0x0000000000759700 in mongo::msgasserted(int, char const*) ()
#7  0x000000000075978c in mongo::msgasserted(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x00000000005c7622 in mongo::BSONElement::chk(int) const ()
#9  0x00000000005c6e8b in mongo::BSONElement::OID() const ()
#10 0x00000000005bc234 in recoverOntimeIntervalThreads() ()
#11 0x00000000005a58ff in ?? ()
#12 0x00000000005a6665 in main ()
(gdb)
5- we try to connect at mongo instance remotelly (mongo --host qa-orion-be-02 orion)
> show collections
Tue May 13 11:14:05 uncaught exception: error: {
 "$err" : "not authorized for query on orion.system.namespaces",
 "code" : 16550
}
>
```

It is impossible to attach a file .log o .rpm. I have a copy of gdb.log (complete) and contextBroker-0.12.0_f9b8ec6_next-dev.x86_64.rpm (current)

**Comment by fgalan** [comment]
ONTIMEINTERVAL functionality has been deprecated in 0.26.0. Thus, according to (https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/deprecated.md):

>  Bugs or issues related with deprecated features and not affecting any other feature are not addressed (they are closed in github.com as soon as they are spotted).

This issue is closed.
