### ISSUE TITLE
Device registration is not working with iotagent due registration failure in orion

### ISSUE THREAD

**Issue by achandana** [telefonicaid/fiware-orion#3734]
We are not able to register the device with iot agent. 

Device provisioning :
curl --location --request POST 'http://localhost:4041/iot/devices/' \
--header 'fiware-service: openiot' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--data-raw'{
"devices": [
{
"device_id": "lamp001",
"entity_name": "urn:ngsi-ld:Lamp:001",
"entity_type": "Lamp",
"transport": "MQTT",
"commands": [
{"name": "on","type": "command"},
{"name": "off","type": "command"}
],
"attributes": [
{"object_id": "s", "name": "state", "type":"Text"},
{"object_id": "l", "name": "luminosity", "type":"Integer",
"metadata":{
          "unitText":{
                "type":"Text",   
                "value":"degree Celsius"
          },
          "Point_Class":{
                "type":"Text",   
                "value":"Sensor"
          },
          "Category":{
                "type":"Text",   
                "value":"HVAC"
          },
          "Kind":{
                "type":"Text",   
                "value":"AC"
          },
          "Setpoint_Min":{
                "type":"Text",   
                "value":"0"
          },
          "Setpoint_Max":{
                "type":"Text",   
                "value":"0"
          },
          "Frequency":{
                "type":"Text",   
                "value":""
          }
       }}
]
}
]
}'

 we are getting the below error
{
    "name": "BAD_REQUEST",
    "message": "Request error connecting to the Context Broker: 400"
}

We are getting below error in iot agent logs 

time=2020-12-03T08:08:03.476Z | lvl=ERROR | corr=fdaad05a-174f-4e13-b8a7-e450dc848aaf | trans=fdaad05a-174f-4e13-b8a7-e450dc848aaf | op=IoTAgentNGSI.DeviceService | srv=n/a | subsrv=n/a | msg=**Registration error connecting to the Context Broker: 400** | comp=IoTAgent

time=2020-12-03T08:08:03.476Z \| lvl=DEBUG \| corr=fdaad05a-174f-4e13-b8a7-e450dc848aaf \| trans=fdaad05a-174f-4e13-b8a7-e450dc848aaf \| op=IoTAgentNGSI.DeviceProvisioning \| srv=n/a \| subsrv=n/a \| msg=Device provisioning failed due to the following error:  \| comp=IoTAgent Request error connecting to the Context Broker: 400 | time=2020-12-03T08:08:03.476Z \| lvl=DEBUG \| corr=fdaad05a-174f-4e13-b8a7-e450dc848aaf \| trans=fdaad05a-174f-4e13-b8a7-e450dc848aaf \| op=IoTAgentNGSI.DeviceProvisioning \| srv=n/a \| subsrv=n/a \| msg=Device provisioning failed due to the following error: \| comp=IoTAgent **Request error connecting to the Context Broker: 400**

Can anyone please help to fix this issue.

**Comment by fgalan** [comment]
This seems to be an exact duplicate (copy-paste) of https://github.com/telefonicaid/iotagent-json/issues/517

Please don't do that :) Let's use only one issue in one of the components (and in this case, I think the proper one is IOTA-JSON). If at the end this is an issue in Orion, it will be transfered between repos.
