### ISSUE TITLE
Problem when the entity value attribute contain special charcter

### ISSUE THREAD

**Issue by amfgomez1219** [telefonicaid/fiware-orion#3776]
Hello
I have tied to insert in OCB an entity with a password attribute codified: 

``````
{
        "id": "prueba-tipo-string2",
        "type": "StringParser",
       "dateObserved": {
            "type": "DateTime",
            "value": "2020-08-13T08:56:56.00Z"
        },
        "password": {
            "type": "text",
            "value": "U2FsdGVkX10bFP8Rj7xLAQDFwMBphXpK/+leH3mlpQ="
        }
    }
```````

* OCB always response to me with the following error: 
"found a forbidden character in the value of an attribute"
* In Postman 
`````
{
    "error": "BadRequest",
    "description": "Invalid characters in attribute value"
}
``````

**Comment by fgalan** [comment]
This is more a question on Orion functionality than an issue of the software. Thus, could you post at http://telefonicaid.github.io/fiware-orion/api/v2/stable/, please? Basically, a copy-paste of the text in the issue. Please use the "fiware-orion" label.

Onces the SOF post has been created, please include the link as a comment in this issue. Then, close the issue. Thanks!

**Comment by amfgomez1219** [comment]
https://ask.fiware.org/question/1223/problem-when-the-entity-value-attribute-contain-special-character/

**Comment by fgalan** [comment]
Sorry I use a wrong link in my comment above :)

I refer to: http://stackoverflow.com

**Comment by amfgomez1219** [comment]
https://stackoverflow.com/questions/66238207/problem-when-the-entity-value-attribute-contain-special-character
