### ISSUE TITLE
Is Orion compatible with AWS DocumentDB

### ISSUE THREAD

**Issue by avkash08** [telefonicaid/fiware-orion#3778]
I am trying to connect Orion with AWS DocumentDB but it's not getting connected. However I tried two other FIWARE components IoTAgent and Sth-Comet with DocumentDB and both are working fine.

Same DocumentDB hostname and credentials are working for IoTAgent and Sth-Comet. I also checked for the connectivity, which is fine, as IoTAgent and Sth-Comet are in same network. I also checked from a different mongo host in same network and this also worked. Below is the error that I am getting for Orion.

`time=2021-02-18T07:03:46.293Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[180]:mongoConnect | msg=Database Startup Error (cannot connect to mongo - doing 100 retries with a 1000 millisecond interval)`

Is there any possibility that Orion is not compatible with AWS DocumentDB?

**Comment by fgalan** [comment]
I think it should be better to deal with your question using https://stackoverflow.com. Could you post a question there, please? Basically, a copy-paste of the text in the issue. Please use the "fiware-orion" label.

Once the SOF post has been created, please include the link as a comment in this issue.

If at the end, after investigation dealing with the question in SOF, we discover there is a problem in the sofware, we will deal with it using this issue. Otherwise, it will be closed.

Thanks!

**Comment by avkash08** [comment]
Hi Fgalan,
Thanks for your replay.

I had already posted this issue on SOF before on this page. As of now, I haven't received any update on this.

https://stackoverflow.com/questions/66255887/is-orion-compatible-with-aws-documentdb

Moreover, during my investigation I found one link on SOF which is a bit similar but not matching with my use case.
https://stackoverflow.com/questions/63842042/fiware-stack-iotagent-orion-context-broker-compatibility-with-aws-documentdb-ins

**Comment by fgalan** [comment]
Maybe the new mongo driver we are going to use in Orion for next release (work in progress in PR #3622) may work. There is an experimental docker version available and it would be great if you could test with it and tell us how it goes.

This is the image to use `telefonicaiot/fiware-orion:newdriver`.

Thanks for the feedback!

**Comment by fgalan** [comment]
> Maybe the new mongo driver we are going to use in Orion for next release (work in progress in PR #3622) may work. There is an experimental docker version available and it would be great if you could test with it and tell us how it goes.
> 
> This is the image to use `telefonicaiot/fiware-orion:newdriver`
> 
> Thanks for the feedback!

Hold on... it seems there is some kind of problem with that image. I'll tell you when it gets ready again.

**Comment by fgalan** [comment]
> Hold on... it seems there is some kind of problem with that image. I'll tell you when it gets ready again.

Fixed. Now the image can be pulled and used. Sorry for the inconveniences.

**Comment by fgalan** [comment]
> 
> 
> Maybe the new mongo driver we are going to use in Orion for next release (work in progress in PR #3622) may work. There is an experimental docker version available and it would be great if you could test with it and tell us how it goes.
> 
> This is the image to use `telefonicaiot/fiware-orion:newdriver`
> 
> Thanks for the feedback!

If you pass me the access information to your AWS DocumentDB database in the cloud (maybe using a private channel, if sensible information like passwords is involved) I can do the test (similar to what I dit at https://github.com/telefonicaid/fiware-orion/issues/3797)

**Comment by fgalan** [comment]
> This is the image to use telefonicaiot/fiware-orion:newdriver

PR #3622 has been merged into master. Thus, we can use `:latest` from now on. In fact, `:newdriver` label will be removed from dockerhub.

**Comment by fgalan** [comment]
Supposedly fixed in PR #3622, similar to #3797. Closing issue.

However, it will be great to have feedback from @avkash08 to confirm it.

**Comment by avkash08** [comment]
Hi Fgalan,

Thanks for your throughout support.

In last quarter, we used pod based MondoDB due to this issue. Now, we will revisit this activity in this quarter again and will test this again. I will update you accordingly.

Thankyou..!!!
