### ISSUE TITLE
Failing notifications

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#381]
### Description
Right now, the broker has no check whatsoever about subscription notifications that don't reach their intended destiny.
The broker can receive a subscription request for an IP address that isn't responding.

We need to implement some checks here.

### Ideas
1. At receiving the subscription request, the broker could send a 'notification test' to the receiver of the notifications (the reference) and if this notification fails, the subscription is refused.
2. ~~For ONTIMEINTERVAL subscriptions - if a notification fails, the interval is changed to ten times its original amount until it starts working again~~ ONTIMEINTERVAL no longer supported
3. If ANY notification-endpoint has a failure N times in a row, the subscription is simply deleted.

**Comment by fgalan** [comment]
At the end, we are not implementing such mechanism. From @mrutid 

> La automágia siempre es mala y tiene daños colaterales. Nunca es buena opción que el software decida por ti (máxime si es un componente de BE multitenant). Ok a API [para activación/desactivación de subscripciones], Ok a alarmas. NO OK a tomar decisiones por nuestra cuenta (al final seria una configuración por cada suscripción que podría sembrar el caos y un exceso de configuración).

Thus, this issue is gogint to be closed.
