### ISSUE TITLE
Allow Case-Insensitive Queries

### ISSUE THREAD

**Issue by JeffersonLupinacci** [telefonicaid/fiware-orion#3840]
Allow Case Insensitive Queries

![image](https://user-images.githubusercontent.com/25394576/114871037-25b57a80-9df9-11eb-9da3-585c2a7a8449.png)

![image](https://user-images.githubusercontent.com/25394576/114871150-467dd000-9df9-11eb-8793-f029fb3b7a25.png)

![image](https://user-images.githubusercontent.com/25394576/114871419-8d6bc580-9df9-11eb-8373-b52e34f82e3b.png)

**Comment by fgalan** [comment]
Thanks for the feedback!

Could you tell the operation you are using? The Postman screenshot only shows part of the payload, but not the verb + URL...

**Comment by fgalan** [comment]
In addition, which version of Orion Context Broker are you using?

**Comment by fgalan** [comment]
NGSIv1 has been removed in Orion 4.0.0 (deprecated more than 5 years ago) so this issue can be closed.

@JeffersonLupinacci if you experiment similar problems in NGSIv2 API, please tell us so.
