### ISSUE TITLE
Option to disable query forwarding at client side

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3851]
Implement an option so CB doesn't trigger CPr forwarding on queries. This will increase the flexibility and control for client in some scenarios.

Eg:

```
GET /v2/entities?options=noForward
```

**Comment by asainzp** [comment]
I need that functionality for a project where we are using IOTA commands.

**Comment by kzangeli** [comment]
Would it not be more appropriate to use an HTTP header for this functionality?

**Comment by fgalan** [comment]
I tend to think that a URL query param is more handy for user, but if some HTTP exists (in the HTTP spec itself or side spec) with that semantic, it could be considered. Do you have a particular header in mind?

**Comment by kzangeli** [comment]
No particular header in mind (`FIWARE-Forwarding: off`?).
It's just not part of the query and IMO it would be cleaner to use an HTTP header instead.

**Comment by fgalan** [comment]
Given that no standard HTTP header exists for that and taking into account we are using options for avoiding initial notifications in subs (which is somehow a similar case) I think is better using something like `?options=skipForwarding`.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/3865 implementing `skipForwarding` option.

**Comment by fgalan** [comment]
Implemented now in `:latest`, it will be available in next CB version 3.1.0. Closing issue.
