### ISSUE TITLE
Document request using Apiary

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#389]
Make sure we have examples of ALL payloads, for both XML and JSON in the wiki.

Preferably as a list with links, like this:

XML Example payloads:
  o registerContextRequest   <hrefs to later in the wiki?>
  o registerContextResponse
  o discoverContextAvailabilityRequest
  o discoverContextAvailabilityResponse

JSON Example payloads:
  o registerContextRequest
  o registerContextResponse
  o discoverContextAvailabilityRequest
  o discoverContextAvailabilityResponse

All standard payloads and all payloads for convenience operations should be in the lists. Actually, some of the convenience operations use the same payload. The best would be to list all convops (and link to the payload part).

This kind of info is pretty typical presented as an 'appendix'.

**Comment by fgalan** [comment]
Part of this work has been already done (NGSI10 convenience operations). The work goes on.

**Comment by fgalan** [comment]
Given that the work has been started and it is progressing at good pace (see the doc/apiary directory) I think this issue is no longer necessary. Closing.
