### ISSUE TITLE
How can I use the federation function?

### ISSUE THREAD

**Issue by ctc-enokida** [telefonicaid/fiware-orion#3891]
Hi

I am currently trying out the federation feature.
However, when I followed the steps described in this document, the data was also registered in the second Orion.

https://fiware-orion.letsfiware.jp/user/federation/

How can I achieve federation?
I have read about the PULL approach in the documentation, but do I need to set any parameters?

Thank you.

**Comment by mapedraza** [comment]
Hello.

First, I want to remark that the official channel for asking support is StackOverflow, using the tags fiware and [fiware-orion](https://stackoverflow.com/questions/tagged/fiware-orion) in this specific case.

If you followed the steps in the guide, you should have 3 different Orion Context Broker (A, B and C) running in your machine.
Then, the next step described is to create the subscriptions to copy the information between brokers. The first one create a subscription in A that send the information to B. The second one creates a subscription that send the information from B to C. This means that any changes sent to A will be sent to B via the subscription, triggering the notification on the second broker sending the information to C. (A->B->C)

If you have more questions, we encourage you to open a question in StackOverflow using the tags mentioned above.

**Comment by fgalan** [comment]
> First, I want to remark that the official channel for asking support is StackOverflow, using the tags fiware and [fiware-orion](https://stackoverflow.com/questions/tagged/fiware-orion) in this specific case.

I'd say that the "rule" to use github issue or SOF question is as follows:

* If the question is about software functionality, then use StackOverflow
* If the question is about some issue in the software (bug, missbehaviour, etc.), then use issue
* In case of doubt use StackOverflow (we will move to github issues if at the end an issue in the software is identified during the discussion at SOF)

**Comment by ctc-enokida** [comment]
mapedraza 
fgalan

Thanks for your answer.
And thanks for kindly telling me how to use github Issue and SOF.
I understand now. 

In the documentation, I understood that Orion B does not contain any data, 
but it is correct that A, B and C all contain data.

In that case, is there any special function as Federation?
Is it exactly the same as two subscriptions?


I'll ask at SOF! Thanks.

**Comment by fgalan** [comment]
It seems discussion has moved to SOF at https://stackoverflow.com/questions/68315407/i-want-to-know-what-orions-federation-feature-is

Thus, maybe this issue can be closed?

**Comment by ctc-enokida** [comment]
Hi fgalan 

You're right.
I will close this Issue.

Thanks.
