### ISSUE TITLE
Custom notification macro doesn't render correctly DateTimes atrributes

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#3894]
We have this entity attribute:

* name: “dateObserved”
* type: “DateTime”
* value: “2021-07-15T11:40:00.000Z”

However, in the custom notification using `${dateObserved}` we get

```
"dateObserved": "1626349200"
```

instead of “2021-07-15T11:40:00.000Z”

**Comment by kzangeli** [comment]
Of course ... should have thought of that!

Look also at creDate/modDate - will probably "fail" the same way (and any other attribute of type DateTime).

**Comment by Anjali-NEC** [comment]
Hi @fgalan @kzangeli Sir,

I would like to work on this issue, Can you please suggest the API to reproduce this issue.

**Comment by fgalan** [comment]
@Anjali-NEC thanks for your willingness to work on this!

To reproduce the issue, create an entity using a DateTime attribute (let's say named `dateObserved`). Then, create a subscription using custom notifications (`httpCustom`) using `${dateObserved}` in some part. Then, stimulate the subscription updating the entity and check that the notification is using a numerical value instead of an actual date in ISO8601 for `${dateObserved}`.

You could have a look to the tests under test/functionalTest/cases/2015_notification_templates for examples on subscriptions with custom notifications.

**Comment by fgalan** [comment]
@Anjali-NEC this issue has become somehow urgent, so I'm taking care of it to provide a quick fix. Thanks anyway for your interested on it!

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/4043
