### ISSUE TITLE
Is Orion officially permits the use of https in the provider url setting of the registration API (test case should be added to cover this)

### ISSUE THREAD

**Issue by Anjali-NEC** [telefonicaid/fiware-orion#4041]
Hi @fgalan 

We would like to know if Orion officially permits the use of https in the provider url setting of the registration API.

We found in the document below that https can be used in the notification url setting of the subscription.
https://fiware-orion.readthedocs.io/en/master/user/security/index.html#https-notifications
However, we couldn't find in the documentation if https can be used in the provider url setting of the registration.

We found a setting example in the following document.
The provider's url setting uses http, but we are not sure if it can also use https.
https://fiware-orion.readthedocs.io/en/master/user/context_providers/index.html

Please confirm whether https can be used  in the provider url setting of the registration officially.

Orion version 2.1

Thanks

**Comment by fgalan** [comment]
I think this is more a question on functionality than an actual issue in the software, so I'd suggest to open a question about this in SOF (https://stackoverflow.com/) using "fiware-orion" label. Then, include the link to the question as comment in this issue, then close the issue.

Thanks!

**Comment by Anjali-NEC** [comment]
Already open a question about this in SOF
link https://stackoverflow.com/questions/70765732/orion-use-https-in-the-provider-url-setting-of-the-registration-api

**Comment by fgalan** [comment]
At the end, maybe this issue makes sense, re-scoping it about creating a basic test with CP using http to ensure this.

**Comment by fgalan** [comment]
PR with the new cases https://github.com/telefonicaid/fiware-orion/pull/4042
