### ISSUE TITLE
Error while updating attribute (command)

### ISSUE THREAD

**Issue by SBlechmann** [telefonicaid/fiware-orion#4045]
Hey there,
I am running an orion instance for quite some time 
	"orion": {
		"version": "3.2.0",
		"uptime": "21 d, 2 h, 19 m, 16 s",
...}
together with (not limited to) mongo 4.2.2,, iota-json 1.19.0 and some mosquitto broker (based on 2.11).
I have connected some devices to the platform and measurement data and commands were working well for me. 
I believe it was yesterday when the update of attributes in form of sending commands was not working properly anymore and the following error occured:
ERROR@2022-01-27T20:19:13.415Z  postUpdateContext.cpp[682]: Orion Bug (empty contextAttributeVector for ContextElementResponse 1)

40% of the commands still arrive at the devices but lots are just lost. 

A colleague of mine mentioned we are apparently facing this issue since we updated our VM's OS to Ubuntu 20.04.3 LTS.... but all components run in docker containers. I also checked the orion container's resources and it seems to be fine.

Does anyone have any idea?

**Comment by fgalan** [comment]
This doesn't seem to be an issue in Orion but in another place (deployment, operating system, etc.). Thus, I'd suggest move this question to StackOverflow (https://stackoverflow.com), closing this issue once the corresponding question gets published there. You would probably get a wider audience there.

Thanks!

**Comment by SBlechmann** [comment]
Thanks for your response. I hope you are right.
https://stackoverflow.com/questions/70891035/fiware-orion-command-messages-to-devices-are-dropped
