### ISSUE TITLE
When Installing latest Orion by following BUILDING FROM SOURCES, getting error "CMake 3.1 or higher is required."

### ISSUE THREAD

**Issue by ArqamFarooqui110719** [telefonicaid/fiware-orion#4064]
- Orion version: Latest (3.5.1)

**Bug description**
While doing source Installation of the latest Orion by following [BUILDING FROM SOURCES](https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html), I'm getting below error on running "cmake" command during installation of  the Mongo-Driver:

```
[root@localhost cmake-build]# cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!

```

![Orion installation error](https://user-images.githubusercontent.com/55977298/154072416-56c268a1-9fd9-4386-afff-d3ccf67c7e99.png)

By default step `sudo yum install make cmake gcc-c++` installs cmake 2.8.12.2 version but required cmake version is 3.1 or higher. Please let me know if any other information is required.

**Expected behavior**
Orion (3.5.1) Installation should be completed without any error.

**Comment by ArqamFarooqui110719** [comment]
I think installation steps in "BUILDING FROM SOURCES" should be updated for cmake as it should install cmake version 3.1 or higher. I would be happy to raise a PR for fix the error. 

Hi @fgalan sir, please let me know your opinion.

**Comment by fgalan** [comment]
> Yes, It is CentOS-7.5.
> 
> ```
> [root@localhost fiware-orion]# cat /etc/redhat-release
> CentOS Linux release 7.5.1804 (Core)
> ```

I'm afraid your CentOS installation is pretty old and outside the official procedure. From https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html:

> Orion Context Broker reference distribution is CentOS 8.x.

So my recommendation is to use the newest CetnOS 8.x version (i.e. CentOS 8.4) to install Orion.

**Comment by ArqamFarooqui110719** [comment]
> So my recommendation is to use the newest CetnOS 8.x version (i.e. CentOS 8.4) to install Orion.

Yes, I have confirmed with CentOS-8 that 'cmake' error not occurred during installation on centOS-8.
By default cmake-3.20.2 has been installed this time.
I think, this issue should be closed.

**Comment by fgalan** [comment]
@ArqamFarooqui110719 thanks for the report! Closing.
