### ISSUE TITLE
Suscripciones Custom for New Type/New Id

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#4085]
Implement flexibility in custom notifications, so the id and type of the notified entity can be changed.

To be detailed.

**Comment by fgalan** [comment]
What about using macros in the mapping itsef? Eg. to provide a prefix to id:

```
    "httpCustom": {
      "url": "http://127.0.0.1:9999/notify",
      "mapping": {
        "id": "PREFIX${id}"
      }
```

**Comment by mrutid** [comment]
I would add all the "first level" information elements, that is: id, type, service, subservice, auth-token (sometimes you don't want to propagate it).

- service, subservice, auth-token may be manipulated throught http headers but thats an implementation caveat in my opinion.

**Comment by mrutid** [comment]
Maybe we should have access to the old id/type/S/SS also in the template... You may want a new id but the old id to be part of some attribute  composition. 
An off topic example may be found in Cygnus NameMappings we use "the NEW" to build the destination, and "the OLD" to populate table values.

NOTE: maybe we just need to hace access to the old ones in the macro language, the new ones always can be build or dereivated.

**Comment by fgalan** [comment]
Somehow related, new macros for service and servicePath are mentioned in https://github.com/telefonicaid/fiware-orion/issues/3913

**Comment by fgalan** [comment]
```
    "httpCustom": {
      "url": "http://127.0.0.1:9999/notify",
      "mapping": {
        "id": "newId",
        "type": "newType",
        "service": "SS",
        "servicePath": "/newSP",
        "authToken": "..."
      }
```

Notes:
* In the case of using "" then the corresponding header will not appear
* In the case of having some of them within `headers` the one in `headers` takes precedence.
* NOTE: ${service}, ${servicePath}, {$authToken} macros will be implemented as part of a separate issue.

**Comment by fgalan** [comment]
We are going to re-define this, based on the payload concept. So, in a custom notification, there would be three ways of defining a payload:

* As a custom text payload (currently supported with the `payload` field)
* As a custom JSON payload (currently supported with the `json` field)
* As a NGSIv2 normalized payload (the purpose of this issue)

The third mode will be associated to the `entity` field, at the same level than `payload` and `json` (note: `payload`, `json` and `entity` are mutually exclusive, i.e. only one of them can be used).

The value of `entity` will allow to defined *mapped* entity fields (id, type or attributes) that will be added the entity subject of the notification. So, let's consider the following updated entity

```
{
  "id": "E",
  "type:" "T",
  "A": {
    "value": 1,
    "type": "Number"
  }
}
```

----------------------

Lets consider several cases:

*A. Nothing to do*

Eg:

```
"entity": {}
```

will notify:


```
{
  "id": "E",
  "type:" "T",
  "A": {
    "value": 1,
    "type": "Number"
  }
}
```

Note2: `"entity": {}` would be equivalente to `"payload": ""` or omitting `payload/json` case [in the current implementation](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#omitting-payload).

*B. Add new attribute*

Eg:

```
"entity": {
  "B": {
    "value": 2,
    "type": "Number
  }
}
```

will notify:


```
{
  "id": "E",
  "type:" "T",
  "A": {
    "value": 1,
    "type": "Number"
  },
  "B": {
    "value": 2,
    "type": "Number
  }
}
```

*C. Map id, type or attribute*

Eg:

```
"entity": {
  "id": "EEEE",
  "A": {
    "value": 10,
    "type": "Number
  }
}
```

will notify:


```
{
  "id": "EEEE",
  "type:" "T",
  "A": {
    "value": 10,
    "type": "Number"
  }
```

*D. Any combination of B and C*

Eg:

```
"entity": {
  "id": "EEEE",
  "B": {
    "value": 2,
    "type": "Number
  }
}
```

will notify:


```
{
  "id": "EEEE",
  "type:" "T",
  "A": {
    "value": 1,
    "type": "Number"
  },
  "B": {
    "value": 2,
    "type": "Number"
  }
```



-----------------

Substitution macros would be allowed in the `entity` fields, eg:

```
"httpCustom": {
  "url": "http://127.0.0.1:9999/notify",
  "headers": {
    "fiware-servicepath": "/mappedSS"
  }
  "entity": {
    "type": "MappedT",
    "originalType": {
      "value": "${type}",
      "type": "Text"
    },
    "originatingSubservice": {
       "value": "${subService}",
       "type": "Text"
    }
  }
```

**Comment by fgalan** [comment]
`entity` -> `patch` as field name

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/4229
