### ISSUE TITLE
Performance Query

### ISSUE THREAD

**Issue by Neeraj-Nec** [telefonicaid/fiware-orion#4110]
I would like to know the maximum data ingress/egress(packet per sec) limit in orion broker for both northbound and southbound. 

suppose orion broker is integrated with json IoT agent. now what would be the data ingress/egress limit

**Comment by mapedraza** [comment]
This question is not an actual issue in the software, so I'd suggest to open a question about this in SOF (https://stackoverflow.com/) using "fiware-orion" label, which is the actual support channel. Then, include the link to the question as comment in this issue and close this issue.

Thanks!

**Comment by fgalan** [comment]
SOF was created at the end at https://stackoverflow.com/questions/72167782/performance-query/72168074#72168074 and it has been answered there.

Thus, I understand this issue can be closed.
