### ISSUE TITLE
Fail when null is in a list of values in a query by attribute values

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/fiware-orion#4120]
**Bug description**
A clear and concise description of what the bug is. Please do not forget to add:

Having entities where for some of them have a specific attr, e.g. municipality with value `null`, a query by a list of values of this attributes gets an error.

**How to reproduce it**
Steps to reproduce the behavior (as an example)

1. Create an entity this way:
    ```BASH
    curl -iX POST 'http://localhost:1026/v2/entities' \
    -H 'Content-Type: application/json' \
    -d '
    {
        "id": "Bug:007",
        "type": "bug",
        "status": {
            "type": "Text",
            "value": "fixed"
        },
        "municipality": {
            "value": null,
            "type": "Text"
        }  
    }'
    ```

2. When make the following query:
```BASH
curl --location --request GET 'http://host:1026/v2/entities?q=municipality:null,alcobendas' \
--header 'Fiware-Service: service' \
--header 'Fiware-ServicePath: /subservice' \
```

3. See error in the request response
```
400 Bad Request
{
    "error": "BadRequest",
    "description": "invalid JSON value type in list"
}
```

4. When the query is just the `null` value the answer is correct

```BASH
curl --location --request GET 'http://host:1026/v2/entities?q=municipality:null' \
--header 'Fiware-Service: service' \
--header 'Fiware-ServicePath: /subservice' \
--header 'X-Auth-Token: ...
```

Response:
200 OK
```json
[
    ...,
    {
        "id": "Bug:007",
        "type": "bug",
        "municipality": {
            "type": "Text",
            "value": null,
            "metadata": {}
        },
        "status": {
            "type": "Text",
            "value": "fixed",
            "metadata": {}
        }
    }
]
```

**Expected behavior**

To be able to retrieve both set of entities, the ones with the `municipality=alcobendas` and the others with `municipality=null`

**Additional information**

NA

**Comment by fgalan** [comment]
Looking in StringFilter.h:

```
typedef enum StringFilterValueType
{
  ...
  SfvtNumberList,
  SfvtDateList,
  SfvtStringList
} StringFilterValueType;
```

So it seems our internal data structures are not though for mixing different types (string and null in this case) but let me think if I can come with some creative solution for this :)

**Comment by fgalan** [comment]
We will use a new bool flag named `nullInList` to mark the existence of  `null` within a list. Not a very smart solution, but it'll work.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/4123

**Comment by danielvillalbamota** [comment]
It seems when `null` is in the list of values, the CB retrieve entities without the filtered attribute (`municipality`), but what is expected are the entities with explicit `null` in the value as when just one value `null` is used (not a list).

**Comment by danielvillalbamota** [comment]
It works
