### ISSUE TITLE
Exporter for Prometheus

### ISSUE THREAD

**Issue by WillFreitag** [telefonicaid/fiware-orion#4212]
**Is your feature request related to a problem / use case? Please describe.**
When using Orion Context Broker in a containerized platform, it would be nice to have some metrics.

**Describe the solution you'd like**
There are client libs available for almost all languages inkl. C++ (https://prometheus.io/docs/instrumenting/clientlibs/).

**Do you have the intention to implement the solution**
- [ ] Yes, I have the knowledge to implement this new feature.
- [ ] Yes, but I will need help.
- [ ] No, I do not have the skills.
- [x] I'd really love to contribute on this, but I fear I will not find the time for that.

**Comment by mapedraza** [comment]
Thank for the suggestion of this Issue 

Currently Orion implements its own metric system, are you aware of metrics API endpoint of Orion? You can review more information in the following link: https://github.com/telefonicaid/fiware-orion/blob/b412aca0527df44f9cf60e152947a69afa6a7a7e/doc/manuals/admin/metrics_api.md

**Comment by WillFreitag** [comment]
Thanks for the feedback and no, I wasn't aware of that API (and I wasn't aware that it's enabled by default - consuming resources w/o using the API at all :-) ).
At a first sight, it looks like it's exactly what I'm looking for!
Thanks again for that hint!

**Comment by WillFreitag** [comment]
Issue already solved.
