### ISSUE TITLE
Error on getting single lazy attribute value

### ISSUE THREAD

**Issue by walterwootz** [telefonicaid/fiware-orion#4222]
Hi everyone,
We are developers from Engineering and we are working on [iotagent-opcua](https://github.com/Engineering-Research-and-Development/iotagent-opcua), trying to improve lazy attributes handling.

**Bug description**
When requesting a lazy attribute value, Orion forward all the registered attributes instead of the one requested. Consequentially the IoT Agent registered does not know which one is the attribute requested.

- Orion version: 3.7.0
- MongoDB version: 4.2
- CLI parameters: -dbhost mongo-db -logLevel DEBUG
- Docker Image used:  latest (3.7.0)

**How to reproduce it**
Steps to reproduce the behavior (as an example)
1. Create an entity, this way:
    ```BASH
    curl --location --request POST 'http://localhost:1026/v2/entities' \
    --header 'Fiware-Service: opcua_car' \
    --header 'Fiware-ServicePath: /demo' \
    --header 'Content-Type: application/json' \
    --data-raw '{
      "id": "age01_Car",
      "type": "Device",
      "Engine_Oxigen": {
        "type": "Property"
      },
      "Engine_Temperature": {
        "type": "Property"
      }
    }'
    ```
2. Create a registration that include at least 1 lazy attribute (Speed) of the entity, this way:
    ```BASH
    curl --location --request POST 'http://localhost:1026/v2/registrations' \
    --header 'Fiware-Service: opcua_car' \
    --header 'Fiware-ServicePath: /demo' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "dataProvided": {
            "entities": [
                {
                    "id": "age01_Car",
                    "type": "Device"
                }
            ],
            "attrs": [
                "Speed",
                "Accelerate"
            ]
        },
        "provider": {
            "http": {
                "url": "http://localhost:4041"
            },
            "supportedForwardingMode": "all",
            "legacyForwarding": false
        },
        "status": "active"
    }'
    ```
4. Ask for value of the lazy attribute this way:
    ```BASH
    curl --location --request GET 'http://localhost:1026/v2/entities/age01_Car/attrs/Speed?type=Device' \
    --header 'fiware-service: opcua_car' \
    --header 'fiware-servicepath: /demo'
    ```

5. See logs on Orion about forwarding all attributes: in the request response
6. Check the log `op=logTracing.cpp[233]:logInfoFwdRequest | msg=Request forwarded (regId: 6346bb7609d4697f6d5a055c): POST http://host.docker.internal:4041/op/query, request payload (95 bytes): {"entities":[{"id":"age01_Car","type":"Device"}],"attrs":["Speed","Accelerate"]}`

**Expected behavior**
Only the requested attribute should be forwarded to the agent as payload.

**Additional information**

With this behaviour the agent does not know which is the original lazy attribute to be fetched.

Thank you for the support.

**Comment by mapedraza** [comment]
Maybe related:
- https://github.com/telefonicaid/fiware-orion/blob/master/src/lib/serviceRoutines/postQueryContext.cpp
- https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/devel/cprs.md#forwarding-of-query-requests

**Comment by fgalan** [comment]
@walterwootz thank you for your report.

In order to fully understand the issue, could you tell us the Orion response to the request sent in step 3, please? Thanks!

**Comment by walterwootz** [comment]
@fgalan there was a typo on step 3 request. I edited it with the correct attribute (Speed).

More about step 3: once the GET request is sent, Orion forward it as a POST to the agent and is waiting for a response, but it depends on how the agent is implemented.
As agent developer, I cannot distinguish which was the original lazy attribute requested by the user (Speed in the example), because Orion is forwarding a request payload with ALL the lazy attributes registered on the context broker (Speed and Accelerate in my test).

On the agent I could consider all the attributes in the forwarded request and return values of all of them, but that's not what the user asked for..

**Comment by fgalan** [comment]
> ... it seems (based on your report) the way it is implemented is that Orion asks for all the attributes involved in the registry

@walterwootz could you do another test using the following in the registration curl:

```
        "attrs": [
            "Speed"
        ]
```

to see how it works in that case, please? Thanks!

**Comment by walterwootz** [comment]
Hi @fgalan,

After some tests we found the solution.

As mentioned before, if Orion is asked for a specific lazy attribute, it will make a call to the context provider at `/op/query` asking for ALL attributes in the registry (greedy approach).

The context provider (in my case an IoT Agent OPC UA) must respond with a structure like this:
```json
[
  {
    "type": "Device",
    "id": "age01_Car",
    "Speed": {
      "type": "Number",
      "value": 150
    },
    "Acceleration": {
      "type": "Number",
      "value": 0
    }
  }
]
```
Orion will fetch the originally requested lazy attribute and return it to the user.

**Comment by fgalan** [comment]
Great to know you finally find a solution! :)

Thus, I understand this issue can be closed, right?
