### ISSUE TITLE
orion statistics issues : measuring_interval_in_secs not reset & /version requests considered as "invalidRequests"

### ISSUE THREAD

**Issue by agaldemas-eridanis** [telefonicaid/fiware-orion#4233]
**Bug description**

A. if you 'DELETE' statistics, and you call again GET /statistics, `measuring_interval_in_secs`, remains at the same value as `uptime_in_secs`, instead of being reset to 0, the others sections are well reset.

B. if you perform a GET /version to orion, it is counted as an `invalidRequests`, and not as `versionRequests`, in statistics, nevertheless `versionRequests` appears in the response, but remains to 0.

- Orion version: 3.6.0, used in NGSI-V2 !
- MongoDB version 4.4.6
- deployed on Kubernetes, image: fiware/orion:3.6.0

**How to reproduce it**
A. measuring_interval_in_secs not reset:
  1. delete statistics, and consult it
 ```bash
curl -iX DELETE 'http://localhost:1026/statistics'
curl -i 'http://localhost:1026/statistics'
 ```
  3. See in the request response, `measuring_interval_in_secs` value is the same as `uptime_in_secs`
 
B. /version request counted as `invalidRequests`, instead of `versionRequests`
  1. perform a GET /version request to orion
  2. perform a GET /statistics request to orion
  3. see in the results of statistics request:
```json
{
    "counters": {
        ...
        "invalidRequests": 1,
        "versionRequests": 0
    }
...
}
```
**Expected behavior**
A. : measuring_interval_in_secs set to 0, when DELETE statistics (as specified in [doc about statistics](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/statistics.md#get-statistics)
B. : version request not counted as invalid requests in statistics.

**Comment by agaldemas-eridanis** [comment]
just checked : the same issues exists in 3.7.0 !

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/4248

**Comment by fgalan** [comment]
@agaldemas-eridanis thanks for the report!

PR #4248 should fix the issue. It has been merged to master, so you could test `telefonicaiot/fiware-orion:latest`.

Could you test and tell us if it is working now for you, please? Thanks!

**Comment by fgalan** [comment]
@agaldemas-eridanis note that after the merging of PR https://github.com/telefonicaid/fiware-orion/pull/4254 the request counter statistics system has been improved. The version counter is no longer using an specific `versionRequests` counter and has been aligned with the other requests. Now you would get the same information this way:

```
{
    "counters": {
        ...        
        "requests": {
            ...
            "/version": {
                "GET": 1
            }
            ...
        },
```

**Comment by fgalan** [comment]
Orion 3.8.0 is has been released today, so we close this issue.

Of course, it could be re-opened if needed.
