### ISSUE TITLE
Cors allowed headers do not include "Authorization" which is the default headers used with OAuth.

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/fiware-orion#4249]
Could you please add "Authorization" in the list of Cors allowed headers?

https://github.com/telefonicaid/fiware-orion/blob/0dc77185b8f98274840abc28364e2bd071c1d7e4/src/lib/rest/HttpHeaders.h#L68

**Comment by fgalan** [comment]
If you create the pull request for adding it, we can include it in the next release (soon to be frozen ;)

Is this the only point that need to be touched? Please check also documentation.

Finally, don't forget to add the corresponding entry to CHANGES_NEXT_RELEASE file, please.

Thanks!

**Comment by chicco785** [comment]
> If you create the pull request for adding it, we can include it in the next release (soon to be frozen ;)
> 
> Is this the only point that need to be touched? Please check also documentation.
> 
> Finally, don't forget to add the corresponding entry to CHANGES_NEXT_RELEASE file, please.
> 
> Thanks!

Not a C developer. Said that, if it's just about adding that to the list, I can do, more complex if I need to develop a test case :)

**Comment by chicco785** [comment]
> Btw, could you provide a little more context about the usage? I mean, in which case (architecture, etc.) are you using Orion with a system requiring CORS.
> 
> Thanks again!

We have an admin interface, now in front of Orion, we recently added a new authz proxy based on envoy, which by default pass all headers, so the issue popped up.

**Comment by fgalan** [comment]
> Not a C developer. Said that, if it's just about adding that to the list, I can do, more complex if I need to develop a test case :)

Do a PR without the test so we can check if something break ;)

Next, maybe just adapting (copy-paste-modify) some of the tests in https://github.com/telefonicaid/fiware-orion/tree/master/test/functionalTest/cases/0501_cors would suffice. Please have a look.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/4251
