### ISSUE TITLE
Modify .test to upgrade to libmicrohttpd 0.9.75

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#4267]
PR https://github.com/telefonicaid/fiware-orion/pull/4259 upgrades libmicrohttpd from 0.9.70 to 0.9.73 before releasing Orion 3.8.0.

At this moment, there is a newer libmicrohttp version (0.9.75) but it changes the order in which HTTP headers appear in responses (more detail in libmicrohttpd list discussion).

Thus, upgrading to 0.9.75 (or beyond) would involve a massive change in .test files, to reorder HTTP headers. There is no point in doing this change manually, probably we need an script to do that.

**Comment by fgalan** [comment]
Link to thread discussion in libmicrohttpd mailing list: https://lists.gnu.org/archive/html/libmicrohttpd/2023-01/msg00002.html

**Comment by Anjali-NEC** [comment]
Hi @fgalan sir,

I would like to work on this issue, As per my understanding we need create a script for reordering of HTTP headers  in .test files as per the current version. Please confirm my understanding and let me know this issue is still valid or not? Thanks

**Comment by fgalan** [comment]
In fact, the script is not the purpose of this issue but a tool to achieve it without a lot of manual changes (I mean, you don't need to include the script in the PR).

What I'd suggest is the following:

1. Upgrade libmicrohttpd to 0.9.75 in you working environment (you can have a look to https://github.com/telefonicaid/fiware-orion/pull/4259/commits/ed50010f7929d082f271e9ca72922ad16958f0d0 if helps...)
2. Run testHarness.sh. A lot of test will fail due to the change in headers order
3. Fix the test. In this step is when a script to automate the changes will help
4. Run testHarness.sh again to check that tests are now ok
5. Creare a PR with the changed .tests and the CI stuff (ci/deb/build-dep.sh, doc/manuals/admin/build_source.md, docker/Dockerfile, docker/Dockerfile.alpine). Don't worry if test in that PR fails first attemps, the CI image would need to be rebuild (I'll take care of it).

Thanks!
