### ISSUE TITLE
ContextBroker not starting on WSL2 Ubuntu 20.04 when installing from source

### ISSUE THREAD

**Issue by rseider-mbe** [telefonicaid/fiware-orion#4272]
**Bug description**
I try to install the contextBroker on WSL2 using source installation. I followed exactly all steps in the documentation (Copy&Paste) and ran into several issues:
- user "orion" was not created - did it after make install
- /opt/fiware-orion was not created
- at least... the contextBroker service (or directly via shell) is starting but without any log entries in the given Logfile. 

I set permissions of /var/run/contextBroker and /var/log/contextBroker to 0700 (owner=orion, group=root)
when I stop the service, the pid file is still remaining. when I start again, the log tells me that the pid file is already existing. Logging works from my point of view. The connection to Mongo DB is working. checked by "nc -zv "$(hostname).local" 27017". Unit tests are all passed. Functional tests are not able to start due to missing /opt/fiware-orion directory.

**Environment**
- Orion version: 3.8.0-next
- MongoDB version 6.0.3
- CLI parameters: -port 1026 -logDir /var/log/contextBroker -pidpath /var/run/contextBroker/contextBroker.pid -dbhost "DESKTOP-31PNO54.local" -db orion -multiservice -logAppend
- Operating System: WSL2 Ubuntu 20.04 on Windows 10 IoT Enterprise LTSC 21H2

**How to reproduce it**
Walk through the install guide and start daemon: "service contextBroker start". In top the process is listed, but sleeping after 2sec of activity.

**Expected behavior**
I want to run the broker on a WSL2 system the same way like in the docker container.

**Additional information**
Docker container works without any problems on the same machine using WSL2 for docker.
Running in Foreground results in this error:
`time=2023-01-19T20:52:09.789Z | lvl=FATAL | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=rest.cpp[1812]:restStart | msg=Fatal Error (error starting REST interface)`

**Comment by fgalan** [comment]
Happy to know you solved it! :)
