### ISSUE TITLE
Update format for notification messages

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#4286]
Instead of using:

```
{
  "subscriptionId": "12345",
  "data": [
    {
      "id": "Room1",
      "type": "Room",
      "temperature": {
        "value": 23,
        "type": "Number",
        "metadata": {}
      },
      "humidity": {
        "value": 70,
        "type": "percentage",
        "metadata": {}
      }
    }
  ]
}
```

use the same format that an update uses, i.e: (normalized)

```
{
   "id": "Room1",
   "type": "Room",
   "temperature": {
     "value": 23,
     "type": "Number",
     "metadata": {}
   },
   "humidity": {
     "value": 70,
     "type": "percentage",
     "metadata": {}
   }
}
```

or keyValues:

```
{
   "id": "Room1",
   "type": "Room",
   "temperature": 23,
   "humidity": 70,
}
```

To take into account:

* It must work with custom notifications (for non-custom notification is not a must, but I guess that it would be also easy to implement)
* For both `normalized` and `keyValues` updates
* Not sure if we should support a "reduced keyValues" format, in which id and type are omitted, to integrate with IOTA-JSON
* Not sure if `attrsFormat` could be expanded or a new field is needed
* Not sure what to do with `Ngsiv2-AttrsFormat` header. Should be omitted (as updates doesn't use it)?

**Comment by fgalan** [comment]
Note this is an alternative way of implementing command features, avoiding to use registrations and without changes in the command endpoints.

**Comment by fgalan** [comment]
A clarification (after looking to PR #4286 at commit [1832670](https://github.com/telefonicaid/fiware-orion/pull/4298/commits/1832670da3e1e8913fdb52002f7879ba6d274d37)).

We don't want to *change* the current notification functionality. On the contrary, what we want is to *add* a new functionality, backward compatible with the previous one.

Maybe we can introduce two new cases for `attrsFormat`

* simplifiedNormalized (same as `normalized` but without subscriptionId and without using a `data` arraty to include entity information)
* simplifiedKeyValues (same as `keyValues` but without subscriptionId and without using a `data` array to include entity information)

**Comment by Anjali-NEC** [comment]
> A clarification (after looking to PR #4298 at commit [1832670](https://github.com/telefonicaid/fiware-orion/pull/4298/commits/1832670da3e1e8913fdb52002f7879ba6d274d37)).
> 
> We don't want to _change the current_ notification functionality. On the contrary, what we want is to _add a new functionality_, backward compatible with the previous one.
> 
> Maybe we can introduce two new cases for `attrsFormat`
> 
> * `simplifiedNormalized` (same as `normalized` but without `subscriptionId` and without using a `data` arraty to include entity information)
> * `simplifiedKeyValues` (same as `keyValues` but without `subscriptionId` and without using a `data` array to include entity information)

@fgalan Thank you for your suggestion I am working on it.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-orion/pull/4298
