### ISSUE TITLE
Change CRS for location

### ISSUE THREAD

**Issue by thaarhoff** [telefonicaid/fiware-orion#4312]
**Is your feature request related to a problem / use case? Please describe.**
Within the documentation (http://telefonicaid.github.io/fiware-orion/archive/api/v2/) this is mentioned:
> By default, coordinates are defined using the [WGS84 Lat Long](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84), [EPSG::4326](http://www.opengis.net/def/crs/EPSG/0/4326) coordinate reference system

My problem is, the coordinates I am processing are given in EPSG:25832 or EPSG:25833 and sadly I am not in an environment where it is possible to make the projection to WGS84.
Orion produces a DatabaseError when transmitting coordinates like:
```
{
  "type": "geo:json",
  "value": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          791678.5516705504,
          5833118.44135623
        ],
        [
          791803.4043193655,
          5832999.235715789
        ],
        [
          791678.5516705504,
          5833118.44135623
        ]
      ]
    ]
  }
}
```

And orion returning a Server Error 500 with 
```
"{"
   error":"InternalError",
   "description":"Database Error &#40;collection: orion-MY_SERVICE.entities - insert&#40;&#41;: { _id: { id: 
   ...
```

During testing - If I replace these coordinates with WGS84 coordinates, orion processes the Polygon and returns 204

I couldn't find any documentation or issues having a similar problem. Is it even possible to change the CRS on an entity level?

**Describe the solution you'd like**
If it is possible to change the CRS it would be good to have documentation adjusted and maybe an example.<br>
If it is not possible, the orion should (maybe?) consider metadata provision for providing a diffrent EPSG
```
		"metadata": {
			"location": {
				"type": "string",
				"value": "EPSG:25832"
			}
		}
```

**Describe alternatives you've considered**
An easy-quick solution could be, to add an option for disabling the CRS check and allow all coordinates.
One also likely alternative is, I am using something wrong and the issue is not located in the different CRS.

**Describe why you need this feature**
- To improve or simplify an scenario.

**Do you have the intention to implement the solution**
- [x] No, I do not have the skills.

**Comment by fgalan** [comment]
Orion geolocation features are based in the ones provided by MongoDB. Do you know if MongoDB supports the coordinates systems you are proposing?

**Comment by fgalan** [comment]
Maybe as first step you could create an issue / feature request at MongoDB repository/JIRA for the coordinate systems you need. Next, once supported in a given version of MongoDB the support could be easily added to Orion.
