### ISSUE TITLE
Creation Times in mongo

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#432]
### Description

The creDate in mongo is using seconds. That is not enough.
We'd need to store at least down to miliseconds.

It might be that only the functional tests suffer because of this.

A few functional tests have been modified (sleeps of 1.1 seconds added) as a workaround:
  o  geoquery_circle.test
  o  geoquery_circle_json.test
  o  query_sequence.test

When the creDate is changed to use mili- or microseconds, these sleeps can be shortened and test time will be less.

**Effort: 2 man day**

**Comment by fgalan** [comment]
Changed to nice-to-have (in my opinion, it is not so critical to be "should").

**Comment by fgalan** [comment]
Related: https://github.com/telefonicaid/fiware-orion/issues/2670

**Comment by chicco785** [comment]
This practically means that Orion cannot support any Industrial IoT scenario :/

**Comment by fgalan** [comment]
> This practically means that Orion cannot support any Industrial IoT scenario :/

I think the situation is not so dramatic :)

Even if Orion doesn't support milliseconds natively, the application always has the option to manage it itself. For instance, using a `modDateMs` which value is an integer with time in milliseconds so each time something is modified in the entity it also updates such attribute.

**Comment by chicco785** [comment]
right, but i was thinking to the current iot-agent -> orion chain.
the iot agent generates a timestamp with milliseconds and attach it to orion, we can't change that now. what about having then an option for the iot agent lib to send long for the timestamp and format as number?

**Comment by fgalan** [comment]
> what about having then an option for the iot agent lib to send long for the timestamp and format as number?

I'd suggest to open an issue about it in the ioagent-node-lib repository explaining the proposal and rationale so we can discuss there.

**Comment by fgalan** [comment]
Related issue (for traceability): https://github.com/telefonicaid/iotagent-node-lib/issues/795

**Comment by fgalan** [comment]
Related question at SOF (which answer should be update when this issue progresses):

https://stackoverflow.com/questions/62516873/when-iot-agent-sends-data-within-milliseconds-the-values-are-not-notified-to-dr/62661681#62661681

**Comment by fgalan** [comment]
PR #3673 (which is the sum of PRs #3668 and #3672) implements milliseconds functionality for DateTime attributes and metadata into master.

@chicco785 it would be great if you could test it (using `:latest` from dockerhub for the Orion container) and provide feedback, please.

**Comment by fgalan** [comment]
Milliseconds support has been implemented for Orion 2.5.0 and, except if somebody tells otherwise, it works as expected. Closing issue.
