### ISSUE TITLE
JSON to NGSI-V2 convertor library

### ISSUE THREAD

**Issue by Anjali-NEC** [telefonicaid/fiware-orion#4377]
Hi @fgalan,

I want to convert json to NGSI-v2, Could you please suggest is there any library available for json to NGSI-V2 conversion? 

Thanks

**Comment by fgalan** [comment]
> I want to convert json to NGSI-v2

What "json" means in this context? JSON is just a data encoding syntax, you can use virtually *unlimited* ways of encoding information in JSON (in fact, NGSIv2 is some of these ways).

Could you elaborate a bit more, please? Maybe providing examples of the input JSON you want to covert.

**Comment by fgalan** [comment]
I have found this is duplicated in https://stackoverflow.com/questions/76489533/converter-form-json-data-to-ngsi-v2-data. Please don't do that :), double-posting leads to disperse information and that's not good...

For question use SOF. For issues in the software please use GitHub repo.

I'm going to close this issue, so we can continue discussion at SOF.
