### ISSUE TITLE
Improve Runtime Error log

### ISSUE THREAD

**Issue by tzzed** [telefonicaid/fiware-orion#4387]
**Is your feature request related to a problem / use case? Please describe.**
When orion return `Runtime Error (unknown attribute value type in DB: )` we don't know the attribute name

**Describe the solution you'd like**
Something like this.
`Runtime Error (unknown attribute value type in DB:  type on attribute "name")`

**Describe alternatives you've considered**

**Describe why you need this feature**
This simplify the debug.

**Additional information**
Add any other information, diagrams or screenshots about the feature request here.

**Do you have the intention to implement the solution**
- [X] Yes, but I will need help.

**Comment by fgalan** [comment]
Thanks for the report! I agree that adding the attribute name would make the log trace more useful.

As far as I have checked, that log trace is used in three places:

![imagen](https://github.com/telefonicaid/fiware-orion/assets/1534240/532c278b-7208-4551-a762-1b4838404493)

I would say that in them all the attribute name is accessible at `caP->name`, so the issue could be easy to implement. @tzzed maybe you could do the PR implementing it, please? Thanks!

**Comment by tzzed** [comment]
I have seen,  but I need to compile orion on mac M2 if it is possible or should compile on linux for more simplicity?

**Comment by fgalan** [comment]
mac M2 is not a supported platform. Maybe it works, but we haven't tested it.

Maybe you could create a Linux-based virtual machine in your mac M2 system using some virtualization tool (VirtualBox, etc.)?

**Comment by mapedraza** [comment]
@tzzed Have a look to https://github.com/abiosoft/colima project. It allows to run containers virtualising the platform.

**Comment by tzzed** [comment]
I get the following when I compile.
 ` error: ‘SHLIB_VERSION_NUMBER’ was not declared in this scope; did you mean ‘OPENSSL_VERSION_NUMBER’?`

I did something wrong ?

**Comment by tzzed** [comment]
@fgalan should the PR only set the attrobute on `LM_E(("Runtime Error (unknown attribute value type in DB: %d)"` or all logs that contains `LM_E(("Runtime Error (unknown attribute value type  %d)"` to have harmonized logs?

**Comment by fgalan** [comment]
> @fgalan should the PR only set the attrobute on `LM_E(("Runtime Error (unknown attribute value type in DB: %d)"` or all logs that contains `LM_E(("Runtime Error (unknown attribute value type %d)"` to have harmonized logs?

I see a PR has been raised for this issue. Let's continue discussion there.

**Comment by fgalan** [comment]
Fixed by PR #4393 

@tzzed should this issue be closed or is there anything else pending, please?
