### ISSUE TITLE
New XML library with XSD support

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#441]
### Description
Our current XML parsing library (rapidxml) is small and fast and works pretty well.
It is especially FAST - it's name does not lie.

However, it is not VERY easy to use and XSD is not supported.
If we want orion to to be able to detect hundreds of possible errors, like empty values in tags, repeated tags, etc, we would not implement all those checks using the current library (the effort would just be TOO much), but we would replace the current library with a library with more functionality, xerces, for example.

The downside is that we'd lose a lot of throughput with a change like that.
How much?
Difficult to say, and to have a realistic estimation is a pretty big effort (weeks).
We'd win in other aspects.

Known problems we have right now, that would be solved with a XML parse library supporting XSD:
1. Repeated XML tags (old issue 77)
2. Missing/empty tags (old issue 36)
3. We have no knowledge about the order in which the XML comes.
4. The check that the payload matches the URL (but only for XML) (issue #53 )

Estimated man-days to replace the current XML library: 30
And, to implement something XSD-like in the current lib: 60

**Comment by fgalan** [comment]
XML is to be deprecated soon (probably in 0.23.0) thus this issue doesn't make sense any more. Closing.
