### ISSUE TITLE
Unable to `PUT` or `PATCH` registered attributes on CPrs entities (that does not exists locally) 

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/fiware-orion#4430]
**Bug description**
When registering an entity provided from a Context Provider, without creating it, the entity is listed when executing `GET /v2/entities/<entityID>` but it is not possible to PUT or PATCH the registered attribute.

This particular case is relevant when creating an only actuation entity. This behaviour is expected for all IoT Agents using the IoTA Node LIB version 3.4.0 or higher since no entity is created when provisioning the devices. 

**How to reproduce it**
Steps to reproduce the behavior (as an example)

After creating a device using the [IoT Agent JSON](http://github.com/telefonicaid/iotagent-json), the entity gets registered, but no entity is created after. Then, it is possible to query the entity 

```bash
curl -L 'http://localhost:1026/v2/entities/Bell:001?options=keyValues' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /'
```

It returns:

```json
{
    "id": "Bell:001",
    "type": "Bell",
    "ring": ""
}
```

But it is not possible to PUT or PATCH that entity

```bash
curl -L -X PUT 'http://localhost:1026/v2/entities/Bell:001/attrs/ring' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
-d '{
      "type" : "command",
      "value" : ""
}'
```

is returning:

```json
{
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
}
```

**Expected behavior**
Allowing PATCH or PUT to registerd attributes in entities that does not exits locally on the context broker. 

**Additional Information**
Related IoTA Issue:
https://github.com/telefonicaid/iotagent-node-lib/issues/1464

**Comment by mapedraza** [comment]
After some tests using latests versions of IoTA and Orion, it is possible to put or patch when specifying the entity type as URL parameter as described here: https://github.com/telefonicaid/iotagent-node-lib/issues/1464#issuecomment-1729614318

Take as an example the following request:

```
curl -L -X PUT 'http://localhost:1026/v2/entities/Bell:001/attrs/ring?type=Bell' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
-d '{
      "type" : "command",
      "value" : ""
}'
```
@jason-fox Please, could you verify if it works for you?

**Comment by jason-fox** [comment]
Yes that works and makes sense. 

```console
curl -L -X PUT \
   'http://localhost:1026/v2/entities/urn:ngsi-ld:Bell:001/attrs/ring'
```

Fails but

```console
curl -L -X PUT \
   'http://localhost:1026/v2/entities/urn:ngsi-ld:Bell:001/attrs/ring?type=Bell'
```

Succeeds.


This is because the IoT Agent registers the Bell as:

```json
[
    {
        "id": "65a907b164f1d24eb30ce7bd",
        "dataProvided": {
            "entities": [
                {
                    "id": "urn:ngsi-ld:Bell:001",
                    "type": "Bell"
                }
            ],
            "attrs": [ "ring"]
        }
    }
]
```

Which is for an Entity with id `urn:ngsi-ld:Bell:001` and type  `Bell`. At this point in time Orion has no local Entity and therefore the type is unknown unless it is supplied in the request.

**Comment by mapedraza** [comment]
Ok, so, after this, we can close this issue and https://github.com/telefonicaid/iotagent-node-lib/issues/1465.

The scope of PR https://github.com/telefonicaid/iotagent-node-lib/pull/1551 should change to reflect latest conclusions
