### ISSUE TITLE
Conflict between -dbURI and Default -dbTimeout Causes Startup Failure

### ISSUE THREAD

**Issue by goten002** [telefonicaid/fiware-orion#4496]
**Bug description**
Encountered a startup failure with Fiware Orion version 3.11.0 due to a conflict between the -dbURI parameter and the default value of -dbTimeout. The issue arises when the -dbURI parameter is used without explicitly setting -dbTimeout to zero.

- Orion version: `3.11.0`
- MongoDB version `4.4`
- CLI parameters: `-dbURI mongodb://mongodb:27017  -logLevel DEBUG`
- Docker Image used: `fiware/orion:3.11.0`

**How to reproduce it**
1. Configure Orion with the `-dbURI` parameter without specifying `-dbTimeout`.
2. Attempt to run the Orion container.
3. Observe the startup failure with the error message indicating a conflict between `-dbURI` and other database parameters.
```text
Invalid Command Line Options: -dbURI cannot be combined with -dbhost, -rplSet, -dbTimeout, -dbuser, -dbAuthMech, -dbAuthDb, -dbSSL and -dbDisableRetryWrites.
```
**Expected Behavior**
Orion should start successfully using the `-dbURI` parameter without needing to explicitly set `-dbTimeout` to zero, as `-dbTimeout` has a default value.

**Investigation and Analysis**
On further investigation, it was found that the `composeMongoUri` function in `mongoConnectionPool.cpp` checks if `timeout > 0` to return an error. The default value of `dbTimeout` is 10000, as seen in `contextBroker.cpp`, which seems to be causing the issue.

**Suggested Fix**
It appears that the check for `timeout > 0` in the condition within `composeMongoUri` is unnecessary when `-dbURI` is used. A proposed solution would be to modify the conditional check to exclude `timeout` when `dbURI` is provided. This would prevent the conflict when the default `dbTimeout` value is used with `-dbURI`.

**Code Reference**
The relevant code is located at:
- [mongoConnectionPool.cpp line 337](https://github.com/telefonicaid/fiware-orion/blob/4e4d96fcef96e50327a802da011d6b7da110926d/src/lib/mongoDriver/mongoConnectionPool.cpp#L337)
- [contextBroker.cpp line 312](https://github.com/telefonicaid/fiware-orion/blob/4e4d96fcef96e50327a802da011d6b7da110926d/src/app/contextBroker/contextBroker.cpp#L312)

**Additional Context**
This issue may impact users who are transitioning to the new `-dbURI` parameter and are unaware of the need to explicitly set `-dbTimeout` to zero.

**Comment by fgalan** [comment]
Thanks for so detailed report and related PR #4497! :)

Let me some time to review it and I'll provide feedback.

**Comment by fgalan** [comment]
Probably the simplest solution is to change the `-dbTimeout` default from 10000 to 0.

On the one hand, this will "pass" the `|| timeout > 0` condition if `-dbUri` is used

On the other hard, this will cause that `connectTimeoutMS=` not being added to the composition of the mongo URI (if `-dbUri` is not used). Although the composed URI will not be the same that with the current 10000 default (i.e `connectTimeoutMS=` the actual effect is the same, taking into account from https://www.mongodb.com/docs/manual/reference/connection-string/#timeout-options

![imagen](https://github.com/telefonicaid/fiware-orion/assets/1534240/39a39a2e-9884-49fe-968d-7dbac4fd1558)

and from the cited driver documentation, in our case (Mongo C driver) from http://mongoc.org/libmongoc/current/mongoc_uri_t.html

![imagen](https://github.com/telefonicaid/fiware-orion/assets/1534240/4825fcfc-fa09-48db-b49e-eea74ad6d60d)

Thus, the default in the case of not using `connectTimeoutMS=` is the same.

@goten002 what do you think? Could you adapt your PR #4497 in that way? (the PR would simplify a lot, in fact)

**Comment by fgalan** [comment]
> I'm documenting this here for awareness and to check if it's related to the changes made for Issue [#4496](https://github.com/telefonicaid/fiware-orion/issues/4496), or if it should be addressed separately.

Thanks for raising it. Solved in PR https://github.com/telefonicaid/fiware-orion/pull/4501

**Comment by goten002** [comment]
> Probably the simplest solution is to change the `-dbTimeout` default from 10000 to 0.
> 
> On the one hand, this will "pass" the `|| timeout > 0` condition if `-dbUri` is used
> 
> On the other hard, this will cause that `connectTimeoutMS=` not being added to the composition of the mongo URI (if `-dbUri` is not used). Although the composed URI will not be the same that with the current 10000 default (i.e `connectTimeoutMS=` the actual effect is the same, taking into account from https://www.mongodb.com/docs/manual/reference/connection-string/#timeout-options
> 
> ![imagen](https://private-user-images.githubusercontent.com/1534240/302551556-39a39a2e-9884-49fe-968d-7dbac4fd1558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTcxNDEsIm5iZiI6MTcwNzIxNjg0MSwicGF0aCI6Ii8xNTM0MjQwLzMwMjU1MTU1Ni0zOWEzOWEyZS05ODg0LTQ5ZmUtOTY4ZC03ZGJhYzRmZDE1NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTA1NDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFiMDhhYmJmZjRlYjk4ZWZmNzBhY2VhYWM4MGUxMmI3YTZiYWI2MzEzNmI4MTFjMDE1ZTIyNTM4ZGI4YTllOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nJ3f0aQ13p7cK6zhlBIplDKfJaYYY4TDQhEI_BZf_r0)
> 
> and from the cited driver documentation, in our case (Mongo C driver) from http://mongoc.org/libmongoc/current/mongoc_uri_t.html
> 
> ![imagen](https://private-user-images.githubusercontent.com/1534240/302551992-4825fcfc-fa09-48db-b49e-eea74ad6d60d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTcxNDEsIm5iZiI6MTcwNzIxNjg0MSwicGF0aCI6Ii8xNTM0MjQwLzMwMjU1MTk5Mi00ODI1ZmNmYy1mYTA5LTQ4ZGItYjQ5ZS1lZWE3NGFkNmQ2MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTA1NDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdmNDRlMjJlNWJjNjQ3MmI5ZDc1YmU4NGE2YzY0ODJkZTNkYzJiMWZhM2ZlNzE3ZmNmNTQ3NjBiYTM0OTdiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eD0kOQjITpiN-NhY0Pq1gvQ7Wt3InFqlphbqBZ42KOE)
> 
> Thus, the default in the case of not using `connectTimeoutMS=` is the same.
> 
> @goten002 what do you think? Could you adapt your PR #4497 in that way? (the PR would simplify a lot, in fact)

Thank you very much for the thorough analysis and the proposed solution. I agree that changing the default value of -dbTimeout from 10000 to 0 is the optimal approach, especially considering the Mongo C driver's default behavior effectively mirrors what we intended with the original 10000 ms default. This change simplifies the implementation and avoids the complications associated with using negative values. I appreciate your help and guidance on this matter and will proceed to adjust my PR #4497 accordingly.

**Comment by fgalan** [comment]
I would say that after merging PRs #4497 and PR #4501 this issue could be closed. @goten002 what do you think?

Thank you for your outstanding contribution! If you want to continue contributing to Orion I'd suggest to have a look to [help wanted labeled issues](https://github.com/telefonicaid/fiware-orion/labels/help%20wanted) or to the [Orion roadmap](https://github.com/telefonicaid/fiware-orion/blob/master/doc/roadmap.md), for more challenging issues.

**Comment by goten002** [comment]
Thank you @fgalan, for your guidance and support throughout this process. I agree that once PRs #4497 and #4501 are merged, the issue can be closed.

**Comment by fgalan** [comment]
Btw, this issue has made me think it is a good idea to deprecated the old CLIs. This PR has been created about it https://github.com/telefonicaid/fiware-orion/pull/4505.
