### ISSUE TITLE
FIWARE NGSI APIv2 Walkthrough document update

### ISSUE THREAD

**Issue by ArqamFarooqui110719** [telefonicaid/fiware-orion#4519]
When I am trying to run below APIs copied from `FIWARE NGSI APIv2 Walkthrough` document, I'm getting below error.
API:
```
curl localhost:1026/v2/entities/Room1?type=Room -s -S -H 'Accept: application/json' | python -mjson.tool
```
Error:
```
Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```
Above error is occurring due to `python` used in API instead of `python3`.
So I think the APIs should be updated with `python3` in `FIWARE NGSI APIv2 Walkthrough` document as below:
updated API:
```
curl localhost:1026/v2/entities/Room1?type=Room -s -S -H 'Accept: application/json' | python3 -mjson.tool
```
@fgalan Please provide your opinion. If my understanding is correct, I'll raise a PR to update the doc.

**Comment by ArqamFarooqui110719** [comment]
PR #4520

**Comment by fgalan** [comment]
The exact name of the Python executable would depend on the environment (in particular, the operating system and the usage or not of virtual env).

For instance, in my case, using Debian 12.4, both works, depending the case:

```
fermin@bodoque:~$ python --version
bash: python: orden no encontrada
fermin@bodoque:~$ python3 --version
Python 3.11.2
fermin@bodoque:~$ . ~/src/venv/p3/bin/activate
(p3) fermin@bodoque:~$ python --version
Python 3.11.2
```

Thus, I think it would better to include a clarification about this in the beginning of the document (as the one in PR https://github.com/telefonicaid/fiware-orion/pull/4524).

@ArqamFarooqui110719 what do you think?

**Comment by ArqamFarooqui110719** [comment]
Yes, it'd also be a good point to add a clarification

**Comment by fgalan** [comment]
So I'd suggest to merge PR #4524 and close PR https://github.com/telefonicaid/fiware-orion/pull/4520.

Could you close PR #4520, please? Thanks!
