### ISSUE TITLE
Get Statistics when mongoConly activated on Orion-LD

### ISSUE THREAD

**Issue by fabiocabrini** [telefonicaid/fiware-orion#4529]
**Get Statistics when mongocOnly activated on Orion-LD**
When Orion-LD is running on Kubernetes and utilizing the clustered MongoDB, the mongocOnly environment variable is used to ensure everything works. However, activating mongocOnly prevents obtaining internal statistics from the clustered Orion-LD. Attempts to retrieve these statistics result in an HTTP message stating that 'Non NGSI-LD requests are not supported when -mongocOnly is set'.

**Describe the solution you'd like**
I would like to obtain these internal performance indicator information from Orion-LD even when mongocOnly mode is activated. Is there any estimate for this feature to be implemented?

**Describe why you need this feature**
- To analyze these statistics to observe the behavior of each broker present in the cluster.

**Do you have the intention to implement the solution**
- No, I do not have the skills.

**Comment by fgalan** [comment]
I think this issue has not been opened in the right repository. I understand this is the right one: https://github.com/FIWARE/context.Orion-LD

**Comment by fabiocabrini** [comment]
Sorry, thanks for answer.  I will open it in the correct topic!
