### ISSUE TITLE
Get all subservices of a service from ThinkingCities APIs Basic Ops (Collection POSTMAN)

### ISSUE THREAD

**Issue by mhinojosa15** [telefonicaid/fiware-orion#4544]
I need all the Fiware-ServicePath of from Fiware-Service on Orion Context Broker but I can't find any call in the postman collection to get all the subservices of a service. 

![image](https://github.com/telefonicaid/fiware-orion/assets/64640295/5425e16e-9245-4264-9cb9-f772513fe92a)

Can you help me @fgalan! Thanks you!

**Comment by fgalan** [comment]
Currently Orion API doesn't include an operation to list existing services. Not sure if even such operation would be a good idea in the API, as subservices are typically used as isolation unit between tenant...

Typically you as an user know which service and subservice has to use in your NGSIv2 calls to Orion API.

Could you provide more detail on your use case? Why do you need to know all the subservices? Your context entities are not univocally contained in a given set of services/subservices?

**Comment by mhinojosa15** [comment]
My organisation have created a mongo sink and I have to create one by one all of the subservice subscriptions for all entities.
We have 90 subservicies and to do it one by one is a hard job.
I have thought to do a Python script to create all of the subscriptions, that is the reason why I need to know all of the subservices. Could you tell me another option?

**Comment by mhinojosa15** [comment]
Could you tell me another option? @fgalan

**Comment by fgalan** [comment]
You can get if from the Orion database corresponding to the service at MongoDB (named `orion-<service>`). The following query will do the job:

```
db.entities.aggregate([{$group: {_id: "$_id.servicePath"}}])
```

**Comment by mhinojosa15** [comment]
Thanks you @fgalan !!

To finish, I would ask you one last question:

Can you get the public name of a subservice? I've searched the Mongo database and can't find it. Is this possible?

**Comment by fgalan** [comment]
Orion Context Broker has no concept for "public name of subservice" :) so you will never get it from Orion DB.

It seems the client using it (Platform Portal?) is the one that deal with that concept.

(If this is the last question, I'd suggest to close this issue)
