### ISSUE TITLE
Input buffer length

### ISSUE THREAD

**Issue by LeandroGuillen** [telefonicaid/fiware-orion#49]
To catch all possible errors regarding Content-Length, including too large input, Fermin will implement a harness test and Ken will later modify the broker to fulfill this harness test.
It would be good to have the harness test file in git, perhaps a new directpory under 'test/' (test/futureHarnessTests) ?

Cases to be caught:
  1) que el usuario ponga Content-Lengh y honre ese Content-Length
  2) que el usuario ponga el Content-Length y no honre ese Conent-Lenght (pe. atacante malicioso que quiera tirar el broker)
  3) que el usuario no ponga Content-Length
  4) que el usuario simplemente mande un buffer > 1M
  5) que el usuario mande un buffer > 64M (que es el tamaño del buffer interno del broker ahora mismo)

The internal buffer size of 64M should be lowered to 2M (for example) and we should try to avoid having MHD answering for us with that funny message: 

```
<html><head><title>Internal server error</title></head><body>Some programmer needs to study the manual more carefully.</body></html>
```

**Effort: 2 man day**

**Comment by fgalan** [comment]
It seems that this is already covered by existint test harness (and if we find them insuficient, we will open a new issue). Closing.
