### ISSUE TITLE
NGSI9 one-time subscription support

### ISSUE THREAD

**Issue by LeandroGuillen** [telefonicaid/fiware-orion#50]
OMA spec section 5.3.3.1 (subscribeContextAvailability) tells:

> In case of the value 0 [for Duration in the request], the context scomponent SAHLL only notify the current value and SHALL NOT send subsequent notifications (one-time subscription)

Surprisingly, the concept of one-time subscription is only in NGSI9 (in NGSI10 subscription, the above paragraph is not found).

I think this should be a low priority (P2) due to this is an "edge case" and that the client can always use discoverContextAvailability to get the same result.

**Comment by fgalan** [comment]
NGSIv1 has been deprecated and there isn't any equivalente functionality (NGSI9 notifications) in NGSIv2. Thus, this issue should be closed.
