### ISSUE TITLE
JSON object render for ALL vectors

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#505]
### Description
We recently changed the rendering (optionally, using a URL parameter) of JSON vectors of ContextAttributes from a vector to an abject. Life gets a little bit easier for our dear programmers that way, as it seems.
Now, we have more vectors than just the vector of context attributes.
We have many vectors more and it would not be THAT difficult to implement this change from vector-rendering to object-rendering for all other vectors too.

See PR #500 

**Effort: 5 man day**

**Comment by fgalan** [comment]
This consideration is being worked in NGSIv2 specification, thus this issue can be closed.
