### ISSUE TITLE
More checks in style guide checker

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#532]
### Description
The python script we use to ensure we follow the style guide could be improved with more rules.
In Orion, we have decided to always use '{}' for 'if', 'for', 'do' and 'while', also for one-liners.
However, the style guide enforcer script doesn't detect this.

Another thing that is not detected are commented lines that end in whitespace.
Code lines ending in whitespace are detected, but not commented lines.

**Effort: 3 man day**

**Comment by fgalan** [comment]
Duplicated in https://github.com/telefonicaid/fiware-orion/issues/966. Merging issue descriptions there.
