### ISSUE TITLE
Compiling in Ubuntu 14.04 64 bits

### ISSUE THREAD

**Issue by acs** [telefonicaid/fiware-orion#565]
When compiling in Ubuntu 14.04 64 bits there are several minor errors with:

/home/acs/devel/fiware/orion/fiware-orion/src/lib/orionTypes/TypeEntityVector.cpp:153:50: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘uint64_t {aka long long unsigned int}’ [-Werror=format=]

Changing %lu to %llu fixes the problem. It seems that the correct fix is to use "PRIu64" but in "gcc version 4.8.2" it does not work directly.

**Effort: 2 man day**

**Comment by vijayn** [comment]
Can some one guide me in setting up Orion Context Broker on a Ubuntu System?

**Comment by fgalan** [comment]
Maybe the information posted in this issue could help: https://github.com/telefonicaid/fiware-orion/issues/11

**Comment by fgalan** [comment]
> Can some one guide me in setting up Orion Context Broker on a Ubuntu System?

A procedure for Ubuntu 18.04 is described at https://fiware-orion.readthedocs.io/en/master/admin/build_source/index.html#ubuntu-1804-lts.

We understand this is enough by the time being so this old issue is closed.
