### ISSUE TITLE
make rpm without coap

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#579]
### Description
A user had problems creating an RPM.
After some investigation we found out it was due to a compilation error. He didn't have COAP installed.
So, we removed proxyCoap from CMakeLists.txt and 'make clean install' worked just fine.

After this, we tried 'make rpm' again and it failed. In the traces we saw that it still failed due to trying to compile proxyCoap ...

We need to investigate why this happens and perhaps even make it possible to create an RPM without COAP.

 **Effort: 2 man day**

**Comment by fgalan** [comment]
Since the existence of https://github.com/telefonicaid/fiware-orion/issues/1202, this issue is obsolete.
