### ISSUE TITLE
Unexpected unique value in the response of convenience query context

### ISSUE THREAD

**Issue by anabelengp** [telefonicaid/fiware-orion#588]
The response to GET v1/contextEntities/Room1 only allows one contextElement as a result:
```
{
  "contextElement": {
    ...
  },
  "statusCode":{
    ...
  }
}
```
However, the response should be formatted as a vector, since the request does not ask for a specific type.
```
{
  "contextResponses": [
    {
      "contextElement": {
        ...
      },
      "statusCode": {
        ...
      }
    }
  ]
}
```
Moreover, it seems that if we have several entities with different types, the entity returned by this operation is an arbitrary one (the first one, perhaps).

The same issue will affect if we have several entities with the same id and type in different servicePaths.

**Comment by fgalan** [comment]
GET operations for entities/attributes has been re-formulated in NGSIv2. Thus, this issues is obsolete. Please have a look to the new methods at http://telefonicaid.github.io/fiware-orion/api/v2/ and, if you need clarifications or oversee new problem, don't hesitate contact me to talk about it.
