### ISSUE TITLE
Allow MongoDB driver tuning (e.g. reduce keep-alive time in DB connections)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#589]
When runnning CB with replica set configuration (i.e. using `rplSet` CLI option) it may happen that if the VM running the host where mongo primary runs goes down, the contextBroker may still have connections established to the powered-off machine. It does not acknowledge that mongo primary is down. As a result, all the requests to the CB fails.

Note that this situation is different from the one in which the mongod primary process goes down, in which case, the host OS seems to be able to manage to cut all the connetions with contextBroker, so CB gets reconnected to the new primary (or secondary in read-only mode).

This problem is probably caused by the default keepalive period used by MongoDB driver is too large. We should look at how this can be configured at start time as a driver/connection startup parameter.

**Effort: 2 man day**

**Comment by fgalan** [comment]
Changes to "backlog" label, as this will become part of the planned work.

**Comment by jmab20** [comment]
http://docs.mongodb.org/manual/faq/diagnostics/#Troubleshooting-Socketerrorsinshardedclustersandreplicasets

You can change the tcp_keepalive_time value with the following operation:
echo 300 > /proc/sys/net/ipv4/tcp_keepalive_time

With C++ driver, for both DBClientConnection and DBClientReplicaSet, the socket timeout is set in the constructor and is just for read and write timeout. Connection timeout is hard-coded to 5 seconds. To set this time can be used a config file.

10gen always responds to update, https://jira.mongodb.org/browse/SERVER-5793 
It looks like the current situation (in mongodb 2.4) is that if a replica set primary loses its network connectivity (we simulate that by doing 'sudo ifdown eth0' on the primary), then reelection happens normally and mongos detects the new primary, BUT existing client connections via that mongos instance will not be terminated, and will continue in their hanging state.

Fix Version/s: 2.5.0

**Comment by fgalan** [comment]
Implemented in PR #841.

At the end, the scope of the tuning has been limited to driver timeout. Regarding further tuneable properties (if needed), it should be better to create separated issues.
