### ISSUE TITLE
New request for the broker to return a list of its services

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#598]
The broker is growing and it has now a LOT of services.
It would be fairly easy to implement a request for the broker to return a list of the services it supports.

I'm thinking:
- GET /services
- GET /*/services
- GET / */ */services

E.g.:
- GET /v1/services:  return all services whose URL-path starts with "/v1"
- GET /v1/log/services: return all services whose URL-path starts with "/v1/log"

Each item in the response would contain the following info:

```
- path  (e.g. "/v1/registry/registerContext")
- short description of the service
- input payload (e.g. "registerContextRequest")
- output payload (e.g. "registerContextResponse")
```

The logic is implemented in one hour, this is easy stuff.
All the short descriptions may take a little longer, and also to look up all the payloads,
Estimated effort for EVERYTHING: 2-3 days

**Comment by fgalan** [comment]
We should consider how this looks like under the light of the NGSIv2 API.

**Comment by fgalan** [comment]
This issue is not especifically related with NGISv2, so APIv2 label is removed. The issue keeps opened.

CC: @jmcanterafonseca

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan Sir,
This issue is pretty old. But it seems a good feature to me. What is your opinion?
A new API (Some thing like):
```
GET /v2/services
```
Which may response list of all the services as output that Orion is using:
