### ISSUE TITLE
Handling of more than one reply from mongo, where only one reply is supported by the broker

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#599]
The issue #588 addresses a current weakness in the broker, about the broker returning not a vector of values but just one single value.
Until this is fixed, in some service routines a check is made to make sure only one response is returned from mongo and if there is more than one, an error response is returned to the caller.

This behavior is implemented, in some of the service routines, e.g. in the function deleteAttributeValueInstanceWithTypeAndId:

    if (response.contextElementResponseVector.size() == 0)
    {
      statusCode.fill(SccContextElementNotFound,
                      std::string("Entity-Attribute pair: '") + entityId + "-" + attributeName + "'");
    }
    else if (response.contextElementResponseVector.size() == 1)
    {
       ContextElementResponse* cerP = response.contextElementResponseVector.get(0);
      
      if (response.errorCode.code != SccNone)
      {
        statusCode.fill(&response.errorCode);
      }
      else if (cerP->statusCode.code != SccNone)
      {
        statusCode.fill(&cerP->statusCode);
      }
      else
      {
        statusCode.fill(SccOk);
      }
    }
    else
    {
      statusCode.fill(SccReceiverInternalError,
                      "More than one response from deleteAttributeValueInstanceWithTypeAndId::mongoUpdateContext");
    }

But, it might be necessary in other service routines as well.

This issue is about finding those service routines and implementing this check.

**Effort: 2 man day**

**Comment by fgalan** [comment]
serviceRoutineV2 implementation is taking this into account from the very beginning (this issue was about to review the existing NGSIv1 conv ops). Thus, it can be closed.
