### ISSUE TITLE
 Missing distro Ubuntu 14.10 on /src/app/contextBroker/CMmakeLists.txt

### ISSUE THREAD

**Issue by tclauss** [telefonicaid/fiware-orion#632]
Installing("sudo make install") contextBroker Orion on Ubuntu 14.10 (after "sudo make") returns liboost link errors: 

/usr/bin/ld: cannot find -lboost_thread-mt
/usr/bin/ld: cannot find -lboost_filesystem-mt
/usr/bin/ld: cannot find -lboost_system-mt

Adding to ../src/app/contextBroker/CMmakeLists.txtCMakeLists.txt: 

ELSEIF(${DISTRO} STREQUAL "Ubuntu_14.10")
  # ADDED FOR UBUNTU 14.10
  MESSAGE("contextBroker: Ubuntu DISTRO: '${DISTRO}'")
  TARGET_LINK_LIBRARIES(contextBroker ${STATIC_LIBS} -lmicrohttpd -lmongoclient -lboost_thread -lboost_filesystem -lboost_system -lpthread -lssl -lcrypto -lgnutls -lgcrypt)

fix this error and the contextBroker install properly on Ubuntu 14.10.

**Comment by LeandroGuillen** [comment]
This is already fixed, I believe. @tclauss, could you check and close this issue?

**Comment by tclauss** [comment]
OK. Thks :-)
