### ISSUE TITLE
Possible wrong format in errorCode for pagination

### ISSUE THREAD

**Issue by FiwareULPGC** [telefonicaid/fiware-orion#668]
Using the pagination feature with details param enabled we get an errorCode like:

XML version
```
<errorCode>
    <code>200</code>
    <reasonPhrase>OK</reasonPhrase>
    <details>Count: 322</details>
</errorCode>
```
JSON version
```
"errorCode" : {
    "code" : "200",
    "reasonPhrase" : "OK",
    "details" : "Count: 322"
 }
```
We have a doubt with the details field, it seems to be a general field and it hasn’t a specific format. The “problem” resides in that “Count” isn’t a field.  For example, if the JSON version is used by  javaScript function, get the numbers of elements is something like:

```javascript
    //data has the orion response
    var elements  =parseInt(data.errorCode.details.replace(“Count: ”,””));
```
If “Count” could be a property the functions would be something like:
```javascript
    //data has the orion response
    var elements  =parseInt(data.errorCode.details.Count);
```

Although according to the official documentation actual approach seems to be the desired behavior, the second approach may be more coherent with the JSON structure. If details field could have more information at same time, getting the number of elements will be harder.

**Comment by fgalan** [comment]
It has been taken into account in APIv2 with the `X-Total-Count` header (see https://github.com/telefonicaid/fiware-orion/issues/947). Thus, this issue can be closed. Any futher comment (welcomed! :) should be included in issue #947
