### ISSUE TITLE
Subscriptions with empty or absent entity.type

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#691]
### Description
Making tests with service-path in subscriptions (PR #689), we discovered two cases that fail with an empty or absent entity.type in the subscription.

Two functional tests are made (to reproduce the problem):

    test/functionalTest/cases/675_servicePath_in_ngsi10_subscriptions/simple_ngsi10_subscriptions_with_empty_type_and_service_path.test.DISABLED
    test/functionalTest/cases/675_servicePath_in_ngsi10_subscriptions/simple_ngsi10_subscriptions_with_no_type_and_service_path.test.DISABLED

[ I'm not sure the service-path has anything to do with these failures, but other func-tests, without service-path, should be made to verify this. ]

**Comment by kzangeli** [comment]
I just did a quick test to verify the problem of this issue:

I took simple_ngsi10_subscriptions_with_empty_type_and_service_path.test.DISABLED, removed the DISABLED and tried the test exactly the way it is:

# 01. Make accumulator subscribe to all entities of Service Path /Madrid/#
# 02. Create entity E/T with Service Path /Madrid
# 03. Create entity E/T with Service Path /Barcelona
# 04. Check that the accumulator received the notification of E/T Madrid only

It failed in part 04 - nothing received by the accumulator.

Next test was to remove all service paths to make sure the service path had nothing to with the failure, and it didn't. Without service path, the accumulator still get no notifications.

Last test was to change the subscription in part 01. The entity::type was changed from empty to "T" and this modification made the test work - finally the accumulator receives notifications.

It seems like we have a problems with subscriptions with empty types.
Should match ANY TYPE but it doesn't work that way.

**Comment by kzangeli** [comment]
The notifications arrive to the accumulator if I change the subscription to

    isPattern=TRUE and
    entity::id='E.*'

**Comment by fgalan** [comment]
Fixed in PR #923
