### ISSUE TITLE
Query forward in JSON

### ISSUE THREAD

**Issue by sergg75** [telefonicaid/fiware-orion#695]
When configuring a context provider, Orion sends the forwarded queryContext messages (and waits for the  response) only in XML.
It would be helpful to support also JSON for forwarded queries and their responses, specially for context providers that do not rely on orion NGSI10 implementation.

**Comment by fgalan** [comment]
This seems to be related with bug https://github.com/telefonicaid/fiware-orion/issues/703. Possibly, once the bug get solved, possible this issue gets solved too.
