### ISSUE TITLE
CB response ok in an entity creation, but is not show when are listed

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion#708]
When an entity is created with a type, and then, an entity with the same id but empty type is created, the contextbroker responds ok, but the entity is not created.

But if the creation is in the opposite order, first the entity with empty id and then, the entity with a a type, the context broker responds as ok and the entityes are listed.

### Script to execute the case 1

```
#/bin/bash
HOST=localhost
SERVICE=Service123
SUBSERVICE=/Subservice123
#Create an entity with id and type
CREATE=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
    -d '
        {
          "id": "firstID",
          "type": "firstType",
          "attributes": []
        }')
#List the entities
LIST=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X GET \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
)
echo $CREATE
echo "**********************"
echo $LIST
#Create an entity with the same ID but different type
CREATE=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
    -d '
        {
          "id": "firstID",
          "type": "",
          "attributes": []
        }')
#List the entityies
LIST=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X GET \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
)
echo
echo "Second Iteration"
echo
echo $CREATE
echo "**********************"
echo $LIST
```

### Script to execute the case 2
```
#/bin/bash
HOST=localhost
SERVICE=Service1234
SUBSERVICE=/Subservice1234
#Create an entity with id and type
CREATE=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
    -d '
        {
          "id": "firstID",
          "type": "",
          "attributes": []
        }')
#List the entities
LIST=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X GET \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
)
echo $CREATE
echo "**********************"
echo $LIST
#Create an entity with the same ID but different type
CREATE=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
    -d '
        {
          "id": "firstID",
          "type": "fistType",
          "attributes": []
        }')
#List the entityies
LIST=$(\
curl http://$HOST:1026/v1/contextEntities \
    -s \
    -X GET \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Fiware-Service: $SERVICE" \
    -H "Fiware-ServicePath: $SUBSERVICE" \
)
echo
echo "Second Iteration"
echo
echo $CREATE
echo "**********************"
echo $LIST

```

**Comment by fgalan** [comment]
Although it may seem to be weird, script 1 is working properly according to CB defined functionality. The meaning of type = "" in the second POST doesn't lead to  "entity with id firstID and without type" but "any entity with id firstID no matter its type" (see https://forge.fi-ware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Using_empty_types). Thus, given that there is already one entity which match that "any entity with id firstID no matter its type" (i.e. the one created in the first POST, with id firstID and type firstType) the request is not interpreted as a creation but as an update (from Orion user manual: "current Orion Context Broker version interprets APPEND [the POST on that URL equals to an APPEND updateContext] as UPDATE if the entity already exists").

There is a way of meaning "entity without type", using the `!exists` filter. If you change the following line 35 in script1

```
curl http://$HOST:1026/v1/contextEntities \
```
for this one

```
curl http://$HOST:1026/v1/contextEntities?!exist=entity::type \
```

you will get 2 entities created at the end (one with type and the othet without it).

**Comment by fgalan** [comment]
After the explation I think this issue is closeable. However, I think is an interesting case to be documented as Q&A in SOF. @jcalderin , what do you think?

**Comment by jcalderin** [comment]
After understanding the functionality, its reasonable how it works, but its difficult to see it.... i'm totally agree about document it in Q&A :)

**Comment by fgalan** [comment]
Moved to SOF: http://stackoverflow.com/questions/27983707/context-broker-with-an-entity-with-type-created-response-ok-in-an-entity-creati
