### ISSUE TITLE
Context Provider: Provider reference is only added to the first contextElement of the response.

### ISSUE THREAD

**Issue by gzarrub** [telefonicaid/fiware-orion#720]
If a queryContext of multiple entities, which have been registered with a context provider, is done, the Context Broker only adds the provider reference to the first contextElement of the response, the response of the other contextElements seems like a normal response of entities without context provider.

I don't know if it is working properly or if on the other hand it hasn't been taken into account.
>
{u'contextResponses': [
{
'contextElement': {'attributes': [...], 'id': 'test_id1', 'isPattern': 'false', 'type': 'test_type'},
**'statusCode': {'code': '200',
                       'details': 'Redirected to context provider (provider url)',
                       'reasonPhrase': 'OK'}**
},
{
'contextElement': {'attributes': [...], 'id': 'test_id2', 'isPattern': 'false', 'type': 'test_type'},
**'statusCode': {'code': '200', 'reasonPhrase': 'OK'}**
},
{
'contextElement': {'attributes': [...], 'id': 'test_id3', 'isPattern': 'false', 'type': 'test_type'},
**'statusCode': {'code': '200', 'reasonPhrase': 'OK'}**
}
]}
>

**Comment by fgalan** [comment]
By the moment we will label this as bug until we have time to analyze in deep. Thanks for the feedback!

**Comment by fgalan** [comment]
From 0.21.0 on (about to be released), CB no longer returns the "Redirected to" detail in order to improve client transparence and topology-hiding security. Thus, this issue will be closed.
