### ISSUE TITLE
Forward ngsi10 Query/Update requests not only in XML

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#722]
The forwarding of requests to context providers is right now always in XML.
Lots of clients prefer JSON so the CB should allow to forward requests in JSON as well.

To implement this we need a few modifications:
- The function **sendHttpSocket** eats the HTTP headers from the response.
   The function must return the headers to the caller somehow.
- The broker is unable to parse QueryContextResponse in JSON
- The broker is unable to parse UpdateContextResponse in JSON
- Selection of the format to use for the forward message (XML or JSON).
  The simplest approach would be to just select the same format as the original
  request. A better approach might be to make the context provider inform the 
  CB about what formats are allowed (perhaps copy the 'Accept' header from the registration?)
- The function sendHttpSocket should get the name changed - *httpMsgSend*?
- sendHttpSocket always sends XML/JSON as Accept HTTP header. Is this what we want?

**Effort: 3 man day**

Optionally (phase II)
- If the context provider doesn't accept the format of the forwarded request (XML/JSON), check the HTTP header 'Accept' and resend the forward in a better format, if possible. If not, report error.

**Comment by fgalan** [comment]
In sprint review meeting on February 27th a simpler approach has been decided:

* The CPr will include either "Accept: application/json" or "Accept: application/xml" in the registerContext request.
* The CB will record "XML" or "JSON" in the registrations document in the DB corresponding to that registerContext. A new field in the document will be needed (similar case that in the subscriptions collection).
* The CB will use always the format stored in the database to interact with the CPr. MongoBackend will provide the format along the CPr URL when return this info to serviceRoutines.

**Comment by fgalan** [comment]
The "simple solution" designed in February 27th has been implemented in PR #899 for Orion 0.21.0. However, let this issue opened in order to implement the optimal solution (HTTP negotiation, paying atention to Accept and Content-Type headers) in the future (milestone will be removed).

**Comment by fgalan** [comment]
NGSIv2 only allows application/json notifications, so maybe this issue can be closed.

**Comment by kzangeli** [comment]
Yes, it can be closed

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by fgalan** [comment]
(Wrongly reopnened... after XML removel this issue has no sense anymore. Closing again)
