### ISSUE TITLE
DB dropping in TEARDOWN

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#733]
All functional tests should drop their databases in the TEARDOWN part of the test

**Effort: 1 man day**

**Comment by kzangeli** [comment]
All dbInit-dbDrop pairs ok (in PR #735).
What is still missing is to make sure all functests using tenants also do the corresponding dbInit-dbDrop.

**Comment by fgalan** [comment]
This issue seems to be a duplicated of #651 (which is already closed).
