### ISSUE TITLE
Orion Convop GET /v1/contextTypes seems to break ContextBroker

### ISSUE THREAD

**Issue by anabelengp** [telefonicaid/fiware-orion#740]
To reproduce the crash:

01. Populate the broker with two entities:

    {
        "contextElements": [
            {
                "type" : "",
                "isPattern" : "false",
                "id" : "QA_Provision_NoType"
            },
            {
                "type" : "",
                "isPattern" : "false",
                "id" : "id2",
                "attributes" : [
                    {
                        "name" : "asdf",
                        "type" : "asdf",
                        "value" : "asdf"
                    }
                ]
            }

02. Make a petition for the contextTypes, with JSON object format:

    curl localhost:1026:/v1/contextTypes?attributesFormat=object

The broker dies trying to put together the output payload.
Curiously enough, the HTTP headers are sent, while the payload is not ...

Also, without the URI parameter 'attributesFormat=object' the petition works just fine

The crash occurs withthe latest broker software from *develop* as of the date of creation of this issue.

**Comment by fgalan** [comment]
Which Orion version are you using? Please send to @ken and me by email a dump of the database y the crash situatio.

**Comment by kzangeli** [comment]
If I remove the attributes for the second entity, the broker doesn't crash (which is an expected result)

**Comment by fgalan** [comment]
Fixed in PR #741 (release/0.4.1) and PR #742 (develop)

Waiting for @anabelengp confirmation to close it.

**Comment by anabelengp** [comment]
Version 0.19.0-next from Tue Feb 24 2015 works! (Tested with the same set of entities that produced the crash)
