### ISSUE TITLE
Push elements in attributes which value is a vector

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#744]
At the present moment (Orion 0.18.1), the only way of adding an element to an attribute which value is a vector is to update such attribute with a new vector containing the new element.

However, I think that pushing elements in attributes which value is a vector whitout needing to update the whole vector is an interesting feature to take into account.

**Comment by fgalan** [comment]
Raised in http://stackoverflow.com/questions/28347889/orion-context-broker-push-array-element-in-entities/28369017

**Comment by fgalan** [comment]
Not only pushing a single element, but a list of them.

**Comment by inter-coder** [comment]
My vision includes the insertion of Observer who will trigger the function on the basis of parameters. The script with functional examples is here https://github.com/inter-coder/Orion-Web-Proxy-for-Cross-Domain

**Comment by fgalan** [comment]
This needs to be re-considered under the light of NGSIv2 API.

**Comment by fgalan** [comment]
Out of the scope of NGSIv2, althouth it is a good idea that could (potentially) be included in a later version of the API (v2.1) in a backward compatible way.

CC: @jmcanterafonseca

**Comment by fgalan** [comment]
> fiware-orion:latest shouldn't point to 3.1.0-next. It should point to latests commit in master branch. Could you provide more detail on how are you pulling and running this image, please?

I've done the test myself and you are right: there is some problem with fiware/orion:latest image. I have opened an issue here: https://github.com/telefonicaid/fiware-orion/issues/4028

In the meanwhile, you can use telefonicaiot/fiware-orion:latest, that it works correctly

**Comment by fgalan** [comment]
I have tested

```
curl localhost:1026/v2/entities/E/attrs -s -S -H 'Content-Type: application/json' -d @- <<EOF
{
  "A": {
    "value": { "\$push": {"\$each": [2, 3, 4]} },
    "type": "Array"
  }
}
EOF
```

but it is not working as expected, as the CB replacing logic in dbEncode() is changing `$each` to `>each` before doing the findAndModify in DB.

I'll try to fix.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-orion/pull/4029
