### ISSUE TITLE
Is '#' considered a valid character for ngsi10 updates?

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#746]
Question raised during PR #743.

Look for (or create a new) functional test that makes sure '#' *is not* accepted as a valid character for the service-path in /v1/updateContext.

If '#' is accepted, then implement a call to the servicePathCheck function (in lib/common/string.cpp) and a functional test to assure it's working.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Not only in /v1/updateContext, but also in all the equivalent conv ops.

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/fiware-orion/pull/748
