### ISSUE TITLE
API v2 wish list

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#768]
After several years of experience with the NGSI "clasical" API (the one we refer with "v1" in the URLs) and several concessions needed to mantain backward compatibility along the time, PR after PR, let's thought about if we could re-design the API without backward compatibilty legacy and call it "v2" :)

This issue is a placeholder to keep all the ideas around. You are encourage to participate in the discussion adding comment to this issue, specially if you are an intense user of NGSI. Periodically, I will review the issue, consolidating comment into items in the issue body (and removing the comments).

List:
- Based exclusively in JSON. No more XML :)
- Error management in v1 API is a little bit crazy: the type name varies (some times is statusCode, some others errorCode) and may appear at the end of the message or in the middle without others elements. We should simplify this.
- Encoding the count value with `&details=on`in the the details field as text is ugly. There are better ways of doing this.
- Updating shouln't include an "echo" message of the same request the client sent. Just the result of the operation (either it was ok or not) is enough.

**Comment by kzangeli** [comment]
Attributes should have two more fields (at least):
- local/remote attribute
- providing application

With this addition, the forwarding of updates and queries we have implemented for NGSI10 would no longer depend on the registrations from NGSI9. That is not the only advantage ...

**Comment by kzangeli** [comment]
Just a detail:
registration responses in NGSI9 have the field 'registrationId' as mandatory.
What if the registration couldn't be performed (e.g. due to a database error).
Right now we return an registrationId of '000000000000000000000000000000000' if that happens.
Doesn't make much sense ...

**Comment by kzangeli** [comment]
Wouldn't it be nice (apart from all other security we can add from outside of the broker) if every attribute had permissions similar to file-permissions in a unix file system?

{ read, write, execute } for { owner, group, world }

Of course, we'd have to manage users and groups to implement this.
No problem! :-)

**Comment by kzangeli** [comment]
Some convenience operations (especially of ngsi10 query type) have the ability to return only one unique entity (context element), while the query could have more than one entity as a result.
What we do in these cases is that we select the first hit from the query and we return it as response.

These convops should be modified to return a list of entities.

**Comment by kzangeli** [comment]
Convenience Operations are operations that do the same operation as a Standard Operation, but with simpler payload (or no payload at all).

Thus, each conv-op has a corresponding std-op.

All conv-ops should respond with the same response-type as their corresponding std-op.

**Comment by kzangeli** [comment]
In v1, all standard operations use the verb POST.
In some cases, *UPDATE*. *APPEND*, *DELETE* is later added in the payload.
This is not very good and we should use the proper verbs for each operation for v2.

E.g. for updates, the updateType should not be in the payload, but reflected in the request verb instead.

**Comment by kzangeli** [comment]
In v1, context provider forwarding depend on NGSI9 registrations to identify the Context Providers of the attributes.

In v2 I would propose to remove this strange way of identifying the Context Providers and just put that information where it should have been from the beginning - as a part of the ContextAttribute.

This enhancement makes us capable to easily implement UpdateContext/APPEND and UpdateContext/DELETE forwarded to Context Providers as well. Right now (in v1) we only support forwarding for  UpdateContext/UPDATE.

**Comment by kzangeli** [comment]
In v1 we cannot support the URI params "entity::type EMPTY" and "entity::type NON-EMPTY" as UpdateContextRequest doesn't contain Restriction.

Unless we forbid EntityId::type to be empty (my vote), we should add a way to be able to pass these flags in the v2-equivalent structure 'UpdateContextRequest'.
This will probably not be the only restriction we'd want in updates, so Restriction should be added to UpdateContextRequest, just in case.

**Comment by fgalan** [comment]
Having entities without a type and querying without a type with special semantics is a mess. Thus, I would be better simply to have pattern for types (how to encode this in NGSI is pending, e.g. "isPatternType"). Morevoer, event allowsing entities with type "" is a bad idea, maybe entity type should be mandatory.

**Comment by fgalan** [comment]
The attribute ID stuff is confusing and easy to implement with regular attributes (e.g. just use ":" to add the ID after the base attribute name). Remove it from v2.

**Comment by kzangeli** [comment]
About entities without type: I agree 100%
Let's make entity::type mandatory in v2, and the same for attributes and even metadata, I think.
Why make life more complicated on purpose?

**Comment by fgalan** [comment]
Remove the operations with "/attributes" which are exactly equal to the same operations without "/attributes". It doesn't make sense to have such duplication in URLs and operations.

**Comment by LeandroGuillen** [comment]
Have entities inform their service path, maybe as a new field, metadata, ...

This opens up new high tech possibilities like changing service paths :)

**Comment by dmoranj** [comment]
Changing service path may be a problematic feature, as other GEs might be
using it in data structures that cannot be easily changed. We better think
about this with care.

**Comment by fgalan** [comment]
The operation to get the value of a single value is higly verbose:

```
GET <cb_host>:<cb_port>/v1/contextEntities/type/Restaurant/id/LeBistro/attributes/average_scoring

{
  "attributes" : [
  {
    "name": "average_scoring",
    "type": "float",
    "value": "3.2"
  }
  ],
  "statusCode" : {
    "code" : "200",
    "reasonPhrase" : "OK"
  }
} 
```

It could be simplified to just:

```
GET <cb_host>:<cb_port>/v1/contextEntities/type/Restaurant/id/LeBistro/attributes/average_scoring

{
   "type": "float",
   "value" : "4.2"
}
```

and, in that sense, be homogenous with the operation to update the attribute:

```
PUT <cb_host>:<cb_port>/v1/contextEntities/type/Restaurant/id/LeBistro/attributes/average_scoring
{
   "value" : "4.2"
}
```

**Comment by Adirio** [comment]
The wish proposed by @fgalan on 7th of April conflict with the first one made by @kzangeli the 23rd of February. One of the two aproaches should be choosen, verbose but common for both standard and convenience operations, or simplified for convenience operations but diferent from the standard ones.

If updateActions don't get removed, they should be properly defined. A forth updateAction should be added (proposed name APPEND&UPDATE) that works as the actual APPEND (updating if it already exists) but APPEND should not work like this as this causes unexpected behaviour.

1. __APPEND:__
  * __Entity does not exist:__ create entity and attributes with their initial value.
  * __Attribute does not exist:__ create attributes with their initial value.
  * __Attribute already exists:__ do nothing and send error (attribute already exists).
2. __UPDATE:__
  * __Entity does not exist:__ do nothing and send error (entity does not exist).
  * __Attribute does not exist:__ do nothing and send error (attribute does not exist).
  * __Attribute already exists:__ update attribute's value.
3. __APPEND&UPDATE:__
  * __Entity does not exist:__ create entity and attributes with their initial value.
  * __Attribute does not exist:__ create attributes with their initial value.
  * __Attribute already exists:__ update attribute's value.
4. __DELETE__
  * __Entity does not exist:__ do nothing and send error (entity does not exist).
  * __Attribute does not exist:__ do nothing and send error (attribute does not exist).
  * __Attribute already exists:__ delete attribute.

If they get swapped with the request verb, POST should retain APPEND behaviour described above, PUT should have the same behaviour as UPDATE and DELETE would keep the behaviour for itself. The APPEND&UPDATE behaviour should not be used by default nor by POST nor PUT requests, it should be only be used if a specific header is set for one or both of the previous request verbs.

Explanation on why APPEND should not update a value if already exists by default. Most of the times when you create a new entity you set some initial values, which may even be empty, that you will modify. If the attribute already exists and someone is already modifying it's value, updating a valid value for an initial value would turn the value non-valid until the next update action arrives. This behaviour should still be offered as non-dafult as it may be useful for some applications but in general the initial value set on a POST/APPEND action should not modify a real value set by a previous UPDATE action.
The same way you don't set a value to empty to delete it (you use the DELETE action), APPEND and UPDATE should be 2 separate actions. In v1 UPDATE is not used as you get the same behaviour with APPEND, so separating this actions would also allow better error handling.

**Comment by kzangeli** [comment]
Thank you very much for your comment, @Adirio.
I pretty much agree to what you say in your post.
Two comments:
1. The new proposed behavior on "APPEND" is probably not according to the NGSI standard, which is not all that important for what we call v2.
I would call it "CREATE" (or "INSERT") instead of "APPEND" though. It is pretty much what it is.
2. The third type 'APPEND&INSERT', isn't this like what's called UPSERT in some database?

**Comment by Adirio** [comment]
@kzangeli names in my post are just place holders, substitute them for whatever you like.

I actually like the __CREATE__ name (it also has 6 letters as the other 3) and the one I called __APPEND&UPDATE__ could stay as __APPEND__. I modified my previous comment to reflect this new names.

**Comment by Adirio** [comment]
To add to the wish list, an following my previous posts, the behaviour of an existing _ONCHANGE_ subscription when __CREATE__ or __UPDATE__ are executed should be defined.

In my opinion, __CREATE__ should be used as an instantiating action, so it shouldn't trigger an _ONCHANGE_ notification. Actual behaviour is like this if the attribute already exists as not modifying the value as specced 3 comments above wouldn't trigger an _ONCHANGE_ notification but if the subscription exists but the attribute doesn't, what can be done, creating a new attribute would trigger an _ONCHANGE_ notification and this behaviour should be changed. The __CREATE__ action is ment to be used when you know you need some entity's attribute but you don't know yet its first value, so you set an initial value that shouldn't be sent to subscribers that are looking for real values. In the other hand, __APPEND__ actions should send an _ONCHANGE_ notification the same way as __UPDATE__ do, as __APPEND__ is ment to be used as an __UPDATE__ for any data that doesn't care if it already existed while __UPDATE__ is ment to be used when you need to have created the attribute prior to the __UPDATE__.

This way the 3 verbs should have a sense:
__CREATE__ a sensor as I'll be using it but not yet have its output.
__UPDATE__ a sensor when i get an output value from it.
__DELETE__ a sensor when you don't want more outputs from that sensor.
__APPEND__ a sensor when I don't care if it exists or not, I have an output value and I'll submit it; or when I want to create a sensor but I already have an output value from it.

A sensor is used as an example because I wasn't sure if my words were clear.

**Comment by fgalan** [comment]
This issue has been considered not essential to be included in final version of NGSIv2, so it will be closed.

CC: @jmcanterafonseca
