### ISSUE TITLE
CPr fully functional

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#787]
Current CPr functionality (as implemented in 0.19.0) has several limitations:
- A query/update request involving several redirections (e.g. a query for E-{A,B} with attribute E-As managed by CPR1 and attribute E-B is managed by CPBR2) is not supported.
- Context Providers are designed to be simple, so they only implement queryContext and updateContext. However, Orion is not able to transform convenience operations to standard operation at forwarding time.
- The case of entities which local attributes and remote attributes at the same time is not correctly supported. We have some temporary hacks for that (developer for CPBR8) but they are not a definitive solution. For example, they only allow mono-CE updateContext and queryContext.

This issue is about implementing full CPr functionality. There is a document that described the issue in detail, just ask me for it.

**Comment by fgalan** [comment]
Part of the work done in 0.20.0, but complete functionality deffered to 0.21.0

**Comment by kzangeli** [comment]
See also issue #858

**Comment by fgalan** [comment]
Implemented in PR #886

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
