### ISSUE TITLE
Include test of URI param notifyFormat in ngsi9 subscription

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#789]
This is the PR that needs to be enhanced with new functests:
https://github.com/telefonicaid/fiware-orion/pull/783

**Comment by kzangeli** [comment]
Looking a little closer, this is not even implemented.

    postUpdateContextAvailabilitySubscription.cpp:
    // FIXME P6: by the moment, we are assuming that notification will be sent in the same format than the one
    // used to do the subscription, so we are passing ciP->inFomat. This is just an heuristic, the client could want
    // for example to use XML in the subscription message but wants notifications in JSON. We need a more
    // flexible approach, to be implemented

**Comment by fgalan** [comment]
However, the test harness uri_params_and_subscriptions.test seems to be testing that behaviour...

Maybe the comment is obsolete?

**Comment by kzangeli** [comment]
This is the call:
    ciP->httpStatusCode = mongoUpdateContextAvailabilitySubscription(&parseDataP->ucas.res,
                                                                   &ucas,
                                                                   ciP->inFormat,
                                                                   ciP->tenant);

(note ciP->inFormatas the third parameter)
So, unless mongoUpdateContextAvailabilitySubscription implements the part with looking at the URI param (I really don't think so), this thing is not implemented.

Note that this is ngsi9.
It is probably implemented for ngsi10 subscription.

**Comment by fgalan** [comment]
The test I mention is for NGSI10 so probably the situation is that it works for NGSI10 but not for NGSI9.

Thus, this PR is not only about including the `?notifyFormat` in cases/111_XXX .test , but also about implementing the missing functionality in NGSI9 standard operations and include a "base .test" for NGSI9 similar to the existing one for NGSI10 (i.e. uri_params_and_subscriptions.test).

**Comment by fgalan** [comment]
Fixed in PR #865
