### ISSUE TITLE
Implement operator[] in all vector-like classes and get rid of all get() occurrences

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#810]
Some classes already implement the operator[] but we have to do an overall refactor of this.

**Effort: 3 man day**

**Comment by kzangeli** [comment]
Also, the older method _**get()**_ should be removed.

Actually, if we start with removing those 'get-methods', the compiler will tell us wherever a modification is necessary.

**Comment by fgalan** [comment]
I understand that we are chosing [] (vs get() or at()) because we found [] shorter and easier to understand.

**Comment by fgalan** [comment]
Fixed in PR #1633
