### ISSUE TITLE
Behavior of URL with final '/' vs without it

### ISSUE THREAD

**Issue by LeandroGuillen** [telefonicaid/fiware-orion#828]
The usage of '/' could make Orion behave in a way that is not particularly obvious.

Example:
**GET /v1/contextEntityTypes/** queries for the empty type "".

Is that what was expected to happen?

**Comment by kzangeli** [comment]
Nice side effect! :-)

No, this should not happen. Needs to be fixed, I would say.

**Comment by LeandroGuillen** [comment]
And how would we query for an empty type? Maybe a special parameter of the "type=empty" kind?

**Comment by fgalan** [comment]
In my opinion, as a general rule, each URL in the form:

```
GET /foo/bar/ruru/
```

show "route" to the same URL than:

```
GET /foo/bar/ruru
```

**Comment by kzangeli** [comment]
Right now we can't do it (except for your new-found feature :-)).
Doesn't make much sense to accept the URI parameter 'empty=entity::type' for a request with a type in the URI;

    GET /v1/contextEntityTypes/xxx?empty=entity::type

A request like that right now gives an error.
GET /v1/contextEntityTypes is not supported (there ?empty=entity::type would make sense), so, there is no way to query for empty types (with convops).
Doing a standard query with id = pattern(.*) and type = "" should give you EVERYTHING, but the URI option 'empty=entity::type' is not supported by the standard op.

I believe we need to think a little and see how to support this (and whether we want to support it - I would definitely prefer to forbid empty types before encouraging its usage).

Meanwhile, the bug should be fixed. 

**GET /v1/contextEntityTypes/** should behave just like **GET /v1/contextEntityTypes**

I am pretty sure this 'feature' is present for all requests.
It needs to be solved in the central place where the URI is parsed.

**Comment by fgalan** [comment]
Labeled as bug (the change about making the "slash-ended" URL behave as the "slash-not_ended" URL... regarding *"And how would we query for an empty type? Maybe a special parameter of the "type=empty" kind?"*, it should be spinned off this issue).

**Comment by kzangeli** [comment]
Yes, we have two different issues here, one is a bug and the other one is a possible feature

**Comment by LeandroGuillen** [comment]
This bug is confirmed to happen also with **GET /v1/contextEntities/** as reported by a user in stackoverflow: http://stackoverflow.com/questions/29409565/how-can-i-delete-an-id-less-entity-in-orion/

But remarkably not with **DELETE /v1/contextEntities/**

**Comment by kzangeli** [comment]
What I will do is simply to remove the last character of the URI-path if it is a slash, right where it is read.
That hopefully fixes all problems of this kind once and for all.

**Comment by fgalan** [comment]
+1

With that strategy and a couple of test harness (don't go crazy trying to test each conv op ;) I think is ok to solve this issue.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/922
