### ISSUE TITLE
Cmake Error if BUILD_ARCH is not defined

### ISSUE THREAD

**Issue by anaselli** [telefonicaid/fiware-orion#842]
cmake ..
CMAKE_BUILD_TYPE not set - setting it to RELEASE
Compiling in system Linux-3.12.26-tmb-laptop-1.mga4
CMAKE_BUILD_TYPE: 'RELEASE'
cmake: RELEASE compilation
Building for 
CMake Error at CMakeLists.txt:133 (if):
  if given arguments:

    "STREQUAL" "x86_64"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!

**Comment by anaselli** [comment]
A possible fixing here https://gist.github.com/anaselli/e39c8a1b6e9b8fa71d44

**Comment by fgalan** [comment]
Thanks for the report! It seems to be easy to fix, so we will try to do it by the next release (0.20.0)
