### ISSUE TITLE
functional tests retries after glitch fail

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#850]
Right now the functional tests sometimes fail, sporadically.
We don't really know why.
Running the test again 'fixes' the problem.

So, it would be nice to incorporate retries in testHarness.sh.
Just one retry - if a test fails twice in a row then we consider it a real failure and not a glitch.

**Effort: 1 man day**

**Comment by fgalan** [comment]
We implemented CB_MAX_TRIES time ago and I understand this is a solution for this issue. Maybe we missied to close that time...

**Comment by kzangeli** [comment]
Definitely.
This was implemented yaers ago.
Just close.
