### ISSUE TITLE
service routine headers and final check

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#856]
All convops have been modified as to use standard ops.
During this refactor, the service routines were added lots of info in their function header.
Info about URL, payload-types, URI-parameters, which StdOp it maps to, etc.

However, this design of the function header was perfectioned during the refactor and not all headers contain all the info they should. And  especially, the Std-op function headers have no info at all.

Also necessary: make sure all convops support all the URI-params they should.

**Effort: 7 man days**

**Comment by fgalan** [comment]
We are already doing this in NGSIv2 ongoing serviceRoutines implementation.
