### ISSUE TITLE
special metadata ID and forwarding

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#858]
Imagine the following scenario:
01. Update/APPEND E1/T1/A1/mID=primary
02. GET /v1/contextEntities/type/T1/id/E1/attributes/A1/backup and see it find nothing
03. Register E1/T1/A1/mID=backup for CP1
04. GET /v1/contextEntities/type/T1/id/E1/attributes/A1/backup and see it fail remotely
05. Update/APPEND E1/T1/A1/mID=backup in CP1
06. GET /v1/contextEntities/type/T1/id/E1/attributes/A1/backup and see it work remotely

Now, in the step 04, there is no forwarding done as the broker finds an attribute E1/T1/A1 locally.
If step 1 is omitted, everything works

**Comment by fgalan** [comment]
Metadata ID has been deprecated in Orion 1.13.0 and definitively removed in Orion 2.2.0. Thus, this issue is going to be closed.
