### ISSUE TITLE
Implement "float" and "integer" types

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#863]
In order to implement filtering functionality for "<", ">", etc. filters, we need a mechanism to specify that a given attribute is a number (up to 0.20.0, all the attributes are considered strings).

In order to do so, CB will interpret the "type" of the attribute in the following way:

* If type is equal to "integer" the value will be interpreted as an integer value
* If type is equal to "float" the value will be interpreted as a float value
* In any other case, the value will be interpreted as string

For numeric types, the following behaviour will be implemented:

* If an update/create in a numeric attribute is not using the right format, CB will response with 400 Bad Request.
* The following filters can be used with numeric attributes: <, <=, >, >=, <>

Note that (in order to mantain coherence with XML) the JSON type is not taken into account at response time, the values are encoded as string in the response payload. From https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Structured_attribute_values:

> Note that in order to align XML/JSON representations, the final "leaf" elements of the structured attribute values after travesing all vectors and key-maps are always considered as strings. String is the "natural" type for elements in XML, but not in JSON (that allow other types, such as integer). Thus, take into account that although you can use for instance a JSON integer as a field value in updates (such as {"x": 3 }), you will retrieve a string in queries and notifications (i.e. { "x": "3" }).

DB migration may be needed (in order to become attrinutes typed as "integer" and "float" in actual numbers in the DB).

**Comment by fgalan** [comment]
Useful link with a summary of planned filters: https://docs.google.com/spreadsheets/d/1f4m624nmO3jRjNalGE11lFLQixnfCENMV6dc54wUCCg/edit#gid=2

**Comment by mrutid** [comment]
Nice!

**Comment by fgalan** [comment]
After the NGSIv2 discussions, we would implement just one numeric type: "number".

**Comment by fgalan** [comment]
This will be implemented along with #970

**Comment by fgalan** [comment]
It has been been implemented (along with #970).
