### ISSUE TITLE
Improve "details" message in GET with Content-Type

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#870]
Context Broker responses with a weird message in the case of GET request with Content-Type header.

```
curl A.B.C.D:1026/v1/contextEntities/099012 -s -S --header 'Accept: application/json' --header 'Fiware-ServicePath: /fiware1' --header 'Fiware-Service: SmartValencia' --header 'X-Auth-Token: XXX' --header 'Content-Type: application/json'
{
  "orionError" : {
    "code" : "400",
    "reasonPhrase" : "Bad Request",
    "details" : "Sorry, no request treating object found for RequestType /IndividualContextEntity/"
  }
}
```

The `details` description is not providing useful information about the problem. In fact, it points into a different direction, not related with the actual cause of the problem.

Some reference info about Content-Type (although that section doesn't specify the behaviour of a server in the abnormal situation of using Content-Type in GET request, e.g. ignoring it or report an error): http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17

**Comment by kzangeli** [comment]
After a pretty big change in convops, the reply to this request (with empty database) is now:

    {
      "contextElement" : {
        "type" : "",
        "isPattern" : "false",
        "id" : "099012"
      },
      "statusCode" : {
        "code" : "404",
        "reasonPhrase" : "No context element found",
        "details" : "Entity id: /099012/"
      }
    }

Which seems like a pretty good reply for 'not found' ...

**Comment by fgalan** [comment]
I think the same. Thus, I would close this issue (after assigning it to milestone 0.21.0).
