### ISSUE TITLE
CPr forwarding timeout

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#880]
Implement a timeout for CPrs forwarding requests (the value could be specified using a CLI parameter).

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/903

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
