### ISSUE TITLE
Make WriteConcern configurable and default to 0

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#889]
Currently WriteConcern is not configurable (the default is 1).

This isuee is about creating a new CLI parameter (e.g. `-writeConcern`) and use 0 as default.

**Comment by fgalan** [comment]
Have a look to the similar work done by @rbl219

**Comment by rbl219** [comment]
Regarding this issue I have checked setting write concern to 0, modifying  mongoConnect function in file MongoGlobal.cpp.


After comment :

    LM_I(("Successful connection to database"));

I have added the code:

    if (connected == true)
    {
        WriteConcern waux =  connection->getWriteConcern();
        LM_E(("WriteConcern by default: %d", waux ));

        connection->setWriteConcern(W_NONE);

        waux =  connection->getWriteConcern();
        LM_E(("WriteConcern forced: %d", waux ));

    }



With mongo 2.6.9, I have checked performance, using a contextBroker generated with this change, but performance has not been improved significantly. I have checked setting mongo to --journal and --nojournal.

**Comment by fgalan** [comment]
Implemented in PR #925

**Comment by rbl219** [comment]
LGTM
