### ISSUE TITLE
Indents and newlines in rendered XML/JSON

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#896]
The rendered response is beautified by the render methods.
This is good for the log file, being able to read easily the responses, but not so good at sending the response, as a lot of extra, unnecessary, bytes are sent.

We should try to avoid sending these extra bytes, but at the same time we don't want to lose the readibility in the logfile.

Approaches:
1. Beautify the rendering only in DEBUG compilations (2 man days)
2. Remove the extra newlines and spaces just before sending the response, after logging it. (1 man day)
3. No beautifying at all (1 man day)
4. No beautifying done by render functions, but by some other library and only for logging purposes. (3 man days?)

It is hard to estimate effort for Option 4. We don't even know what library to use ...

**Effort: 3 man days**

**Comment by fgalan** [comment]
Another possibility would be to make indent variable depending on wether the tracelevels related with printing output in the log are enabled or not (I think there are 4 tracelevels related with this).

**Comment by fgalan** [comment]
NGSIv2 doesn't uses any whitespace.
