### ISSUE TITLE
File and function names for clientSocketHttp.cpp

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#897]
lib/rest/clientSocketHttp.cpp

The name of this file is ... horrible.
Also the function sendHttpSocket should be changed.   httpRequestSend() ?

socketHttpConnect => httpRequestConnect() ?

[ socketHttpConnect should be static ]

**Effort: 1 man day**

**Comment by LeandroGuillen** [comment]
Yes, please. I don't know how many times I've gone into this file and I never remember the name :)

**Comment by kzangeli** [comment]
Fixed in PR #892
