### ISSUE TITLE
notify_format_in_ngsi9_subscriptions.test

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#898]
The functest notify_format_in_ngsi9_subscriptions.test has not been completed.
What's missing: cases for update-subscription.
Also, we might need to modify the broker for this to work.

When a registration/subscription is updated, should the notifyFormat be modified as well?

**Effort: 2 man days**

**Comment by fgalan** [comment]
Regarding timing, implement this issue first, after that implement https://github.com/telefonicaid/fiware-orion/issues/893 (given that #893 implies copying the NGSI9 test).

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/904
