### ISSUE TITLE
possible bug when local and remote entities have similar names

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#901]
Local attributes not found when having:

a local EntityId/AttributeName TestClient/position_status and 
a remote EntityId/AttributeName TestClient:Robot/position_status.

The type of the entities is 'Robot', locally and remote.

Is ':' a valid character for EntityId::id ?

**Comment by fgalan** [comment]
"Interesting" bug...

In this that ":" is valid. At least it is used extensively in examples: http://www.fiware.org/devguides/development-context-aware-applications/how-to-update-and-query-context-information/

**Comment by kzangeli** [comment]
I'm unable to reproduce it.
Been trying for hours ...

**Comment by fgalan** [comment]
If it cannot be reproduced, it could be a glitch or false positive. Let his issue in "quarentine" status in order to see if this happens again.

**Comment by fgalan** [comment]
Lowering priority, due to non-reproductibility.

@dmoranj , if you find it again, please add the request(s) raising the problem to this issue.

**Comment by fgalan** [comment]
Quarentine has longed for 6 months :). Thus I'm closing the issue.
