### ISSUE TITLE
-useSemaphore CLI parameter

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#910]
Up to 0.21.0, CB ensures than no more than one request is processed at the same time at mongoBackend using a semaphore-based system. However, in Active/Active configurations, that cannot be ensured globally, so why don't relax some request semaphore?

To this end, develop a new CLI parameter "useSemaphore " of type string:

* If the value is "all" then all the requests use the semafore. This would be de default value and the one we have in 0.21.0 and before.
* If the value is "read" then only read-like requests use the semaphore.
* If the value is "write" then only write-like requests use the semaphore.
* If the value is "none" then no request uses the semaphore.

**Comment by fgalan** [comment]
Maybe useSemaphore is not a very good name... Another alternative is "-blockRequest"

**Comment by fgalan** [comment]
To implement this, the simplest approach maybe is to modify reqSemTake() and reqSemGive() functions in sem.cpp, doing actual taking/giving or pass-through depending on the CLI flag value and the `who` argument.

**Comment by kzangeli** [comment]
-dbMutex ?

Now, what if we actually perform two updates on the same data ...
What is the worst case scenario?

**Comment by fgalan** [comment]
> what if we actually perform two updates on the same data

In this case, we are in the same situation that with 2 CBs configured in Active/Active mode, that, if you rememeber the analysis we did last month ;), is a safe case after implementing https://github.com/telefonicaid/fiware-orion/issues/878 in 0.21.0.

I like `-dbMutex` more than `-useSemaphore`. However, I think I can improve it... what about `-dbMutexPolicy`?

**Comment by fgalan** [comment]
Actually, `db` in the name should be removed, as the CLI parameters is about the *request* semaphore (DB semaphores are for driver protection, should they must not be configurable and remain as they are now). 

Thus, my proposal is for `-mutexPolicy`.

**Comment by kzangeli** [comment]
'-dbMutexPolicy' ... I expect the policy to come after, like "-dbMutexPolicy NONE", or something (actually, "-dbMutex" is a little like that also. "-useSemaphore" on the other is clearly a flag)

Let's try to find some clearer name.

-dbMutexProtect?

**Comment by fgalan** [comment]
`-mutexProtect` is also fine.

**Comment by kzangeli** [comment]
There is a value coming after the option, as I was 'wanting' in my last comment before this one.
-dbMutexPolicy is just fine as a name.

[ I guess I didn't really read the first comment on this issue ... ]

**Comment by fgalan** [comment]
Implemented in PR #913
