### ISSUE TITLE
Possible bug: error deleting entities, using empty entity::type in DELETE request

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#921]
An orion user reports a possible bug in SOF.
http://stackoverflow.com/questions/30187308/delete-entities-dont-work-in-orion

**Comment by kzangeli** [comment]
I just tested this in a new functest and it works just the way it should.
Perhaps Cristina (the bug reporter in SOF) is using an older version pf the broker?

Func test:

    echo "01. Update/APPEND E1/T1/A1+A2"
    echo "============================="
    payload='{
      "contextElements": [
        {
          "id": "E1",
          "type": "T",
          "attributes": [
            {
              "name": "A1",
              "type": "string",
              "value": "A1 in step 01"
            },
            {
              "name": "A2",
              "type": "string",
              "value": "A2 in step 01"
            }
          ]
        }
      ],
      "updateAction": "APPEND"
    }'
    orionCurl --url /v1/updateContext --payload "$payload" --json
    echo
    echo


    echo "02. Delete E1 using convop DELETE /v1/contextEntities/E1"
    echo "========================================================"
    orionCurl --url /NGSI10/contextEntities/E1 -X DELETE --json
    echo
    echo


    echo "03. Query E1"
    echo "============"
    orionCurl --url /v1/contextEntities/E1 --json

Response:

    01. Update/APPEND E1/T1/A1+A2
    =============================
    HTTP/1.1 200 OK
    Content-Length: 490
    Content-Type: application/json
    Date: Tue, 12 May 2015 18:08:33 GMT
    
    {
        "contextResponses": [
            {
                "contextElement": {
                    "attributes": [
                        {
                            "name": "A1",
                            "type": "string",
                            "value": ""
                        },
                        {
                            "name": "A2",
                            "type": "string",
                            "value": ""
                        }
                    ],
                    "id": "E1",
                    "isPattern": "false",
                    "type": "T"
                },
                "statusCode": {
                    "code": "200",
                    "reasonPhrase": "OK"
                }
            }
        ]
    }
    
    
    02. Delete E1 using convop DELETE /v1/contextEntities/E1
    ========================================================
    HTTP/1.1 200 OK
    Content-Length: 46
    Content-Type: application/json
    Date: Tue, 12 May 2015 18:08:33 GMT

    {
        "code": "200",
        "reasonPhrase": "OK"
    }
    
    
    03. Query E1
    ============
    HTTP/1.1 200 OK
    Content-Length: 218
    Content-Type: application/json
    Date: Tue, 12 May 2015 18:08:33 GMT
    
    {
        "contextElement": {
            "id": "E1",
            "isPattern": "false",
            "type": ""
        },
        "statusCode": {
            "code": "404",
            "details": "Entity id: /E1/",
            "reasonPhrase": "No context element found"
        }
    }

**Comment by fgalan** [comment]
The PR has been included in the repository, thus CB seems to work fine. Let's hold this for a bit as "quarentine" (in the case reporter could provide more feedabck) with a low priority.

**Comment by fgalan** [comment]
Quarenty has longed for 5 month :), time enough to close the issue.
