### ISSUE TITLE
Remove function mongoDisconnect

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#929]
The function mongoDisconnect is no longer needed (after the inclusion of the connection pool for mongo).
The function should be removed from MongoGlobal.cpp/h and wherever it is called (especially in unit-tests).

**Effort: 1 man day**

**Comment by fgalan** [comment]
I understand that is a matter of replacing mongoDisconnect() by setMongoConnectionForUnitTest(NULL) in the unit test, right?

**Comment by fgalan** [comment]
Fixed in PR #977
