### ISSUE TITLE
Change --httpTenant for --tenant in functests

### ISSUE THREAD

**Issue by kzangeli** [telefonicaid/fiware-orion#938]
The name of the option --httpTenant comes from when we accepted tenants both in the URL and as HTTP header.
Now that we no longer support URL tenants, the tenant is *always* in the HTTP header and the name of the option should be changed to --tenant (or even --service).

orionCurl supports both --httpTenant and --tenant but the *.test all use --httpTenant.
Those *.test should be modified and --httpTenant should be removed from orionCurl.

**Effort: 1 man day**

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-orion/pull/1013
