### ISSUE TITLE
Multitenancy without access to MongoDB admin database

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#954]
Raised at http://stackoverflow.com/questions/30503199/how-to-deploy-multitenant-orion-without-direct-mongodb-admin-access

In some cases (e.g. PaaS-based MongoDB) Orion administrator hasn't access to the MongoDB admin database.

This could be solved using an "authorization table" in Orion, including the user/password for each tenant database. Thus, at mongoConenction() time, Orion auth() in each one of the tenant in that table for each connection in the DB pool. That table could be provided in a file and the passwords should be in cleartext (passing the information in the CLI should be complex).

A characteristic of this solution is that it requires to know the tenant in advance. If a new tenant is added, then Orion should be restarted or re-read the table and re-do the auth() in the existing connections on the fly.

**Comment by giuliopaci** [comment]
This feature would be very useful.
It would also be great if it was possible:
* to specify multiple instances;
* update the table programmatically and  on-the-fly.

**Comment by fgalan** [comment]
With the ability to set the DB used for authentication (`-dbAuthDb`) introduced in Orion 2.3.0 I understand this is no longer an issue.
