### ISSUE TITLE
API v2: List all entities by pattern matching

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#969]
Implement list all entities by pattern matching operation in v2, i.e. 

```
GET /v2/entities?idPattern=<pattern>&extraparams
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by kzangeli** [comment]
Just a suggestion - we could extend the pattern matching to types as well:

    GET /v2/entities?idPattern=<pattern>&extraparams
    GET /v2/entities?typePattern=<pattern>&extraparams

Perhaps even patterns for attribute names

**Comment by fgalan** [comment]
Using patterns in types would be useful. However, we have to analyze its implications (e.g. it is not part of the NGSI OMA standard and we should find a way of fittin it). In anycase, I think it is advanced feature, outside of the scope of this issue (I'd suggest you open a new issue about it, labeling it with "APIv2" label).

However, inside the scope of this issue, maybe is clever to use "idPattern" instead of just "pattern", anticipating a possible "typePattern" in the future.

**Comment by fgalan** [comment]
Issue about extending the pattern concept to entity type and attribute names: #978

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1139
