### ISSUE TITLE
API v2: Get entity attributes (by entity ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#971]
Implement get entity attribute in v2, i.e.

```
GET /v2/entities/<entityId>?attrs=<attrName>
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Implemented in PR #1131

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature
```
