### ISSUE TITLE
API v2: Get entity attributes (by entity ID and type)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#972]
Same as #971 but with the following URL:

```
GET /v2/entities/type/<entityType>/id/<entityId>?attrs=<attrName>
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/1768

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
```
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature
```
