### ISSUE TITLE
Extend the pattern concept to attribute values

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#978]
OMA NGSI only considers patterns in entity ID. To that end, the `?idPattern` parameter has been defined (see https://github.com/telefonicaid/fiware-orion/issues/969).

However it would be useful to implement also pattern for entity type and attribute values. A way of fitting it in OMA NGSI has to be found, but, by the moment, the following has been suggested:
- `?typePattern` for entity type pattern
- New operator for `?q` filter (see https://github.com/telefonicaid/fiware-orion/issues/967), e.g. `^=` so `?q=color^=b.*` means "all the colors that start with letter 'b'".

**Comment by fgalan** [comment]
As alterantive, `=~` could be used as operator for attribute pattern matching.

**Comment by fgalan** [comment]
Another possiblity is to use `~=` which seems to be more aligned with Perl or Ruby. The final decision, either `~=` or `=~` (or other :) is deferred until the time to implement this issue comes.

**Comment by fgalan** [comment]
Originally this issue covers also patterns for entity types. However, that part has been "moved" to https://github.com/telefonicaid/fiware-orion/issues/1853

**Comment by fgalan** [comment]
> The final decision, either ~= or =~ (or other :) is deferred until the time to implement this issue comes.

Time has come :)

I'll finally use ~= which is aligned with

!=
>=
<=
~=

**Comment by fgalan** [comment]
Implementation in PR #2081. Documentation changes in PR #2088.

**Comment by fgalan** [comment]
Moving to QATestPending milestone while the functional test covering this are implemented.

**Comment by iariasleon** [comment]
still it has not been developed `?typePattern` for entity type pattern? Only New operator for `?q` filter

**Comment by fgalan** [comment]
That's correct: the present issue is about `~=` for attribute values pattern. Note that `?typePattern` has its own issue (#1853).

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
