### ISSUE TITLE
API v2: Strictly append attributes (by entity ID) 

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#983]
Implement the following operation in in v2:

```
POST /v2/entities/<entityId>?op=append
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Implemented in PR #1124

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
See 
```
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_part4.feature
```
