### ISSUE TITLE
API v2: Strictly append attributes (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#984]
Implement the following operation in in v2:

```
POST /v2/entities/type/<entityType>/id/<entityId>?op=append
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by fgalan** [comment]
...and `op=append` is no longer used, but `options=append`.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1775

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM
See 
```
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_part4.feature
```

**Comment by iariasleon** [comment]
pending `type` and `type+options=append` queries parameters

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
