### ISSUE TITLE
API v2: Delete entity (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#986]
Implement the following operation in in v2:

```
DELETE /v2/entities/type/<entityType>/id/<entityId>
```
See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1770.

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity.feature
```
