### ISSUE TITLE
API v2: Replace attributes (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#988]
Implement the following operation in in v2:

```
PUT /v2/entities/type/<entityType>/id/<entityId>
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by crbrox** [comment]
closed by #1779 

@iariasleon

**Comment by iariasleon** [comment]
reopened and pending to tests by @iariasleon

**Comment by fgalan** [comment]
"backlog" issues are closed once the PR that implement them is created/merged (only "bug" issues are passed to QA in opened status for final verfication).

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
pending tests: `PUT - /v2/entities/<entity_id>?type=<entityType>`

**Comment by fgalan** [comment]
Issues in milestone QATestPending are going to be closed (it is not realistic to think we would have people working on behave testing at the present moment). However, issue is labeles with QATestPending label in the case thinks change and we need to recover it.
