### ISSUE TITLE
API v2: Get a single attribute (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#990]
Implement the following operation in in v2:

```
GET /v2/entities/type/<entityType>/id/<entityId>/attrs/<attrName>
```

Same operation that https://github.com/telefonicaid/fiware-orion/issues/989, but taking into account entityType also in the URL.

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-orion/pull/1768

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data.feature
```
