### ISSUE TITLE
API v2: Update single attribute (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#992]
Implement the following operation in in v2:

```
PUT /v2/entities/type/<entityType>/id/<entityId>/attrs/<attrName>
```

Same operation that https://github.com/telefonicaid/fiware-orion/issues/991, but taking into account entityType also in the URL.

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by crbrox** [comment]
closed by #1779 

@iariasleon

**Comment by fgalan** [comment]
"backlog" issues are closed once the PR that implement them is created/merged (only "bug" issues are passed to QA in opened status for final verfication).

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data_part4.feature
```
