### ISSUE TITLE
API v2: Remove a single attribute (by entity type and ID)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#994]
Implement the following operation in in v2:

```
DELETE /v2/entities/type/<entityType>/id/<entityId>/attrs/<attrName>
```

Same operation that https://github.com/telefonicaid/fiware-orion/issues/993, but taking into account entityType also in the URL.

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
At the end, this is going to be implemented using `?type=<entityType>`.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-orion/pull/1770.

**Comment by fgalan** [comment]
QA Acceptance Test pending. Reopened and asigned to QATestPending milestone.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
```
