### ISSUE TITLE
API v2: Get a single attribute value (by entity)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-orion#997]
Implement the following operation in in v2:

```
GET /v2/entities/<entityId>/attrs/<attrName>/value
```

See detailed description in the NGSIv2 APIary reference at http://telefonicaid.github.io/fiware-orion/api/v2/.

**Comment by fgalan** [comment]
Implemented in PR #1147

**Comment by fgalan** [comment]
This has been reopened and set at QATestPending milestone to complete its functional test.

**Comment by iariasleon** [comment]
LGTM 

See:
```
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value.feature
```
